### ISSUE TITLE
Text generation task?

### ISSUE THREAD

**Issue by matthew-jurewicz** [huggingface/autotrain-advanced#110]
Any plans to implement this?

**Comment by abhishekkrthakur** [comment]
if you are looking for summarization models, it is already implemented. generative question and answering is in the pipeline.

**Comment by matthew-jurewicz** [comment]
No, I mean like if I train a model with short stories, I want a task to generate new stories from scratch.

**Comment by matthew-jurewicz** [comment]
Any updates?

**Comment by Michellehbn** [comment]
Closing issue as obsolete to new autotrain-advanced that is soon releasing.
