### ISSUE TITLE
Choosing a separator

### ISSUE THREAD

**Issue by sasu08** [huggingface/autotrain-advanced#111]
Hi! This issue is most like a recommendation.
When I tried to upload a .csv file in huggingface, I don't have the option to choose a separator.
I understand that the .csv file is a "comma separated values" but in some cases the .csv has another separator, like in this case.

![image](https://user-images.githubusercontent.com/73124427/134282015-86e8bec9-438f-48d6-8a91-e32cc211392e.png)

I think the problem it will resolve if I change the "|" to "," but hopefully, in the future, you can implement something like what I said above.
Best regards!

**Comment by Michellehbn** [comment]
Closing issue as obsolete to new autotrain-advanced that is soon releasing.
