### ISSUE TITLE
Doc pages are missing --max_models

### ISSUE THREAD

**Issue by juliensimon** [huggingface/autotrain-advanced#113]
Hello,

--max_models is a required parameter. However, it doesn't appear in the task doc pages, e.g. https://huggingface.co/docs/autonlp/multi_class_classification.html

Thank you :)

**Comment by juliensimon** [comment]
Yes. If I omit the parameter, I get an error.

autonlp create_project --name my_project --language en --task multi_class_classification
usage: autonlp <command> [<args>] create_project [-h] --name NAME --task TASK [--language LANGUAGE] --max_models MAX_MODELS [--hub_model HUB_MODEL]
autonlp <command> [<args>] create_project: error: the following arguments are required: --max_models

**Comment by Michellehbn** [comment]
Closing issue as obsolete to new autotrain-advanced that is soon releasing.
