### ISSUE TITLE
Failed to upload processed data files to huggingface hub

### ISSUE THREAD

**Issue by hiiamsid** [huggingface/autotrain-advanced#114]
> INFO    Fetching info for project: Summarization
> INFO    🗝 Retrieving credentials from config...
> INFO    ☁ Retrieving project 'Summarization' from AutoNLP...
> INFO    🔄 Refreshing project status...
> INFO    🔄 Refreshing uploaded files information...
> INFO    🔄 Refreshing models information...
> INFO    🔄 Refreshing cost information...
> INFO    ✅ Successfully loaded project: 'Summarization'!
AutoNLP Project (id # 2068)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 • Name:        Summarization
 • Owner:       hiiamsid
 • Status:      ❌ Failed to upload processed data files to the huggingface hub
 • Task:        Summarization
 • Created at:  2021-10-18 06:33 Z
 • Last update: 2021-10-18 10:55 Z

💰 Project current cost: USD 481.79

~~~~~~~~~~~~~~ Files ~~~~~~~~~~~~~~

Dataset ID:
hiiamsid/autonlp-data-Summarization

📁 spanish_paraphrase_train.csv (id # 1775)
   • Split:             train
   • Processing status: ✅ Success!
   • Last update:       2021-10-18 10:44 Z
📁 es_paraphrase_test.csv (id # 1776)
   • Split:             valid
   • Processing status: ✅ Success!
   • Last update:       2021-10-18 10:43 Z

**Comment by Michellehbn** [comment]
Closing issue as obsolete to new autotrain-advanced that is soon releasing.
