### ISSUE TITLE
Issue with running AutoNLP

### ISSUE THREAD

**Issue by prakash2www** [huggingface/autotrain-advanced#119]
Hi,

I am trying to use AutoNLP for Summarization task. Was able to upload data and when I tried to train the model. I got below error:
There was a problem while uploading your dataset files.

URL: https://ui.autonlp.huggingface.co/4395/trainings

Let me know if you need more details.

**Comment by fleuryc** [comment]
Same issue here : https://ui.autonlp.huggingface.co/4827/trainings with Sentiment Analysis on [sentiment140](https://www.kaggle.com/kazanova/sentiment140) dataset.

No issue when I imported the dataset, but same error when training.

**Comment by Michellehbn** [comment]
Closing issue as obsolete to new autotrain-advanced that is soon releasing.
