### ISSUE TITLE
How to run locally?

### ISSUE THREAD

**Issue by gfunkgod** [huggingface/autotrain-advanced#133]
How can I run this locally?

**Comment by davidberenstein1957** [comment]
streamlit run autotrain-advanced/app.py

**Comment by abhishekkrthakur** [comment]
you can clone the repo and install locally:

`$ pip install -e .`

then run:

`$ autotrain app`

**Comment by loganamcnichols** [comment]
Will the other auto train tasks be implemented locally at some point in the future?

**Comment by Barnplaid** [comment]
> you can clone the repo and install locally:
> 
> `$ pip install -e .`
> 
> then run:
> 
> `$ autotrain app`

This runs the training on HuggingFace's hardware. Is there any way to run the GUI with local resources?
