### ISSUE TITLE
LLM finetune stopped without any error logs

### ISSUE THREAD

**Issue by NajiAboo** [huggingface/autotrain-advanced#136]
I am trying to fine tune LLM with my data. After starting the autotrain, it seems to be stopped. I dont see any logs to identify the problem

**Comment by mahdouch9165** [comment]
Same here.

**Comment by thenatefisher** [comment]
same

**Comment by guidodinello** [comment]
I'm facing the same problem. Could this be due to insufficient RAM for loading the shards?

**Comment by bitstormFA** [comment]
I have the same problem. I have checked RAM usage and it doesn't seem to be the problem. Could this be some kind of early stopping?

**Comment by abhishekkrthakur** [comment]
A solution cannot be provided without error logs.
However, if it says `Killed`, it means your system ran out of memory.
