### ISSUE TITLE
Dreambooth Error: path_in_repo=f"concept{concept_num + 1}/{file.name}", AttributeError: 'str' object has no attribute 'name'

### ISSUE THREAD

**Issue by mangoplane** [huggingface/autotrain-advanced#137]
The string path to the uploaded images doesn't have an attribute "name" on the instance of the str class. Please see the problematic line of code here:
https://github.com/huggingface/autotrain-advanced/blob/main/src/autotrain/preprocessor/dreambooth.py#LL43C63-L43C66

You can see the image paths are passed in as an array of strings. As far as I know, str doesn't have a 'name' attribute.

Happy to PR a fix if this is indeed an error, as opposed to a config setup. I'm running this in HuggingFace, and it appears as though I've filled out all fields.

Thanks.

**Comment by Spit-fires** [comment]
any updates on this?

**Comment by abhishekkrthakur** [comment]
seems go be fixed
