### ISSUE TITLE
AutoTrain advanced CLI: error: invalid choice: 'llm' (choose from 'app')

### ISSUE THREAD

**Issue by dsdanielpark** [huggingface/autotrain-advanced#146]
Is the interface undergoing changes? We are encountering various errors.

**Comment by abhishekkrthakur** [comment]
Please post more details in order for me to understand what the issue might be

**Comment by dsdanielpark** [comment]
<img width="434" alt="image" src="https://github.com/huggingface/autotrain-advanced/assets/81407603/d85a89bd-dbff-4fc8-ba5b-2772c8e2c835">

While Google Colab instances cannot be initialized to reproduce errors, I encountered the same error consistently on my local PC (Windows 10 with RTX3090). The same error message was also replicated on Google Colab.

After conducting multiple experiments on various Google Colab instances, some resulted in installation errors, some displayed the same error message as mentioned above, and only once did it work properly.

I am experiencing a shortage of GPU resources, which makes Colab an essential choice for me. Could you provide me with some advice on how to deal with these issues regarding the package I have been using? Or is it possible that it should not be used yet due to ongoing development?

I believe your project is very meaningful and will become the future of Hugging Face. Thank you for your fantastic work.

**Comment by abhishekkrthakur** [comment]
Which version of autotrain-advanced are you using? Could you please try the latest version?

**Comment by Prabhakar-M1** [comment]
Hi Abhishek,
I'm trying to execute the "autotrain" command for training, but I'm getting the following error message.

(base) C:\Users\2021781>autotrain llm --train --project_name my-llm --model meta-llama/Llama-2-7b-hf --data_path . --use_peft --use_int4 --learning_rate 2e-4 --train_batch_size 12 --num_train_epochs 3 --trainer sft

usage: autotrain <command> [<args>]

AutoTrain advanced CLI: error: invalid choice: 'llm' (choose from 'app').

-->autotrain-advanced -> current Version - 0.5.2

If you try to install the latest version 0.6.2 (autotrain-advanced)

Again asking for dependency library "triton" latest version(triton==2.0.0.post1)

Trying to install "triton" library latest(triton==2.0.0.post1)  as well as lowest(triton==0.4.0) version's .

Getting the below error.

Requirement already satisfied: huggingface-hub>=0.14.1 in c:\programdata\anaconda3\envs\llama\lib\site-packages (from autotrain-advanced==0.6.2) (0.16.4)

INFO: pip is looking at multiple versions of autotrain-advanced to determine which version is compatible with other requirements. This could take a while.

ERROR: Could not find a version that satisfies the requirement triton==2.0.0.post1 (from autotrain-advanced) (from versions: none)

ERROR: No matching distribution found for triton==2.0.0.post1

(llama) C:\Users\2021781>pip3 install triton==2.0.0.post1

ERROR: Could not find a version that satisfies the requirement triton==2.0.0.post1 (from versions: none)

ERROR: No matching distribution found for triton==2.0.0.post1

(llama) C:\Users\2021781>pip3 install triton==0.4.0

ERROR: Could not find a version that satisfies the requirement triton==0.4.0 (from versions: none)

ERROR: No matching distribution found for triton==0.4.0

(llama)

NOTE: Machine Details :
Windows 11 
64-bit
RAM : 16GB.

Please provide the solution for above error.

**Comment by EnggQasim** [comment]
(lmv4) C:\Users\Saheeq\Desktop\qasim\llamva-finetune>autotrain llm --train --project_name my-llm --model abhishek/llama-2-7b-hf-small-shards --data_path . --use_peft --use_int4 --learning_rate 2e-4 --train_batch_size 12 --num_train_epochs 3 --trainer sft
usage: autotrain <command> [<args>]
AutoTrain advanced CLI: error: invalid choice: 'llm' (choose from 'app')

**Comment by EnggQasim** [comment]
I have created "lmv4 conda env with python 3.8" or 3.9 or 3.10, and 3.10
then install "pip install autotrain-advanced" 
its only run python 3.8 version to 3.10 version
I have Alieware Gaming Computer with 64 GB RAM and RTX 4090 Nvidia GPU

I really need to resolve this issue, i have also tried on google colab but facing short resources error there.

**Comment by abhishekkrthakur** [comment]
3.11 is supported now. you need to use latest version. if pip doesnt work, install from source

**Comment by mctb32** [comment]
I also have the same problem. On Windows pip installs the version 0.5.2 which doesn't accept any commands. Forcing pip to install version 0.6.2 fails when it can't install the triton 2.0.0.post1 dependency. From what I know, triton is a linux-only package.

So my question is, is Triton necessary to run autotrain-advanced, or can it run without it on windows? I recently used khoya_ss on windows to fine-tune stable diffusion and it gives warnings that triton not being available will disable some optimisations but other than that it works fine.

**Comment by llacki** [comment]
> 

I got the same error? Where you able to find the solution?

**Comment by mctb32** [comment]
Sort of... After a lot of work I managed to get it running on windows via WSL. The process of setting up everything was very painful - I had to install a lot of libraries (the right version of CUDA, all dependencies for pillow) and fix system paths before autotrain was able to install correctly. I managed to train an SDXL Lora via dreambooth in autotrain, but the resulting .safetensors file was not compatible with Comfy UI or Automatic1111, so I ended up going back to Kohya GUI, which currently works fine with SDXL and is probably the best choice for sdxl training on windows.

**Comment by dsdanielpark** [comment]
This package is very useful, but it seems to lack consideration for various environmental factors at a low-level. Additionally, due to its heavy reliance on diverse resources and hardware drivers for training, it appears to be a challenging task. It might be desirable to completely redesign the package's architecture.

**Comment by gaurav15113010** [comment]
--use_peft --use_int4 >> these two arguments are showing invalid after upgradation of autotrain-advance package. It is working fine on  0.6.51 this version

**Comment by a-ml** [comment]
Hello,

Apologies for reopening this thread, I'm having the error bellow and I don't any reference in the internet on what am I missing.

> autotrain <command> [<args>] llm: error: the following arguments are required: --project-name

The command that I'm running is the following:

```
autotrain llm \
--train \
--project_name llama-angolan-tuned \
--model abhishek/llama-2-7b-hf-small-shards \
--data_path . \
--use_peft \
--use_int4 \
--learning_rate 2e-4 \
--train_batch_size 4 \
--num_train_ephocs 3 \
--trainer sft > trainer.log
```

Any hint? I'm running on Macbook M1 for learning purposes.

**Comment by abhishekkrthakur** [comment]
it clearly says what you need and what you have :) see project-name vs project_name ;)

**Comment by a-ml** [comment]
ops! sorry my mistake... I looked into it thousands times, and the biased eyes always looked the same. Thanks!
