### ISSUE TITLE
Error with target_modules

### ISSUE THREAD

**Issue by VandeveldePaul** [huggingface/autotrain-advanced#147]
Hello,

When i run this command : autotrain llm --train --project_name output --model OpenAssistant/falcon-7b-sft-top1-696 --data_path tatsu-lab/alpaca --use_peft --trainer sft --learning_rate 2e-4 --use_int4

The model downloads, and my 3 GPUs are being started but i get this error: ValueError: Please specify `target_modules` in `peft_config`

With this traceback: 

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/buinno/Desktop/Falcon/autotrain-env/bin/autotrain:8 in <module>                            │
│                                                                                                  │
│   5 from autotrain.cli.autotrain import main                                                     │
│   6 if __name__ == '__main__':                                                                   │
│   7 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 8 │   sys.exit(main())                                                                         │
│   9                                                                                              │
│                                                                                                  │
│ /home/buinno/Desktop/Falcon/autotrain-env/lib/python3.10/site-packages/autotrain/cli/autotrain.p │
│ y:32 in main                                                                                     │
│                                                                                                  │
│   29 │   │   exit(1)                                                                             │
│   30 │                                                                                           │
│   31 │   command = args.func(args)                                                               │
│ ❱ 32 │   command.run()                                                                           │
│   33                                                                                             │
│   34                                                                                             │
│   35 if __name__ == "__main__":                                                                  │
│                                                                                                  │
│ /home/buinno/Desktop/Falcon/autotrain-env/lib/python3.10/site-packages/autotrain/cli/run_llm.py: │
│ 479 in run                                                                                       │
│                                                                                                  │
│   476 │   │   │   │   trainer=self.trainer,                                                      │
│   477 │   │   │   │   target_modules=self.target_modules,                                        │
│   478 │   │   │   )                                                                              │
│ ❱ 479 │   │   │   train_llm(params)                                                              │
│   480                                                                                            │
│                                                                                                  │
│ /home/buinno/Desktop/Falcon/autotrain-env/lib/python3.10/site-packages/autotrain/trainers/clm.py │
│ :115 in train                                                                                    │
│                                                                                                  │
│   112 │   │   │   task_type="CAUSAL_LM",                                                         │
│   113 │   │   │   target_modules=utils.get_target_modules(config),                               │
│   114 │   │   )                                                                                  │
│ ❱ 115 │   │   model = get_peft_model(model, peft_config)                                         │
│   116 │                                                                                          │
│   117 │   if config.block_size == -1:                                                            │
│   118 │   │   config.block_size = None                                                           │
│                                                                                                  │
│ /home/buinno/Desktop/Falcon/autotrain-env/lib/python3.10/site-packages/peft/mapping.py:98 in     │
│ get_peft_model                                                                                   │
│                                                                                                  │
│   95 │   │   return PeftModel(model, peft_config, adapter_name=adapter_name)                     │
│   96 │   if isinstance(peft_config, PromptLearningConfig):                                       │
│   97 │   │   peft_config = _prepare_prompt_learning_config(peft_config, model_config)            │
│ ❱ 98 │   return MODEL_TYPE_TO_PEFT_MODEL_MAPPING[peft_config.task_type](model, peft_config, a    │
│   99                                                                                             │
│                                                                                                  │
│ /home/buinno/Desktop/Falcon/autotrain-env/lib/python3.10/site-packages/peft/peft_model.py:893 in │
│ __init__                                                                                         │
│                                                                                                  │
│    890 │   """                                                                                   │
│    891 │                                                                                         │
│    892 │   def __init__(self, model, peft_config: PeftConfig, adapter_name="default"):           │
│ ❱  893 │   │   super().__init__(model, peft_config, adapter_name)                                │
│    894 │   │   self.base_model_prepare_inputs_for_generation = self.base_model.prepare_inputs_f  │
│    895 │                                                                                         │
│    896 │   def forward(                                                                          │
│                                                                                                  │
│ /home/buinno/Desktop/Falcon/autotrain-env/lib/python3.10/site-packages/peft/peft_model.py:112 in │
│ __init__                                                                                         │
│                                                                                                  │
│    109 │   │   self.peft_type = peft_config.peft_type                                            │
│    110 │   │   if not isinstance(peft_config, PromptLearningConfig):                             │
│    111 │   │   │   self.peft_config[adapter_name] = peft_config                                  │
│ ❱  112 │   │   │   self.base_model = PEFT_TYPE_TO_MODEL_MAPPING[peft_config.peft_type](          │
│    113 │   │   │   │   self.base_model, self.peft_config, adapter_name                           │
│    114 │   │   │   )                                                                             │
│    115 │   │   │   self.set_additional_trainable_modules(peft_config, adapter_name)              │
│                                                                                                  │
│ /home/buinno/Desktop/Falcon/autotrain-env/lib/python3.10/site-packages/peft/tuners/lora.py:180   │
│ in __init__                                                                                      │
│                                                                                                  │
│    177 │   │   self.model = model                                                                │
│    178 │   │   self.forward = self.model.forward                                                 │
│    179 │   │   self.peft_config = config                                                         │
│ ❱  180 │   │   self.add_adapter(adapter_name, self.peft_config[adapter_name])                    │
│    181 │   │                                                                                     │
│    182 │   │   # transformers models have a .config attribute, whose presence is assumed later   │
│    183 │   │   if not hasattr(self, "config"):                                                   │
│                                                                                                  │
│ /home/buinno/Desktop/Falcon/autotrain-env/lib/python3.10/site-packages/peft/tuners/lora.py:192   │
│ in add_adapter                                                                                   │
│                                                                                                  │
│    189 │   │   │   if hasattr(model_config, "to_dict"):                                          │
│    190 │   │   │   │   model_config = model_config.to_dict()                                     │
│    191 │   │   │                                                                                 │
│ ❱  192 │   │   │   config = self._prepare_lora_config(config, model_config)                      │
│    193 │   │   │   self.peft_config[adapter_name] = config                                       │
│    194 │   │   self._find_and_replace(adapter_name)                                              │
│    195 │   │   if len(self.peft_config) > 1 and self.peft_config[adapter_name].bias != "none":   │
│                                                                                                  │
│ /home/buinno/Desktop/Falcon/autotrain-env/lib/python3.10/site-packages/peft/tuners/lora.py:434   │
│ in _prepare_lora_config                                                                          │
│                                                                                                  │
│    431 │   def _prepare_lora_config(peft_config, model_config):                                  │
│    432 │   │   if peft_config.target_modules is None:                                            │
│    433 │   │   │   if model_config["model_type"] not in TRANSFORMERS_MODELS_TO_LORA_TARGET_MODU  │
│ ❱  434 │   │   │   │   raise ValueError("Please specify `target_modules` in `peft_config`")      │
│    435 │   │   │   peft_config.target_modules = TRANSFORMERS_MODELS_TO_LORA_TARGET_MODULES_MAPP  │
│    436 │   │   return peft_config                                                                │
│    437                                                                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯

I already tried to change the model but i got the same error.
Do you have any idea that could resolve this problem ?

Thank you,
Paul

**Comment by abhishekkrthakur** [comment]
you can fix it by updating peft: `pip install git+https://github.com/huggingface/peft.git`
it will also be fixed in the next release of autotrain-advanced.

**Comment by VandeveldePaul** [comment]
Thank you, this solved the problem but i now have another one: module 'torch.nn.functional' has no attribute 'scaled_dot_product_attention'

Traceback:
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/buinno/Desktop/Falcon/autotrain-env/bin/autotrain:33 in <module>                           │
│                                                                                                  │
│   30                                                                                             │
│   31 if __name__ == '__main__':                                                                  │
│   32 │   sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])                       │
│ ❱ 33 │   sys.exit(load_entry_point('autotrain-advanced', 'console_scripts', 'autotrain')())      │
│   34                                                                                             │
│                                                                                                  │
│ /home/buinno/Desktop/Falcon/autotrain-advanced/src/autotrain/cli/autotrain.py:32 in main         │
│                                                                                                  │
│   29 │   │   exit(1)                                                                             │
│   30 │                                                                                           │
│   31 │   command = args.func(args)                                                               │
│ ❱ 32 │   command.run()                                                                           │
│   33                                                                                             │
│   34                                                                                             │
│   35 if __name__ == "__main__":                                                                  │
│                                                                                                  │
│ /home/buinno/Desktop/Falcon/autotrain-advanced/src/autotrain/cli/run_llm.py:479 in run           │
│                                                                                                  │
│   476 │   │   │   │   trainer=self.trainer,                                                      │
│   477 │   │   │   │   target_modules=self.target_modules,                                        │
│   478 │   │   │   )                                                                              │
│ ❱ 479 │   │   │   train_llm(params)                                                              │
│   480                                                                                            │
│                                                                                                  │
│ /home/buinno/Desktop/Falcon/autotrain-advanced/src/autotrain/trainers/clm.py:262 in train        │
│                                                                                                  │
│   259 │   │   #         if script_args.bf16 and module.weight.dtype == torch.float32:            │
│   260 │   │   #             module = module.to(torch.bfloat16)                                   │
│   261 │                                                                                          │
│ ❱ 262 │   trainer.train()                                                                        │
│   263 │                                                                                          │
│   264 │   logger.info("Finished training, saving model...")                                      │
│   265 │   trainer.save_model(config.project_name)                                                │
│                                                                                                  │
│ /home/buinno/Desktop/Falcon/autotrain-env/lib/python3.10/site-packages/transformers/trainer.py:1 │
│ 645 in train                                                                                     │
│                                                                                                  │
│   1642 │   │   inner_training_loop = find_executable_batch_size(                                 │
│   1643 │   │   │   self._inner_training_loop, self._train_batch_size, args.auto_find_batch_size  │
│   1644 │   │   )                                                                                 │
│ ❱ 1645 │   │   return inner_training_loop(                                                       │
│   1646 │   │   │   args=args,                                                                    │
│   1647 │   │   │   resume_from_checkpoint=resume_from_checkpoint,                                │
│   1648 │   │   │   trial=trial,                                                                  │
│                                                                                                  │
│ /home/buinno/Desktop/Falcon/autotrain-env/lib/python3.10/site-packages/transformers/trainer.py:1 │
│ 938 in _inner_training_loop                                                                      │
│                                                                                                  │
│   1935 │   │   │   │   │   self.control = self.callback_handler.on_step_begin(args, self.state,  │
│   1936 │   │   │   │                                                                             │
│   1937 │   │   │   │   with self.accelerator.accumulate(model):                                  │
│ ❱ 1938 │   │   │   │   │   tr_loss_step = self.training_step(model, inputs)                      │
│   1939 │   │   │   │                                                                             │
│   1940 │   │   │   │   if (                                                                      │
│   1941 │   │   │   │   │   args.logging_nan_inf_filter                                           │
│                                                                                                  │
│ /home/buinno/Desktop/Falcon/autotrain-env/lib/python3.10/site-packages/transformers/trainer.py:2 │
│ 759 in training_step                                                                             │
│                                                                                                  │
│   2756 │   │   │   return loss_mb.reduce_mean().detach().to(self.args.device)                    │
│   2757 │   │                                                                                     │
│   2758 │   │   with self.compute_loss_context_manager():                                         │
│ ❱ 2759 │   │   │   loss = self.compute_loss(model, inputs)                                       │
│   2760 │   │                                                                                     │
│   2761 │   │   if self.args.n_gpu > 1:                                                           │
│   2762 │   │   │   loss = loss.mean()  # mean() to average on multi-gpu parallel training        │
│                                                                                                  │
│ /home/buinno/Desktop/Falcon/autotrain-env/lib/python3.10/site-packages/transformers/trainer.py:2 │
│ 784 in compute_loss                                                                              │
│                                                                                                  │
│   2781 │   │   │   labels = inputs.pop("labels")                                                 │
│   2782 │   │   else:                                                                             │
│   2783 │   │   │   labels = None                                                                 │
│ ❱ 2784 │   │   outputs = model(**inputs)                                                         │
│   2785 │   │   # Save past state if it exists                                                    │
│   2786 │   │   # TODO: this needs to be fixed and made cleaner later.                            │
│   2787 │   │   if self.args.past_index >= 0:                                                     │
│                                                                                                  │
│ /home/buinno/Desktop/Falcon/autotrain-env/lib/python3.10/site-packages/torch/nn/modules/module.p │
│ y:1194 in _call_impl                                                                             │
│                                                                                                  │
│   1191 │   │   # this function, and just call forward.                                           │
│   1192 │   │   if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks o  │
│   1193 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1194 │   │   │   return forward_call(*input, **kwargs)                                         │
│   1195 │   │   # Do not call functions when jit is used                                          │
│   1196 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1197 │   │   if self._backward_hooks or _global_backward_hooks:                                │
│                                                                                                  │
│ /home/buinno/Desktop/Falcon/autotrain-env/lib/python3.10/site-packages/peft/peft_model.py:926 in │
│ forward                                                                                          │
│                                                                                                  │
│    923 │   │   │   │   │   **kwargs,                                                             │
│    924 │   │   │   │   )                                                                         │
│    925 │   │   │                                                                                 │
│ ❱  926 │   │   │   return self.base_model(                                                       │
│    927 │   │   │   │   input_ids=input_ids,                                                      │
│    928 │   │   │   │   attention_mask=attention_mask,                                            │
│    929 │   │   │   │   inputs_embeds=inputs_embeds,                                              │
│                                                                                                  │
│ /home/buinno/Desktop/Falcon/autotrain-env/lib/python3.10/site-packages/torch/nn/modules/module.p │
│ y:1194 in _call_impl                                                                             │
│                                                                                                  │
│   1191 │   │   # this function, and just call forward.                                           │
│   1192 │   │   if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks o  │
│   1193 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1194 │   │   │   return forward_call(*input, **kwargs)                                         │
│   1195 │   │   # Do not call functions when jit is used                                          │
│   1196 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1197 │   │   if self._backward_hooks or _global_backward_hooks:                                │
│                                                                                                  │
│ /home/buinno/Desktop/Falcon/autotrain-env/lib/python3.10/site-packages/accelerate/hooks.py:165   │
│ in new_forward                                                                                   │
│                                                                                                  │
│   162 │   │   │   with torch.no_grad():                                                          │
│   163 │   │   │   │   output = old_forward(*args, **kwargs)                                      │
│   164 │   │   else:                                                                              │
│ ❱ 165 │   │   │   output = old_forward(*args, **kwargs)                                          │
│   166 │   │   return module._hf_hook.post_forward(module, output)                                │
│   167 │                                                                                          │
│   168 │   module.forward = new_forward                                                           │
│                                                                                                  │
│ /home/buinno/.cache/huggingface/modules/transformers_modules/OpenAssistant/falcon-7b-sft-top1-69 │
│ 6/9f95b9e269c1d99c29f70be8d5ef3d0fb1bd1c30/modelling_RW.py:753 in forward                        │
│                                                                                                  │
│    750 │   │                                                                                     │
│    751 │   │   return_dict = return_dict if return_dict is not None else self.config.use_return  │
│    752 │   │                                                                                     │
│ ❱  753 │   │   transformer_outputs = self.transformer(                                           │
│    754 │   │   │   input_ids,                                                                    │
│    755 │   │   │   past_key_values=past_key_values,                                              │
│    756 │   │   │   attention_mask=attention_mask,                                                │
│                                                                                                  │
│ /home/buinno/Desktop/Falcon/autotrain-env/lib/python3.10/site-packages/torch/nn/modules/module.p │
│ y:1194 in _call_impl                                                                             │
│                                                                                                  │
│   1191 │   │   # this function, and just call forward.                                           │
│   1192 │   │   if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks o  │
│   1193 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1194 │   │   │   return forward_call(*input, **kwargs)                                         │
│   1195 │   │   # Do not call functions when jit is used                                          │
│   1196 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1197 │   │   if self._backward_hooks or _global_backward_hooks:                                │
│                                                                                                  │
│ /home/buinno/.cache/huggingface/modules/transformers_modules/OpenAssistant/falcon-7b-sft-top1-69 │
│ 6/9f95b9e269c1d99c29f70be8d5ef3d0fb1bd1c30/modelling_RW.py:640 in forward                        │
│                                                                                                  │
│    637 │   │   │   │   │                                                                         │
│    638 │   │   │   │   │   return custom_forward                                                 │
│    639 │   │   │   │                                                                             │
│ ❱  640 │   │   │   │   outputs = torch.utils.checkpoint.checkpoint(                              │
│    641 │   │   │   │   │   create_custom_forward(block),                                         │
│    642 │   │   │   │   │   hidden_states,                                                        │
│    643 │   │   │   │   │   alibi,                                                                │
│                                                                                                  │
│ /home/buinno/Desktop/Falcon/autotrain-env/lib/python3.10/site-packages/torch/utils/checkpoint.py │
│ :249 in checkpoint                                                                               │
│                                                                                                  │
│   246 │   │   raise ValueError("Unexpected keyword arguments: " + ",".join(arg for arg in kwar   │
│   247 │                                                                                          │
│   248 │   if use_reentrant:                                                                      │
│ ❱ 249 │   │   return CheckpointFunction.apply(function, preserve, *args)                         │
│   250 │   else:                                                                                  │
│   251 │   │   return _checkpoint_without_reentrant(                                              │
│   252 │   │   │   function,                                                                      │
│                                                                                                  │
│ /home/buinno/Desktop/Falcon/autotrain-env/lib/python3.10/site-packages/torch/utils/checkpoint.py │
│ :107 in forward                                                                                  │
│                                                                                                  │
│   104 │   │   ctx.save_for_backward(*tensor_inputs)                                              │
│   105 │   │                                                                                      │
│   106 │   │   with torch.no_grad():                                                              │
│ ❱ 107 │   │   │   outputs = run_function(*args)                                                  │
│   108 │   │   return outputs                                                                     │
│   109 │                                                                                          │
│   110 │   @staticmethod                                                                          │
│                                                                                                  │
│ /home/buinno/.cache/huggingface/modules/transformers_modules/OpenAssistant/falcon-7b-sft-top1-69 │
│ 6/9f95b9e269c1d99c29f70be8d5ef3d0fb1bd1c30/modelling_RW.py:636 in custom_forward                 │
│                                                                                                  │
│    633 │   │   │   │   def create_custom_forward(module):                                        │
│    634 │   │   │   │   │   def custom_forward(*inputs):                                          │
│    635 │   │   │   │   │   │   # None for past_key_value                                         │
│ ❱  636 │   │   │   │   │   │   return module(*inputs, use_cache=use_cache, output_attentions=ou  │
│    637 │   │   │   │   │                                                                         │
│    638 │   │   │   │   │   return custom_forward                                                 │
│    639                                                                                           │
│                                                                                                  │
│ /home/buinno/Desktop/Falcon/autotrain-env/lib/python3.10/site-packages/torch/nn/modules/module.p │
│ y:1194 in _call_impl                                                                             │
│                                                                                                  │
│   1191 │   │   # this function, and just call forward.                                           │
│   1192 │   │   if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks o  │
│   1193 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1194 │   │   │   return forward_call(*input, **kwargs)                                         │
│   1195 │   │   # Do not call functions when jit is used                                          │
│   1196 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1197 │   │   if self._backward_hooks or _global_backward_hooks:                                │
│                                                                                                  │
│ /home/buinno/Desktop/Falcon/autotrain-env/lib/python3.10/site-packages/accelerate/hooks.py:165   │
│ in new_forward                                                                                   │
│                                                                                                  │
│   162 │   │   │   with torch.no_grad():                                                          │
│   163 │   │   │   │   output = old_forward(*args, **kwargs)                                      │
│   164 │   │   else:                                                                              │
│ ❱ 165 │   │   │   output = old_forward(*args, **kwargs)                                          │
│   166 │   │   return module._hf_hook.post_forward(module, output)                                │
│   167 │                                                                                          │
│   168 │   module.forward = new_forward                                                           │
│                                                                                                  │
│ /home/buinno/.cache/huggingface/modules/transformers_modules/OpenAssistant/falcon-7b-sft-top1-69 │
│ 6/9f95b9e269c1d99c29f70be8d5ef3d0fb1bd1c30/modelling_RW.py:385 in forward                        │
│                                                                                                  │
│    382 │   │   residual = hidden_states                                                          │
│    383 │   │                                                                                     │
│    384 │   │   # Self attention.                                                                 │
│ ❱  385 │   │   attn_outputs = self.self_attention(                                               │
│    386 │   │   │   layernorm_output,                                                             │
│    387 │   │   │   layer_past=layer_past,                                                        │
│    388 │   │   │   attention_mask=attention_mask,                                                │
│                                                                                                  │
│ /home/buinno/Desktop/Falcon/autotrain-env/lib/python3.10/site-packages/torch/nn/modules/module.p │
│ y:1194 in _call_impl                                                                             │
│                                                                                                  │
│   1191 │   │   # this function, and just call forward.                                           │
│   1192 │   │   if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks o  │
│   1193 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1194 │   │   │   return forward_call(*input, **kwargs)                                         │
│   1195 │   │   # Do not call functions when jit is used                                          │
│   1196 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1197 │   │   if self._backward_hooks or _global_backward_hooks:                                │
│                                                                                                  │
│ /home/buinno/Desktop/Falcon/autotrain-env/lib/python3.10/site-packages/accelerate/hooks.py:165   │
│ in new_forward                                                                                   │
│                                                                                                  │
│   162 │   │   │   with torch.no_grad():                                                          │
│   163 │   │   │   │   output = old_forward(*args, **kwargs)                                      │
│   164 │   │   else:                                                                              │
│ ❱ 165 │   │   │   output = old_forward(*args, **kwargs)                                          │
│   166 │   │   return module._hf_hook.post_forward(module, output)                                │
│   167 │                                                                                          │
│   168 │   module.forward = new_forward                                                           │
│                                                                                                  │
│ /home/buinno/.cache/huggingface/modules/transformers_modules/OpenAssistant/falcon-7b-sft-top1-69 │
│ 6/9f95b9e269c1d99c29f70be8d5ef3d0fb1bd1c30/modelling_RW.py:279 in forward                        │
│                                                                                                  │
│    276 │   │   │   key_layer_ = key_layer.reshape(batch_size, self.num_kv, -1, self.head_dim)    │
│    277 │   │   │   value_layer_ = value_layer.reshape(batch_size, self.num_kv, -1, self.head_di  │
│    278 │   │   │                                                                                 │
│ ❱  279 │   │   │   attn_output = F.scaled_dot_product_attention(                                 │
│    280 │   │   │   │   query_layer_, key_layer_, value_layer_, None, 0.0, is_causal=True         │
│    281 │   │   │   )                                                                             │
│    282                                                                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯

I tried updating torch but then triton becomes incompatible because : The 'triton==2.0.0.dev20221202' distribution was not found and is required by autotrain-advanced

When i install 'triton==2.0.0.dev20221202', it installs a compatible torch version which gives the error.

Thank you,
Paul

**Comment by abhishekkrthakur** [comment]
you need pytorch 2.0. a new release with this fixed comes in less than 2 hours.

**Comment by VandeveldePaul** [comment]
Alright, thank you, waiting for this fix !
