### ISSUE TITLE
add command line argument for huggingface auth token

### ISSUE THREAD

**Issue by ghost** [huggingface/autotrain-advanced#148]
Would be great to have an option to provide huggingface authorization token in cli for llm training for example for accessing llama2 weights or accessing private repo

**Comment by abhishekkrthakur** [comment]
you can use `huggingface-cli login` command to login with your token before running the training :)

**Comment by viai957** [comment]
You can use 
''' from huggingface_hub import notebook_login
notebook_login()
'''
