### ISSUE TITLE
AutoTrain-Advanced command not working

### ISSUE THREAD

**Issue by Paduk** [huggingface/autotrain-advanced#154]
Hi. at first, i want to say thank you giving me a great packages and youtube resource.
i want to raise one issue.

even i installed autotrain-advanced, command not found
any ideas? 

tf-docker ~ > autotrain llm --help
bash: autotrain: command not found

**Comment by arghhjayy** [comment]
Can you pls provide the steps for recreating this? Did you use a virtual environment?
