### ISSUE TITLE
How to do inference via autotrain-advanced?

### ISSUE THREAD

**Issue by sujithjoseph** [huggingface/autotrain-advanced#155]
I see an option to do inference autotrain llm --help. 
1. Can you share command to do inference on say llama2 model ? How do you pass lora files to do inference?
2.  Any option to do merge and unload while saving the model locally?
3. Any option for multi-gpu training with single node - specify local rank?

**Comment by boehm-e** [comment]
+1
Could be great to have documentation for this feature.

**Comment by abhishekkrthakur** [comment]
sorry for my late response. autotrain is generally for training only. for inference, i'd recommend one of the options from huggingface. for example, if you want to do inference for llms, you can use text-generation-inference, deploy in spaces, deploy using inference endpoints or just simply use transformers. i might add a simple inference module to autotrain if there is interest but it will never be as optimized as the features mentioned above and will only be useful for testing purposes.

**Comment by boehm-e** [comment]
For those interested, you can try your model after training like this:

```
autotrain llm --inference --project_name <your_project> [--use_int4 | --use_int8]
```

**Comment by yairVanti** [comment]
all the options above assume the fine tuned model is pushed to huggingface and inferred from there.
i need to do inference locally (possibly with text-generation-inference installed locally)
how can i achieve it ?

**Comment by Luke-in-the-sky** [comment]
have you tried something like this?
```
model_path = 'abhishek/llama-2-7b-hf-small-shards'   # this is the base model, the one you started from and then finetuned
adapter_path = '/mylocaldir/my_autotrain_project'  # this is the path to the local dir where autotune saved your adapter

base_model = AutoModelForCausalLM.from_pretrained(
      model_path,  # this is the base model, the one you started from and then finetuned
      low_cpu_mem_usage=True,
      trust_remote_code=True,
      load_in_4bit=True,
      torch_dtype=torch.float16,
      device_map="auto",
  )
  
model = PeftModel.from_pretrained(
    base_model,
    adapter_path,
    torch_dtype=torch.float16,
    low_cpu_mem_usage=True,
    trust_remote_code=True,
    load_in_4bit=True,
    device_map="auto",
)

model.eval()

tokenizer = AutoTokenizer.from_pretrained(
      adapter_path,
      trust_remote_code=True,
  )

## Next, we want to generate some text. See https://huggingface.co/bertin-project/bertin-alpaca-lora-7b/discussions/1 for why we **can't** use a `pipeline` here

from transformers import GenerationConfig
import textwrap

def pipe(prompt_text):
  input_ids = tokenizer.encode(prompt_text, return_tensors="pt").to('cuda')
  generation_output = model.generate(
          input_ids=input_ids,
          generation_config=GenerationConfig(
              # these params you'll have to tweak
              do_sample=True,
              temperature=0.3,
              top_p=0.9,
              num_beams=2,
              ),
          return_dict_in_generate=True,
          output_scores=True,
          max_new_tokens=150
      )
  for seq in generation_output.sequences:
      output = tokenizer.decode(seq)
      wrapped_string = textwrap.fill(output, width=80)
      print(f'---\n{wrapped_string}')


pipe("""Hello World""")
```

**Comment by rsjenwar** [comment]
Hi @abhishekkrthakur @Luke-in-the-sky  when i tried above code to inference a finetune model with autotrain. I am htting below error. Kindly help.

RuntimeError                              Traceback (most recent call last)
[<ipython-input-8-d8edeca7d95c>](https://localhost:8080/#) in <cell line: 62>()
     60 
     61 
---> 62 pipe("""Hello World""")

4 frames
[/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py](https://localhost:8080/#) in beam_sample(self, input_ids, beam_scorer, logits_processor, stopping_criteria, logits_warper, max_length, pad_token_id, eos_token_id, output_attentions, output_hidden_states, output_scores, return_dict_in_generate, synced_gpus, **model_kwargs)
   3398             probs = nn.functional.softmax(next_token_scores, dim=-1)
   3399 
-> 3400             next_tokens = torch.multinomial(probs, num_samples=2 * num_beams)
   3401             next_token_scores = torch.gather(next_token_scores, -1, next_tokens)
   3402 

RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

**Comment by rsjenwar** [comment]
commenting  # num_beams=2, 
in GenerationConfig() i.e. using default solves the issue  (RuntimeError: probability tensor contains either inf, nan or element < 0)
But even after training, the inference is not able to answer direct questions  (what is X?) on trained data. How to fix this issue ?
