### ISSUE TITLE
Fine tuning example on llama 2?

### ISSUE THREAD

**Issue by ryanshrott** [huggingface/autotrain-advanced#157]
Does anyone have an example working? i tried:
! autotrain llm --train --project_name my-llm --model meta-llama/Llama-2-7b-hf --data_path . --use_peft --use_int4 --learning_rate 2e-4 --train_batch_size 12 --num_train_epochs 3 --trainer sft --push_to_hub --repo_id rshrott/my-llama-test

But it seems to get stuck pushing to hub!

**Comment by abhishekkrthakur** [comment]
is it stuck or is it pushing to hub? the model is huge so it might take a while depending on your network connection

**Comment by ryanshrott** [comment]
It's been running on lambda cloud server for 45 mins now!

**Comment by ryanshrott** [comment]
Push to hub worked for anyone else?

**Comment by ryanshrott** [comment]
@abhishekkrthakur it just worked! took me 1hr to push to hub

**Comment by abhishekkrthakur** [comment]
As i said, the model size is huge and it takes time depending on how fast your internet is :)

**Comment by ryanshrott** [comment]
@abhishekkrthakur  have you tried using petals.ml for inference?

**Comment by ryanshrott** [comment]
@abhishekkrthakur I just tried deploying on HF as API endpoint for inference and it gives me errors. Any idea why?

RuntimeError(f\"weight {tensor_name} does not exist\")\n\nRuntimeError: weight model.layers.0.self_attn.rotary_emb.inv_freq does not exist\n"},"target":"text_generation_launcher","span":{"rank":0,"name":"shard-manager"},"spans":[{"rank":0,"name":"shard-manager"}]}
2023/07/23 10:26:45 ~ {"timestamp":"2023-07-23T14:26:45.609094Z","level":"ERROR","fields":{"message":"Shard 0 failed to start"},"target":"text_generation_launcher"}
2023/07/23 10:26:45 ~ {"timestamp":"2023-07-23T14:26:45.609124Z","level":"INFO","fields":{"message":"Shutting down shards"},"target":"text_generation_launcher"}
2023/07/23 10:26:45 ~ Error: ShardCannotStart

**Comment by Darshan2003** [comment]
On running this command:
`!autotrain llm --train --project_name my-llm --model meta-llama/Llama-2-7b-hf --data_path . --use_peft --use_int4 --learning_rate 2e-4 --train_batch_size 4 --num_train_epochs 3 --trainer sft
`

I get following error:
```
> INFO    Running LLM
> INFO    Train: True
/usr/local/lib/python3.10/dist-packages/datasets/load.py:2069: FutureWarning: 'use_auth_token' was deprecated in favor of 'token' in version 2.14.0 and will be removed in 3.0.0.
You can remove this warning by passing 'token=None' instead.
  warnings.warn(
Downloading data files: 100% 1/1 [00:00<00:00, 7121.06it/s]
Extracting data files: 100% 1/1 [00:00<00:00, 450.52it/s]
Generating train split: 10 examples [00:00, 1106.65 examples/s]
Using pad_token, but it is not set yet.
Loading checkpoint shards: 100% 2/2 [01:04<00:00, 32.07s/it]
/usr/local/lib/python3.10/dist-packages/peft/utils/other.py:102: FutureWarning: prepare_model_for_int8_training is deprecated and will be removed in a future version. Use prepare_model_for_kbit_training instead.
  warnings.warn(
Running tokenizer on train dataset: 100% 10/10 [00:00<00:00, 98.33 examples/s]
Grouping texts in chunks of 1024 (num_proc=4): 100% 10/10 [00:00<00:00, 30.09 examples/s]
> INFO    creating trainer
Traceback (most recent call last):
  File "/usr/local/bin/autotrain", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/autotrain/cli/autotrain.py", line 36, in main
    command.run()
  File "/usr/local/lib/python3.10/dist-packages/autotrain/cli/run_llm.py", line 489, in run
    train_llm(params)
  File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/clm.py", line 280, in train
    trainer.train()
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 1553, in _inner_training_loop
    train_dataloader = self.get_train_dataloader()
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 850, in get_train_dataloader
    dataloader_params["sampler"] = self._get_train_sampler()
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 821, in _get_train_sampler
    return RandomSampler(self.train_dataset)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/sampler.py", line 107, in _init_
    raise ValueError("num_samples should be a positive integer "
ValueError: num_samples should be a positive integer value, but got num_samples=0
```

I'm testing it with 10 samples in my `train.csv` file. 
Doing all this on google colab

Cannot understand why it gives this error

**Comment by pavan-growexxer** [comment]
> On running this command: `!autotrain llm --train --project_name my-llm --model meta-llama/Llama-2-7b-hf --data_path . --use_peft --use_int4 --learning_rate 2e-4 --train_batch_size 4 --num_train_epochs 3 --trainer sft `
> 
> I get following error:
> 
> ```
> > INFO    Running LLM
> > INFO    Train: True
> /usr/local/lib/python3.10/dist-packages/datasets/load.py:2069: FutureWarning: 'use_auth_token' was deprecated in favor of 'token' in version 2.14.0 and will be removed in 3.0.0.
> You can remove this warning by passing 'token=None' instead.
>   warnings.warn(
> Downloading data files: 100% 1/1 [00:00<00:00, 7121.06it/s]
> Extracting data files: 100% 1/1 [00:00<00:00, 450.52it/s]
> Generating train split: 10 examples [00:00, 1106.65 examples/s]
> Using pad_token, but it is not set yet.
> Loading checkpoint shards: 100% 2/2 [01:04<00:00, 32.07s/it]
> /usr/local/lib/python3.10/dist-packages/peft/utils/other.py:102: FutureWarning: prepare_model_for_int8_training is deprecated and will be removed in a future version. Use prepare_model_for_kbit_training instead.
>   warnings.warn(
> Running tokenizer on train dataset: 100% 10/10 [00:00<00:00, 98.33 examples/s]
> Grouping texts in chunks of 1024 (num_proc=4): 100% 10/10 [00:00<00:00, 30.09 examples/s]
> > INFO    creating trainer
> Traceback (most recent call last):
>   File "/usr/local/bin/autotrain", line 8, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python3.10/dist-packages/autotrain/cli/autotrain.py", line 36, in main
>     command.run()
>   File "/usr/local/lib/python3.10/dist-packages/autotrain/cli/run_llm.py", line 489, in run
>     train_llm(params)
>   File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/clm.py", line 280, in train
>     trainer.train()
>   File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 1539, in train
>     return inner_training_loop(
>   File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 1553, in _inner_training_loop
>     train_dataloader = self.get_train_dataloader()
>   File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 850, in get_train_dataloader
>     dataloader_params["sampler"] = self._get_train_sampler()
>   File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 821, in _get_train_sampler
>     return RandomSampler(self.train_dataset)
>   File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/sampler.py", line 107, in _init_
>     raise ValueError("num_samples should be a positive integer "
> ValueError: num_samples should be a positive integer value, but got num_samples=0
> ```
> 
> I'm testing it with 10 samples in my `train.csv` file. Doing all this on google colab
> 
> Cannot understand why it gives this error

Autotrain requires atleast 50 rows, otherwise it throws this error.

**Comment by Clairemuw** [comment]
Does anyone know what could cause this. V**alueError: Token must be specified for push to hub.**
error pushing model to hugging face Traceback (most recent call last):
  File "/usr/local/bin/autotrain", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/autotrain/cli/autotrain.py", line 47, in main
    command = args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/autotrain/cli/run_llm.py", line 14, in run_llm_command_factory
    return RunAutoTrainLLMCommand(args)
  File "/usr/local/lib/python3.10/dist-packages/autotrain/cli/run_llm.py", line 445, in __init__
    raise ValueError("Token must be specified for push to hub")
ValueError: Token must be specified for push to hub. here is the code **!autotrain llm --train --project_name 'llama2-alpaca-gpt4' --model TinyPixel/Llama-2-7B-bf16-sharded --data_path vicgalle/alpaca-gpt4 --text_column text --use_peft --use_int4 --learning_rate 2e-4 --train_batch_size 2 --num_train_epochs 3 --trainer sft --push_to_hub --repo_id nameofrepo**

**Comment by Nicat-dcw** [comment]
> On running this command: `!autotrain llm --train --project_name my-llm --model meta-llama/Llama-2-7b-hf --data_path . --use_peft --use_int4 --learning_rate 2e-4 --train_batch_size 4 --num_train_epochs 3 --trainer sft `
> 
> I get following error:
> 
> ```
> > INFO    Running LLM
> > INFO    Train: True
> /usr/local/lib/python3.10/dist-packages/datasets/load.py:2069: FutureWarning: 'use_auth_token' was deprecated in favor of 'token' in version 2.14.0 and will be removed in 3.0.0.
> You can remove this warning by passing 'token=None' instead.
>   warnings.warn(
> Downloading data files: 100% 1/1 [00:00<00:00, 7121.06it/s]
> Extracting data files: 100% 1/1 [00:00<00:00, 450.52it/s]
> Generating train split: 10 examples [00:00, 1106.65 examples/s]
> Using pad_token, but it is not set yet.
> Loading checkpoint shards: 100% 2/2 [01:04<00:00, 32.07s/it]
> /usr/local/lib/python3.10/dist-packages/peft/utils/other.py:102: FutureWarning: prepare_model_for_int8_training is deprecated and will be removed in a future version. Use prepare_model_for_kbit_training instead.
>   warnings.warn(
> Running tokenizer on train dataset: 100% 10/10 [00:00<00:00, 98.33 examples/s]
> Grouping texts in chunks of 1024 (num_proc=4): 100% 10/10 [00:00<00:00, 30.09 examples/s]
> > INFO    creating trainer
> Traceback (most recent call last):
>   File "/usr/local/bin/autotrain", line 8, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python3.10/dist-packages/autotrain/cli/autotrain.py", line 36, in main
>     command.run()
>   File "/usr/local/lib/python3.10/dist-packages/autotrain/cli/run_llm.py", line 489, in run
>     train_llm(params)
>   File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/clm.py", line 280, in train
>     trainer.train()
>   File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 1539, in train
>     return inner_training_loop(
>   File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 1553, in _inner_training_loop
>     train_dataloader = self.get_train_dataloader()
>   File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 850, in get_train_dataloader
>     dataloader_params["sampler"] = self._get_train_sampler()
>   File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 821, in _get_train_sampler
>     return RandomSampler(self.train_dataset)
>   File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/sampler.py", line 107, in _init_
>     raise ValueError("num_samples should be a positive integer "
> ValueError: num_samples should be a positive integer value, but got num_samples=0
> ```
> 
> I'm testing it with 10 samples in my `train.csv` file. Doing all this on google colab
> 
> Cannot understand why it gives this error

Which auto train version are you used in this

**Comment by abhishekkrthakur** [comment]
10 samples is too little. use > 50

**Comment by Nicat-dcw** [comment]
I got this error: usage: autotrain <command> [<args>] autotrain advanced cli: error: unrecognized arguments: --data_path . --use_peft --use_int4 --learning_rate 2e-4 --train_batch_size 12 --num_train_epochs 3 --push_to_hub --repo_id onlycheeini/mistral-7b-mj-finetuned

**Comment by Clairemuw** [comment]
used 52,000 same error
