### ISSUE TITLE
MultiGPU with AutoTrain

### ISSUE THREAD

**Issue by ahmadmustafaanis** [huggingface/autotrain-advanced#159]
I have 2 T4 on Kaggle. How to use them both.

command:
```bash
$ !autotrain llm --train --project_name llamav2 --model abhishek/llama-2-7b-hf-small-shards --data_path . --use_peft --use_int4 --learning_rate 2e-4 --train_batch_size 4 --num_train_epochs 1 --trainer sft
```
It is using single GPU only. How to do multi training.

**Comment by Patrick10203** [comment]
Have the exact same issue. When there are more than one Graficscard available it uses all of them but only uses 1 at time to do processing and jumps between cards every step. So one graficscard is used 100% all other 0%. But memory is full on all of them.

**Comment by qas2021** [comment]
@tobi can you elaborate please, I'm a beginner in this
