### ISSUE TITLE
not enough GPU  RAM on  Nvidia 3060 GPU  (12GB RAM)

### ISSUE THREAD

**Issue by RocketStar** [huggingface/autotrain-advanced#162]
I tried to run on my Linux desktop with Nvidia 3060 GPU  (12GB RAM), but ran into errors complaining not enough GPU  RAM.
Here is the command:

`$ autotrain llm --train --project_name my-llm --model abhishek/llama-2-7b-hf-small-shards  --data_path . --use_peft --use_int4 --learning_rate 2e-4 --train_batch_size 1 --num_train_epochs 3 --trainer sft`

Here is the error message:
 Some modules are dispatched on the CPU or the disk. Make sure you have enough GPU RAM to fit the quantized model. If you want to dispatch the model on the CPU or the disk while keeping these modules in 32-bit, you need to set `load_in_8bit_fp32_cpu_offload=True` and pass a custom `device_map` to `from_pretrained`.

**Comment by abhishekkrthakur** [comment]
did you do setup using `autotrain setup` command?

**Comment by RocketStar** [comment]
first do setup using autotrain setup command, and then start training.  Now it has a different error:

`raise ImportError(
ImportError: Using `load_in_8bit=True` requires Accelerate: `pip install accelerate` and the latest version of bitsandbytes `pip install -i https://test.pypi.org/simple/ bitsandbytes` or pip install bitsandbytes` `

**Comment by atanuGuin** [comment]
> did you do setup using `autotrain setup` command?

The autotrain setup command executed successfully, Still I'm facing same error. Is there anyway to pass this argument `load_in_8bit_fp32_cpu_offload=True`  to autotrain llm command options?
