### ISSUE TITLE
Can't get email confirmation thus can't use HF

### ISSUE THREAD

**Issue by giladros** [huggingface/autotrain-advanced#168]
Hi,

I can't confirm my email.
I once got this email, confirmed and it wasn't updated in HF that it was confirmed.
Since then , when I press resend confirmation number i dont get the email.

Please help, can't login for a couple of weeks now.
please see the first time I pressed confirm suggesting a bug on your end. thanks!

![image (43)](https://github.com/huggingface/autotrain-advanced/assets/36266885/dd1e237d-140b-4ba8-8d40-7821ab313ecf)

**Comment by abhishekkrthakur** [comment]
@Michellehbn

**Comment by Michellehbn** [comment]
Hi @giladros ! Thanks for reaching out and sorry to hear about the email confirmation issue. Can you let us know the email address or username ? If you prefer to send me an email with this information please feel free! My email is michelle@huggingface.co and you can cc: website@huggingface.co. Thanks!
