### ISSUE TITLE
SDXL Dreambooth checkpoint not saving in Colab. 

### ISSUE THREAD

**Issue by sandeshrajbhandari** [huggingface/autotrain-advanced#172]
I'm using following settings but still encounter OOM error after the training run stops.
```
!autotrain dreambooth \
--model stabilityai/stable-diffusion-xl-base-1.0 \
--output output/ \
--image-path /input\
--prompt "photo of sks man" \
--resolution 512 \
--batch-size 1 \
--num-steps 500 \
--fp16 \
--gradient-accumulation 4 \
--lr 1e-4 \
--use-8bit-adam \
```
- error log
```
Steps: 100% 500/500 [28:39<00:00,  3.65s/it, loss=0.138, lr=0.0001]Traceback (most recent call last):
  File "/usr/local/bin/autotrain", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/autotrain/cli/autotrain.py", line 36, in main
    command.run()
  File "/usr/local/lib/python3.10/dist-packages/autotrain/cli/run_dreambooth.py", line 469, in run
    train_dreambooth(params)
  File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/dreambooth/main.py", line 248, in train
    trainer.train()
  File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/dreambooth/trainer.py", line 395, in train
    self._save_checkpoint()
  File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/dreambooth/trainer.py", line 280, in _save_checkpoint
    self.accelerator.save_state(save_path)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/accelerator.py", line 2551, in save_state
    weights.append(self.get_state_dict(model, unwrap=False))
  File "/usr/local/lib/python3.10/dist-packages/accelerate/accelerator.py", line 2851, in get_state_dict
    state_dict[k] = state_dict[k].float()
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 14.75 GiB total capacity; 12.75 GiB already allocated; 4.81 MiB free; 13.43 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Steps: 100% 500/500 [28:40<00:00,  3.44s/it, loss=0.138, lr=0.0001]
```

is it trying to save the whole model instead of the LORA?

**Comment by abhishekkrthakur** [comment]
No. it only saves LORA. However, it seems like GPU memory is exploding for some reason. Could you try by adding `--xformers` parameter?

**Comment by abhishekkrthakur** [comment]
Using checkpointing-steps and setting it to a very high value (not saving checkpoints), could solve your issue. please let us know :)

**Comment by sandeshrajbhandari** [comment]
it works. do you know of any workaround to train on 1024px images? 

```
%%time
!accelerate launch --mixed_precision="fp16"  train_dreambooth_lora_sdxl.py \
  --pretrained_model_name_or_path="stabilityai/stable-diffusion-xl-base-1.0" \
  --instance_data_dir="/content/irfan" \
  --instance_prompt="a photo of irfn person" \
  --resolution=512 \
  --train_batch_size=1 \
  --gradient_accumulation_steps=5 \
  --gradient_checkpointing \
  --max_train_steps=250 \
  --learning_rate=1e-04 \
  --output_dir="/content/output" \
  --use_8bit_adam \
  --enable_xformers_memory_efficient_attention \
  --checkpointing_steps=2000
```

**Comment by danieltanhx** [comment]
i think the conversion from torch.float16 to float32 max out the gpu ram. i directly comment it out in accelerate.py directly in the library. if you think it's risky, then can build a new environment git clone accelerate and pip install -e. to modify it
            state_dict = model.state_dict()

        #if state_dict is not None:
         #   for k in state_dict:
          #      if getattr(state_dict[k], "dtype", None) == torch.float16:
           #         state_dict[k] = state_dict[k].float()

**Comment by abhishekkrthakur** [comment]
> it works. do you know of any workaround to train on 1024px images?
for that you need to have colab pro, unfortunately

**Comment by danieltanhx** [comment]
Actually, we can use free Kaggle P100 gpu and train 1024 size

**Comment by sandeshrajbhandari** [comment]
> Actually, we can use free Kaggle P100 gpu and train 1024 size

thanks for the tip. I tried it for 50 steps, and there is no OOM error. I didn't realize they offered p100 and 2 T4s. gonna have to port the code to work on Kaggle. but definitely worth it. 

I still don't understand why colab t4 with 15 gb vram gives OOM error, while p100 on kaggle with 16gb vram doesn't?

**Comment by danieltanhx** [comment]
T4 only gives 14.8GB in full VRAM while P100 gives 15.9GB. u can check the colab/kaggle resources
