### ISSUE TITLE
Got fully blacked out image at inference after training SDXL

### ISSUE THREAD

**Issue by alexcode4u** [huggingface/autotrain-advanced#173]
I use following command. It works on kaggle:
!autotrain dreambooth \
--model stabilityai/stable-diffusion-xl-base-1.0 \
--output output/ \
--image-path images/ \
--prompt "photo of sks person" \
--resolution 1024 \
--batch-size 1 \
--epochs 250 \
--fp16 \
--gradient-accumulation 4 \
--lr 1e-4 \
--use-8bit-adam \
--checkpointing-steps 100000

I set checkpointing-steps to huge number because when checkpoints save, i get cuda OOM.
After training i downloaded lora weights, used inference code from [here](https://gist.github.com/abhishekkrthakur/ebe82f7140d3b5bff925320d59972b14), and for prompt: "photo of dog" got fully blacked out image.

**Comment by abhishekkrthakur** [comment]
do all prompts produce full black image or just one? nsfw filter is enabled by default which might give black images if it thinks its nsfw.

**Comment by alexcode4u** [comment]
@abhishekkrthakur When i use lora weights all prompts produce black images. I also tried to disable nsfw filter. When i don't use lora weights, i'm able to generate usual and nsfw images, but when i use lora weights i can't generate anything, only black images.

**Comment by alexcode4u** [comment]
But the "images" folder contains pictures similar to nsfw. I looked at the sources, seems like nsfw filter is disabled during training.

**Comment by alexcode4u** [comment]
@abhishekkrthakur But actually "images" folder is not nsfw, that's just me at the beach. I want to save beach style for SD.

**Comment by abhishekkrthakur** [comment]
Definitely. the folder can contain anything. it seems like the model isnt learning. Could you set the epochs to 1 and steps to 500?

I'd usually set steps to 100xNumber of images. 

You can also try removing 8bit adam.

**Comment by abhishekkrthakur** [comment]
If there's no person in the image, you can also set prompt to "photo of sks object"

**Comment by alexcode4u** [comment]
@abhishekkrthakur I replaced epochs to num-steps and removed 8bitAdam, now everything works.
