### ISSUE TITLE
Custom model path?

### ISSUE THREAD

**Issue by KnutJaegersberg** [huggingface/autotrain-advanced#176]
would be handy to be able to point the command line tool to our own model path? Right now, the easiest approach is to let the tool re-download the models, for huge ones that's not very handy.

**Comment by KnutJaegersberg** [comment]
I donwloaded models with git command, not within transformers. It appears to expect the model folder just as downloaded by transformers.

**Comment by KnutJaegersberg** [comment]
(I already tried to place my model folders in the huggingface caching folder)

**Comment by ekimia** [comment]
@KnutJaegersberg have an example? im looking to cache some of these bulky model files as well.
