### ISSUE TITLE
Error while Pip installing

### ISSUE THREAD

**Issue by Karthikk-2003** [huggingface/autotrain-advanced#180]
![image](https://github.com/huggingface/autotrain-advanced/assets/88925956/29aeb9eb-cd1a-4f3d-a1fa-dfba5a86afeb)
this is the preview for the error

**Comment by evanrodgers** [comment]
I am getting this error as well. Check out some of the other issues here on this repo, some people have had success manually installing some of the dependencies.

Are you trying to use WSL btw?

**Comment by wyxos** [comment]
I got the same error, both on Windows 11 and inside a WSL instance.

**Comment by Karthikk-2003** [comment]
> 

Oh thanks for the idea, and yes I'm trying to use WSL

**Comment by Karthikk-2003** [comment]
> I got the same error, both on Windows 11 and inside a WSL instance.

Did u rectified that error? If yes can u provide more details for how to solve the problem please?

**Comment by wyxos** [comment]
@Karthikk-2003 Unfortunately no. I encountered this error while following a video to train SDXL. I am exploring another option at the moment via Kohya.
I wanted to consider the suggestion of fixing dependencies manually, but suspect that there'd be a lot of them to go through and while I understand programming, I am not fluent with python.

**Comment by Karthikk-2003** [comment]
> @Karthikk-2003 Unfortunately no. I encountered this error while following a video to train SDXL. I am exploring another option at the moment via Kohya. I wanted to consider the suggestion of fixing dependencies manually, but suspect that there'd be a lot of them to go through and while I understand programming, I am not fluent with python.

**Comment by Karthikk-2003** [comment]
@wyxos, I want to fine-tune my GPT model. If you have any ideas, can you help me out with this?

**Comment by wyxos** [comment]
@Karthikk-2003 I am not very familiar with training LLM but I recall seeing that hugging face has spaces to allow such training and has a version of CPU that's free. You may want to search around that option. If your use case requires local fine tuning, I suspect the only way at the moment would be to figure out and sort the issue around installing autotrainer.

**Comment by neue** [comment]
Same error on M1 Mac

**Comment by abhishekkrthakur** [comment]
Removed some requirements and pushed updated version. M1/M2 mac is now working fine with installation. I have just tested.
triton will need to be installed by end-user if they need it.

**Comment by abhishekkrthakur** [comment]
please try: `pip install -U autotrain-advanced` and check if it gets version 0.6.15

**Comment by wyxos** [comment]
@abhishekkrthakur Thanks. That is absolutely strange, was there an update to the package or something? Been running this exact command since then and all of a sudden it's now working.

**Comment by abhishekkrthakur** [comment]
yes. we pushed some fixes and made an update. glad to know its working now.

**Comment by Karthikk-2003** [comment]
> @Karthikk-2003 I am not very familiar with training LLM but I recall seeing that hugging face has spaces to allow such training and has a version of CPU that's free. You may want to search around that option. If your use case requires local fine tuning, I suspect the only way at the moment would be to figure out and sort the issue around installing autotrainer.

hey thanks, btw can you help me to delete those models, I've installed ton of GPT models through Visual Studio Code where it automatically downloaded those models when I just typed their names in the "model name", I'm running out of storage, Please someone help me to figure out how to delete those models, I don't remember Some of the model name that I've downloaded

**Comment by abhishekkrthakur** [comment]
models are downloaded in HF_CACHE which is usually located at `~/.cache/huggingface`
