### ISSUE TITLE
Error while training a local model

### ISSUE THREAD

**Issue by brngylni** [huggingface/autotrain-advanced#182]
autotrain llm --train --project_name "pythonProject" --model "D:\internship\oobabooga_windows\oobabooga_windows\text-generation-webui\models\Llama-2-7b-hf" --data_path "D:\internship\archive" --use_peft --learning_rate 2e-4 --train_batch_size 12 --num_train_epochs 3 --trainer sft

Using the above command to train the model I downloaded from hugging face but it gives the following error:

D:\internship\pythonProject\venv\lib\site-packages\bitsandbytes\cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
'NoneType' object has no attribute 'cadam32bit_grad_fp32'
D:\internship\pythonProject\venv\lib\site-packages\torchvision\io\image.py:13: UserWarning: Failed to load image Python extension:
 'Could not find module 'D:\internship\pythonProject\venv\Lib\site-packages\torchvision\image.pyd' (or one of its dependencies). T
ry using the full path with constructor syntax.'If you don't plan on using image functionality from `torchvision.io`, you can igno
re this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
> INFO    Running LLM
> INFO    Train: True
Found cached dataset json (C:/Users/hp/.cache/huggingface/datasets/json/archive-b901b5331764b9f2/0.0.0/8bb11242116d547c741b2e8a1f18598ffdd40a1d4f2a2872c7a28b697434bc96)
Using pad_token, but it is not set yet.
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 14.39it/s]
Traceback (most recent call last):
  File "D:\Program Files\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Program Files\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\internship\pythonProject\venv\Scripts\autotrain.exe\__main__.py", line 7, in <module>
  File "D:\internship\pythonProject\venv\lib\site-packages\autotrain\cli\autotrain.py", line 36, in main
    command.run()
  File "D:\internship\pythonProject\venv\lib\site-packages\autotrain\cli\run_llm.py", line 489, in run
    train_llm(params)
  File "D:\internship\pythonProject\venv\lib\site-packages\autotrain\trainers\clm.py", line 105, in train
    model = AutoModelForCausalLM.from_pretrained(
  File "D:\internship\pythonProject\venv\lib\site-packages\transformers\models\auto\auto_factory.py", line 511, in from_pretrained
    return model_class.from_pretrained(
  File "D:\internship\pythonProject\venv\lib\site-packages\transformers\modeling_utils.py", line 2996, in from_pretrained
    dispatch_model(model, **kwargs)
  File "D:\internship\pythonProject\venv\lib\site-packages\accelerate\big_modeling.py", line 364, in dispatch_model
    weights_map = OffloadedWeightsLoader(
  File "D:\internship\pythonProject\venv\lib\site-packages\accelerate\utils\offload.py", line 150, in __init__
    raise ValueError("Need either a `state_dict` or a `save_folder` containing offloaded weights.")
ValueError: Need either a `state_dict` or a `save_folder` containing offloaded weights.

**Comment by abhishekkrthakur** [comment]
does your model path have all files as here: https://huggingface.co/meta-llama/Llama-2-7b-hf/tree/main ?

**Comment by brngylni** [comment]
> does your model path have all files as here: https://huggingface.co/meta-llama/Llama-2-7b-hf/tree/main ? 

Yes actually I just cloned the repo into that directory.

**Comment by brngylni** [comment]
> does your model path have all files as here: https://huggingface.co/meta-llama/Llama-2-7b-hf/tree/main ?

When I try to use autotrain like in your video, it tries to download the model again and uses the C drive for this which I don't want. How do I use a local directory for this?

**Comment by ogensec** [comment]
Did you find a way to train a local model ? local path not working

**Comment by abhishekkrthakur** [comment]
whats the error using local path? many including me have tried and it works.

**Comment by ogensec** [comment]
Commande : 

autotrain llm --train --project_name custom-llm --model "/home/ogs-x/Desktop/development/llama-node/test/llama-2-7b.ggmlv3.q8_0.bin" --data_path . --use_peft --use_int4 --learning_rate 2e-4 --train_batch_size 2 --num_train_epochs 3 --trainer sft --model_max_length 2048

Error : 
![image](https://github.com/huggingface/autotrain-advanced/assets/40295857/24a971a1-68b2-45ff-87da-127120e49bab)


Thanks for your help

**Comment by abhishekkrthakur** [comment]
ggml doesnt work. please use a folder with safetensors instead

**Comment by ogensec** [comment]
Ok, sorry I'm noob with IA model, I'm still trying to find how to get a tensorflow folder :D anyway thanks for you help.

**Comment by abhishekkrthakur** [comment]
here is the folder for the model you are trying to train. you can either git clone this url or download all files manually in a folder and then point the model argument to that folder. or you can just do --model meta-llama/Llama-2-7b and it will download everything and start training.

**Comment by ogensec** [comment]
Thank you very much

**Comment by ogensec** [comment]
So we can only train original model from meta-llama, it's not possible to train a model like this one :
https://huggingface.co/TheBloke/Llama-2-7B-Chat-GGML or any other "chat" model ?

**Comment by abhishekkrthakur** [comment]
here is chat model too: https://huggingface.co/meta-llama/Llama-2-7b-chat-hf
Ggml is not possible yet.
