### ISSUE TITLE
what's the best approach to fine tuning Llama-2-chat models?

### ISSUE THREAD

**Issue by astarostap** [huggingface/autotrain-advanced#189]
I've seen Abhishek's youtube video on how to fine tune Llama-2 base models and multiple blogs also doing the same. But, what's the best way to fine tune chat models so that you can leverage their chat ability but train them on more tasks?

**Comment by ivahno** [comment]
I would like to see an example too

**Comment by astarostap** [comment]
@ivahno i found this good video: https://www.youtube.com/watch?v=Kbk16bqmtO0
