### ISSUE TITLE
Push an already autotrained model to hub

### ISSUE THREAD

**Issue by abhinand5** [huggingface/autotrain-advanced#190]
I have trained a model with autotrain with `--repo_id` argument but I didn't already have the model repo created on huggingface so the it threw an error in the end - `huggingface_hub.utils._errors.RepositoryNotFoundError`. 

Running the command again only retrains the model. Now how do I push it to hub?

**Comment by abhishekkrthakur** [comment]
please share the full command used. did you also login with `huggingface-cli login` before running the training command?

**Comment by abhinand5** [comment]
I used this command: 
 
```
autotrain llm --train --project_name 'llama2-custom' \
    --model TinyPixel/Llama-2-7B-bf16-sharded \
    --data_path abhinand/llama2-custom-dataset \
    --train_split train \
    --text_column text \
    --use_peft --use_int4 \
    --learning_rate 2e-4 \
    --train_batch_size 2 \
    --num_train_epochs 1 \
    --trainer sft \
    --model_max_length 512 \
    --push_to_hub \
    --repo_id abhinand/llama2-custom-model \
    --block_size 512 |& tee training.log
```

This is the command that I used. And before doing this I logged in with `huggingface-cli login` using an access token that had R/W access. Both the model and dataset are private. 

Train stage was successful but it did not push the model to hub because of `RepositoryNotFoundError` which was actually the case because I thought `autotrain` would create the model repo for me.

Is there a way to push the model after completing the training? I tried to do it with code but it complained saying that `config.json` is not available. The same is reported here #166

**Comment by abhinand5** [comment]
This issue got resolved in a new environment after I did `autotrain setup` and `pip install accelerate --upgrade`.
