### ISSUE TITLE
Is it possible to train without GPU? I have 

### ISSUE THREAD

**Issue by Koushik667** [huggingface/autotrain-advanced#194]
i have a server with 1 TB of RAM, I am getting following error 

~/proj$ autotrain llm --train --project_name my-llm --model meta-llama/Llama-2-7b-hf --data_path . --use_peft --learning_rate 2e-4 --train_batch_size 6 --num_train_epochs 3 --trainer sft
/home/kopadava/.local/lib/python3.8/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
/home/kopadava/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cpu.so: undefined symbol: cadam32bit_grad_fp32
2023-08-09 23:32:19.214711: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
> WARNING ❌ Some DreamBooth components are missing! Please run `autotrain setup` to install it. Ignore this warning if you are not using DreamBooth or running `autotrain setup` already.
Traceback (most recent call last):
  File "/home/kopadava/.local/bin/autotrain", line 8, in <module>
    sys.exit(main())
  File "/home/kopadava/.local/lib/python3.8/site-packages/autotrain/cli/autotrain.py", line 35, in main
    command = args.func(args)
  File "/home/kopadava/.local/lib/python3.8/site-packages/autotrain/cli/run_llm.py", line 16, in run_llm_command_factory
    return RunAutoTrainLLMCommand(args)
  File "/home/kopadava/.local/lib/python3.8/site-packages/autotrain/cli/run_llm.py", line 359, in __init__
    raise ValueError("No GPU found. Please install CUDA and try again.")
ValueError: No GPU found. Please install CUDA and try again.

Since sufficient RAM is available, Can you please let me know how i can train it with CPU alone?

**Comment by sakshamio** [comment]
Hey, I went through the code, and turns out you can't use auto train without GPUs for now - And that's for good reason. Bitsandbytes is a lightweight wrapper around CUDA custom functions, which really helps you optimize your model training. There are a lot of resources around training models with very little gpu memory. I would recommend using google colab, or other cloud instances to train your models.
