### ISSUE TITLE
Blurry dreambooth images

### ISSUE THREAD

**Issue by chris-aeviator** [huggingface/autotrain-advanced#199]
I'm getting blurry outputs with AutoTrain Advanced using SDXL https://colab.research.google.com/github/huggingface/autotrain-advanced/blob/main/colabs/AutoTrain_Dreambooth.ipynb

Kept the standard settings and only disabled gradient checkpointing. Training 500 steps on 21 images (and yes it's supermarkets ;) ).

![grafik](https://github.com/huggingface/autotrain-advanced/assets/11522213/84e321b2-cf0f-48fe-b2ef-867589df4f86)

### edit:
prompt used for training and generation:

prompt = 'photo of a wYeF8yu5 supermarket'

**Comment by abhishekkrthakur** [comment]
do you use refiner?

**Comment by chris-aeviator** [comment]
@abhishekkrthakur  yes - using pretty much the exact same code

```
    seed = random.randint(1, torch.initial_seed())
    generator = torch.Generator("cuda").manual_seed(seed)
    image = pipe(
        prompt=prompt,
        negative_prompt="woman, human head, human, face, eyes, hands, legs, animal, side angle, bottles, bottle, cups, cup, sharp edge of models, hard edges, deformed, mutated, ugly, disfigured, blur, blurry, noise, noisy",
        generator=generator
    ).images[0]
    image = refiner(prompt=prompt, generator=generator, image=image).images[0]
    image.save(f"projects/wYeF8yu5_supermarket/out/{randomword(12)}.png")
```

**Comment by chris-aeviator** [comment]
someone on reddit suggested to increase the lora_alpha and rank, but I do not see this as a supported CLI flag.

**Comment by abhishekkrthakur** [comment]
thanks. lemme test it and if it works, i can add the params. btw, if your dataset is not private can you share it?

**Comment by chris-aeviator** [comment]
@abhishekkrthakur sure & thanks!

https://filedrop.oi.myzel.io/f.php?h=0Awdm10x&d=1

**Comment by abhishekkrthakur** [comment]
thank you. this will help me reproduce the issue. if you could, i'd request you to share the prompts for training and generation in the OP too. :)

**Comment by chris-aeviator** [comment]
@abhishekkrthakur do you think https://github.com/huggingface/diffusers/pull/4765  as mentioned inside https://github.com/huggingface/diffusers/issues/4528#issuecomment-1693545140 could have something to do with this? (find my reproduction prompts in the OP)

**Comment by abhishekkrthakur** [comment]
if its already merged, updating the diffusers version using `autotrain setup` and re-running should help. unfortunately, i couldnt get around starting my own training yet.
