### ISSUE TITLE
images/

### ISSUE THREAD

**Issue by grebenshyo** [huggingface/autotrain-advanced#200]
on google colab it's telling me that i cannot have "/" in the title

**Comment by nhatItsforce** [comment]
just create folder with name "images", the author added "/" just to describe it as a folder

**Comment by grebenshyo** [comment]
it's with the slash in the code. i tried removing it from the folder's name, from the code and from both. it didn't help

**Comment by grebenshyo** [comment]
the whole path has to be inserted. that's what i was missing
