### ISSUE TITLE
Stable Diffusion XL DreamBooth text embeds error.

### ISSUE THREAD

**Issue by ArvindSharma18** [huggingface/autotrain-advanced#203]
Error while trying to run dreambooth with Stable Diffusion XL.

if "text_embeds" not in added_cond_kwargs:
TypeError: argument of type 'NoneType' is not iterable

**Comment by ArvindSharma18** [comment]
Cloned the model:
git lfs install
git clone https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0


>autotrain dreambooth \
> --model /datadrive/src/sdxl/models/stable-diffusion-xl-base-1.0 \
> --output model/ \
> --image-path /datadrive/src/sdxl/source/dog \
> --prompt "photo of sks dog" \
> --resolution 1024 \
> --batch-size 1 \
> --num-steps 500 \
> --fp16 \
> --gradient-accumulation 4 \
> --lr 1e-4
> INFO    Namespace(adam_beta1=0.9, adam_beta2=0.999, adam_epsilon=1e-08, adam_weight_decay=0.01, allow_tf32=None, batch_size=1, bf16=None, center_crop=None, checkpointing_steps=100000, checkpoints_total_limit=None, class_image_path=None, class_labels_conditioning=None, class_prompt=None, dataloader_num_workers=0, epochs=1, fp16=True, func=<function run_dreambooth_command_factory at 0x7f710e24a0d0>, gradient_accumulation=4, gradient_checkpointing=None, hub_model_id=None, hub_token=None, image_path='/datadrive/src/sdxl/source/dog', local_rank=-1, logging=None, lr=0.0001, lr_power=1.0, max_grad_norm=1.0, model='/datadrive/src/sdxl/models/stable-diffusion-xl-base-1.0', num_class_images=100, num_cycles=1, num_steps=500, num_validation_images=4, output='model/', pre_compute_text_embeddings=None, prior_generation_precision=None, prior_loss_weight=1.0, prior_preservation=None, prompt='photo of sks dog', push_to_hub=None, rank=4, resolution=1024, resume_from_checkpoint=None, revision=None, sample_batch_size=4, scale_lr=None, scheduler='constant', seed=42, text_encoder_use_attention_mask=None, tokenizer=None, tokenizer_max_length=None, train_text_encoder=None, use_8bit_adam=None, validation_epochs=50, validation_images=None, validation_prompt=None, version=False, warmup_steps=0, xformers=None, xl=None)
> INFO    Running DreamBooth Training
You are using a model of type clip_text_model to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
{'clip_sample_range', 'dynamic_thresholding_ratio', 'thresholding', 'variance_type'} was not found in config. Values will be initialized to default values.
> INFO    ***** Running training *****
> INFO      Num examples = 5
> INFO      Num batches each epoch = 5
> INFO      Num Epochs = 250
> INFO      Instantaneous batch size per device = 1
> INFO      Total train batch size (w. parallel, distributed & accumulation) = 4
> INFO      Gradient Accumulation steps = 4
> INFO      Total optimization steps = 500
> INFO      Training config = model='/datadrive/src/sdxl/models/stable-diffusion-xl-base-1.0' revision=None tokenizer=None image_path='/datadrive/src/sdxl/source/dog' class_image_path=None prompt='photo of sks dog' class_prompt=None num_class_images=100 class_labels_conditioning=None prior_preservation=False prior_loss_weight=1.0 output='model/' seed=42 resolution=1024 center_crop=False train_text_encoder=False batch_size=1 sample_batch_size=4 epochs=250 num_steps=500 checkpointing_steps=100000 resume_from_checkpoint=None gradient_accumulation=4 gradient_checkpointing=False lr=0.0001 scale_lr=False scheduler='constant' warmup_steps=0 num_cycles=1 lr_power=1.0 dataloader_num_workers=0 use_8bit_adam=False adam_beta1=0.9 adam_beta2=0.999 adam_weight_decay=0.01 adam_epsilon=1e-08 max_grad_norm=1.0 allow_tf32=False prior_generation_precision=None local_rank=-1 xformers=False pre_compute_text_embeddings=False tokenizer_max_length=None text_encoder_use_attention_mask=False rank=4 xl=False fp16=True bf16=False hub_token=None hub_model_id=None push_to_hub=False validation_prompt=None num_validation_images=4 validation_epochs=50 checkpoints_total_limit=None validation_images=None logging=False
Steps:   0%|                                                                                                                                    | 0/500 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/datadrive/src/sdxl/.venv/bin/autotrain", line 8, in <module>
    sys.exit(main())
  File "/datadrive/src/sdxl/.venv/lib/python3.8/site-packages/autotrain/cli/autotrain.py", line 36, in main
    command.run()
  File "/datadrive/src/sdxl/.venv/lib/python3.8/site-packages/autotrain/cli/run_dreambooth.py", line 469, in run
    train_dreambooth(params)
  File "/datadrive/src/sdxl/.venv/lib/python3.8/site-packages/autotrain/trainers/dreambooth/main.py", line 249, in train
    trainer.train()
  File "/datadrive/src/sdxl/.venv/lib/python3.8/site-packages/autotrain/trainers/dreambooth/trainer.py", line 383, in train
    model_pred = self._get_model_pred(batch, channels, noisy_model_input, timesteps, bsz)
  File "/datadrive/src/sdxl/.venv/lib/python3.8/site-packages/autotrain/trainers/dreambooth/trainer.py", line 330, in _get_model_pred
    model_pred = self.unet(
  File "/datadrive/src/sdxl/.venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/datadrive/src/sdxl/.venv/lib/python3.8/site-packages/accelerate/utils/operations.py", line 581, in forward
    return model_forward(*args, **kwargs)
  File "/datadrive/src/sdxl/.venv/lib/python3.8/site-packages/accelerate/utils/operations.py", line 569, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/datadrive/src/sdxl/.venv/lib/python3.8/site-packages/torch/amp/autocast_mode.py", line 14, in decorate_autocast
    return func(*args, **kwargs)
  File "/datadrive/src/sdxl/.venv/lib/python3.8/site-packages/diffusers/models/unet_2d_condition.py", line 836, in forward
    if "text_embeds" not in added_cond_kwargs:
TypeError: argument of type 'NoneType' is not iterable
Steps:   0%|                                                                                                                                    | 0/500 [00:14<?, ?it/s]

**Comment by abhishekkrthakur** [comment]
does it work if you run `autotrain setup` before the training command?

**Comment by ArvindSharma18** [comment]
I did run `autotrain setup --update-torch`, before running the training command.

**Comment by abhishekkrthakur** [comment]
ohkay, it seems like since you are using a downloaded model, its not able to infer if its xl model. 
you should be able to run the same command by adding the `--xl` flag.
please let me know if it works.

**Comment by ArvindSharma18** [comment]
Yes it worked, thanks for the help!
