### ISSUE TITLE
Training using Kaggle GPU T4 x2 run out of memory after the training has finalized

### ISSUE THREAD

**Issue by vbdata** [huggingface/autotrain-advanced#207]
Using Kaggle account to do the training fails after the model training has completed. 

The training of the model actually seems to work (takes ca 7 hours) but it runs out of memory when trying to save/do the final steps related to the new model.

![image](https://github.com/huggingface/autotrain-advanced/assets/3061445/593ac623-0988-4a38-81df-49d0cabe24b4)

Any suggestions on how to overcome this issue in Kaggle?

**Comment by abhishekkrthakur** [comment]
a new version will be released today that will solve this issue
