### ISSUE TITLE
Trained lora has no effect neither in a1111 nor DT

### ISSUE THREAD

**Issue by lustfeind** [huggingface/autotrain-advanced#208]
Installed on M1 pro apple silicon 16GB RAM. Well, SDXL always fails, mem issue.

Then I try to train a SD 1.5 lora with 6 images 512x512, but NO effect on the generated image.
I use the lora in a1111 and Draw Things

autotrain dreambooth --model runwayml/stable-diffusion-v1-5 --output model/ --image-path images/ --prompt "photo of a sks man" --resolution 512 --batch-size 1 --num-steps 500  --gradient-accumulation 4 --lr 1e-4  --allow-tf32

Whats wrong?

**Comment by lustfeind** [comment]
ok thanks,.. I'm not very familiar with these things. I thought that .safetensors would work everywhere. Silly me.

**Comment by DarkAlchy** [comment]
It does work in ComfyUI.
