### ISSUE TITLE
lora sdxl does not appear in auto1111

### ISSUE THREAD

**Issue by loboere** [huggingface/autotrain-advanced#209]
lora sdxl does not appear in auto1111

When I finish training lora sdxl in the colab I get a 22 mb safetensor
I move it to the auto1111 loras folder but auto1111 doesn't seem to detect it, it only shows the loras downloaded from civit ai.

**Comment by eduardonba1** [comment]
Try to use Fooocus UI
 https://github.com/lllyasviel/Fooocus

**Comment by loboere** [comment]
I noticed that loras only appear if I use sd1.5 or a model based on 1.5 but not when I use sdxl

**Comment by franz101** [comment]
same here

**Comment by abhishekkrthakur** [comment]
you need to ask the developers of a1111 to support it
