### ISSUE TITLE
diffusers lora sdxl produces different results in comfyui

### ISSUE THREAD

**Issue by loboere** [huggingface/autotrain-advanced#210]
I train lora for sdxl on diffuser with this colab

https://colab.research.google.com/drive/1P5g5mCmNdF-2bzHPxNiScDMj8-03FJjJ?usp=sharing&authuser=1#scrollTo=pJl6EpzApyzL

, but using it produces different results even though it uses the same seed.

Steps to reproduce.
1-train a single image in the lora sdxl diffuser colab
2-type a keyword to activate
3-generate results in the colab with the keyword and something else
4-load the lora in comfyui
5-repeat the same seed hyperparameters keyword and something else from the colab in comfyui
6-images generated in colab are different in comfyui

**Comment by abhishekkrthakur** [comment]
so the safetensor made by autotrain works in comfyui?

**Comment by syllebra** [comment]
> 

Indeed, for me it does not load as Lora in ComfyUI....
