### ISSUE TITLE
Autotrain says that it finishes training after only completing a percentage of run

### ISSUE THREAD

**Issue by wafflefox2023** [huggingface/autotrain-advanced#212]
All of my attempted training runs end with autotrain not completing 100% of the run, but outputting "INFO    Finished training, saving model... " and not saving a trained model file.

 Has anyone else experienced this? If so, how did you fix the issue? Below is the terminal window showing a run.

![Screenshot 2023-08-17 090457](https://github.com/huggingface/autotrain-advanced/assets/130866657/f8ce7945-514a-4dab-84bd-94f0816075c9)

**Comment by abhishekkrthakur** [comment]
sft's estimate is not correct and finishes faster since its grouping texts. its totally fine. your model should be saved in folder specified by project_name param

**Comment by wafflefox2023** [comment]
Thank you for the quick response. The problem is the model is not being saved. He is the model directory when the run completes. There is no config and no model files.

![Screenshot 2023-08-17 093730](https://github.com/huggingface/autotrain-advanced/assets/130866657/2795ca05-ba90-4f00-881b-1e40ace6de50)

**Comment by abhishekkrthakur** [comment]
adapter_* are the model files. since you didnt use `--merge-adapter` param, you are seeing only the adapters and not the full model. you can merge the adapters manually by using the following code: 


```
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer
from peft import PeftModel


base_model_path = ...
adapter_path = ...
target_model_path = ...


model = AutoModelForCausalLM.from_pretrained(
    base_model_path,
    torch_dtype=torch.float16,
    low_cpu_mem_usage=True,
)
model = PeftModel.from_pretrained(model, adapter_path)
tokenizer = AutoTokenizer.from_pretrained(base_model_path)
model = model.merge_and_unload()
model.save_pretrained(target_model_path)
tokenizer.save_pretrained(target_model_path)
```

**Comment by wafflefox2023** [comment]
Fantastic! Thank you. I really appreciate your help. I figured I was missing something obvious.

**Comment by abhishekkrthakur** [comment]
No worries! Will close the issue for now. Feel free to re-open if there's something missing still :)
