### ISSUE TITLE
Colab fails in Inference code (after training)

### ISSUE THREAD

**Issue by metaphorz** [huggingface/autotrain-advanced#214]
I trained a model on 24 images and made sure it wrote to my Google Drive:

/content/drive/MyDrive/Strutt/pytorch_lora_weights.safetensors

so, the trained model is there. I then uncommented the Inference code. Here is the
traceback:

AttributeError                            Traceback (most recent call last)
[<ipython-input-9-43757481ebe3>](https://localhost:8080/#) in <cell line: 15>()
     13 )
     14 pipe.to("cuda")
---> 15 pipe.load_lora_weights(prj_path, weight_name="pytorch_lora_weights.safetensors")
     16 
     17 refiner = StableDiffusionXLImg2ImgPipeline.from_pretrained(

3 frames
[/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py](https://localhost:8080/#) in __getattr__(self, name)
   1612             if name in modules:
   1613                 return modules[name]
-> 1614         raise AttributeError("'{}' object has no attribute '{}'".format(
   1615             type(self).__name__, name))
   1616 

AttributeError: 'DownBlock2D' object has no attribute 'attentions'

**Comment by metaphorz** [comment]
Here is the uncommented code I am running for inference:

# Inference
# this is the inference code that you can use after you have trained your model
# Unhide code below and change prj_path to your repo or local path (e.g. my_dreambooth_project)
#
from diffusers import DiffusionPipeline, StableDiffusionXLImg2ImgPipeline
import torch

prj_path = "/content/drive/MyDrive/Strutt"
model = "stabilityai/stable-diffusion-xl-base-1.0"
pipe = DiffusionPipeline.from_pretrained(
     model,
     torch_dtype=torch.float16,
)
pipe.to("cuda")
pipe.load_lora_weights(prj_path, weight_name="pytorch_lora_weights.safetensors")

refiner = StableDiffusionXLImg2ImgPipeline.from_pretrained(
     "stabilityai/stable-diffusion-x1-base-1.0",
     torch_dtype=torch.float16,
)
refiner.to("cuda")

prompt = "an engraving of an oak tree"

seed = 42
generator = torch.Generator("cuda").manual_seed(seed)
image = pipe(prompt=prompt, generator=generator).images[0]
image = refiner(prompt=prompt, generator=generator, image=image).images[0]
image.save(f"generated_image.png")

**Comment by yaping1119** [comment]
Hello, have you solved your problem? I have also encountered a similar problem.
The loaders load_lora_into_unet() function throw out AttributeError: 'DownBlock2D' object has no attribute 'attentions'
```
  File "/usr/local/miniconda3/lib/python3.8/site-packages/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py", line 920, in load_lora_weights
    self.load_lora_into_unet(state_dict, network_alphas=network_alphas, unet=self.unet)
  File "/usr/local/miniconda3/lib/python3.8/site-packages/diffusers/loaders.py", line 1456, in load_lora_into_unet
    unet.load_attn_procs(
  File "/usr/local/miniconda3/lib/python3.8/site-packages/diffusers/loaders.py", line 422, in load_attn_procs
    attn_processor = getattr(attn_processor, sub_key)
  File "/usr/local/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1185, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'DownBlock2D' object has no attribute 'attentions'
```
