### ISSUE TITLE
resume sdxl lora training

### ISSUE THREAD

**Issue by loboere** [huggingface/autotrain-advanced#215]
Thank you for this great work. I was wondering how to continue training a safetensor, since a free colab session lasts 2 hours. I want to load and continue training a lora safetensor in a new colab session

**Comment by loboere** [comment]
please someone tell me a way to keep training

**Comment by loboere** [comment]
please authors answer me

**Comment by loboere** [comment]
hello  ? Is there an author who answers me?

**Comment by loboere** [comment]
please authors answer me

**Comment by abhishekkrthakur** [comment]
its not possible as of now, but you can open a feature request

**Comment by loboere** [comment]
How is it possible that there is no way to resume training, that is something essential and indispensable, developers please implement this as soon as possible.
