### ISSUE TITLE
How to do inference after train llama2

### ISSUE THREAD

**Issue by muhammadfhadli1453** [huggingface/autotrain-advanced#216]
i trained model using this command
```
autotrain llm --train --project_name 'llama2-indo-testing' \
    --model meta-llama/Llama-2-7b-hf \
    --data_path data/ \
    --text_column text \
    --use_peft \
    --use_int4 \
    --learning_rate 2e-4 \
    --train_batch_size 2 \
    --num_train_epochs 3 \
    --trainer sft \
    --model_max_length 2048 \
    --push_to_hub \
    --repo_id fhadli/llama2-7b-hf-id \
    --block_size 2048 \
    > training.log
```
after that, i tried to load the model using this script
```
from transformers import AutoTokenizer
import transformers
import torch

model = "/home/muhammad.fhadli/explorasi/llama2-indo/llama2-indo-testing"

tokenizer = AutoTokenizer.from_pretrained(model)
pipeline = transformers.pipeline(
    "text-generation",
    model=model,
    torch_dtype=torch.float16,
    device_map="auto",
)
```

but it gave me this error, can someone please explain why i got this error, or what is the rigth way to do inference?
```
Traceback (most recent call last):
  File "play.py", line 8, in <module>
    pipeline = transformers.pipeline(
  File "/home/muhammad.fhadli/.pyenv/versions/3.8.10/envs/llama/lib/python3.8/site-packages/transformers/pipelines/__init__.py", line 705, in pipeline
    config = AutoConfig.from_pretrained(model, _from_pipeline=task, **hub_kwargs, **model_kwargs)
  File "/home/muhammad.fhadli/.pyenv/versions/3.8.10/envs/llama/lib/python3.8/site-packages/transformers/models/auto/configuration_auto.py", line 983, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/muhammad.fhadli/.pyenv/versions/3.8.10/envs/llama/lib/python3.8/site-packages/transformers/configuration_utils.py", line 617, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/muhammad.fhadli/.pyenv/versions/3.8.10/envs/llama/lib/python3.8/site-packages/transformers/configuration_utils.py", line 672, in _get_config_dict
    resolved_config_file = cached_file(
  File "/home/muhammad.fhadli/.pyenv/versions/3.8.10/envs/llama/lib/python3.8/site-packages/transformers/utils/hub.py", line 388, in cached_file
    raise EnvironmentError(
OSError: /home/muhammad.fhadli/explorasi/llama2-indo/llama2-indo-testing/ does not appear to have a file named config.json. Checkout 'https://huggingface.co//home/muhammad.fhadli/explorasi/llama2-indo/llama2-indo-testing//None' for available files.
```
here is the content inside my folder
```
$ls /home/muhammad.fhadli/explorasi/llama2-indo/llama2-indo-testing/
adapter_config.json  optimizer.pt  rng_state_0.pth  scheduler.pt             tokenizer_config.json  tokenizer.model     training_args.bin
adapter_model.bin    README.md     rng_state_1.pth  special_tokens_map.json  tokenizer.json         trainer_state.json
```

**Comment by atwine** [comment]
I am having the same issue and I can't seem to figure out a way around it right now.

**Comment by huvers** [comment]
This should really be in the ReadMe ^^^

**Comment by msobo** [comment]
it seems:
after autotrain-advanced you need to merge finetuned with base-model: for this i found [here ](https://colab.research.google.com/drive/1mV9sAY4QBKLmS58dpFGHgwCXQKRASR31?usp=sharing#scrollTo=lY-3DvlIpVSl)

base_model_name = "abhishek/llama-2-7b-hf-small-shards" # change for your basemodel
new_model_name = "my-llm"
model_path = "my-llm/merged"
device_map = {"": 0} # single gpu? 

base_model = AutoModelForCausalLM.from_pretrained(
    base_model_name,
    low_cpu_mem_usage=True,
    return_dict=True,
    torch_dtype=torch.float16,
    device_map=device_map,
)
model = PeftModel.from_pretrained(base_model, new_model_name)
merged_model = model.merge_and_unload()

# Reload tokenizer to save it
tokenizer = AutoTokenizer.from_pretrained(base_model_name, trust_remote_code=True)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"

# Save the merged model
merged_model.save_pretrained(model_path)
tokenizer.save_pretrained(model_path)

and than this can be used for inference (but not working for me out of the box);
################ Inference something like this

from transformers import AutoModelForCausalLM, AutoTokenizer

model_path = "my-llm/merged"

model = AutoModelForCausalLM.from_pretrained(model_path)
tokenizer = AutoTokenizer.from_pretrained(model_path)
from transformers import pipeline

prompt = "your promt here"

gen = pipeline('text-generation', model=model, tokenizer=tokenizer)
result = gen(prompt)
print(result[0]['generated_text'])

But unfortunately for me it just reprints my own promt ..

**Comment by abhishekkrthakur** [comment]
> after autotrain-advanced you need to merge finetuned with base-model
or you can use `--merge-adapters` parameter

**Comment by ASH1998** [comment]
> But unfortunately for me it just reprints my own promt ..

@msobo Did you try increasing `max_new_tokens` ? Limit is set at 20 by default.

**Comment by AhmetEkiz** [comment]
> This is one way to load the model as:
> 
> tokenizer = AutoTokenizer.from_pretrained('your_finetune_model/checkpoint-51/') model = AutoModelForCausalLM.from_pretrained('Base_Model', torch_dtype = torch.float16, device_map="auto") #Base_Model for example :meta-llama/Llama-2-13b-chat-hf model = PeftModel.from_pretrained(model, 'your_finetune_model', device_map="auto")
> 
> or you would need to merge the adapter weights into the base model. So you have single model dir and then you can load it the HF way
> 
> from peft import AutoPeftModelForCausalLM
> 
> model = AutoPeftModelForCausalLM.from_pretrained( args.output_dir, #lora model dir low_cpu_mem_usage=True, )
> 
> #Merge LoRA and base model merged_model = model.merge_and_unload()
> 
> #Save the merged model merged_model.save_pretrained("merged_model",safe_serialization=True) tokenizer.save_pretrained("merged_model")
> 
> #push merged model to the hub #merged_model.push_to_hub("user/repo") #tokenizer.push_to_hub("user/repo")

This gives me a RAM error on Kaggle. My LLAMA v2 Finetune hyperparameters in below. could it be related to batch size?

#### Hyperparameters
learning_rate = 2e-4 # @param {type:"number"}
num_epochs = 1 #@param {type:"number"}
batch_size = 4 # @param {type:"slider", min:1, max:32, step:1}
block_size = 1024 # @param {type:"number"}
trainer = "sft" # @param ["default", "sft"] {type:"raw"}
warmup_ratio = 0.1 # @param {type:"number"}
weight_decay = 0.01 # @param {type:"number"}
gradient_accumulation = 4 # @param {type:"number"}
use_fp16 = True # @param ["False", "True"] {type:"raw"}
use_peft = True # @param ["False", "True"] {type:"raw"}
use_int4 = True # @param ["False", "True"] {type:"raw"}
lora_r = 16 #@param {type:"number"}
lora_alpha = 32 #@param {type:"number"}
lora_dropout = 0.05 #@param {type:"number"}
