### ISSUE TITLE
Does autotrain advanced support 'scaling' context length of a model using RoPE?

### ISSUE THREAD

**Issue by miwojc** [huggingface/autotrain-advanced#217]

**Comment by rlasseri** [comment]
Is it ?

**Comment by piegu** [comment]
Hi,
when I see the [LM trainer code](https://github.com/huggingface/autotrain-advanced/blob/main/src/autotrain/trainers/lm_trainer.py) and the arguments list for [LLM training](https://github.com/huggingface/autotrain-advanced/blob/main/src/autotrain/cli/run_llm.py), there is no rope argument.

@abhishekkrthakur : do you plan to implement it? 

Thank you.
