### ISSUE TITLE
llm PEFT have resume from checkpoint options was supported ?

### ISSUE THREAD

**Issue by stevensu1977** [huggingface/autotrain-advanced#218]
This is great project,  I was wondering how to continue training LLAM2 , I found dreambooth have  --resume-from-checkpoint , but LLM haven't this option , I'm not sure how to load checkpoint resume LLM PEFT training .

**Comment by talhalatifkhan** [comment]
any updates on this ?

**Comment by willclarktech** [comment]
I believe for LLMs you can just pass the path to the model directory or the `config.json` for the saved model. If you're using PEFT you won't have a `config.json` unless you used the `--merge-adapter` option when running `autotrain` (see https://github.com/huggingface/autotrain-advanced/issues/225#issuecomment-1702324734).

Apparently there's a way to merge the configs for an existing model (see https://github.com/huggingface/autotrain-advanced/issues/211#issuecomment-1681826693) but this seems to require a lot of RAM.

**Comment by xihajun** [comment]
#349
