### ISSUE TITLE
Autotrain a (GPTQ) quantized model

### ISSUE THREAD

**Issue by afdezt** [huggingface/autotrain-advanced#224]
HugginFace transformers now allows performing PEFT from quantitzed models (https://huggingface.co/docs/transformers/main_classes/quantization). 

Is it possible to run autotrain with a quantized model? If not, are there plans to allow this feature in the near future?

Thanks in advance!

**Comment by eviigenius** [comment]
Any update?
Even I want to know , can I train the model on my dataset on a 4bit quantized version of a LLM?
And generate a single file so I can run  it on say LM studio or WebUI locally!!
