### ISSUE TITLE
Getting error in colab while finetuning LLM

### ISSUE THREAD

**Issue by allthingssecurity** [huggingface/autotrain-advanced#227]
In colab though I am getting error
INFO    creating trainer
> ERROR   train has failed due to an exception:
> ERROR   Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/autotrain/utils.py", line 280, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/clm/__main__.py", line 297, in train
    trainer.train()
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 1555, in train
    return inner_training_loop(
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 1569, in _inner_training_loop
    train_dataloader = self.get_train_dataloader()
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 837, in get_train_dataloader
    dataloader_params["sampler"] = self._get_train_sampler()
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 808, in _get_train_sampler
    return RandomSampler(self.train_dataset)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/sampler.py", line 107, in _init_
    raise ValueError("num_samples should be a positive integer "
ValueError: num_samples should be a positive integer value, but got num_samples=0

Although i placed train.csv in data folder and csv has a text column as well. Still I get this error. I just followed the colab for LLM

**Comment by abhishekkrthakur** [comment]
it seems like your csv doesnt have `text` column

**Comment by allthingssecurity** [comment]
[k8s.csv](https://github.com/huggingface/autotrain-advanced/files/12427517/k8s.csv)
this is my csv. I renamed as train.csv (you can see it has text column as well). I placed it in data folder

**Comment by abhishekkrthakur** [comment]
could you please post a screenshot of the sidebar: 
<img width="1304" alt="image" src="https://github.com/huggingface/autotrain-advanced/assets/1183441/1b49fced-1f9a-41b4-a670-515e7bcf3efc">

**Comment by allthingssecurity** [comment]
![image](https://github.com/huggingface/autotrain-advanced/assets/49463903/60d52b60-5ab3-4389-8c9d-a5bc107210f3)
And this is the command
autotrain llm --train --model abhishek/llama-2-7b-hf-small-shards --project-name my_autotrain_llm --data-path /content/data/ --text-column text --lr 0.0002 --batch-size 1 --epochs 1 --block-size 1024 --warmup-ratio 0.1 --lora-r 16 --lora-alpha 32 --lora-dropout 0.05 --weight-decay 0.01 --gradient-accumulation 4 --fp16 --use-peft --use-int4

**Comment by abhishekkrthakur** [comment]
the dataset that you uploaded is the actual dataset or just a sample? it seems to have quite less samples, maybe reducing the block size will help, can you repeat the dataset and make a few hundred samples?

**Comment by abhishekkrthakur** [comment]
i was able to reproduce the error with your dataset. its indeed the block size. its not able to chunk dataset into chunks of 1024. a larger dataset will help or you can reduce chunksize to a ridiculously small number like 8 or 16. i wont recommend the latter.

**Comment by allthingssecurity** [comment]
sure.. Thanks. will try and update you. Thanks a lot for such prompt replies

**Comment by allthingssecurity** [comment]
It works. Thanks a lot Abhishek.

**Comment by abhishekkrthakur** [comment]
No problem. ill close the issue for now :)
