### ISSUE TITLE
Should i disable 8-bit Adam and xformers for Nvidia A100?

### ISSUE THREAD

**Issue by otorre1** [huggingface/autotrain-advanced#236]
I'm training on an a100, but it's not using the 40gb of  vram

**Comment by DarkAlchy** [comment]
For LoRA (no, I refuse to call it Dreambooth as it is a LoRA (directed at HF not you)) training YES.  For SDXL it has issues with Adam8 and people are finding out (with Kohya) that if you have the memory use AdamW instead.  Xformer usage is optional.
