### ISSUE TITLE
how to start without " pip install autotrain-advanced"

### ISSUE THREAD

**Issue by RedBlack888** [huggingface/autotrain-advanced#239]
Dear, 

Thanks for your work.

After installing through `pip`, running

**`autotrain llm --train --project_name my-llm --model luodian/llama-7b-hf --data_path . --use_peft --use_int4 --learning_rate 2e-4 --train_batch_size 12 --num_train_epochs 3 --trainer sft`**

can achieve fine-tuning on your own data. 

If I want to run the project from source code for fine-tuning, which function should I start from?
That is, from which function do the `autotrain` and `llm` parameters come from? 

Best,

**Comment by vempaliakhil96** [comment]
Hey, the `train` function can be imported like this 
```
from autotrain.trainers.clm import train
from autotrain.trainers.utils import LLMTrainingParams
training_config = <all the args go here as a dict>
config = LLMTrainingParams(
    model_name="gpt2",
    data_path=".",
    train_split="train_small",
    valid_split="valid_small",
    huggingface_token=HF_TOKEN,
    text_column="text",
    learning_rate=3e-3,
    num_train_epochs=5,
    use_peft=True,
    push_to_hub=True,
    use_int4=True,
    trainer="sft"
)
train(config)
```
