### ISSUE TITLE
autotrain setup failed on SM notebook & studio

### ISSUE THREAD

**Issue by ngun7** [huggingface/autotrain-advanced#241]
I tried `!pip install -U autotrain-advanced` and the setup failed in AWS Sagemaker studio and notebook too. I tested with different Images (Pytorch 2.0.0.0 Python 3.10 GPU Optimized) and also with (Pytorch 1.13 Python 3.9 GPU Optimized), none of them worked. These images work fine for all other experiments but autotrain. 

RuntimeError: Detected that PyTorch and torchvision were compiled with different CUDA versions. PyTorch has CUDA Version=11.7 and torchvision has CUDA Version=11.8. Please reinstall the torchvision that matches your PyTorch install.

**Comment by abhishekkrthakur** [comment]
can you use dockerfile for aws studio?
