### ISSUE TITLE
how to load the fine-tuned model in the local? 

### ISSUE THREAD

**Issue by kennyluke1023** [huggingface/autotrain-advanced#246]
hi 
thz for your super convenient package makes easier for cookies like me to fine-tune a new model. However, as a cookie, I dont really know how to load my fine-tuned model and apply. 
I was fine-tuning in Google colab and download on my PC but know how to call it out? 
thz bro

**Comment by Wokaccount** [comment]
hii,
got the same problem, do you find a solution?
