### ISSUE TITLE
Using DDP with Huggingface Trainer

### ISSUE THREAD

**Issue by mrout94** [huggingface/autotrain-advanced#247]
How is it that this autotrainer is able to do DDP with model initialisation with `device_map='auto'` while I get the following error when trying to do DDP with the native Huggingface trainer?

> ValueError: You can't train a model that has been loaded with `device_map='auto'` in any distributed mode. Please rerun your script specifying `--num_processes=1` or by launching with `python {{myscript.py}}`.

**Comment by abhishekkrthakur** [comment]
it uses accelerate

**Comment by riyaj8888** [comment]
You can't train a model that has been loaded with `device_map='auto'` in any distributed mode. Please rerun your script specifying `--num_processes=1` or by launching with `python {{myscript.py}}`.

i am using torchrun for dist trainning.

**Comment by CNUIGB** [comment]
I have same situation, is there any way to train model with DDP?

**Comment by abhishekkrthakur** [comment]
what is the situation? write full log and create new issue please. all models train with ddp in a multi gpu setup by default.

**Comment by CNUIGB** [comment]
> what is the situation? write full log and create new issue please. all models train with ddp in a multi gpu setup by default.

yep, my situation is when i use torchrun for training and set --nproc_per_node as more than 2, it just copy the parameters of model to every avaliable gpus, instead of loading model's different part to different GPUs. 

I wonder know how can I load model's different layer to different gpu while training.

**Comment by abhishekkrthakur** [comment]
is this a autotrain issue? where does torchrun come from in autotrain? if its not a issue concerning this repo, please find appropriate repo to ask the question in.

**Comment by CNUIGB** [comment]
sorry, if I want to use autotrainer to do DDP, how can I set parameters?

**Comment by abhishekkrthakur** [comment]
as i mentioned, it automatically uses ddp. ill lock this issue now as it was never relevant to autotrain. please feel free to create a new issue with all the logs in order for me to help.
