### ISSUE TITLE
Got charged 650$ after using the text classification example script

### ISSUE THREAD

**Issue by Stealthwriter** [huggingface/autotrain-advanced#253]
Hi, 

I tried to use the text classification example script thinking it would train the model on my gpu, I was trying it on random models, nothing was mentioned that it costs lots of money to run this script, please check what I got after i ran the script:

![image](https://github.com/huggingface/autotrain-advanced/assets/126798556/e883779a-52c0-41d7-a7df-808213d1b425)

After some minutes I got an invoice from hugging face for 650$, what should I do in this case? Why the script is randomly charging me money, it didn't mention that it would cost money to run this script. Also as you can see in the picture the script stops after starting training, isn't this an open source project which i can use to train models on my GPU? How can I get a refund for the money that got charged? this is the script i ran: https://github.com/huggingface/autotrain-advanced/blob/main/examples/text_classification_binary.py

**Comment by Michellehbn** [comment]
Hi @Stealthwriter ! We've sent you an email though let us know if you have any further questions! Thanks again
