### ISSUE TITLE
Error with the LLM colab file

### ISSUE THREAD

**Issue by alielfilali01** [huggingface/autotrain-advanced#263]
![image](https://github.com/huggingface/autotrain-advanced/assets/58257628/d645e3c9-62d1-495a-a292-f39c0f4445dc)

i haven't changed anything in the original colab file, but still getting this error

**Comment by mmazurkevich** [comment]
@alielfilali01 I think it's not only you who faced this exception. See the original discussion here https://github.com/huggingface/autotrain-advanced/issues/259

**Comment by mmazurkevich** [comment]
@alielfilali01 The possible workaround could be the downgradion of `diffusers`
https://github.com/huggingface/autotrain-advanced/issues/259#issuecomment-1718196818

**Comment by alielfilali01** [comment]
Thank you @mmazurkevich for your efforts 🙏🏻, yah from reading #259 i figured i may need to downgrade the version of diffusers
