### ISSUE TITLE
google-colab 1.0.0 requires pandas==1.5.3, but you have pandas 2.0.3 which is incompatible

### ISSUE THREAD

**Issue by ASHR12** [huggingface/autotrain-advanced#265]
Getting Error while trying to use Google Colab.
 I tried to install my pandas version, but seems didnt work. The same for tensorflow-metadata :(
![image](https://github.com/huggingface/autotrain-advanced/assets/19724759/8deeab6c-3e11-41a4-a2b8-3ac77ae3c1d1)

**Comment by abhishekkrthakur** [comment]
issue has been resolved in latest update. no need to manually downgrade/upgrade anymore. the error part with pandas and google colab versions can be safely ignored.
