### ISSUE TITLE
protobuf version fighting?

### ISSUE THREAD

**Issue by solarslurpi** [huggingface/autotrain-advanced#267]
if i `pip install autotrain-advanced`, it installs protobuf v 4.23.4.  This causes the complaint: `ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow-metadata 1.14.0 requires protobuf<4.21,>=3.20.3, but you have protobuf 4.23.4 which is incompatible.`

fine. So I uninstall this version of protobuf and `!pip install protobuf>=3.20.3`.  Now pip is complaining: `ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
autotrain-advanced 0.6.32 requires protobuf==4.23.4, but you have protobuf 4.24.3 which is incompatible.
tensorflow-metadata 1.14.0 requires protobuf<4.21,>=3.20.3, but you have protobuf 4.24.3 which is incompatible.`  

I merrily go on..but this seems problematic???

**Comment by abhishekkrthakur** [comment]
it can be ignored

**Comment by solarslurpi** [comment]
@abhishekkrthakur  Thank you for the quick reply.
