### ISSUE TITLE
Getting issue NameError: name 'VALID_IMAGE_EXTENSIONS' is not defined

### ISSUE THREAD

**Issue by Anshuman2121** [huggingface/autotrain-advanced#269]
Getting this below error. Even I tried to add VALID_IMAGE_EXTENSIONS in run_dreambooth.py. After it started throwing another env missing. Running is on M2 processor and shell is zsh

⚠️ WARNING | 2023-09-18 03:00:00 | autotrain.cli.run_dreambooth:<module>:14 - ❌ Some DreamBooth components are missing! Please run `autotrain setup` to install it. Ignore this warning if you are not using DreamBooth or running `autotrain setup` already.
🚀 INFO   | 2023-09-18 03:00:01 | autotrain.cli.run_dreambooth:__init__:428 - Namespace(version=False, model='stabilityai/stable-diffusion-xl-base-1.0', revision=None, tokenizer=None, image_path='images/', class_image_path=None, prompt='photo of a aa', class_prompt=None, num_class_images=100, class_labels_conditioning=None, prior_preservation=None, prior_loss_weight=1.0, project_name='my_dreambooth_project', seed=42, resolution=1024, center_crop=None, train_text_encoder=None, batch_size=1, sample_batch_size=4, epochs=1, num_steps=500, checkpointing_steps=100000, resume_from_checkpoint=None, gradient_accumulation=4, gradient_checkpointing=True, lr=0.0001, scale_lr=None, scheduler='constant', warmup_steps=0, num_cycles=1, lr_power=1.0, dataloader_num_workers=0, use_8bit_adam=True, adam_beta1=0.9, adam_beta2=0.999, adam_weight_decay=0.01, adam_epsilon=1e-08, max_grad_norm=1.0, allow_tf32=None, prior_generation_precision=None, local_rank=-1, xformers=True, pre_compute_text_embeddings=None, tokenizer_max_length=None, text_encoder_use_attention_mask=None, rank=4, xl=None, fp16=True, bf16=None, token=None, repo_id=None, push_to_hub=None, validation_prompt=None, num_validation_images=4, validation_epochs=50, checkpoints_total_limit=None, validation_images=None, logging=None, username=None, func=<function run_dreambooth_command_factory at 0x13ebc35e0>)
Traceback (most recent call last):
  File "/Users/anshuman/Library/Python/3.9/bin/autotrain", line 8, in <module>
    sys.exit(main())
  File "/Users/anshuman/Library/Python/3.9/lib/python/site-packages/autotrain/cli/autotrain.py", line 45, in main
    command = args.func(args)
  File "/Users/anshuman/Library/Python/3.9/lib/python/site-packages/autotrain/cli/run_dreambooth.py", line 27, in run_dreambooth_command_factory
    return RunAutoTrainDreamboothCommand(args)
  File "/Users/anshuman/Library/Python/3.9/lib/python/site-packages/autotrain/cli/run_dreambooth.py", line 460, in __init__
    num_images = count_images(self.args.image_path)
  File "/Users/anshuman/Library/Python/3.9/lib/python/site-packages/autotrain/cli/run_dreambooth.py", line 21, in count_images
    for files in VALID_IMAGE_EXTENSIONS:
NameError: name 'VALID_IMAGE_EXTENSIONS' is not defined

**Comment by abhishekkrthakur** [comment]
you seem to be running an older version of autotrain-advanced

**Comment by Anshuman2121** [comment]
I am on latest version

➜  ~ pip freeze | grep autotrain-advanced
autotrain-advanced==0.6.32

<img width="515" alt="image" src="https://github.com/huggingface/autotrain-advanced/assets/11799570/5c6eccd9-9d85-46e3-a8ce-750db582b910">

**Comment by sumanmichael** [comment]
Did you run `autotrain setup`?

**Comment by sumanmichael** [comment]
I guess, autotrain doesn't support M1/M2 yet. Can anyone please confirm?

**Comment by debashisbiswas** [comment]
@sumanmichael
> I also faced the same issue on M1 Pro. After going through code, I learned that it was due to this [ImportError](https://github.com/huggingface/autotrain-advanced/blob/7c269406ff3960729030dd88a51479f9f225b12f/src/autotrain/cli/run_dreambooth.py#L13C14-L13C14). I debugged and figured that - for some reason torchvision was not installed. After manual installation, It's running now, but I'm yet to test it.

I've run into this issue as well and installing `torchvision` fixed the issue.
