### ISSUE TITLE
Unable to run in Sagemaker StudioLab - Dreambooth Training

### ISSUE THREAD

**Issue by mahimairaja** [huggingface/autotrain-advanced#273]
I tried to replicate the [Dreambooth Training](https://colab.research.google.com/github/huggingface/autotrain-advanced/blob/main/colabs/AutoTrain_Dreambooth.ipynb) Notebook in AWS Sagemaker StudioLab. 

I got the below error 

``` bash
Traceback (most recent call last):
  File "/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/diffusers/utils/import_utils.py", line 684, in _get_module
    return importlib.import_module("." + module_name, self.__name__)

RuntimeError: Failed to import diffusers.pipelines.stable_diffusion_xl.pipeline_stable_diffusion_xl because of the following error (look up to see its traceback):
libgthread-2.0.so.0: cannot open shared object file: No such file or directory
```

I understand that I could resolve the issue by 

```bash
sudo apt-get install libglib2.0-0
```

But, since SageMaker does not permit root access. 

### Is there any possible way to solve this?

**Comment by abhishekkrthakur** [comment]
im not sure if there is a way around. you can use autotrain huggingface spaces (see readme) to get better and faster GPUs for dreambooth training
