### ISSUE TITLE
Can't tell if Autotrain is complete

### ISSUE THREAD

**Issue by asherisaac** [huggingface/autotrain-advanced#276]
Hi, I have been running my autotrain for many hours and in the spaces the indicator shows as 'Running', but the text on screen says 'Your model is being trained...'.  When I try to connect to the output model via Inferences API, it doesn't yet recognize the model so I'm assuming it's still training but I can't really tell.  Logs below. Any help appreciated.

> INFO    AUTOTRAIN_USERNAME: asherisaac
> INFO    PROJECT_NAME: 4k5a-p5uv-y1m9-0
> INFO    TASK_ID: 9
> INFO    DATA_PATH: asherisaac/autotrain-data-4k5a-p5uv-y1m9
> INFO    MODEL: meta-llama/Llama-2-7b-chat-hf
> INFO    OUTPUT_MODEL_REPO: asherisaac/4k5a-p5uv-y1m9-0
INFO:     Started server process [35]
INFO:     Waiting for application startup.
> INFO    {"model": "meta-llama/Llama-2-7b-chat-hf", "data_path": "asherisaac/autotrain-data-4k5a-p5uv-y1m9", "project_name": "4k5a-p5uv-y1m9-0", "train_split": "train", "valid_split": null, "text_column": "autotrain_text", "token": "hf_**********************************", "lr": 0.0002, "epochs": 3, "batch_size": 2, "warmup_ratio": 0.1, "gradient_accumulation": 1, "optimizer": "adamw_torch", "scheduler": "linear", "weight_decay": 0.01, "max_grad_norm": 1.0, "seed": 42, "add_eos_token": true, "block_size": 1024, "use_peft": true, "lora_r": 16, "lora_alpha": 32, "lora_dropout": 0.1, "logging_steps": -1, "evaluation_strategy": "epoch", "save_total_limit": 1, "save_strategy": "epoch", "auto_find_batch_size": false, "fp16": true, "push_to_hub": true, "use_int8": false, "model_max_length": 2048, "repo_id": "asherisaac/4k5a-p5uv-y1m9-0", "use_int4": true, "trainer": "sft", "target_modules": null, "merge_adapter": false, "username": "asherisaac"}
> INFO    ['accelerate', 'launch', '--num_machines', '1', '--num_processes', '1', '--mixed_precision', 'fp16', '-m', 'autotrain.trainers.clm', '--training_config', '/tmp/model/training_params.json']
> INFO    Started training with PID 61
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:7860 (Press CTRL+C to quit)
INFO:     10.16.31.122:19188 - "GET /?__sign=eyJhbGciOiJFZERTQSJ9.eyJpYXQiOjE2OTUyOTY2MDgsInN1YiI6ImFzaGVyaXNhYWMvYXV0b3RyYWluLTRrNWEtcDV1di15MW05LTAiLCJleHAiOjE2OTUzODMwMDgsImlzcyI6Imh0dHBzOi8vaHVnZ2luZ2ZhY2UuY28ifQ.xjzKc3xjlXaNfq2cewbor39veiJrzv0Jk0rqBFMvonztUG9VXie5v7NfTGsF0HLGq-RZaJmMYX2bycq-lLp7Ag HTTP/1.1" 200 OK
The following values were not passed to `accelerate launch` and had defaults used instead:
	`--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
/app/env/lib/python3.9/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
/app/env/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cpu.so: undefined symbol: cadam32bit_grad_fp32
Traceback (most recent call last):
  File "/app/env/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/app/env/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/app/src/autotrain/trainers/clm/__main__.py", line 23, in <module>
    from trl import SFTTrainer
  File "/app/env/lib/python3.9/site-packages/trl/__init__.py", line 7, in <module>
    from .extras import BestOfNSampler
  File "/app/env/lib/python3.9/site-packages/trl/extras/__init__.py", line 16, in <module>
    from .best_of_n_sampler import BestOfNSampler
  File "/app/env/lib/python3.9/site-packages/trl/extras/best_of_n_sampler.py", line 7, in <module>
    from ..models import SUPPORTED_ARCHITECTURES, PreTrainedModelWrapper
  File "/app/env/lib/python3.9/site-packages/trl/models/__init__.py", line 29, in <module>
    from .modeling_sd_base import (
  File "/app/env/lib/python3.9/site-packages/trl/models/modeling_sd_base.py", line 27, in <module>
    from diffusers.utils import randn_tensor
ImportError: cannot import name 'randn_tensor' from 'diffusers.utils' (/app/env/lib/python3.9/site-packages/diffusers/utils/__init__.py)
Traceback (most recent call last):
  File "/app/env/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/app/env/lib/python3.9/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/app/env/lib/python3.9/site-packages/accelerate/commands/launch.py", line 986, in launch_command
    simple_launcher(args)
  File "/app/env/lib/python3.9/site-packages/accelerate/commands/launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/app/env/bin/python', '-m', 'autotrain.trainers.clm', '--training_config', '/tmp/model/training_params.json']' returned non-zero exit status 1.
INFO:     10.16.31.122:31443 - "GET /?__sign=eyJhbGciOiJFZERTQSJ9.eyJpYXQiOjE2OTUyOTY3MTMsInN1YiI6ImFzaGVyaXNhYWMvYXV0b3RyYWluLTRrNWEtcDV1di15MW05LTAiLCJleHAiOjE2OTUzODMxMTMsImlzcyI6Imh0dHBzOi8vaHVnZ2luZ2ZhY2UuY28ifQ.kxnFgyDnnKbuxloRxTb6kJd3_BaMpNUf7JM_DYXbb6p6UFqNXdn4XRgTUgV-ITZPNwczbotoQCIgw-wABhNSBg HTTP/1.1" 200 OK
INFO:     10.16.31.122:31443 - "GET /?__sign=eyJhbGciOiJFZERTQSJ9.eyJpYXQiOjE2OTUyOTY3MTcsInN1YiI6ImFzaGVyaXNhYWMvYXV0b3RyYWluLTRrNWEtcDV1di15MW05LTAiLCJleHAiOjE2OTUzODMxMTcsImlzcyI6Imh0dHBzOi8vaHVnZ2luZ2ZhY2UuY28ifQ.c3-rffU_8dAbeRFKnXgZKoced8wiQf92nusCWQPZqbmBZEG1d1Eh-uN1WjrfbaEhxVkpm1SlvAvPQs6XMpw5DQ HTTP/1.1" 200 OK
INFO:     10.16.31.122:62572 - "GET /?__sign=eyJhbGciOiJFZERTQSJ9.eyJpYXQiOjE2OTUyOTY3MjksInN1YiI6ImFzaGVyaXNhYWMvYXV0b3RyYWluLTRrNWEtcDV1di15MW05LTAiLCJleHAiOjE2OTUzODMxMjksImlzcyI6Imh0dHBzOi8vaHVnZ2luZ2ZhY2UuY28ifQ.j9ixV0qNONmS0e0TYRspQevPgjN_4_7dQu0iQorADifrGzUx615NzoTrV_rM2DjVLDKLwp_CBmzgdit3reF-Ag HTTP/1.1" 200 OK
INFO:     10.16.31.122:2604 - "GET /?__sign=eyJhbGciOiJFZERTQSJ9.eyJpYXQiOjE2OTUyOTY3NjUsInN1YiI6ImFzaGVyaXNhYWMvYXV0b3RyYWluLTRrNWEtcDV1di15MW05LTAiLCJleHAiOjE2OTUzODMxNjUsImlzcyI6Imh0dHBzOi8vaHVnZ2luZ2ZhY2UuY28ifQ.LUN_E6aLNB1zWfGhX4aDsTMPjVaBzNLI0teFjPw0p8-kp5qwr-ZsD3qNLF2w9krCevwkQbsCT0XS9m-w1YrOCA HTTP/1.1" 200 OK
INFO:     10.16.38.82:63248 - "GET /?__sign=eyJhbGciOiJFZERTQSJ9.eyJpYXQiOjE2OTUyOTY3NzEsInN1YiI6ImFzaGVyaXNhYWMvYXV0b3RyYWluLTRrNWEtcDV1di15MW05LTAiLCJleHAiOjE2OTUzODMxNzEsImlzcyI6Imh0dHBzOi8vaHVnZ2luZ2ZhY2UuY28ifQ.7VWQ8-O0uYQUDuJPJW2CydZKn5cbH-ltzMgyOlu6fhh-659ZqXQ-XoF0oNL7zLFr4c3Eg55AXlyekCEvhpuABQ HTTP/1.1" 200 OK
INFO:     10.16.31.122:64274 - "GET /?__sign=eyJhbGciOiJFZERTQSJ9.eyJpYXQiOjE2OTUyOTY4NTYsInN1YiI6ImFzaGVyaXNhYWMvYXV0b3RyYWluLTRrNWEtcDV1di15MW05LTAiLCJleHAiOjE2OTUzODMyNTYsImlzcyI6Imh0dHBzOi8vaHVnZ2luZ2ZhY2UuY28ifQ.uHbS7Jg6FZmJBpH7nQHz4J_BMhrIWG-Ym1xQjT1P3hoCbnNMuqatVdjhub86sI_odvePAnnMxrNWztmrofb_DA HTTP/1.1" 200 OK
INFO:     10.16.38.82:18164 - "GET /?__sign=eyJhbGciOiJFZERTQSJ9.eyJpYXQiOjE2OTUyOTY5MDAsInN1YiI6ImFzaGVyaXNhYWMvYXV0b3RyYWluLTRrNWEtcDV1di15MW05LTAiLCJleHAiOjE2OTUzODMzMDAsImlzcyI6Imh0dHBzOi8vaHVnZ2luZ2ZhY2UuY28ifQ.JI01eCbO0qEeQKa0DYK3zwL3Md84u2089iyijilhljbM2ddi44DJQQPhVOM8hC4vtd0QE2SIlZ9Zxq-1FTaUDg HTTP/1.1" 200 OK
INFO:     10.16.38.82:52697 - "GET /?__sign=eyJhbGciOiJFZERTQSJ9.eyJpYXQiOjE2OTUyOTcwMzEsInN1YiI6ImFzaGVyaXNhYWMvYXV0b3RyYWluLTRrNWEtcDV1di15MW05LTAiLCJleHAiOjE2OTUzODM0MzEsImlzcyI6Imh0dHBzOi8vaHVnZ2luZ2ZhY2UuY28ifQ.r_feyuWRfqcY2s6M5HTT485l6-p7u8EfNDocGvBmeEurPgegV7w79268jYrYJ8lne21sRg8YBBH47Sjzuq1pAA HTTP/1.1" 200 OK
INFO:     10.16.38.82:63457 - "GET /?__sign=eyJhbGciOiJFZERTQSJ9.eyJpYXQiOjE2OTUyOTcwOTEsInN1YiI6ImFzaGVyaXNhYWMvYXV0b3RyYWluLTRrNWEtcDV1di15MW05LTAiLCJleHAiOjE2OTUzODM0OTEsImlzcyI6Imh0dHBzOi8vaHVnZ2luZ2ZhY2UuY28ifQ.YzWU1XINUCWY6r07nKZ1KCGuca4uyeOQf_cSOQDuJ5ysYjG7Z7WcBMXNGw3EvRVZv_gPPAPOZaud8KT3eqjsDA HTTP/1.1" 200 OK
INFO:     10.16.38.82:46584 - "GET /?__sign=eyJhbGciOiJFZERTQSJ9.eyJpYXQiOjE2OTUyOTcxMjksInN1YiI6ImFzaGVyaXNhYWMvYXV0b3RyYWluLTRrNWEtcDV1di15MW05LTAiLCJleHAiOjE2OTUzODM1MjksImlzcyI6Imh0dHBzOi8vaHVnZ2luZ2ZhY2UuY28ifQ.wX9zV0Exmd7jAbjdstbnLIfQerZhsgSQc4ULn5rl7c8RhK6FCI87_RYaS01cEQLYhYpBf3NREhREOHlYjrsMDg HTTP/1.1" 200 OK
INFO:     10.16.31.122:28398 - "GET /?__sign=eyJhbGciOiJFZERTQSJ9.eyJpYXQiOjE2OTUyOTcxMjksInN1YiI6ImFzaGVyaXNhYWMvYXV0b3RyYWluLTRrNWEtcDV1di15MW05LTAiLCJleHAiOjE2OTUzODM1MjksImlzcyI6Imh0dHBzOi8vaHVnZ2luZ2ZhY2UuY28ifQ.wX9zV0Exmd7jAbjdstbnLIfQerZhsgSQc4ULn5rl7c8RhK6FCI87_RYaS01cEQLYhYpBf3NREhREOHlYjrsMDg HTTP/1.1" 200 OK
INFO:     10.16.31.122:41611 - "GET /?__sign=eyJhbGciOiJFZERTQSJ9.eyJpYXQiOjE2OTUzMjE5MjgsInN1YiI6ImFzaGVyaXNhYWMvYXV0b3RyYWluLTRrNWEtcDV1di15MW05LTAiLCJleHAiOjE2OTU0MDgzMjgsImlzcyI6Imh0dHBzOi8vaHVnZ2luZ2ZhY2UuY28ifQ.6MQ90YQqBBK9-3qVtNEPvlTZa3tofv_BUruw2EdQommVkfSG7DByR8KACbccZWTYuIQAxXAOQXPdjRaziHPNDA HTTP/1.1" 200 OK
INFO:     10.16.31.122:12171 - "GET /?__sign=eyJhbGciOiJFZERTQSJ9.eyJpYXQiOjE2OTUzMjE5MzcsInN1YiI6ImFzaGVyaXNhYWMvYXV0b3RyYWluLTRrNWEtcDV1di15MW05LTAiLCJleHAiOjE2OTU0MDgzMzcsImlzcyI6Imh0dHBzOi8vaHVnZ2luZ2ZhY2UuY28ifQ.J3pxYIrnlYUIKAmKSlXTv8CiPHFjC_QgYOJcsjR25U-Lr01203okpBo4WMMBi-cSFv1Su28ScenotPxHGUo1DA HTTP/1.1" 200 OK
INFO:     10.16.38.82:25382 - "GET /?__sign=eyJhbGciOiJFZERTQSJ9.eyJpYXQiOjE2OTUzMjIwNDcsInN1YiI6ImFzaGVyaXNhYWMvYXV0b3RyYWluLTRrNWEtcDV1di15MW05LTAiLCJleHAiOjE2OTU0MDg0NDcsImlzcyI6Imh0dHBzOi8vaHVnZ2luZ2ZhY2UuY28ifQ.g8mWi3mKOEq3AJ4mP7a6mMVA5S9x1_k8S6jQMbSvD08S0FSuYBdOWa_UhvQyP7yv2AJVkYwTjB3HMlFtyHm3AQ HTTP/1.1" 200 OK
INFO:     10.16.38.82:59552 - "GET /?__sign=eyJhbGciOiJFZERTQSJ9.eyJpYXQiOjE2OTUzMjIwODEsInN1YiI6ImFzaGVyaXNhYWMvYXV0b3RyYWluLTRrNWEtcDV1di15MW05LTAiLCJleHAiOjE2OTU0MDg0ODEsImlzcyI6Imh0dHBzOi8vaHVnZ2luZ2ZhY2UuY28ifQ.bPvrQUa6kfe90h596X_ZRG8lyE0YTwOds_3IbBuOz_pZwxoPD-DMTkDZpPE-D1pQS9raasT9KuGC6b4Frs8QBQ HTTP/1.1" 200 OK
INFO:     10.16.38.82:23843 - "GET /?__sign=eyJhbGciOiJFZERTQSJ9.eyJpYXQiOjE2OTUzMjIwOTQsInN1YiI6ImFzaGVyaXNhYWMvYXV0b3RyYWluLTRrNWEtcDV1di15MW05LTAiLCJleHAiOjE2OTU0MDg0OTQsImlzcyI6Imh0dHBzOi8vaHVnZ2luZ2ZhY2UuY28ifQ.jGbwD68SjetBzeacPdY-RQ0zcpjaAzW3YJ0qSG2OZ-FNo-UyDob5Ey_YH_Axlq2jYYJb8-3iHntKxSFivFpXAg HTTP/1.1" 200 OK
INFO:     10.16.31.122:11175 - "GET /?__sign=eyJhbGciOiJFZERTQSJ9.eyJpYXQiOjE2OTUzMjIyNTksInN1YiI6ImFzaGVyaXNhYWMvYXV0b3RyYWluLTRrNWEtcDV1di15MW05LTAiLCJleHAiOjE2OTU0MDg2NTksImlzcyI6Imh0dHBzOi8vaHVnZ2luZ2ZhY2UuY28ifQ._5yP0vwtK0WJaFjbok5hl6t3H9dAX72KdQ4pJdqERlLXI3JMatv-JZ_smOuOyOyjrqqjW0_BhhbJp7ZuZ39MBg HTTP/1.1" 200 OK
INFO:     10.16.38.82:34708 - "GET /?__sign=eyJhbGciOiJFZERTQSJ9.eyJpYXQiOjE2OTUzMjIyODMsInN1YiI6ImFzaGVyaXNhYWMvYXV0b3RyYWluLTRrNWEtcDV1di15MW05LTAiLCJleHAiOjE2OTU0MDg2ODMsImlzcyI6Imh0dHBzOi8vaHVnZ2luZ2ZhY2UuY28ifQ.WbxRCcfFsrfs4V6ugzTL1WZZN4juyQHG-yR6IzS-AxdsLJktu_JKe8NyFP1iwdnKis-OPwXi7u1K-DOYCFbdAQ HTTP/1.1" 200 OK
INFO:     10.16.38.82:5745 - "GET /?__sign=eyJhbGciOiJFZERTQSJ9.eyJpYXQiOjE2OTUzMjIzMDUsInN1YiI6ImFzaGVyaXNhYWMvYXV0b3RyYWluLTRrNWEtcDV1di15MW05LTAiLCJleHAiOjE2OTU0MDg3MDUsImlzcyI6Imh0dHBzOi8vaHVnZ2luZ2ZhY2UuY28ifQ._vAHIXMDAueQJZ5GxI45hZr5PfUKmB87qdHCjnNeIPi3XyOPAijMryQnQgu7nvBORN9IYEjJIz3OuVyeSmzmCw HTTP/1.1" 200 OK
INFO:     10.16.31.122:58342 - "GET /?__sign=eyJhbGciOiJFZERTQSJ9.eyJpYXQiOjE2OTUzMjIwOTQsInN1YiI6ImFzaGVyaXNhYWMvYXV0b3RyYWluLTRrNWEtcDV1di15MW05LTAiLCJleHAiOjE2OTU0MDg0OTQsImlzcyI6Imh0dHBzOi8vaHVnZ2luZ2ZhY2UuY28ifQ.jGbwD68SjetBzeacPdY-RQ0zcpjaAzW3YJ0qSG2OZ-FNo-UyDob5Ey_YH_Axlq2jYYJb8-3iHntKxSFivFpXAg HTTP/1.1" 200 OK
INFO:     10.16.31.122:57014 - "GET /?__sign=eyJhbGciOiJFZERTQSJ9.eyJpYXQiOjE2OTUzMjIwOTQsInN1YiI6ImFzaGVyaXNhYWMvYXV0b3RyYWluLTRrNWEtcDV1di15MW05LTAiLCJleHAiOjE2OTU0MDg0OTQsImlzcyI6Imh0dHBzOi8vaHVnZ2luZ2ZhY2UuY28ifQ.jGbwD68SjetBzeacPdY-RQ0zcpjaAzW3YJ0qSG2OZ-FNo-UyDob5Ey_YH_Axlq2jYYJb8-3iHntKxSFivFpXAg HTTP/1.1" 200 OK
INFO:     10.16.31.122:59058 - "GET /?__sign=eyJhbGciOiJFZERTQSJ9.eyJpYXQiOjE2OTUzNTkzMzIsInN1YiI6ImFzaGVyaXNhYWMvYXV0b3RyYWluLTRrNWEtcDV1di15MW05LTAiLCJleHAiOjE2OTU0NDU3MzIsImlzcyI6Imh0dHBzOi8vaHVnZ2luZ2ZhY2UuY28ifQ.KEEbI6NsIasrfI7pOEZ03HZSNDj2WDjtaJm1ohv24YNyeqPfFHdXbcDYS__yyKOufaP_zYMdVGvJPywsJByLDg HTTP/1.1" 200 OK

**Comment by abhishekkrthakur** [comment]
seems like a trl issue. could you please factory reset the training space? it will fix the problem.

**Comment by asherisaac** [comment]
Thank you that worked perfectly. Do you recommend I factory reboot all new autotrain nodes upon creation?

**Comment by abhishekkrthakur** [comment]
No. Not anymore. I just pushed a fix. New trainings shouldn't have this issue.

**Comment by Fax** [comment]
> No. Not anymore. I just pushed a fix. New trainings shouldn't have this issue.
I had the same issue yesterday evening, I was paying for the space that crashed on training start. 
Now it doesn't crash, but the training is not performed. The space is automatically paused and the logs contain only this:

`Error: Failed to load logs: Not Found. Logs are persisted for 30 days after the Space stops running.`

What is happening? Why is it auto pausing? where are the logs?

**Comment by abhishekkrthakur** [comment]
when a training is successful, the training spaces pause automatically to avoid extra charges. if your training was successful, you will find the trained models in your hf account

**Comment by abhishekkrthakur** [comment]
if the training space crashed before training, please factory reboot it. issue has been resolved
