### ISSUE TITLE
How to run AutoTrain Advanced UI locally

### ISSUE THREAD

**Issue by LronDC** [huggingface/autotrain-advanced#279]
How to run AutoTrain Advanced UI locally 😢

**Comment by haizadtarik** [comment]
run `autotrain app`

**Comment by LronDC** [comment]
> run `autotrain app`

Thanks. I tried and it's raised `Please login with a write token`.
![image](https://github.com/huggingface/autotrain-advanced/assets/59912384/4c715551-6642-4b82-85a3-cc668052fab3)

I can't find documentation anywhere and neither can't find information in `--help`. How should I pass the token?

**Comment by LronDC** [comment]
> > run `autotrain app`
> 
> Thanks. I tried and it's raised `Please login with a write token`. ![image](https://user-images.githubusercontent.com/59912384/270552208-69dfb14c-42dd-4a28-9ee4-84be28ab4279.png)
> 
> I can't find documentation anywhere and neither can't find information in `--help`. How should I pass the token?

I solved this by setting `HF_TOKEN` environment variable not `TOKEN`. But still can't run app due to next error: `ValueError: When localhost is not accessible, a shareable link must be created. Please set share=True or check your proxy settings to allow access to localhost.` 
![image](https://github.com/huggingface/autotrain-advanced/assets/59912384/8e766ea6-167f-4087-b850-a4a4ba02e8db)

**Comment by LronDC** [comment]
👆 Problem solved [here](https://github.com/microsoft/TaskMatrix/issues/250#issuecomment-1477468422), finally it's running. However,  `To create a public link, set 'share=True' in 'launch()'.`, don't know how to do that to make it public link, still digging.

**Comment by haizadtarik** [comment]
can set it [here](https://github.com/huggingface/autotrain-advanced/blob/4ef5f411158867c56ea2d1ef7bb43e5fb588be43/src/autotrain/cli/run_app.py#L60C34-L60C34)

**Comment by BrainSlugs83** [comment]
> run `autotrain app`

Can someone please put this into the docs -- somewhere? -- It's not in the hf hub documentation or in the readme.md for this repo.  Having to track this information down by searching through the repo issues was rough.

Also, just to clarify, when I run this, it's demanding to login to the hub with a write token.  Is this really running locally?  Why does it need any token to the hub?

**Comment by abhishekkrthakur** [comment]
the app can be run locally but trainings cannot. i guess this isnt what you want. if you want to run trainings locally, use the autotrain cli.

**Comment by louisdeb** [comment]
> the app can be run locally but trainings cannot. i guess this isnt what you want. if you want to run trainings locally, use the autotrain cli.

Any references to that?

**Comment by BrainSlugs83** [comment]
> run autotrain app
1. Again, can we please update the readme.md and/or the hugging face docs with this info as it was not present.

> the app can be run locally but trainings cannot. i guess this isnt what you want. if you want to run trainings locally, use the autotrain cli.

2. There were no mentions of these limitations in the hugging face docs ... and it even seemed to explicitly indicate that this functionality was available... (i.e. "Developers can [...] run AutoTrain Advanced UI Locally" and "AutoTrain Advanced processes your data either in a Hugging Face Space or locally") -- If it truly can't do this, then can you please update your hugging face documentation as well to make it explicitly clear? -- As the current wording is at best unclear, and at worst, purposefully misleading:
![image](https://github.com/huggingface/autotrain-advanced/assets/5217366/c57e0239-718d-4161-a50e-7529f09a57ce)
(Source: [https://huggingface.co/docs/autotrain/main/en/index](https://huggingface.co/docs/autotrain/main/en/index))

3. Finally... can we log this as a feature request? -- To be able to run the Autotrain UI locally? -- Like truly locally, so that we can use it end-to-end to train models with it locally as well? -- As it sounds like you have a set of CLI tools that can do this, and a UI that can simplify the process... so it just seems like the next logical step is to connect those two... 😉

**Comment by abhishekkrthakur** [comment]
running locally has been implemented and will be announced soon. however, the first iteration isnt going to be completely local. your dataset will be formatted and uploaded to hugging face hub, it can be deleted once the training is over. the models will also be downloaded from the huggingface face hub. watch out in the next couple of days. :)

**Comment by BrianVB** [comment]
> the app can be run locally but trainings cannot. i guess this isnt what you want. if you want to run trainings locally, use the autotrain cli.

@abhishekkrthakur  Is there any information anywhere about how to use the autotrain cli? I've tried using the help command and searching the internet but I'm not coming up with anything.

**Comment by abhishekkrthakur** [comment]
run autotrain app to run both training and app loclly

**Comment by doomkugar** [comment]
i'm keeping having this error trying to run locally:

C:\Users\Admin>autotrain app
ERROR    | 2024-04-08 15:02:57 | autotrain.app:<module>:37 - HF_TOKEN not set
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\Scripts\autotrain.exe\__main__.py", line 7, in <module>
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\autotrain\cli\autotrain.py", line 50, in main
    command.run()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\autotrain\cli\run_app.py", line 51, in run
    from autotrain.app import app
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\autotrain\app.py", line 38, in <module>
    raise ValueError("HF_TOKEN environment variable is not set")
ValueError: HF_TOKEN environment variable is not set

Where to set the HF token?

**Comment by abhishekkrthakur** [comment]
`export HF_TOKEN=.....`

**Comment by doomkugar** [comment]
> `export HF_TOKEN=.....`

i can't find where is this line

**Comment by doomkugar** [comment]
> `export HF_TOKEN=.....`

Can you show me where to insert my hf token?

**Comment by LronDC** [comment]
> > `export HF_TOKEN=.....`
> 
> Can you show me where to insert my hf token?

Set it as environment variable.
