### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'use_flash_attention_2'

### ISSUE THREAD

**Issue by stmtstk** [huggingface/autotrain-advanced#284]
Hi,

I tried `autotrain-advanced` GUI version by using spaces.
I specified `LLM` and some models, and click `Start Training`.
While building, TypeError occurred below and the space was suspended.

```
> ERROR   train has failed due to an exception:
> ERROR   Traceback (most recent call last):
  File "/app/src/autotrain/utils.py", line 280, in wrapper
    return func(*args, **kwargs)
  File "/app/src/autotrain/trainers/clm/__main__.py", line 133, in train
    model = AutoModelForCausalLM.from_pretrained(
  File "/app/env/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 563, in from_pretrained
    return model_class.from_pretrained(
  File "/app/env/lib/python3.9/site-packages/transformers/modeling_utils.py", line 2959, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
TypeError: __init__() got an unexpected keyword argument 'use_flash_attention_2'
```

I would like to avoid this error.  Does anyone know how to do this?

Thanks!

**Comment by abhishekkrthakur** [comment]
apologies for the inconvenience. it should work now. please reopen this issue if it doesnt.

**Comment by stmtstk** [comment]
Thank you for your response.
I am looking forward to fixing it.

**Comment by abhishekkrthakur** [comment]
i meant its fixed. is it still not working?

**Comment by stmtstk** [comment]
I tried once more to `Factory Reboot` train-space.
I then uploaded the dataset, reconfigured the parameters, added the job, and ran the job.
A new job (space) was launched and the build started.
After the model load was finished, I still got the same error as before

```
> ERROR   train has failed due to an exception:
> ERROR   Traceback (most recent call last):
  File "/app/src/autotrain/utils.py", line 280, in wrapper
    return func(*args, **kwargs)
  File "/app/src/autotrain/trainers/clm/__main__.py", line 122, in train
    model = AutoModelForCausalLM.from_pretrained(
  File "/app/env/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 563, in from_pretrained
    return model_class.from_pretrained(
  File "/app/env/lib/python3.9/site-packages/transformers/modeling_utils.py", line 2959, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
TypeError: __init__() got an unexpected keyword argument 'use_flash_attention_2'
```

If I've done it wrong, I'd appreciate it if you could point it out to me.

**Comment by stmtstk** [comment]
```
  File "/app/env/lib/python3.9/site-packages/transformers/modeling_utils.py", line 2959, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
```

I checked the lastest `modeling_utils.py` on the GitHub.

https://github.com/huggingface/transformers/blob/211f93aab95d1c683494e61c3cf8ff10e1f5d6b7/src/transformers/modeling_utils.py#L2959

It seems to be the line 2959 is not `cls(config, *model_args, **model_kwargs)`.
We should check the `transformers` version in the docker hub image.

https://hub.docker.com/r/huggingface/autotrain-advanced/tags

**Comment by stmtstk** [comment]
@abhishekkrthakur san

I tried the latest autotrain-advanced. It seems like a step forward.
However, after printing info message below,

```
> INFO    Finished training, saving model...
> INFO    Pushing model to hub...
```

An error occurred.

```
error: code = NotFound desc = an error occurred when try to find container "0e06e6138d9424d5ce42e65f92ca09ac36d5f297c06033e4d23cfebe5a8a74e0": not found
```

This error could be due to another cause.

Anyway, I will check the reason. If you have any good ideas, please let me know.
Thank you!

**Comment by abhishekkrthakur** [comment]
that error can be ignored for now. if it pushed model to the hub, you are good :)

**Comment by stmtstk** [comment]
@abhishekkrthakur san

I tried to train again. After the training and show the error message again, I confirmed that a new model was generated!
I will enjoy the autotrain-advanced!

Thank you for your support!

**Comment by martincpt** [comment]
I experience the same issue by training llm from cli.

I installed the latest dev from git but no luck with this issue.

**Comment by abhishekkrthakur** [comment]
in cli, you need to run autotrain setup command first.

**Comment by stmtstk** [comment]
I found that I can not find `config.json` in the generated model repository.
Do I need to do any special configuration before starting a Job?

**Comment by stmtstk** [comment]
Do I have to do a process below?

1. git clone from the generated model repository into local PC
2. git clone from based model repository into local PC
3. Load based model and generated model on local PC
4. Merge two models into new models
5. Push the merged model into Hugging Face as a new model

**Comment by stmtstk** [comment]
I found the `--merge_adapter` parameter.
I specified the parameter, trained again, and finally could inference from the generated model page.

I would be very happy if it would be possible to specify the `--merge_adapter` option from the `AutoTraining Advanced GUI`.

Anyway, I would like to appreciate your kind support again.
