### ISSUE TITLE
autotrain dreambooth showing Error "NameError: name 'VALID_IMAGE_EXTENSIONS' is not defined'

### ISSUE THREAD

**Issue by purnasanyal** [huggingface/autotrain-advanced#285]
I am running this code

!autotrain dreambooth \
--model ${MODEL_NAME} \
--project-name ${PROJECT_NAME} \
--image-path /root/images \
--prompt "${PROMPT}" \
--resolution ${RESOLUTION} \
--batch-size ${BATCH_SIZE} \
--num-steps ${NUM_STEPS} \
--gradient-accumulation ${GRADIENT_ACCUMULATION} \
--lr ${LEARNING_RATE} \
$( [[ "$USE_FP16" == "True" ]] && echo "--fp16" ) \
$( [[ "$USE_XFORMERS" == "True" ]] && echo "--xformers" ) \
$( [[ "$TRAIN_TEXT_ENCODER" == "True" ]] && echo "--train-text-encoder" ) \
$( [[ "$USE_8BIT_ADAM" == "True" ]] && echo "--use-8bit-adam" ) \
$( [[ "$GRADIENT_CHECKPOINTING" == "True" ]] && echo "--gradient-checkpointing" ) 

I am getting this error 
⚠️ WARNING | 2023-09-29 08:25:15 | autotrain.cli.run_dreambooth:<module>:14 - ❌ Some DreamBooth components are missing! Please run `autotrain setup` to install it. Ignore this warning if you are not using DreamBooth or running `autotrain setup` already.
🚀 INFO   | 2023-09-29 08:25:16 | autotrain.cli.run_dreambooth:__init__:428 - Namespace(version=False, model='stabilityai/stable-diffusion-xl-base-1.0', revision=None, tokenizer=None, image_path='/root/images', class_image_path=None, prompt='photo of a sks dog', class_prompt=None, num_class_images=100, class_labels_conditioning=None, prior_preservation=None, prior_loss_weight=1.0, project_name='my_dreambooth_project', seed=42, resolution=1024, center_crop=None, train_text_encoder=None, batch_size=1, sample_batch_size=4, epochs=1, num_steps=500, checkpointing_steps=100000, resume_from_checkpoint=None, gradient_accumulation=4, gradient_checkpointing=True, lr=0.0001, scale_lr=None, scheduler='constant', warmup_steps=0, num_cycles=1, lr_power=1.0, dataloader_num_workers=0, use_8bit_adam=True, adam_beta1=0.9, adam_beta2=0.999, adam_weight_decay=0.01, adam_epsilon=1e-08, max_grad_norm=1.0, allow_tf32=None, prior_generation_precision=None, local_rank=-1, xformers=True, pre_compute_text_embeddings=None, tokenizer_max_length=None, text_encoder_use_attention_mask=None, rank=4, xl=None, fp16=True, bf16=None, token=None, repo_id=None, push_to_hub=None, validation_prompt=None, num_validation_images=4, validation_epochs=50, checkpoints_total_limit=None, validation_images=None, logging=None, username=None, func=<function run_dreambooth_command_factory at 0x7f7dce20fd90>)
Traceback (most recent call last):
  File "/opt/conda/bin/autotrain", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.10/site-packages/autotrain/cli/autotrain.py", line 45, in main
    command = args.func(args)
  File "/opt/conda/lib/python3.10/site-packages/autotrain/cli/run_dreambooth.py", line 27, in run_dreambooth_command_factory
    return RunAutoTrainDreamboothCommand(args)
  File "/opt/conda/lib/python3.10/site-packages/autotrain/cli/run_dreambooth.py", line 460, in __init__
    num_images = count_images(self.args.image_path)
  File "/opt/conda/lib/python3.10/site-packages/autotrain/cli/run_dreambooth.py", line 21, in count_images
    for files in VALID_IMAGE_EXTENSIONS:
NameError: name 'VALID_IMAGE_EXTENSIONS' is not defined

**Comment by Sarievo** [comment]
+1

**Comment by Sarievo** [comment]
Installing `torchvision` on M1/M2 fixed the issue for me
https://github.com/huggingface/autotrain-advanced/issues/269

**Comment by mrbeandev** [comment]
@Sarievo thank you 👍🏻 
Fixed for me too !! 
🌟🌟🌟🌟🌟
