### ISSUE TITLE
Defaults

### ISSUE THREAD

**Issue by DarkAlchy** [huggingface/autotrain-advanced#290]
When I train I see it says I left XX out so using defaults but I can't find where those defaults are at.  Mentions a config file but I don't even find that and help is useless, as is the documentation for this.

Any ideas?

**Comment by abhishekkrthakur** [comment]
are you talking about the cli or the ui? which task?

**Comment by DarkAlchy** [comment]
Sorry, I don't do cloud stuff so always forget that is even a thing.

I meant locally.

**Comment by DarkAlchy** [comment]
Of course, as yet another GitHub dev page that does address tickets.

**Comment by abhishekkrthakur** [comment]
please try the newer version and lemme know if you still get issues.
