### ISSUE TITLE
Missing config.json file after training using AutoTrain

### ISSUE THREAD

**Issue by KabaTubare** [huggingface/autotrain-advanced#299]
Context:

Environment: Google Colab (Pro Version using a V100) for training.
Tool: Utilizing Hugging Face AutoTrain for fine-tuning a language model.
Sequence of Events:

**Initial Training:**
Successfully trained a model using AutoTrain.
Process seemingly completed without errors, resulting in several output files.
Missing config.json:
Despite successful training, noticed that the config.json file was not generated.
Without config.json, the trained model cannot be loaded for inference or further training.

**Manual Configuration:**
Created a config.json manually based on a the ‘base model’ used for fine-tuning (NousResearch/Llama-2-7b-chat-hf) plus additional training and adapter parameters derived from the fine-tuned model’s files AutoTrain uploads to the HF repository.
Uploaded this config.json to the Hugging Face repository where the model resides.
Upload to Repository:
Uploaded all relevant files, including pytorch_model.bin, adapter_config.json, adapter_model.bin, and others, to a Hugging Face repository named Kabatubare/meta_douglas_2.
Model Loading Error:
Attempted to load the model and encountered the following error:
vbnetCopy code

OSError: Kabatubare/meta_douglas_2 does not appear to have a file named pytorch_model.bin, tf_model.h5, model.ckpt, or flax_model.msgpack.
File Size Anomaly:
Noticed that the size of the uploaded pytorch_model.bin is only 888 Bytes, which is far smaller than what is typical for such files.

**Repository File Structure:**
adapter_config.json
adapter_model.bin
added_tokens.json
config.json (manually added)
pytorch_model.bin (888 Bytes, suspected to be incorrect or incomplete)
Tokenizer files (tokenizer.json, tokenizer.model, etc.)
Training parameters (training_args.bin, training_params.json)

**Specific Questions for the Hugging Face /GitHub Community:**

_Configuration File:_ Why is a config.json not generated by AutoTrain by default? Is there a specific setting or flag that needs to be enabled to output this file?
_File Size Issue:_
What could cause pytorch_model.bin to be so small (888 Bytes)?
Could this be a symptom of an incomplete or failed save operation?
_Manual Configuration:_
Are there standard procedures or checks to verify that a manually created config.json is accurate?
Are there tools to validate the config.json against the actual PyTorch model file?
Error Resolution:
How to resolve the OSError encountered while loading the model?
Are there specific requirements for the directory structure when loading models from a Hugging Face repository?
_Model Integrity:_
Given the missing config.json and the small size of pytorch_model.bin, are there steps to verify the integrity of the trained model?

**Comment by abhishekkrthakur** [comment]
peft are adapter only models. they dont have config.json. you need to merge it to base model after training manually or use --merge-adapter argument while training.

**Comment by abhishekkrthakur** [comment]
you can also use this space to merge adapters: https://huggingface.co/spaces/autotrain-projects/llm-merge-adapter

**Comment by ruvilonix** [comment]
Is there a way to use the --merge-adapter argument when using the Docker space?

**Comment by harshrumbum** [comment]
> you can also use this space to merge adapters: https://huggingface.co/spaces/autotrain-projects/llm-merge-adapter

This space give me error all the time I was tried to many time what was happen I don't no

**Comment by VishalPranavAG** [comment]
I keep on getting this error after successful finetuning of gpt2 model . I have merged adapters But i keep on getting this error in inference API in model card .

Could not load model vishalpranavag/gp2-twitgen2 with any of the following classes: (<class 'transformers.models.gpt2.modeling_gpt2.GPT2LMHeadModel'>, <class 'transformers.models.gpt2.modeling_tf_gpt2.TFGPT2LMHeadModel'>). See the original errors: while loading with GPT2LMHeadModel, an error is thrown: Traceback (most recent call last): File "/usr/local/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py", line 270, in hf_raise_for_status response.raise_for_status() File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status raise HTTPError(http_error_msg, response=self) requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/vishalpranavag/gp2-twitgen2/resolve/d9ec3aad2cf115926c9a28e2dd0e37a2c2a0c1c0/tf_model.h5 The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/src/transformers/src/transformers/utils/hub.py", line 620, in has_file hf_raise_for_status(r) File "/usr/local/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py", line 320, in hf_raise_for_status raise RepositoryNotFoundError(message, response) from e huggingface_hub.utils._errors.RepositoryNotFoundError: 401 Client Error. (Request ID: Root=1-657c1df6-69d07fff3381f21e5f545ea7) Repository Not Found for url: https://huggingface.co/vishalpranavag/gp2-twitgen2/resolve/d9ec3aad2cf115926c9a28e2dd0e37a2c2a0c1c0/tf_model.h5. Please make sure you specified the correct `repo_id` and `repo_type`. If you are trying to access a private or gated repo, make sure you are authenticated. Invalid username or password. During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/src/transformers/src/transformers/pipelines/base.py", line 269, in infer_framework_load_model model = model_class.from_pretrained(model, **kwargs) File "/src/transformers/src/transformers/modeling_utils.py", line 3117, in from_pretrained if has_file(pretrained_model_name_or_path, TF2_WEIGHTS_NAME, **has_file_kwargs): File "/src/transformers/src/transformers/utils/hub.py", line 631, in has_file raise EnvironmentError(f"{path_or_repo} is not a local folder or a valid repository name on 'https://hf.co'.") OSError: vishalpranavag/gp2-twitgen2 is not a local folder or a valid repository name on 'https://hf.co'. while loading with TFGPT2LMHeadModel, an error is thrown: Traceback (most recent call last): File "/usr/local/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py", line 270, in hf_raise_for_status response.raise_for_status() File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status raise HTTPError(http_error_msg, response=self) requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/vishalpranavag/gp2-twitgen2/resolve/d9ec3aad2cf115926c9a28e2dd0e37a2c2a0c1c0/model.safetensors.index.json The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/src/transformers/src/transformers/utils/hub.py", line 620, in has_file hf_raise_for_status(r) File "/usr/local/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py", line 320, in hf_raise_for_status raise RepositoryNotFoundError(message, response) from e huggingface_hub.utils._errors.RepositoryNotFoundError: 401 Client Error. (Request ID: Root=1-657c1df6-689648b82fb4c9a51b2dc5dc) Repository Not Found for url: https://huggingface.co/vishalpranavag/gp2-twitgen2/resolve/d9ec3aad2cf115926c9a28e2dd0e37a2c2a0c1c0/model.safetensors.index.json. Please make sure you specified the correct `repo_id` and `repo_type`. If you are trying to access a private or gated repo, make sure you are authenticated. Invalid username or password. During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/src/transformers/src/transformers/pipelines/base.py", line 269, in infer_framework_load_model model = model_class.from_pretrained(model, **kwargs) File "/src/transformers/src/transformers/modeling_tf_utils.py", line 2818, in from_pretrained if has_file(pretrained_model_name_or_path, SAFE_WEIGHTS_INDEX_NAME, **has_file_kwargs): File "/src/transformers/src/transformers/utils/hub.py", line 631, in has_file raise EnvironmentError(f"{path_or_repo} is not a local folder or a valid repository name on 'https://hf.co'.") OSError: vishalpranavag/gp2-twitgen2 is not a local folder or a valid repository name on 'https://hf.co'.

**Comment by ebayes** [comment]
Hi! I've also been having a similar issue inferencing a finetuned model. I used the no code version of AutoTrain to finetune Mistral 7B (specifically this sharded version: https://huggingface.co/alexsherstinsky/Mistral-7B-v0.1-sharded) using a custom dataset in the correct format and I've hosted it (here: https://huggingface.co/seyabde/mistral_7b_yo_instruct). I've used Abhishek's space to merge adapters (https://huggingface.co/spaces/autotrain-projects/llm-merge-adapter) but it's not performing as expected. Any ideas why? Perhaps it could be because my finetuned model is saved in a checkpoint folder (here: https://huggingface.co/seyabde/mistral_7b_yo_instruct/tree/main/checkpoint-32028). Does this mean I should run the adapter on the contents of the checkpoint folder instead? I spent quite a bit on the training run so trying to avoid retraining! Any help much appreciated. Thanks!

**Comment by abhishekkrthakur** [comment]
@ebayes what doesnt perform as expected? is there an error? can you post screenshot of trained model files?

**Comment by ebayes** [comment]
I've launched it on Inference Endpoint and there it doesn't return an error but some prompts don't return any outputs i.e. [{'generated_text': ''}]. Because my AutoTrain run was saved in a checkpoint folder I'm not sure if when I merged the adapters, it it inferencing the base model instead of my finetuned version.

Screenshot of trained model files:

1. Main folder (after merging the adapters)
<img width="1264" alt="Screenshot 2023-12-18 at 9 04 02 PM" src="https://github.com/huggingface/autotrain-advanced/assets/51138168/c79a5803-68d4-4a3b-91d3-a748d1ad9a75">

2. checkpoint-32028 folder:
<img width="1267" alt="Screenshot 2023-12-18 at 9 04 18 PM" src="https://github.com/huggingface/autotrain-advanced/assets/51138168/1756bb10-c524-4bcd-a133-8b91da5f6012">

**Comment by ebayes** [comment]
Another reason it might not return any output is because it's finetuned on Yoruba instruction-following demonstrations (not English) so if Mistral's training dataset doesn't contain much Yoruba, then it might just produce gobbledygook. If this is the case, I am going to finetune again first extending pre-training with a large unstructured Yoruba corpus then finetuning this model. If I were to do this, would I select SFT / Generic Trainer? What format should the data be in? just "text:"? re: (https://huggingface.co/docs/autotrain/llm_finetuning)

**Comment by vishalmysore** [comment]
please let me know once you have the solution, since i am in process of finetuning Mistral 7B and want to avoid finetuning again!

**Comment by xihajun** [comment]
> you can also use this space to merge adapters: [huggingface.co/spaces/autotrain-projects/llm-merge-adapter](https://huggingface.co/spaces/autotrain-projects/llm-merge-adapter)

We can also use this space locally with docker (testing it)
```
docker run -it -p 7860:7860 --platform=linux/amd64 \
	registry.hf.space/autotrain-projects-llm-merge-adapter:latest python app.py
```

**Comment by xihajun** [comment]
Anyone has idea why the merged file's accuracy is so different from the one without merging?

**Comment by xihajun** [comment]
Anyone has idea why the merged file's accuracy is so different from the one without merging? 

Here is the script I used for merging manually
```
from transformers import AutoModelForCausalLM, AutoTokenizer, AutoConfig
import torch
from peft import PeftModel
adapter_path="xxx"
base_model_path="mistralai/Mistral-7B-v0.1"
target_model_path="model_output/"
config = AutoConfig.from_pretrained(base_model_path)


model = AutoModelForCausalLM.from_pretrained(
    base_model_path,
    torch_dtype=torch.float16,
    low_cpu_mem_usage=True,
    trust_remote_code=True,
)

model = PeftModel.from_pretrained(model, adapter_path)

tokenizer = AutoTokenizer.from_pretrained(
    base_model_path,
    trust_remote_code=True,
)
model = model.merge_and_unload()

logger.info("Saving target model...")
model.save_pretrained(target_model_path)
tokenizer.save_pretrained(target_model_path)
config.save_pretrained(target_model_path)
```

**Comment by abhishekkrthakur** [comment]
@xihajun how different is it? could you please create a new issue with more details on how you merge and how you calculate accuracy for merged and unmerged models and we will investigate?

**Comment by KabaTubare** [comment]
Thank you sonnuxj for getting back. At this point I've moved past this as
there are easier ways, especially now, to get this work done.

Kind regards,

Troy Woodson

**Comment by xihajun** [comment]
sure, I will do that, thanks @abhishekkrthakur

**Comment by SrushtiAckno** [comment]
> peft are adapter only models. they dont have config.json. you need to merge it to base model after training manually or use --merge-adapter argument while training.

how do we specify the --merge-adapter parameter in the colab notebook, like what should be the argument passed?

**Comment by ahmed8047762** [comment]
@abhishekkrthakur I finetuned **_HuggingFaceH4/zephyr-7b-beta_** model on custom dataset using **autotrain** and tried to merge it with base model using duplicated space of your space but after 8/8 model's shreds were loaded, following error occured:

**_TypeError: LoraConfig.__init__() got an unexpected keyword argument 'layer_replication'_**

any idea how to resolve this issue?
