### ISSUE TITLE
Finetuning mistral7B tokenization issue

### ISSUE THREAD

**Issue by VandeveldePaul** [huggingface/autotrain-advanced#302]
Hello,

I am trying to use autotrain-advanced to finetune mistral. After the finetune, the results are bad, you can see below what I get when I use the newly finetuned model : 

Loading checkpoint shards: 100%|█████████████████████████████| 2/2 [00:04<00:00,  2.46s/it]
Loading adapter weights from ./output/ led to unexpected keys not found in the model:  ['score.weight']. 
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Using sep_token, but it is not set yet.
Using cls_token, but it is not set yet.
Using mask_token, but it is not set yet.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
<s> [INST] What is your favourite condiment? [/INST]Well, I'm quite partial to a good squeeze of fresh lemon juice. It adds just the right amount of zesty flavour to whatever I'm cooking up in the kitchen!</s>  [INST] Do you have mayonnaise recipes? [/INST]
 t
 inB _6H64  in73A7_I-* andH3.3
_. =322 -' _  a</s>

The model is : mistralai/Mistral-7B-Instruct-v0.1
The dataset is : Anthropic/hh-rlhf

The code that executed this : 

`from transformers import AutoModelForCausalLM, AutoTokenizer

device = "cuda"

model = AutoModelForCausalLM.from_pretrained("mistralai/Mistral-7B-Instruct-v0.1")
tokenizer = AutoTokenizer.from_pretrained("mistralai/Mistral-7B-Instruct-v0.1")

messages = [
    {"role": "user", "content": "Quel est ton moment dans l'histoire préféré?"},
    {"role": "assistant", "content": "Mon moment dans l'histoire préféré est le 26 mai 1993, qui représente la date de la victoire de l'Olympique de Marseille en Ligue des champions !"},
    {"role": "user", "content": "Comment inverser une liste en python?"}
]

encodeds = tokenizer.apply_chat_template(messages, return_tensors="pt")

model_inputs = encodeds.to(device)
model.to(device)

generated_ids = model.generate(model_inputs, max_new_tokens=1000, do_sample=True)
decoded = tokenizer.batch_decode(generated_ids)
print(decoded[0])
`

I don't understand why the model prints some random characters, do you have an idea / do you need more information ?

PS: the command-line I used to train : autotrain llm --train --project_name output --model mistralai/Mistral-7B-Instruct-v0.1 --data_path Anthropic/hh-rlhf --use-peft  --trainer reward --fp16 --lr 2e-4 --use-int4 --batch-size 2 --text-column chosen --rejected-text-column rejected --block-size 512

Thank you.

**Comment by abhishekkrthakur** [comment]
for mistral, if you are using peft, please disable gradient checkpointing using `--disable-gc` flag

**Comment by VandeveldePaul** [comment]
Thank you, I am trying this right now.

Coming back to you when the fine-tune finishes

**Comment by VandeveldePaul** [comment]
Alright so the finetune just finished (on 1 H100) and I still get some weird prints : 

Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████| 2/2 [00:04<00:00,  2.36s/it]
Loading adapter weights from ./mistral-finetuned/ led to unexpected keys not found in the model:  ['score.weight']. 
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Using sep_token, but it is not set yet.
Using cls_token, but it is not set yet.
Using mask_token, but it is not set yet.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
<s> [INST] Quel est ton moment dans l'histoire préféré? [/INST]Mon moment dans l'histoire préféré est le 26 mai 1993, qui représente la date de la victoire de l'Olympique de Marseille en Ligue des champions !</s>  [INST] Comment inverser une liste en python? [/INST] /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/TDM /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/INCLUDING /******/ /******/ /******/ /******/ /******/ fün /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/лази /******/ /******/ /******/ /******/ /******/ /******/־ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/Ħ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ bekan /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/Ħ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/DIP /******/ /******/ /******/ /******/ /******/� /******/ /******/ CHAPTER /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ʷ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ CHAPTER /******/ /******/ /******/़ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ --( /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/FAULT /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ṯ /******/ /******/ bekan /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/TDM /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ Fuß /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/scriptstyle /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/� /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ٹ /******/ /******/ /******/scriptstyle /******/ /******/Ī /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ --( /******/ /******/ /******/ /******/ /******/ /******/ /******/� /******/ /******/ /******/TDMℓpuis /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ fün /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/même /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ṯ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ǧ /******/ /******/ /******/ /******/ /******/ /******/ /******/DRV /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/DIP /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/лази丶 /******/ /******/TDM /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/ /******/� /******/ /******/ /******/ /******/ /******/ /******/


Still the same model and dataset and the command used to train is the same but with --disable-gc


Paul

**Comment by abhishekkrthakur** [comment]
you can merge adapters locally or on spaces by using this space: https://huggingface.co/spaces/autotrain-projects/llm-merge-adapter

**Comment by chiefMarlin** [comment]
Did you get your model to work properly ?

**Comment by mathis-lambert** [comment]
Hi @chiefMarlin,
Nop i keep tryin' but tokenization doesn't seem to work properly .... 
i've paused this for now

**Comment by eviigenius** [comment]
Any update guys @mathis-lambert @chiefMarlin @VandeveldePaul , how to merge the adapter with the base model, can some one suggest me code that may work ?

**Comment by abhishekkrthakur** [comment]
the comment above has the code and space that works. else you can use --merge-adapter argument while training.

**Comment by eviigenius** [comment]
> the comment above has the code and space that works. else you can use --merge-adapter argument while training.

Thanks for replying , I tried the spaces but it showed me error, 
Also I tried using the --merge-adapter argument while training, after training the model it just adds a ^C at the end every time before pushing the model to hub (maybe since I am using the free version of colab T4 GPU & it gets out of memory)
Hence I am trying to load the base model in 4 bits and then trying to attach adapter to it and then pushing that model to hub.

**Comment by xihajun** [comment]
> Alright so the finetune just finished (on 1 H100) and I still get some weird prints :
> 
> Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████| 2/2 [00:04<00:00, 2.36s/it] Loading adapter weights from ./mistral-finetuned/ led to unexpected keys not found in the model: ['score.weight']. Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained. Using sep_token, but it is not set yet. Using cls_token, but it is not set yet. Using mask_token, but it is not set yet. The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results. Setting `pad_token_id` to `eos_token_id`:2 for open-end generation. [INST] Quel est ton moment dans l'histoire préféré? [/INST]Mon moment dans l'histoire préféré est le 26 mai 1993, qui représente la date de la victoire de l'Olympique de Marseille en Ligue des champions ! [INST] Comment inverser une liste en python? [/INST] /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /**/ /*/******/
> 
> Still the same model and dataset and the command used to train is the same but with --disable-gc
> 
> Paul

Since you have the outputs already, maybe there is something to fix with the finetuning inputs? Also, the learning rate, and other parameters. I used some parameters (lower learning rates) and the finetuned model prints `.....`, I also tried a large dataset with the same parameters I finetuned for 100 datapoints, the outputs are also really bad
