### ISSUE TITLE
text-classification errors. 'Value' object has no attribute 'names'

### ISSUE THREAD

**Issue by Andrew-MAQ** [huggingface/autotrain-advanced#316]
**Description:**
I have run into a few errors when trying to use text-classification with autotrain. I will list out what problems I have encountered and what my solutions were, although I don't know if they are good solutions.

**Errors encountered:**
1) 'Value' object has no attribute 'names'. This was caused by line 73 in [text_classification/__main__.py](https://github.com/huggingface/autotrain-advanced/blob/main/src/autotrain/trainers/text_classification/__main__.py#L73). To fix this, I changed the line to `classes = list(set(train_data[config.target_column]))`

2) KeyErrror: 'token' line 180 in [text_classification/__main__.py](https://github.com/huggingface/autotrain-advanced/blob/main/src/autotrain/trainers/text_classification/__main__.py#L180). Fixed by adding a check in line 179 `if "token" in training_params:`. I am unsure about the original intent of this code as I do not know about any 'token' key in training params, can someone enlighten me?

3) ValueError: invalid literal for int() with base 10: 'negative' line 18 in [text_classification/dataset.py](https://github.com/huggingface/autotrain-advanced/blob/main/src/autotrain/trainers/text_classification/dataset.py#L18C9-L18C29). Caused by having sentiments as strings (e.g. positive, negative, neutral) instead of as ints in dataset. The [Huggingface docs](https://huggingface.co/docs/autotrain/text_classification#data-format) show using sentiments as strings, but that doesn't seem to be supported? I avoided this problem by switching to using ints instead of strings as the sentiments in the dataset.

4) RuntimeError: No executable batch size found, reached zero. This was caused by OOM, I just had to switch to a smaller model. I'm just sad that there is no quantization or peft support for text-classification.

5) After training, the config.json file showed the problem_type as "single_label_classification" even though I trained with 3 labels, and the _num_labels shown in the config file is 3. The id2label and label2id also show 3 labels. I would expect it to be "multi_label_classification".

I'm unsure if I'm just mis-using autotrain text-classification. Please let me know if the command line arguments are incorrect or if the dataset is in the wrong format.
Below are the command line arguments and datasets used:

**Command line arguments:**

autotrain text-classification --train --project-name autotrain-test --model distilbert-base-uncased --data-path datasets/test --lr 5.5e-5 --epochs 1 --gradient-accumulation 8 --save-strategy epoch --fp16 --auto-find-batch-size --scheduler cosine --text-column review --target-column sentiment

autotrain text-classification --train --project-name autotrain-tweet --model distilbert-base-uncased --data-path datasets/test --lr 5.5e-5 --epochs 1 --gradient-accumulation 8 --save-strategy epoch --fp16 --auto-find-batch-size --scheduler cosine --text-column review --target-column sentiment

**Datasets:**

test dataset - named train.csv - quite literally the dataset in the Huggingface docs
```
review,sentiment
"this movie is great",positive
"this movie is bad",negative
```

tweet dataset - reformatted from [mteb/tweet_sentiment_extraction](https://huggingface.co/datasets/mteb/tweet_sentiment_extraction) to be in this format:
```
,review,sentiment
0,Last session of the day  http://twitpic.com/67ezh,1
1, Shanghai is also really exciting (precisely -- skyscrapers galore). Good tweeps in China:  (SH)  (BJ).,2
```
saved in dir tweet as test.csv and train.csv.

Same tweet dataset formatted with strings as sentiments, got error 3 above:
```
,review,sentiment
0,Last session of the day  http://twitpic.com/67ezh,neutral
1, Shanghai is also really exciting (precisely -- skyscrapers galore). Good tweeps in China:  (SH)  (BJ).,positive
```

**Comment by OpenSpacesAndPlaces** [comment]
Same issue. Simple commands and dataset.  seq2seq with the same file appears ok.

**Comment by sofi444** [comment]
This is marked as closed but I am having the same problem when using an HF dataset and setting 
- train split = train.jsonl
- validation split (optional) = test.jsonl (or val.jsonl)

It expects a ClassLabel type.

@abhishekkrthakur
