### ISSUE TITLE
Trying to find acceptable format CSV to upload to Autotrain-Advanced.

### ISSUE THREAD

**Issue by OfferLa** [huggingface/autotrain-advanced#321]
Hello.

After getting errors with some pre-built datasets, I've tried to make my own very basic csv file to see it getting through without errors.
For some reason, just making a file with extension .csv, making sure there are no un-wanted delimiters in it, and even adding a header (and id field) - doesn't work for me.
Since the model doesn't give a detailed error message, I don't have a clue where to start looking.

I'll really appreciate all great clever guys here look into it.

[xxxllm.csv](https://github.com/huggingface/autotrain-advanced/files/13226190/xxxllm.csv)

**Comment by OfferLa** [comment]
Now it seems to me the length of the text lines was too much for it.
First, I wonder what's the text length limit per record.
Second, I've tried to split the lines and it made it, but now the trainer says the dataset it empty.
Here is the new version of the file:
[xxxllm2.csv](https://github.com/huggingface/autotrain-advanced/files/13227507/xxxllm2.csv)

Any help would be appreciated!

**Comment by abhishekkrthakur** [comment]
please post a few lines/rows from csv file instead of raw file. the data format is same as: https://huggingface.co/datasets/timdettmers/openassistant-guanaco
