### ISSUE TITLE
config.json file missing after finetuning

### ISSUE THREAD

**Issue by ruvilonix** [huggingface/autotrain-advanced#322]
I am trying to fine tune gpt2 using the HF Docker space. It seems to make the model, but when trying to use the inference widget on the model card page, it at first gave the error that it couldn't determine the library, so I added `transformers` as the library to the model card. Now it gives the error "[model] does not appear to have a file named config.json." and I'm not sure what to do.

**Comment by abhishekkrthakur** [comment]
please see the pinned issue
