### ISSUE TITLE
Getting this error message and i dont know what to do:

### ISSUE THREAD

**Issue by ronaldomirandah** [huggingface/autotrain-advanced#326]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
lida 0.0.10 requires kaleido, which is not installed.
llmx 0.0.15a0 requires cohere, which is not installed.
llmx 0.0.15a0 requires openai, which is not installed.
tensorflow-metadata 1.14.0 requires protobuf<4.21,>=3.20.3, but you have protobuf 4.23.4 which is incompatible.
tensorflow-probability 0.22.0 requires typing-extensions<4.6.0, but you have typing-extensions 4.8.0 which is incompatible.

Sometimes i got a error message and ignored, and the result was ok.
But lately, after this error, and after finished the trainning, my LORA produces just noise
or a complete black image.

**Comment by abhishekkrthakur** [comment]
this error can be ignored. noise or black image is mostly data or training issue.

**Comment by ronaldomirandah** [comment]
> this error can be ignored. noise or black image is mostly data or training issue.

I wish i could ignore man, but after this error message started to show up, all my loras now got just noise results, no image at all :(
I tried different photos, no matter, just noise results. For sure there is something wrong.
Cause my previous loras without this message error, worked fine.

**Comment by sujitahirrao** [comment]
> ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts. lida 0.0.10 requires kaleido, which is not installed. llmx 0.0.15a0 requires cohere, which is not installed. llmx 0.0.15a0 requires openai, which is not installed. tensorflow-metadata 1.14.0 requires protobuf<4.21,>=3.20.3, but you have protobuf 4.23.4 which is incompatible. tensorflow-probability 0.22.0 requires typing-extensions<4.6.0, but you have typing-extensions 4.8.0 which is incompatible.
> 
> Sometimes i got a error message and ignored, and the result was ok. But lately, after this error, and after finished the trainning, my LORA produces just noise or a complete black image.

You can fix the noise or black image output issue by setting `use_8bit_adam = False`.

**Comment by ronaldomirandah** [comment]
> > ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts. lida 0.0.10 requires kaleido, which is not installed. llmx 0.0.15a0 requires cohere, which is not installed. llmx 0.0.15a0 requires openai, which is not installed. tensorflow-metadata 1.14.0 requires protobuf<4.21,>=3.20.3, but you have protobuf 4.23.4 which is incompatible. tensorflow-probability 0.22.0 requires typing-extensions<4.6.0, but you have typing-extensions 4.8.0 which is incompatible.
> > Sometimes i got a error message and ignored, and the result was ok. But lately, after this error, and after finished the trainning, my LORA produces just noise or a complete black image.
> 
> You can fix the noise or black image output issue by setting `use_8bit_adam = False`.

Yes, thanks, already saw and got the message fix in another thread.
