### ISSUE TITLE
Why do I get completely black images or noise?

### ISSUE THREAD

**Issue by loboere** [huggingface/autotrain-advanced#327]
I installed the latest version of autotrain then installed xformers
!pip install xformers==0.0.22
i use colab

My training images look good, I had already trained with these images before and I didn't have this problem but now the results look black

![image](https://github.com/huggingface/autotrain-advanced/assets/15265895/5fbabebe-818b-4713-a26c-1ba745e46b06)

**Comment by ronaldomirandah** [comment]
> I installed the latest version of autotrain then installed xformers !pip install xformers==0.0.22 i use colab
> 
> My training images look good, I had already trained with these images before and I didn't have this problem but now the results look black
> 
> ![image](https://user-images.githubusercontent.com/15265895/280138338-5fbabebe-818b-4713-a26c-1ba745e46b06.png)

wow finally. You are not alone, i am getting just noise and black images too. Something definetely is wrong :(

**Comment by norflin321** [comment]
I'm using the current version of colab and getting completely black images too

**Comment by norflin321** [comment]
I fixed it by settings `use_8bit_adam = False`

**Comment by ronaldomirandah** [comment]
> I fixed it by setting `use_8bit_adam = False`

wow, finally. it worked for me too. Thanks
