### ISSUE TITLE
Finetuning Zephyr or Mistral with default config results in Error

### ISSUE THREAD

**Issue by luisblanche-mirakl** [huggingface/autotrain-advanced#328]
I got the same error with both models  : 
```bash
ValueError: Please specify `target_modules` in `peft_config`
```
I don't see anywhere I could access to peft_config in the ui 
My colleague apparently used the same service not more than a few weeks ago without issue

**Comment by abhishekkrthakur** [comment]
`--target-modules q_proj,v_proj`

**Comment by abhishekkrthakur** [comment]
ohh, sorry, you are using the ui. fix coming in 15-20mins!

**Comment by abhishekkrthakur** [comment]
its fixed now. you need to factory reset the space ui and start trainings. thank you for pointing the issue.

**Comment by LuisBlanche** [comment]
I ran did factory reset and tried it again for both Zephyr and Mistral and got : 
```bash
ValueError: Target modules q_proj,v_proj not found in the base model. Please check the target modules and try again.
```

**Comment by huerlisi** [comment]
Also getting "Target modules q_proj,v_proj not found in the base model" with Mistral.

I forced a newer version of `peft` (0.6.0) which downgraded `autotrain-advanced` to `autotrain-advanced-0.6.41`. This works now.

**Comment by LuisBlanche** [comment]
@abhishekkrthakur any news on this ? I ended up using  `autotrain-advanced-0.6.41` as well with my own server and could train both mistral and zephyr but could not do so using the UI

**Comment by ataerdem** [comment]
It could be useful to add a custom parameter input box to the UI for these types of situations. I am also looking for a workaround other than running my own server
