### ISSUE TITLE
Trained lora producing balck/noisy image

### ISSUE THREAD

**Issue by jsr-09** [huggingface/autotrain-advanced#333]
I have trained 7 times from last week with different steps but still the lora producing either black image or noisy image. This is happening from last week.
I am using v0.6.42 on colab and you can test the lora - [here](https://huggingface.co/jsram/face_test1)
here is the generated images -

![generated_image (1)](https://github.com/huggingface/autotrain-advanced/assets/148004529/5f9736d1-f89d-4cfc-8523-0f23ec8a17cf)

![generated_image](https://github.com/huggingface/autotrain-advanced/assets/148004529/6d1d1d5e-0ee6-4201-9ff4-9d42678cccee)

please help me to fix this @abhishekkrthakur

**Comment by abhishekkrthakur** [comment]
can you disable xformers and 8bit adam?

**Comment by abhishekkrthakur** [comment]
can you also post all the params used?

**Comment by abhishekkrthakur** [comment]
can you disable 8 bit adam and try?

**Comment by jsr-09** [comment]
ok i will try and update you 🙏

**Comment by jsr-09** [comment]
Disabling 8 bit adam worked. Thankyou @abhishekkrthakur

**Comment by AlexanderKozhevin** [comment]
@abhishekkrthakur thank you 🙏

**Comment by jsr-09** [comment]
can I change the model for training? like can i use any other models other than listed (model from civitai)?

**Comment by abhishekkrthakur** [comment]
not sure if that works. only huggingface supported models are officially supported. feel free to give it a try and let us know too!

**Comment by jsr-09** [comment]
i tried `segmind/SSD-1B` but giving error

 INFO    Namespace(version=False, model='segmind/SSD-1B', revision=None, tokenizer=None, image_path='/content/images/', class_image_path=None, prompt='dhon1', class_prompt=None, num_class_images=100, class_labels_conditioning=None, prior_preservation=None, prior_loss_weight=1.0, project_name='ssd_face', seed=42, resolution=1024, center_crop=None, train_text_encoder=None, batch_size=1, sample_batch_size=4, epochs=1, num_steps=300, checkpointing_steps=100000, resume_from_checkpoint=None, gradient_accumulation=4, gradient_checkpointing=True, lr=0.0001, scale_lr=None, scheduler='constant', warmup_steps=0, num_cycles=1, lr_power=1.0, dataloader_num_workers=0, use_8bit_adam=None, adam_beta1=0.9, adam_beta2=0.999, adam_weight_decay=0.01, adam_epsilon=1e-08, max_grad_norm=1.0, allow_tf32=None, prior_generation_precision=None, local_rank=-1, xformers=None, pre_compute_text_embeddings=None, tokenizer_max_length=None, text_encoder_use_attention_mask=None, rank=4, xl=None, fp16=True, bf16=None, token='******', repo_id='**/**', push_to_hub=True, validation_prompt=None, num_validation_images=4, validation_epochs=50, checkpoints_total_limit=None, validation_images=None, logging=None, username=None, func=<function run_dreambooth_command_factory at 0x7db36be98550>)
> INFO    Running DreamBooth Training
> WARNING Parameters supplied but not used: func, version
You are using a model of type clip_text_model to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
The config attributes {'reverse_transformer_layers_per_block': [[4, 4, 10], [2, 1, 1], 1]} were passed to UNet2DConditionModel, but are not expected and will be ignored. Please verify your config.json configuration file.
{'dropout', 'attention_type'} was not found in config. Values will be initialized to default values.
> ERROR   train has failed due to an exception:
> ERROR   Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/autotrain/utils.py", line 280, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/dreambooth/__main__.py", line 106, in train
    tokenizers, text_encoders, vae, unet, noise_scheduler = utils.load_model_components(
  File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/dreambooth/utils.py", line 268, in load_model_components
    unet = UNet2DConditionModel.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/modeling_utils.py", line 636, in from_pretrained
    model = cls.from_config(config, **unused_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/configuration_utils.py", line 254, in from_config
    model = cls(**init_dict)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/configuration_utils.py", line 636, in inner_init
    init(self, *args, **init_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/unet_2d_condition.py", line 440, in __init__
    down_block = get_down_block(
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/unet_2d_blocks.py", line 119, in get_down_block
    return CrossAttnDownBlock2D(
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/unet_2d_blocks.py", line 1001, in __init__
    Transformer2DModel(
  File "/usr/local/lib/python3.10/dist-packages/diffusers/configuration_utils.py", line 636, in inner_init
    init(self, *args, **init_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/transformer_2d.py", line 191, in __init__
    for d in range(num_layers)
TypeError: 'list' object cannot be interpreted as an integer
