### ISSUE TITLE
I am having errors while running the first cell please help 

### ISSUE THREAD

**Issue by ISMIALKHAN17** [huggingface/autotrain-advanced#334]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
lida 0.0.10 requires kaleido, which is not installed.
llmx 0.0.15a0 requires cohere, which is not installed.
llmx 0.0.15a0 requires openai, which is not installed.
tensorflow-metadata 1.14.0 requires protobuf<4.21,>=3.20.3, but you have protobuf 4.23.4 which is incompatible.
tensorflow-probability 0.22.0 requires typing-extensions<4.6.0, but you have typing-extensions 4.8.0 which is incompatible

**Comment by abhishekkrthakur** [comment]
this error doesnt matter.
