### ISSUE TITLE
How to 

### ISSUE THREAD

**Issue by eviIgenius** [huggingface/autotrain-advanced#338]
I successfully trained the mistral 7B sharded model on google colab using the autotrain

Now, how can I do inference , I am unable to merger the adapter with the base model , can someone please share the code for inference with me . Please help

**Comment by abhishekkrthakur** [comment]
see pinned issue

**Comment by eviigenius** [comment]
> see pinned issue

Thanks @abhishekkrthakur , I was finally able to do the inference after first loading the base model in 4bits using bits and bytes and then adding the adapters to it , is there a way where I can like generate a single file and make a simple ggml/gguf 4 bit model so I can use it natively in say LM studio or webUI?

**Comment by Faraz1243** [comment]
> > see pinned issue
> 
> Thanks @abhishekkrthakur , I was finally able to do the inference after first loading the base model in 4bits using bits and bytes and then adding the adapters to it , is there a way where I can like generate a single file and make a simple ggml/gguf 4 bit model so I can use it natively in say LM studio or webUI?

kindly share the url of solution
