### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by xihajun** [huggingface/autotrain-advanced#339]
I'm intrigued by the fine-tuning capabilities provided here, which allow customization of the language model without requiring extensive technical knowledge. As I'm relatively new to this, I'd appreciate some guidance on how the process works.

Upon fine-tuning the model, I noticed that the resulting `pytorch_model.bin` file is quite small, leading me to believe that the original model remains largely unchanged and only certain layers are updated. Could anyone kindly clarify if this is the case and possibly direct me to the part of the source code where this "magic" happens?

Thank you very much for your assistance.

**Comment by abhishekkrthakur** [comment]
yes. this is indeed the case. if you used peft, you trained an adapter only model. adapter only model can be merged with base model and then can be consumed/deployed in the same manner. check out this issue: https://github.com/huggingface/autotrain-advanced/issues/299

**Comment by xihajun** [comment]
Ah, I see! Thanks a lot @abhishekkrthakur
