### ISSUE TITLE
Please use autotrain advanced

### ISSUE THREAD

**Issue by Dnsibu** [huggingface/autotrain-advanced#340]
<img width="958" alt="Screenshot 2023-11-13 at 2 18 29 PM" src="https://github.com/huggingface/autotrain-advanced/assets/57369957/dadce8ec-00d8-42ec-9307-daf3de89b126">
cannot create a new project with autotrain for any task

**Comment by abhishekkrthakur** [comment]
hf.co/docs/autotrain. the ui has now been deprecated
