### ISSUE TITLE
autotrain advance error in HF !!

### ISSUE THREAD

**Issue by mrbeandev** [huggingface/autotrain-advanced#341]
This is the error log from the HF app I created

```
===== Application Startup at 2023-11-14 13:05:12 =====


==========
== CUDA ==
==========

CUDA Version 12.1.0

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

WARNING: The NVIDIA Driver was not detected.  GPU functionality will not be available.
   Use the NVIDIA Container Toolkit to start this container with GPU support; see
   https://docs.nvidia.com/datacenter/cloud-native/ .

*************************
** DEPRECATION NOTICE! **
*************************
THIS IMAGE IS DEPRECATED and is scheduled for DELETION.
    https://gitlab.com/nvidia/container-images/cuda/blob/master/doc/support-policy.md

> INFO    Installing latest xformers
> INFO    Successfully installed latest xformers
Downloading (…)_schema%400.3.9.json:   0%|          | 0.00/12.7k [00:00<?, ?B/s]
Downloading (…)_schema%400.3.9.json: 100%|██████████| 12.7k/12.7k [00:00<00:00, 78.0MB/s]
> INFO    Authenticating user...
Traceback (most recent call last):
  File "/app/env/bin/autotrain", line 33, in <module>
    sys.exit(load_entry_point('autotrain-advanced', 'console_scripts', 'autotrain')())
  File "/app/src/autotrain/cli/autotrain.py", line 48, in main
    command.run()
  File "/app/src/autotrain/cli/run_app.py", line 57, in run
    from ..apps.main import main
  File "/app/src/autotrain/apps/main.py", line 10, in <module>
    llm = llm()
  File "/app/src/autotrain/apps/llm.py", line 52, in main
    user_token, valid_can_pay, who_is_training = common.user_validation()
  File "/app/src/autotrain/apps/common.py", line 24, in user_validation
    user_token, valid_can_pay, who_is_training = _login_user(user_token)
  File "/app/src/autotrain/apps/utils.py", line 94, in _login_user
    username = user_info["name"]
KeyError: 'name'
ERROR conda.cli.main_run:execute(49): `conda run /bin/bash -c autotrain setup && autotrain app --port 7860` failed. (See above for error)
```

**Comment by lhallee** [comment]
I had to add my write token to the settings with the same error

**Comment by eviigenius** [comment]
The error was  : WARNING: The NVIDIA Driver was not detected.  GPU functionality will not be available.

I would recommend you to check whether your GPU is detected or not

try 

```
!nvidia-smi
```

**Comment by lhallee** [comment]
NVIDIA is not available because they are likely on a CPU runtime. Pretty sure the actual error was

> INFO    Authenticating user...
Traceback (most recent call last):
  File "/app/env/bin/autotrain", line 33, in <module>
    sys.exit(load_entry_point('autotrain-advanced', 'console_scripts', 'autotrain')())
  File "/app/src/autotrain/cli/autotrain.py", line 48, in main
    command.run()
  File "/app/src/autotrain/cli/run_app.py", line 57, in run
    from ..apps.main import main
  File "/app/src/autotrain/apps/main.py", line 10, in <module>
    llm = llm()
  File "/app/src/autotrain/apps/llm.py", line 52, in main
    user_token, valid_can_pay, who_is_training = common.user_validation()
  File "/app/src/autotrain/apps/common.py", line 24, in user_validation
    user_token, valid_can_pay, who_is_training = _login_user(user_token)
  File "/app/src/autotrain/apps/utils.py", line 94, in _login_user
    username = user_info["name"]
KeyError: 'name'
ERROR conda.cli.main_run:execute(49): `conda run /bin/bash -c autotrain setup && autotrain app --port 7860` failed. (See above for error)

So need to add a write authentication token
