### ISSUE TITLE
Training zephyr LLM fails while using huggingface space

### ISSUE THREAD

**Issue by goodrahstar** [huggingface/autotrain-advanced#344]
Hi, I am trying to finetune zephyr model.

The model fails to train due to following errors.
zephyr](ValueError: Target modules q_proj,v_proj not found in the base model. Please check the target modules and try again.)

More logs:
```

Loading checkpoint shards: 100%|██████████| 8/8 [00:09<00:00, 1.08s/it]
Loading checkpoint shards: 100%|██████████| 8/8 [00:09<00:00, 1.22s/it]
/app/env/lib/python3.10/site-packages/transformers/utils/hub.py:374: FutureWarning: The use_auth_token argument is deprecated and will be removed in v5 of Transformers.
warnings.warn(
Downloading (…)neration_config.json: 0%| | 0.00/111 [00:00<?, ?B/s]
Downloading (…)neration_config.json: 100%|██████████| 111/111 [00:00<00:00, 1.32MB/s]

ERROR train has failed due to an exception:
ERROR Traceback (most recent call last):
File "/app/src/autotrain/utils.py", line 280, in wrapper
return func(*args, **kwargs)
File "/app/src/autotrain/trainers/clm/main.py", line 226, in train
model = get_peft_model(model, peft_config)
File "/app/env/lib/python3.10/site-packages/peft/mapping.py", line 106, in get_peft_model
return MODEL_TYPE_TO_PEFT_MODEL_MAPPING[peft_config.task_type](model, peft_config, adapter_name=adapter_name)
File "/app/env/lib/python3.10/site-packages/peft/peft_model.py", line 889, in init
super().init(model, peft_config, adapter_name)
File "/app/env/lib/python3.10/site-packages/peft/peft_model.py", line 111, in init
self.base_model = PEFT_TYPE_TO_MODEL_MAPPING[peft_config.peft_type](
File "/app/env/lib/python3.10/site-packages/peft/tuners/lora.py", line 274, in __init__
super().init(model, config, adapter_name)
File "/app/env/lib/python3.10/site-packages/peft/tuners/tuners_utils.py", line 88, in init
self.inject_adapter(self.model, adapter_name)
File "/app/env/lib/python3.10/site-packages/peft/tuners/tuners_utils.py", line 222, in inject_adapter
raise ValueError(
ValueError: Target modules q_proj,v_proj not found in the base model. Please check the target modules and try again.
```

**Comment by abhishekkrthakur** [comment]
fixed

**Comment by eviIgenius** [comment]
> Hi, I am trying to finetune zephyr model.
> 
> The model fails to train due to following errors. zephyr](ValueError: Target modules q_proj,v_proj not found in the base model. Please check the target modules and try again.)
> 
> More logs:
> 
> ```
> 
> Loading checkpoint shards: 100%|██████████| 8/8 [00:09<00:00, 1.08s/it]
> Loading checkpoint shards: 100%|██████████| 8/8 [00:09<00:00, 1.22s/it]
> /app/env/lib/python3.10/site-packages/transformers/utils/hub.py:374: FutureWarning: The use_auth_token argument is deprecated and will be removed in v5 of Transformers.
> warnings.warn(
> Downloading (…)neration_config.json: 0%| | 0.00/111 [00:00<?, ?B/s]
> Downloading (…)neration_config.json: 100%|██████████| 111/111 [00:00<00:00, 1.32MB/s]
> 
> ERROR train has failed due to an exception:
> ERROR Traceback (most recent call last):
> File "/app/src/autotrain/utils.py", line 280, in wrapper
> return func(*args, **kwargs)
> File "/app/src/autotrain/trainers/clm/main.py", line 226, in train
> model = get_peft_model(model, peft_config)
> File "/app/env/lib/python3.10/site-packages/peft/mapping.py", line 106, in get_peft_model
> return MODEL_TYPE_TO_PEFT_MODEL_MAPPING[peft_config.task_type](model, peft_config, adapter_name=adapter_name)
> File "/app/env/lib/python3.10/site-packages/peft/peft_model.py", line 889, in init
> super().init(model, peft_config, adapter_name)
> File "/app/env/lib/python3.10/site-packages/peft/peft_model.py", line 111, in init
> self.base_model = PEFT_TYPE_TO_MODEL_MAPPING[peft_config.peft_type](
> File "/app/env/lib/python3.10/site-packages/peft/tuners/lora.py", line 274, in __init__
> super().init(model, config, adapter_name)
> File "/app/env/lib/python3.10/site-packages/peft/tuners/tuners_utils.py", line 88, in init
> self.inject_adapter(self.model, adapter_name)
> File "/app/env/lib/python3.10/site-packages/peft/tuners/tuners_utils.py", line 222, in inject_adapter
> raise ValueError(
> ValueError: Target modules q_proj,v_proj not found in the base model. Please check the target modules and try again.
> ```

Use the below tag while fine tuning the model in autotrain advance
```
--target-modules q_proj,v_proj 
```

**Comment by goodrahstar** [comment]
Great, Thanks for the fix @abhishekkrthakur .  Eedeployed the UI and running. Its working fine now. Appreciate your blazing fast response.
