### ISSUE TITLE
Dreambooth error on T4 medium: "xformers is not available. Make sure it is installed correctly"

### ISSUE THREAD

**Issue by Norod** [huggingface/autotrain-advanced#347]
```

Downloading (…)ch_model.safetensors: 100%|██████████| 10.3G/10.3G [03:53<00:00, 44.0MB/s]
{'attention_type', 'dropout'} was not found in config. Values will be initialized to default values.
Downloading (…)cheduler_config.json:   0%|          | 0.00/479 [00:00<?, ?B/s]
Downloading (…)cheduler_config.json: 100%|██████████| 479/479 [00:00<00:00, 4.38MB/s]
{'dynamic_thresholding_ratio', 'variance_type', 'clip_sample_range', 'thresholding'} was not found in config. Values will be initialized to default values.

> ERROR   train has failed due to an exception:
> ERROR   Traceback (most recent call last):
  File "/app/src/autotrain/utils.py", line 280, in wrapper
    return func(*args, **kwargs)
  File "/app/src/autotrain/trainers/dreambooth/__main__.py", line 108, in train
    utils.enable_xformers(unet, config)
  File "/app/src/autotrain/trainers/dreambooth/utils.py", line 317, in enable_xformers
    raise ValueError("xformers is not available. Make sure it is installed correctly")
ValueError: xformers is not available. Make sure it is installed correctly

> INFO    Pausing space...
```

**Comment by eviIgenius** [comment]
> ```
> 
> Downloading (…)ch_model.safetensors: 100%|██████████| 10.3G/10.3G [03:53<00:00, 44.0MB/s]
> {'attention_type', 'dropout'} was not found in config. Values will be initialized to default values.
> Downloading (…)cheduler_config.json:   0%|          | 0.00/479 [00:00<?, ?B/s]
> Downloading (…)cheduler_config.json: 100%|██████████| 479/479 [00:00<00:00, 4.38MB/s]
> {'dynamic_thresholding_ratio', 'variance_type', 'clip_sample_range', 'thresholding'} was not found in config. Values will be initialized to default values.
> 
> > ERROR   train has failed due to an exception:
> > ERROR   Traceback (most recent call last):
>   File "/app/src/autotrain/utils.py", line 280, in wrapper
>     return func(*args, **kwargs)
>   File "/app/src/autotrain/trainers/dreambooth/__main__.py", line 108, in train
>     utils.enable_xformers(unet, config)
>   File "/app/src/autotrain/trainers/dreambooth/utils.py", line 317, in enable_xformers
>     raise ValueError("xformers is not available. Make sure it is installed correctly")
> ValueError: xformers is not available. Make sure it is installed correctly
> 
> > INFO    Pausing space...
> ```

Maybe autotrain is not properly installed in your environment. Try Using this command :

```
!pip install -U autotrain-advanced 
!autotrain setup --colab 
```

You may get the below error but xformers and rest of libraries will work fine while fine tuning the model.

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
lida 0.0.10 requires kaleido, which is not installed.
llmx 0.0.15a0 requires cohere, which is not installed.
llmx 0.0.15a0 requires openai, which is not installed.
tensorflow-metadata 1.14.0 requires protobuf<4.21,>=3.20.3, but you have protobuf 4.23.4 which is incompatible.
tensorflow-probability 0.22.0 requires typing-extensions<4.6.0, but you have typing-extensions 4.8.0 which is incompatible.

> INFO    Installing latest xformers
> INFO    Successfully installed latest xformers
```

**Comment by Norod** [comment]
Sorry, I should have mentioned it in the issue description. 
It was not my own environment, it was a fork of the official https://huggingface.co/autotrain-projects space which did the setup and created the T4 based environment space for me (as well as generated the dataset in HF from the images I provided). Everything was done from the Space's UI.

**Comment by abhishekkrthakur** [comment]
Thanks for reporting. Ill fix it. in the meantime, you can just uncheck xformers.

**Comment by abhishekkrthakur** [comment]
should be fixed now. if not, feel free to reopen.
