### ISSUE TITLE
Question about the naming (Test dataset split)

### ISSUE THREAD

**Issue by xihajun** [huggingface/autotrain-advanced#348]
If there is any good reason of using the term `--train_split` for testset?
https://github.com/huggingface/autotrain-advanced/blob/22944c0cbb1c5e0f0929407438e8a6ae34fe9ed2/src/autotrain/cli/run_llm.py#L47-L52

Would it be more straightforward with a name `--test_split`?

**Comment by abhishekkrthakur** [comment]
sorry, thats a typo. fixed
