### ISSUE TITLE
How to reload the checkpoints for LLM finetuning?

### ISSUE THREAD

**Issue by xihajun** [huggingface/autotrain-advanced#349]
May I ask how to resume from the latest checkpoint using `autotrain llm` if it crashed. I only found one from the `dreambooth` trainers, but I cannot find the `resume_from_checkpoint` anywhere else. 

I was wondering if it has currently not fully supported this feature yet or I was missing something? It would be super helpful if anyone can kindly pointing out how to do that using autotrain?

Many thanks!

**Comment by xihajun** [comment]
```
  --optimizer OPTIMIZER
                        Optimizer to use
  --scheduler SCHEDULER
                        Scheduler to use
```

I think I can just use the two parameters?

**Comment by ZarakiKanzaki** [comment]
@xihajun  sorry If my question sounds dumb, but why these 2 parameters would load from checkpoint?
