### ISSUE TITLE
It doesn't work when I use save_pretrained

### ISSUE THREAD

**Issue by loboere** [huggingface/autotrain-advanced#355]
It doesn't work when I use save_pretrained

I want to train lora on a model created by the pipe.save_pretrained function.
but when trying to train it seems to run out of memory, which is strange since I can train on the sdxl 1.0 model without problems.

use pipe.save_pretrained("loramodel") to save the model

![image](https://github.com/huggingface/autotrain-advanced/assets/15265895/6b47e204-f919-4bf1-809f-1421b1f3c69d)

**Comment by abhishekkrthakur** [comment]
which model is it? 🤔

**Comment by loboere** [comment]
I create a pipe with sdxl1.0 then load a lora with lora_load_weight
then I use pipe.lora_fuse and finally pipe.save_pretrained("loramodel").

I don't understand why loramodel doesn't work, but if sdxl 10. it works fine if lora model is based on sdxl1.0

**Comment by loboere** [comment]
any news? please
