### ISSUE TITLE
Error: 'Project' object has no attribute 'max_models'

### ISSUE THREAD

**Issue by mfahadakbar** [huggingface/autotrain-advanced#357]
HIi

I pip-installed the latest version on my Mac and tried it on the GCP Vertex AI instance as well. I am simply experimenting and running the example file for text classification. 
[https://github.com/huggingface/autotrain-advanced/blob/main/examples/text_classification_binary.py](url) 

It throws this error:

`Traceback (most recent call last):
  File "/Users/64323/Documents/repos/autotrain/text_classification1/eda.py", line 79, in <module>
    project_id = project.create()
  File "/Users/64323/opt/miniconda3/envs/auto_train/lib/python3.10/site-packages/autotrain/project.py", line 324, in create
    "max_models": self.max_models,
AttributeError: 'Project' object has no attribute 'max_models'`

I checked the main branch and tried to compare the project.py file, but I believe the main branch and pypi versions are different. 

Can you please help?

Thank you

**Comment by abhishekkrthakur** [comment]
examples are deprecated. will be removed tomorrow. please use deploy using spaces.

**Comment by mfahadakbar** [comment]
oh, does that mean we can not fine-tune locally?

**Comment by abhishekkrthakur** [comment]
you can fine tune locally. using the cli. use autorain command. colabs in colabs folder
