### ISSUE TITLE
ModuleNotFoundError: No module named 'gradio' Error when running Docker with AutoTrain

### ISSUE THREAD

**Issue by roozbeh397** [huggingface/autotrain-advanced#358]
I am getting ModuleNotFoundError: No module named 'gradio' Error when running Docker with AutoTrain error when ruuning the example from https://huggingface.co/blog/Llama2-for-non-engineers. 
WARNING: The NVIDIA Driver was not detected.  GPU functionality will not be available.
   Use the NVIDIA Container Toolkit to start this container with GPU support; see
   https://docs.nvidia.com/datacenter/cloud-native/ .

*************************
** DEPRECATION NOTICE! **
*************************
THIS IMAGE IS DEPRECATED and is scheduled for DELETION.
    https://gitlab.com/nvidia/container-images/cuda/blob/master/doc/support-policy.md

> INFO    Installing latest xformers
> INFO    Successfully installed latest xformers
Traceback (most recent call last):
  File "/app/env/bin/autotrain", line 33, in <module>
    sys.exit(load_entry_point('autotrain-advanced', 'console_scripts', 'autotrain')())
  File "/app/src/autotrain/cli/autotrain.py", line 48, in main
    command.run()
  File "/app/src/autotrain/cli/run_app.py", line 57, in run
    from ..apps.main import main
  File "/app/src/autotrain/apps/main.py", line 1, in <module>
    import gradio as gr
ModuleNotFoundError: No module named 'gradio'
ERROR conda.cli.main_run:execute(49): `conda run /bin/bash -c autotrain setup && autotrain app --port 7860` failed. (See above for error)

**Comment by abhishekkrthakur** [comment]
please factory reset. this issue is resolved now

**Comment by roozbeh397** [comment]
thanks, all good. Issue resolved.
