### ISSUE TITLE
Error when ruuning finetunning for llama27B

### ISSUE THREAD

**Issue by roozbeh397** [huggingface/autotrain-advanced#360]
I am getting  below error when i try to run the example from https://huggingface.co/blog/Llama2-for-non-engineers 
Please note that I use the data set downloaded as per suggestion from the blog post, data source called "alpaca". 
aenter__ 
    await self._router.startup()
  File "/app/env/lib/python3.10/site-packages/starlette/routing.py", line 654, in startup
    await handler()
  File "/app/src/autotrain/api.py", line 181, in startup_event
    process_pid = run_training()
  File "/app/src/autotrain/api.py", line 41, in run_training
    params = LLMTrainingParams.model_validate_json(params)
  File "/app/env/lib/python3.10/site-packages/pydantic/main.py", line 532, in model_validate_json
    return cls.__pydantic_validator__.validate_json(json_data, strict=strict, context=context)
  File "/app/src/autotrain/trainers/common.py", line 41, in __init__
    super().__init__(**data)
  File "/app/env/lib/python3.10/site-packages/pydantic/main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 5 validation errors for LLMTrainingParams
valid_split
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.5/v/string_type
rejected_text_column
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.5/v/string_type
target_modules
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.5/v/string_type
model_ref
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.5/v/string_type
prompt_text_column
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.5/v/string_type

ERROR:    Application startup failed. Exiting.
ERROR conda.cli.main_run:execute(49): `conda run /bin/bash -c autotrain api --port 7860 --host 0.0.0.0` failed. (See above for error) Error 

see below for the setup:
![image](https://github.com/huggingface/autotrain-advanced/assets/6134037/063fbe68-f4a1-4683-9e83-228a09a9e74f)

**Comment by abhishekkrthakur** [comment]
fixed
