### ISSUE TITLE
Error 500 - Running AutoTrain

### ISSUE THREAD

**Issue by roozbeh397** [huggingface/autotrain-advanced#361]
now get the following error with the new UI:
![image](https://github.com/huggingface/autotrain-advanced/assets/6134037/80fc03dc-8639-4d76-a780-7a131f044d3c)
see here for all the parameters
{
  "lr": 0.00003,
  "epochs": 3,
  "batch_size": 2,
  "warmup_ratio": 0.1,
  "gradient_accumulation": 1,
  "optimizer": "adamw_torch",
  "scheduler": "linear",
  "weight_decay": 0,
  "max_grad_norm": 1,
  "seed": 42,
  "block_size": 1024,
  "use_peft": true,
  "lora_r": 16,
  "lora_alpha": 32,
  "lora_dropout": 0.05,
  "logging_steps": -1,
  "evaluation_strategy": "epoch",
  "save_total_limit": 1,
  "save_strategy": "epoch",
  "auto_find_batch_size": false,
  "fp16": true,
  "use_int8": false,
  "model_max_length": 2048,
  "use_int4": true,
  "target_modules": "",
  "merge_adapter": false,
  "use_flash_attention_2": false,
  "disable_gradient_checkpointing": false
}:

**Comment by abhishekkrthakur** [comment]
what do the logs say?

**Comment by abhishekkrthakur** [comment]
you also need special access to A100, if you dont have access, choose A10G Large

**Comment by roozbeh397** [comment]
it seems that it is working now: 
![image](https://github.com/huggingface/autotrain-advanced/assets/6134037/222a236a-0f49-4bdd-b6d6-311cdbe34fac)
![image](https://github.com/huggingface/autotrain-advanced/assets/6134037/f88f0fdb-c27a-4553-8b06-74c90b4b6edb)
thanks!

**Comment by abhishekkrthakur** [comment]
💥 closing the issue :)
