### ISSUE TITLE
Error: 500 when try to do Text Classification

### ISSUE THREAD

**Issue by apriandito** [huggingface/autotrain-advanced#369]
I always get error 500 when trying to do training (Attached Image). I've tried several base model and hardware but still the same error 500. Is there something wrong?
![image](https://github.com/huggingface/autotrain-advanced/assets/39885445/730c3636-b449-4e4e-a1dc-3ba4af7e589f)

**Comment by apriandito** [comment]
Well, iam not aware about the logs there. i found that there are wrong label at my dataset. and not it works. 

![image](https://github.com/huggingface/autotrain-advanced/assets/39885445/79976543-f7fb-4c69-85cb-f9e93fcffb58)

but, when i open the link, the training was early stopped because of  something. I put the logs below

`
===== Application Startup at 2023-12-01 15:08:02 =====


==========
== CUDA ==
==========

CUDA Version 12.1.1

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

WARNING: The NVIDIA Driver was not detected.  GPU functionality will not be available.
   Use the NVIDIA Container Toolkit to start this container with GPU support; see
   https://docs.nvidia.com/datacenter/cloud-native/ .

> INFO    AUTOTRAIN_USERNAME: apriandito
> INFO    PROJECT_NAME: test-0
> INFO    TASK_ID: 2
> INFO    DATA_PATH: apriandito/autotrain-data-test
> INFO    MODEL: https://huggingface.co/bert-base-uncased
> INFO    OUTPUT_MODEL_REPO: apriandito/test-0
INFO:     Started server process [35]
INFO:     Waiting for application startup.
> INFO    {'data_path': 'apriandito/autotrain-data-test', 'model': 'https://huggingface.co/bert-base-uncased', 'lr': 5e-05, 'epochs': 3, 'max_seq_length': 128, 'batch_size': 8, 'warmup_ratio': 0.1, 'gradient_accumulation': 1, 'optimizer': 'adamw_torch', 'scheduler': 'linear', 'weight_decay': 0.0, 'max_grad_norm': 1.0, 'seed': 42, 'train_split': 'train', 'valid_split': 'validation', 'text_column': 'autotrain_text', 'target_column': 'autotrain_label', 'logging_steps': -1, 'project_name': 'test-0', 'auto_find_batch_size': False, 'fp16': False, 'save_total_limit': 1, 'save_strategy': 'epoch', 'token': 'hf_**********************************', 'push_to_hub': True, 'repo_id': 'apriandito/test-0', 'evaluation_strategy': 'epoch', 'username': 'apriandito', 'log': 'none'}
> INFO    ['accelerate', 'launch', '--num_machines', '1', '--num_processes', '1', '--mixed_precision', 'no', '-m', 'autotrain.trainers.text_classification', '--training_config', '/tmp/model/training_params.json']
> INFO    Started training with PID 102
> INFO    Process status: running
The following values were not passed to `accelerate launch` and had defaults used instead:
	`--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
/app/env/lib/python3.10/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
/app/env/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so: undefined symbol: cadam32bit_grad_fp32
> INFO    Starting training...
> INFO    Training config: {'data_path': 'apriandito/autotrain-data-test', 'model': 'https://huggingface.co/bert-base-uncased', 'lr': 5e-05, 'epochs': 3, 'max_seq_length': 128, 'batch_size': 8, 'warmup_ratio': 0.1, 'gradient_accumulation': 1, 'optimizer': 'adamw_torch', 'scheduler': 'linear', 'weight_decay': 0.0, 'max_grad_norm': 1.0, 'seed': 42, 'train_split': 'train', 'valid_split': 'validation', 'text_column': 'autotrain_text', 'target_column': 'autotrain_label', 'logging_steps': -1, 'project_name': '/tmp/model', 'auto_find_batch_size': False, 'fp16': False, 'save_total_limit': 1, 'save_strategy': 'epoch', 'token': '*****', 'push_to_hub': True, 'repo_id': 'apriandito/test-0', 'evaluation_strategy': 'epoch', 'username': 'apriandito', 'log': 'none'}
Downloading readme:   0%|          | 0.00/803 [00:00<?, ?B/s]
Downloading readme: 100%|██████████| 803/803 [00:00<00:00, 6.90MB/s]
> INFO    Process status: sleeping
Downloading data files:   0%|          | 0/2 [00:00<?, ?it/s]
Downloading data:   0%|          | 0.00/1.10M [00:00<?, ?B/s]
Downloading data: 100%|██████████| 1.10M/1.10M [00:00<00:00, 6.32MB/s]
Downloading data: 100%|██████████| 1.10M/1.10M [00:00<00:00, 6.31MB/s]
Downloading data files:  50%|█████     | 1/2 [00:00<00:00,  5.66it/s]
Downloading data:   0%|          | 0.00/260k [00:00<?, ?B/s]
Downloading data: 100%|██████████| 260k/260k [00:00<00:00, 5.37MB/s]
Downloading data files: 100%|██████████| 2/2 [00:00<00:00,  8.83it/s]
Extracting data files:   0%|          | 0/2 [00:00<?, ?it/s]
Extracting data files: 100%|██████████| 2/2 [00:00<00:00, 2436.42it/s]
Generating train split:   0%|          | 0/4283 [00:00<?, ? examples/s]
Generating train split: 100%|██████████| 4283/4283 [00:00<00:00, 508555.20 examples/s]
Generating validation split:   0%|          | 0/1071 [00:00<?, ? examples/s]
Generating validation split: 100%|██████████| 1071/1071 [00:00<00:00, 456004.42 examples/s]
/app/env/lib/python3.10/site-packages/transformers/utils/hub.py:604: UserWarning: Using `from_pretrained` with the url of a file (here https://huggingface.co/bert-base-uncased) is deprecated and won't be possible anymore in v5 of Transformers. You should host your file on the Hub (hf.co) instead and use the repository ID. Note that this is not compatible with the caching system (your file will be downloaded at each execution) or multiple processes (each process will download the file in a different temporary file).
  warnings.warn(
Downloading (…)co/bert-base-uncased:   0%|          | 0.00/229k [00:00<?, ?B/s]
Downloading (…)co/bert-base-uncased: 100%|██████████| 229k/229k [00:00<00:00, 137MB/s]
> ERROR   train has failed due to an exception:
> ERROR   Traceback (most recent call last):
  File "/app/env/lib/python3.10/site-packages/transformers/configuration_utils.py", line 707, in _get_config_dict
    config_dict = cls._dict_from_json_file(resolved_config_file)
  File "/app/env/lib/python3.10/site-packages/transformers/configuration_utils.py", line 803, in _dict_from_json_file
    return json.loads(text)
  File "/app/env/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/app/env/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/app/env/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/src/autotrain/utils.py", line 280, in wrapper
    return func(*args, **kwargs)
  File "/app/src/autotrain/trainers/text_classification/__main__.py", line 87, in train
    model_config = AutoConfig.from_pretrained(config.model, num_labels=num_classes)
  File "/app/env/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 1048, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/app/env/lib/python3.10/site-packages/transformers/configuration_utils.py", line 622, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/app/env/lib/python3.10/site-packages/transformers/configuration_utils.py", line 710, in _get_config_dict
    raise EnvironmentError(
OSError: It looks like the config file at '/tmp/tmp7n4tbxce' is not a valid JSON file.

> INFO    Pausing space...
> INFO    Process status: zombie
> INFO    Training process finished. Shutting down the server.
`

**Comment by abhishekkrthakur** [comment]
please use `bert-base-uncased` as model name instead of URL

**Comment by apriandito** [comment]
OMG thats a silly mistake.

**Comment by abhishekkrthakur** [comment]
fixed.
