### ISSUE TITLE
Autotrain for text classification, non specified error

### ISSUE THREAD

**Issue by charles2youmean** [huggingface/autotrain-advanced#373]
In my Autotrain space (built with Gradio), I've a message "Erreur" when I launch a text classification (e few seconds after the launch). No access to a log explaining the error. No matter if I change the processor, the model, etc. Or if I try with a smaller csv training file.

Any clue ?

<img width="765" alt="error_autotrain" src="https://github.com/huggingface/autotrain-advanced/assets/152991298/2c1beef5-5cdf-432c-afe8-7b137c752289">

**Comment by abhishekkrthakur** [comment]
please factory rebuild your space. you are using an older version.

**Comment by charles2youmean** [comment]
Ah OK thanks, I try that.
