### ISSUE TITLE
autotrain-advanced and tensorflow-metadata, have conflicting requirements for the protobuf package

### ISSUE THREAD

**Issue by isilberfin** [huggingface/autotrain-advanced#378]
I was implementing the code from notebook "AutoTrain_Dreambooth.ipynb". The line : 
`!pip install -U autotrain-advanced > install_logs.txt`
caused problem spesifying : **"tensorflow-metadata 1.14.0 requires protobuf<4.21,>=3.20.3, but you have protobuf 4.23.4 which is incompatible"** and after installing the required protobuf version I got the error : **"autotrain-advanced 0.6.51 requires protobuf==4.23.4, but you have protobuf 3.20.3 which is incompatible."**

**Comment by abhishekkrthakur** [comment]
this is not an error. did you try tunning anything after this?
