### ISSUE TITLE
Issue with docker

### ISSUE THREAD

**Issue by sayansinha2019** [huggingface/autotrain-advanced#383]
/opt/nvidia/nvidia_entrypoint.sh: line 67: exec: autotrain: not found

Any idea how to resolve it

**Comment by abhishekkrthakur** [comment]
too less information to give any suggestions or solutions

**Comment by sayansinha2019** [comment]
I tried installing the docker file, after installation and formation of image, i used this command to start the conatiner:
docker run --gpus all -p 8883:7860 --name autotrain_cont autotrain_llm:1.3 autotrain api --port 7860 --ip 0.0.0.0

But getting the above error

**Comment by abhishekkrthakur** [comment]
we dont recommend using docker container this way. please use the hugging face space.

**Comment by seancheung** [comment]
That's because conda env is not activated yet. You could follow this:
```bash
docker run --gpus=all huggingface/autotrain-advanced conda run --no-capture-output -p /app/env autotrain --help
```
