### ISSUE TITLE
Feature request: Specify a file path instead using a hf repo

### ISSUE THREAD

**Issue by angussiberry** [huggingface/autotrain-advanced#384]
I would like to train a local model without using HF to get the model. In order to still utilize autotrain-advanced could a local path be specified as a feature please?

To summarize, in command line parameters, can "--model" or a new parameter allow for a path variable input to local model to train.

Thanks :)

**Comment by abhishekkrthakur** [comment]
this feature is already available with the CLI. are you facing any issues?
