### ISSUE TITLE
autotrain always fails (solved)

### ISSUE THREAD

**Issue by FiveTechSoft** [huggingface/autotrain-advanced#388]
could someone confirm if HuggingFace autotrain is working fine ? Here it errors always

thank you

> WARNING Parameters not supplied by user and set to default: valid_split, max_target_length, token, data_path, epochs, batch_size, text_column, seed, max_seq_length, optimizer, use_peft, project_name, lora_dropout, lr, save_total_limit, lora_alpha, scheduler, repo_id, use_int8, evaluation_strategy, username, gradient_accumulation, train_split, target_modules, weight_decay, warmup_ratio, fp16, target_column, model, push_to_hub, max_grad_norm, auto_find_batch_size, save_strategy, logging_steps, lora_r
> WARNING Parameters not supplied by user and set to default: categorical_columns, repo_id, valid_split, num_trials, time_limit, target_columns, token, data_path, categorical_imputer, username, numeric_scaler, train_split, task, numerical_imputer, seed, project_name, model, push_to_hub, id_column, numerical_columns
INFO:     Started server process [37]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     10.16.20.172:1717 - "GET /?logs=container&__sign=eyJhbGciOiJFZERTQSJ9.eyJyZWFkIjp0cnVlLCJvbkJlaGFsZk9mIjp7Il9pZCI6IjY0MzNjNDhkN2I4MjQ3NDgwMTA2YjA2OSIsInVzZXIiOiJmaXZldGVjaCJ9LCJpYXQiOjE3MDIzMjA2OTMsInN1YiI6Ii9zcGFjZXMvZml2ZXRlY2gvdGVzdDMiLCJleHAiOjE3MDI0MDcwOTMsImlzcyI6Imh0dHBzOi8vaHVnZ2luZ2ZhY2UuY28ifQ.jNz5QJR7cf1-pi4RwGfi2FDcT7RM69zIYxfxw4LG9a3O3UDWWGl_8DhO94GAIwlvd4XmyVmgZ8dstxQ-zZCtBA HTTP/1.1" 200 OK
INFO:     10.16.20.172:1717 - "GET /logo.png HTTP/1.1" 200 OK
> INFO    Task: llm:sft
INFO:     10.16.20.172:1717 - "GET /params/llm%3Asft HTTP/1.1" 200 OK
INFO:     10.16.20.172:50080 - "POST /create_project HTTP/1.1" 422 Unprocessable Entity
INFO:     10.16.20.172:55845 - "GET /?__sign=eyJhbGciOiJFZERTQSJ9.eyJyZWFkIjp0cnVlLCJvbkJlaGFsZk9mIjp7Il9pZCI6IjY0MzNjNDhkN2I4MjQ3NDgwMTA2YjA2OSIsInVzZXIiOiJmaXZldGVjaCJ9LCJpYXQiOjE3MDIzMjA3NDksInN1YiI6Ii9zcGFjZXMvZml2ZXRlY2gvdGVzdDMiLCJleHAiOjE3MDI0MDcxNDksImlzcyI6Imh0dHBzOi8vaHVnZ2luZ2ZhY2UuY28ifQ.LzxXnrfh22ioL2HM0TaCfjmGQ4oBeOAuBAThsfgtj0LTNPUb0qyIO93EWBCRs3-0Iczpbv6sQeNaf4p9ryF3DQ HTTP/1.1" 200 OK
> INFO    Task: llm:sft
INFO:     10.16.20.172:38186 - "GET /params/llm%3Asft HTTP/1.1" 200 OK
INFO:     10.16.20.172:49740 - "POST /create_project HTTP/1.1" 422 Unprocessable Entity
INFO:     10.16.20.172:54970 - "POST /create_project HTTP/1.1" 422 Unprocessable Entity
INFO:     10.16.20.172:37962 - "GET /?__sign=eyJhbGciOiJFZERTQSJ9.eyJyZWFkIjp0cnVlLCJvbkJlaGFsZk9mIjp7Il9pZCI6IjY0MzNjNDhkN2I4MjQ3NDgwMTA2YjA2OSIsInVzZXIiOiJmaXZldGVjaCJ9LCJpYXQiOjE3MDIzODE1MjQsInN1YiI6Ii9zcGFjZXMvZml2ZXRlY2gvdGVzdDMiLCJleHAiOjE3MDI0Njc5MjQsImlzcyI6Imh0dHBzOi8vaHVnZ2luZ2ZhY2UuY28ifQ.a1tDn6ISRxbO_JkXzRE0oz-ofym3-CmygEaF85IxBn6uLNRSydG75V8cnZssdRKfBjUfisP38hOJ4Y-05-pEDw HTTP/1.1" 200 OK
INFO:     10.16.20.172:37962 - "GET /logo.png HTTP/1.1" 304 Not Modified
> INFO    Task: llm:sft
INFO:     10.16.20.172:37962 - "GET /params/llm%3Asft HTTP/1.1" 200 OK
INFO:     10.16.20.172:55506 - "POST /create_project HTTP/1.1" 422 Unprocessable Entity

**Comment by FiveTechSoft** [comment]
I just edited the posted msg, thank you sir

**Comment by abhishekkrthakur** [comment]
which task are you training for? your params seem like tabular task

**Comment by FiveTechSoft** [comment]
LLM/SFT
default base model: HuggingFaceH4/zephir-7b-beta
A10 Large (I tried also with the free one)
and uploaded prompts.csv with this content:
id,label,text
1,positive,"This movie was amazing! I loved it."
2,negative,"The plot of this book made no sense to me."
3,neutral,"It was okay, but not my favorite."
4,positive,"I couldn't stop listening to this song all day!"
5,negative,"These shoes were uncomfortable and didn't fit well."
6,neutral,"The food at the restaurant was decent, but nothing special."
7,positive,"My experience with customer service was great!"
8,negative,"I had trouble understanding what the instructor was saying in class today."
9,neutral,"Overall, I thought the event was pretty average."

**Comment by abhishekkrthakur** [comment]
autotrain llm-sft is working fine. just tested. the issue seems like you might be using parameters not supported for llm-sft. could you please factory rebuild the space and try again? also, from your data it seems like you want to do text classification and not llm sft. are you sure you want to train a llm model? did you type in the model name? the default is just a placeholder.

**Comment by FiveTechSoft** [comment]
Could you please provide a basic example that works ? I am sure many will appreciate it

All youtube videos are outdated nad are not showing the current user interface. thank you

**Comment by FiveTechSoft** [comment]
> the issue seems like you might be using parameters not supported for llm-sft

I use the ones provided by default by autotrain

**Comment by abhishekkrthakur** [comment]
In this example, i dont change any parameters:
<img width="1047" alt="image" src="https://github.com/huggingface/autotrain-advanced/assets/1183441/02ac316a-bd6d-410f-a92e-ac21a9e10585">
data looks like this:

```
text
"Below is an instruction that describes a task. Write a response that appropriately completes the request.

### Instruction:
Give three tips for staying healthy.

### Response:
1.Eat a balanced diet and make sure to include plenty of fruits and vegetables.
2. Exercise regularly to keep your body active and strong.
3. Get enough sleep and maintain a consistent sleep schedule."
"Below is an instruction that describes a task. Write a response that appropriately completes the request.

### Instruction:
What are the three primary colors?

### Response:
The three primary colors are red, blue, and yellow."
"Below is an instruction that describes a task. Write a response that appropriately completes the request.

### Instruction:
Describe the structure of an atom.

### Response:
An atom is made up of a nucleus, which contains protons and neutrons, surrounded by electrons that travel in orbits around the nucleus. The protons and neutrons have a positive charge, while the electrons have a negative charge, resulting in an overall neutral atom. The number of each particle determines the atomic number and the type of atom."
"Below is an instruction that describes a task. Write a response that appropriately completes the request.

### Instruction:
How can we reduce air pollution?

### Response:
There are a number of ways to reduce air pollution, such as shifting to renewable energy sources, encouraging the use of public transportation, prohibiting the burning of fossil fuels, implementing policies to reduce emissions from industrial sources, and implementing vehicle emissions standards. Additionally, individuals can do their part to reduce air pollution by reducing car use, avoiding burning materials such as wood, and changing to energy efficient appliances."
"Below is an instruction that describes a task. Write a response that appropriately completes the request.

### Instruction:
Describe a time when you had to make a difficult decision.

### Response:
I had to make a difficult decision when I was working as a project manager at a construction company. I was in charge of a project that needed to be completed by a certain date in order to meet the client’s expectations. However, due to unexpected delays, we were not able to meet the deadline and so I had to make a difficult decision. I decided to extend the deadline, but I had to stretch the team’s resources even further and increase the budget. Although it was a risky decision, I ultimately decided to go ahead with it to ensure that the project was completed on time and that the client’s expectations were met. The project was eventually successfully completed and this was seen as a testament to my leadership and decision-making abilities."
"Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.

### Instruction:
Identify the odd one out.

### Input:
Twitter, Instagram, Telegram

### Response:
Telegram"
```

however, as i mentioned, you are probably looking for text classification. see docs for proper formatting of data: hf.co/docs/autotrain

**Comment by FiveTechSoft** [comment]
Success!

You can check the progress of your training here: https://hf.co/spaces/fivetech/autotrain-w11x-iaf7-rjnr-0

thank you sir so much for your working example!
