### ISSUE TITLE
How to disable default used --multi_gpu ?

### ISSUE THREAD

**Issue by FiveTechSoft** [huggingface/autotrain-advanced#389]
File "/app/env/lib/python3.10/site-packages/accelerate/commands/launch.py", line 822, in _validate_launch_command
    raise ValueError("You need to use at least 2 processes to use `--multi_gpu`.")
ValueError: You need to use at least 2 processes to use `--multi_gpu`.

How to disable this from the default provided params ? 

Can autotrain be used with the free CPU version ?

thank you

**Comment by abhishekkrthakur** [comment]
fixed. please factory rebuild and you wont get this issue.

**Comment by FiveTechSoft** [comment]
wow, that was really fast. Going to test it.

Thank you Sir

**Comment by abhishekkrthakur** [comment]
you need to factory rebuild the base image that started the training and start a new one. i just verified it to be working

**Comment by FiveTechSoft** [comment]
testing it, please wait for my answer till closing this issue, thanks

**Comment by FiveTechSoft** [comment]
building, running now...

white screen, waiting...

**Comment by FiveTechSoft** [comment]
![image](https://github.com/huggingface/autotrain-advanced/assets/10235217/38b8b6f4-7f62-4eda-92b0-68e181773648)

**Comment by abhishekkrthakur** [comment]
click logs

**Comment by abhishekkrthakur** [comment]
unfortunately, you need gpu to train LLMs

**Comment by abhishekkrthakur** [comment]
yeah. if you want to check, you can use AutoTrain cli locally. however, there is no way to test run it on gpu. A10g should work. GPU varies based on model size. we dont support cpu as it will take several weeks to train a good model on a cpu and only a few hours on a gpu.

**Comment by FiveTechSoft** [comment]
understood, many thanks

**Comment by FiveTechSoft** [comment]
How to use AutoTrain cli locally ?

**Comment by abhishekkrthakur** [comment]
deviating from main topic. please see other issues. `pip install autotrain-advanced`. closing.
