### ISSUE TITLE
Missing pytorch_model.bin file after training using AutoTrain

### ISSUE THREAD

**Issue by harshithvh** [huggingface/autotrain-advanced#390]
this is the command I used
!autotrain llm --train --project_name 'llama2' --model meta-llama/Llama-2-7b-hf --data_path harshithvh/llama2_format2 --use_peft --use_int4 --learning_rate 2e-4 --train_batch_size 6 --num_train_epochs 3 --trainer sft --merge-adapter 

there seems to no pytorch_model.bin generated

**Comment by abhishekkrthakur** [comment]
read pinned issue
