### ISSUE TITLE
autotrain mistral finetune

### ISSUE THREAD

**Issue by phraslyai** [huggingface/autotrain-advanced#391]
I'm getting this issue after attempting to use autotrain on huggingface with my dataset. I have uploaded a .csv dataset with the texts

huggingface_hub.utils._errors.RepositoryNotFoundError: 404 Client Error. (Request ID: Root=1-6579f648-58e42eeb2bfdd3df1047b8b4;4a34a50f-2b40-4cc0-a29d-bfc50a53b497)

Repository Not Found for url: https://huggingface.co/api/datasets/xxx/xxx.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.

**Comment by abhishekkrthakur** [comment]
not sure if i understand the error without any context/logs. please add more information, then reopen the issue.
