### ISSUE TITLE
Input is too long, try to truncate or use a paramater to handle this

### ISSUE THREAD

**Issue by Shailendar** [huggingface/autotrain-advanced#394]
Hi Team,

I had created a model using auto train advanced. The base model used to train the model is **DTAI-KULeuven/mbert-corona-tweets-belgium-topics**. The below are the parameters I had given as training parameters.

{
  "lr": 0.00005,
  "epochs": 3,
  "max_seq_length": 128,
  "batch_size": 8,
  "warmup_ratio": 0.1,
  "gradient_accumulation": 1,
  "optimizer": "adamw_torch",
  "scheduler": "linear",
  "weight_decay": 0,
  "max_grad_norm": 1,
  "seed": 42,
  "logging_steps": -1,
  "auto_find_batch_size": false,
  "fp16": false,
  "save_total_limit": 1,
  "save_strategy": "epoch",
  "evaluation_strategy": "epoch"
}

The training got completed succssfully and I am getting responses properly for some of my inputs but when I give the below text as input I am getting the error.

**Text:** I have come through the drive thru at 10.35am on 23/07/2023 as usual there were only 2 or so cars in the drive thru including myself I got to the window and was given my food by a nice female and was asked to wait there for my coffee as that was what they were waiting for, so this is what I did. I then had a young boy with short brown hair stare at me rudely through the window then eventually opened the window and snarled at me what are you waiting for?!? In an annoyed tone,  I said my coffees.. I have been told to wait here for them he responded with well you have to go park and wait obviously. Excuse me!?! It shouldn't be that you're so under staffed (presumably because half your staff are now working in silverdale in the new store) this is not my problem. It should not be that I am to just expect that you'll take so long to make my coffee that I will have to park, let my food go cold, the grease hardens and is disgusting the hash browns go cold and stick to the packets making them not eatable we are not ever told sorry or feel this inconvenience is being acknowledged by your staff, i went inside after 10 mins of waiting in the carpark to be told by the single barista that he was inundated and the coffee had been ready for some time but when he asked for it to be delivered to the car nobody responded to do so, meaning i wouldnt have received it for god know how long if i hadnt come inside to get it myself whilst everything became cold and uneatable. This food costed far more than your staff members even get paid per hour... it is meant to be a treat but instead becomes an infuriating time and money wasting experience. This happens almost every weekend. The boy on the window was so unbelievably rude it was the icing on the cake. Absolutely unacceptable. I'll mention the phone dosent get answered at all. I have also made this feedback in the past and requested follow up and expected some form of contact regarding my complaints. I'd appreciate if you actually this time or i will go further than just reviewing through this app as obviously nobody reads, acknowledges or cares about this feedback platform.

**Error I am getting:** Input is too long, try to truncate or use a paramater to handle this: The size of tensor a (527) must match the size of tensor b (512) at non-singleton dimension 1

Could you please help me in this regard. Thanks in advance.

**Comment by abhishekkrthakur** [comment]
doesnt look like this is an issue with autotrain but more of a general "how to do inference" using a trained model question. you can take a look here: https://huggingface.co/docs/transformers/multilingual

**Comment by Shailendar** [comment]
Thanks for the details provided. But could you please help me out how the above link will support to my requirement. I had trained a new model(https://huggingface.co/gbwsolutions/TopicModelingTest-0) based on pre trained model(https://huggingface.co/DTAI-KULeuven/mbert-corona-tweets-belgium-topics). I haven't done any coding to create or train the model. I had created my new model using AutoTrain Advanced and once after training completed it created my new model and it is giving the error which I mentioned above.
![AutoTrainedModelError](https://github.com/huggingface/autotrain-advanced/assets/42084617/43690964-ae43-4320-a995-63db06d37cec)
