### ISSUE TITLE
AutoTrain advanced CLI: error: unrecognized arguments: --fp16 --use-int4

### ISSUE THREAD

**Issue by athuKawale** [huggingface/autotrain-advanced#395]
I am currently facing an issue while fine-tuning my data with the LLM model in a Colab notebook using the provided autotrain tool. The error message suggests that the arguments '--fp16' and '--use-int4' are not recognized by autotrain. I've checked the documentation and syntax, but the problem persists. Could you provide guidance on resolving this issue or offer insights into any potential solutions? Thank you.
```

/usr/local/lib/python3.10/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/usr/local/lib/python3.10/dist-packages/torchvision/image.so: undefined symbol: _ZN3c104cuda9SetDeviceEi'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
usage: autotrain <command> [<args>]
AutoTrain advanced CLI: error: unrecognized arguments: --fp16 --use-int4
```

![Screenshot from 2023-12-15 11-20-28](https://github.com/huggingface/autotrain-advanced/assets/143707547/961bb92f-a234-42ce-8bbd-4e2abc731569)

**Comment by abhishekkrthakur** [comment]
colab updated. 
you can always do `autotrain llm --help` to see if some parameters have changed.
