### ISSUE TITLE
Unable to run my finetuned model using free inference api

### ISSUE THREAD

**Issue by VishalPranavAG** [huggingface/autotrain-advanced#396]
After successful finetuning of gpt2 model i am not able to run my model in inference api and i get the following error. 
Repo: vishalpranavag/gp2-twitgen2

Could not load model vishalpranavag/gp2-twitgen2 with any of the following classes: (<class 'transformers.models.gpt2.modeling_gpt2.GPT2LMHeadModel'>, <class 'transformers.models.gpt2.modeling_tf_gpt2.TFGPT2LMHeadModel'>). See the original errors: while loading with GPT2LMHeadModel, an error is thrown: Traceback (most recent call last): File "/usr/local/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py", line 270, in hf_raise_for_status response.raise_for_status() File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status raise HTTPError(http_error_msg, response=self) requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/vishalpranavag/gp2-twitgen2/resolve/d9ec3aad2cf115926c9a28e2dd0e37a2c2a0c1c0/tf_model.h5 The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/src/transformers/src/transformers/utils/hub.py", line 620, in has_file hf_raise_for_status(r) File "/usr/local/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py", line 320, in hf_raise_for_status raise RepositoryNotFoundError(message, response) from e huggingface_hub.utils._errors.RepositoryNotFoundError: 401 Client Error. (Request ID: Root=1-657c1df6-69d07fff3381f21e5f545ea7) Repository Not Found for url: https://huggingface.co/vishalpranavag/gp2-twitgen2/resolve/d9ec3aad2cf115926c9a28e2dd0e37a2c2a0c1c0/tf_model.h5. Please make sure you specified the correct `repo_id` and `repo_type`. If you are trying to access a private or gated repo, make sure you are authenticated. Invalid username or password. During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/src/transformers/src/transformers/pipelines/base.py", line 269, in infer_framework_load_model model = model_class.from_pretrained(model, **kwargs) File "/src/transformers/src/transformers/modeling_utils.py", line 3117, in from_pretrained if has_file(pretrained_model_name_or_path, TF2_WEIGHTS_NAME, **has_file_kwargs): File "/src/transformers/src/transformers/utils/hub.py", line 631, in has_file raise EnvironmentError(f"{path_or_repo} is not a local folder or a valid repository name on 'https://hf.co'.") OSError: vishalpranavag/gp2-twitgen2 is not a local folder or a valid repository name on 'https://hf.co'. while loading with TFGPT2LMHeadModel, an error is thrown: Traceback (most recent call last): File "/usr/local/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py", line 270, in hf_raise_for_status response.raise_for_status() File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status raise HTTPError(http_error_msg, response=self) requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/vishalpranavag/gp2-twitgen2/resolve/d9ec3aad2cf115926c9a28e2dd0e37a2c2a0c1c0/model.safetensors.index.json The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/src/transformers/src/transformers/utils/hub.py", line 620, in has_file hf_raise_for_status(r) File "/usr/local/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py", line 320, in hf_raise_for_status raise RepositoryNotFoundError(message, response) from e huggingface_hub.utils._errors.RepositoryNotFoundError: 401 Client Error. (Request ID: Root=1-657c1df6-689648b82fb4c9a51b2dc5dc) Repository Not Found for url: https://huggingface.co/vishalpranavag/gp2-twitgen2/resolve/d9ec3aad2cf115926c9a28e2dd0e37a2c2a0c1c0/model.safetensors.index.json. Please make sure you specified the correct `repo_id` and `repo_type`. If you are trying to access a private or gated repo, make sure you are authenticated. Invalid username or password. During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/src/transformers/src/transformers/pipelines/base.py", line 269, in infer_framework_load_model model = model_class.from_pretrained(model, **kwargs) File "/src/transformers/src/transformers/modeling_tf_utils.py", line 2818, in from_pretrained if has_file(pretrained_model_name_or_path, SAFE_WEIGHTS_INDEX_NAME, **has_file_kwargs): File "/src/transformers/src/transformers/utils/hub.py", line 631, in has_file raise EnvironmentError(f"{path_or_repo} is not a local folder or a valid repository name on 'https://hf.co'.") OSError: vishalpranavag/gp2-twitgen2 is not a local folder or a valid repository name on 'https://hf.co'.

**Comment by abhishekkrthakur** [comment]
it seems like a adapter model. you didnt merge the adapter. please take a look at pinned issue. ill close this issue to reduce noise.
