### ISSUE TITLE
❌ ERROR  | 2023-12-15 14:04:00 | autotrain.trainers.common:wrapper:80 - num_samples should be a positive integer value, but got num_samples=0 

### ISSUE THREAD

**Issue by fatihayUtopia** [huggingface/autotrain-advanced#397]
ı tried every format and did not work ı still get the same issue. I put that ı have tried csv files.
Secondly you say "An example dataset for this format can be found here: https://huggingface.co/datasets/timdettmers/openassistant-guanaco" in the autotrain section. there is no csv format in the link you referred.
[dataset.csv](https://github.com/huggingface/autotrain-advanced/files/13686756/dataset.csv)
[dataset1.csv](https://github.com/huggingface/autotrain-advanced/files/13686757/dataset1.csv)
[dataset2.csv](https://github.com/huggingface/autotrain-advanced/files/13686758/dataset2.csv)
[dataset3.csv](https://github.com/huggingface/autotrain-advanced/files/13686759/dataset3.csv)

**Comment by abhishekkrthakur** [comment]
you need more than 50 samples. if you have less samples, change block_size to something like 128 or even lower.

**Comment by ejohb** [comment]
> yes it worked thank you

Which one worked?
