### ISSUE TITLE
AutoTrain LoRA Dreambooth Training error

### ISSUE THREAD

**Issue by Bullseye110** [huggingface/autotrain-advanced#408]
Hello!
So I tried to train a SDXL 1.0 Dreambooth LoRA with the latest google colab notebook posted here and I always get the errors from screenshots.
Let me to know if it can be fixed.
Thanks!

![fix](https://github.com/huggingface/autotrain-advanced/assets/137621616/1a4bb426-6756-45ce-ad41-62e8e31d5bec)
![fix 1](https://github.com/huggingface/autotrain-advanced/assets/137621616/441ac8f2-1598-4e63-969c-066f1817c8b4)

**Comment by abhishekkrthakur** [comment]
The model you are using doesnt look like SDXL. was this model previously working?
Can you try adding: `pip install -U xformers==0.0.22` in a cell before the very first cell and then run everything?

**Comment by abhishekkrthakur** [comment]
Does this colab work: https://colab.research.google.com/github/huggingface/autotrain-advanced/blob/main/colabs/AutoTrain_Dreambooth.ipynb ?

**Comment by Bullseye110** [comment]
> Does this colab work: https://colab.research.google.com/github/huggingface/autotrain-advanced/blob/main/colabs/AutoTrain_Dreambooth.ipynb ?

Yes, this one is working.

**Comment by Bullseye110** [comment]
> The model you are using doesnt look like SDXL. was this model previously working? Can you try adding: `pip install -U xformers==0.0.22` in a cell before the very first cell and then run everything?

I tried with the base SDXL 1.0 model too, but I forgot to take screenshots. It gave me the same error anyway.

**Comment by abhishekkrthakur** [comment]
> Yes, this one is working.

Thanks! fix to new UI coming soon.

**Comment by Bullseye110** [comment]
> > Yes, this one is working.
> 
> Thanks! fix to new UI coming soon.

These are from SDXL 1.0 training with your "!pip install -U xformers==0.0.22" code.

![fix 2](https://github.com/huggingface/autotrain-advanced/assets/137621616/89b39b18-74c6-4a19-a023-c1e1e5e1e877)
![fix 3](https://github.com/huggingface/autotrain-advanced/assets/137621616/8061c707-aa8b-46dc-b4cc-8ba59796a448)

**Comment by abhishekkrthakur** [comment]
<img width="1402" alt="image" src="https://github.com/huggingface/autotrain-advanced/assets/1183441/6596fdfc-7e28-4086-9f2f-cca2bffdc920">
without any changes, im able to train just fine. you dont need "!pip install -U xformers==0.0.22" either. did you set the resolution parameter correctly? here's the params i used, changed only resolution and model was sdxl 1.0: stabilityai/stable-diffusion-xl-base-1.0
<img width="1063" alt="image" src="https://github.com/huggingface/autotrain-advanced/assets/1183441/30ef5611-8a3c-4db1-9ed8-cf3263950a21">

**Comment by Bullseye110** [comment]
> <img alt="image" width="1402" src="https://private-user-images.githubusercontent.com/1183441/291573546-6596fdfc-7e28-4086-9f2f-cca2bffdc920.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5ODYwNDEsIm5iZiI6MTcwMjk4NTc0MSwicGF0aCI6Ii8xMTgzNDQxLzI5MTU3MzU0Ni02NTk2ZmRmYy03ZTI4LTQwODYtOWYyZi1jY2EyYmZmZGM5MjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTlUMTEzNTQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDhhNGUzMjg1MGQxYzZhNDI5ZmMwM2IwZDY3ZWM5ZWFmZDBjMmY0YzMyZmZjZjJiY2M0NTZhOTU2NDBjNGVlMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.R4YSfxtLCwNFh3RKp6CEqrnJZX7gNXmVCcRS01V6cWA"> without any changes, im able to train just fine. you dont need "!pip install -U xformers==0.0.22" either. did you set the resolution parameter correctly? here's the params i used, changed only resolution and model was sdxl 1.0: stabilityai/stable-diffusion-xl-base-1.0 <img alt="image" width="1063" src="https://private-user-images.githubusercontent.com/1183441/291573931-30ef5611-8a3c-4db1-9ed8-cf3263950a21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5ODYwNDEsIm5iZiI6MTcwMjk4NTc0MSwicGF0aCI6Ii8xMTgzNDQxLzI5MTU3MzkzMS0zMGVmNTYxMS04YTNjLTRkYjEtOWVkOC1jZjMyNjM5NTBhMjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTlUMTEzNTQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTQ3MjMzZWQzODAyYTVhN2RiZGU5NzVkMWFiZjczMDA5NGNjYTRkOTAzNjY0NDA2ZjdlN2VjYWMzNmI2ZGU2ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.l6zeaTRoIPOJutnqcqauBLzeFfTi2Q7Dx-77VMZzej4">

So you didn't upload the images with the "Upload Training File(s)" button. Do we create a folder called "images" again in colab and put the images there?

**Comment by abhishekkrthakur** [comment]
I uploaded the images using the "Upload Training File(s)" button. There is no need to create the "images" folder if you are using the new UI. Did you change any parameters ?

**Comment by abhishekkrthakur** [comment]
could you please try the ui from scratch with stabilityai/stable-diffusion-xl-base-1.0 default params, only resolution changed to 1024?

**Comment by Bullseye110** [comment]
> could you please try the ui from scratch with stabilityai/stable-diffusion-xl-base-1.0 default params, only resolution changed to 1024?

Right now.

**Comment by Bullseye110** [comment]
> could you please try the ui from scratch with stabilityai/stable-diffusion-xl-base-1.0 default params, only resolution changed to 1024?

It works now.
