### ISSUE TITLE
Autotrain - LLM training column names don't match

### ISSUE THREAD

**Issue by Oddadmix** [huggingface/autotrain-advanced#411]
First thank you for the amazing library.

I am trying to run the autotrain to fine-tune llm model

`!PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python autotrain llm --train --project_name "./llm-colors" --model meta-llama/Llama-2-7b-hf --data_path . --learning_rate 2e-4 --train_batch_size 12 --num_train_epochs 3 --trainer sft`

Here is sample of the data `train.csv`
```
text
"Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.

### Instruction:
Generate hex color using a theme name or color name

### Input:
Black

### Response:
#000000"

I am getting the below error

```
 Running LLM
> INFO    Params: Namespace(version=False, train=True, deploy=False, inference=False, data_path='.', train_split='train', valid_split=None, text_column='text', rejected_text_column='rejected', prompt_text_column='prompt', model='meta-llama/Llama-2-7b-hf', model_ref=None, learning_rate=0.0002, num_train_epochs=3, train_batch_size=12, warmup_ratio=0.1, gradient_accumulation_steps=1, optimizer='adamw_torch', scheduler='linear', weight_decay=0.0, max_grad_norm=1.0, seed=42, add_eos_token=False, block_size=-1, peft=False, lora_r=16, lora_alpha=32, lora_dropout=0.05, logging_steps=-1, project_name='./llm-colors', evaluation_strategy='epoch', save_total_limit=1, save_strategy='epoch', auto_find_batch_size=False, mixed_precision=None, quantization=None, push_to_hub=False, model_max_length=1024, repo_id=None, trainer='sft', target_modules=None, merge_adapter=False, token=None, backend='default', username=None, use_flash_attention_2=False, log='none', disable_gradient_checkpointing=False, dpo_beta=0.1, func=<function run_llm_command_factory at 0x7f7cfeebd550>)
Downloading data files: 100%|██████████████████| 3/3 [00:00<00:00, 13617.87it/s]
Extracting data files: 100%|████████████████████| 3/3 [00:00<00:00, 1344.62it/s]
Generating train split: 2 examples [00:00, 144.42 examples/s]
> ERROR   train has failed due to an exception: Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/datasets/builder.py", line 1940, in _prepare_split_single
    writer.write_table(table)
  File "/usr/local/lib/python3.9/dist-packages/datasets/arrow_writer.py", line 572, in write_table
    pa_table = table_cast(pa_table, self._schema)
  File "/usr/local/lib/python3.9/dist-packages/datasets/table.py", line 2328, in table_cast
    return cast_table_to_schema(table, schema)
  File "/usr/local/lib/python3.9/dist-packages/datasets/table.py", line 2286, in cast_table_to_schema
    raise ValueError(f"Couldn't cast\n{table.schema}\nto\n{features}\nbecause column names don't match")
ValueError: Couldn't cast
model: string
project_name: string
data_path: string
train_split: string
valid_split: null
add_eos_token: bool
block_size: int64
model_max_length: int64
trainer: string
use_flash_attention_2: bool
log: string
disable_gradient_checkpointing: bool
logging_steps: int64
evaluation_strategy: string
save_total_limit: int64
save_strategy: string
auto_find_batch_size: bool
mixed_precision: null
lr: double
epochs: int64
batch_size: int64
warmup_ratio: double
gradient_accumulation: int64
optimizer: string
scheduler: string
weight_decay: double
max_grad_norm: double
seed: int64
quantization: null
target_modules: null
merge_adapter: bool
peft: bool
lora_r: int64
lora_alpha: int64
lora_dropout: double
model_ref: null
dpo_beta: double
prompt_text_column: string
text_column: string
rejected_text_column: string
push_to_hub: bool
repo_id: null
username: null
token: null
to
{'version': Value(dtype='string', id=None), 'data': [{'id': Value(dtype='int64', id=None), 'Question': Value(dtype='string', id=None), 'Answer': Value(dtype='string', id=None)}]}
because column names don't match

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/autotrain/trainers/common.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/autotrain/trainers/clm/__main__.py", line 111, in train
    train_data, valid_data = process_input_data(config)
  File "/usr/local/lib/python3.9/dist-packages/autotrain/trainers/clm/__main__.py", line 51, in process_input_data
    train_data = load_dataset(
  File "/usr/local/lib/python3.9/dist-packages/datasets/load.py", line 2153, in load_dataset
    builder_instance.download_and_prepare(
  File "/usr/local/lib/python3.9/dist-packages/datasets/builder.py", line 954, in download_and_prepare
    self._download_and_prepare(
  File "/usr/local/lib/python3.9/dist-packages/datasets/builder.py", line 1049, in _download_and_prepare
    self._prepare_split(split_generator, **prepare_split_kwargs)
  File "/usr/local/lib/python3.9/dist-packages/datasets/builder.py", line 1813, in _prepare_split
    for job_id, done, content in self._prepare_split_single(
  File "/usr/local/lib/python3.9/dist-packages/datasets/builder.py", line 1958, in _prepare_split_single
    raise DatasetGenerationError("An error occurred while generating the dataset") from e
datasets.builder.DatasetGenerationError: An error occurred while generating the dataset

> ERROR   An error occurred while generating the dataset

Isn't the expectation to have only one column in that case called `text` ?

**Comment by abhishekkrthakur** [comment]
I've a few questions :) 
how many examples do you have it in train.csv? are you able to load train.csv using pandas without any issues? is train.csv located in the same directory where you running the command from (since your data path is .) ?

**Comment by Oddadmix** [comment]
I think you are correct. Looks like it was a path issue for loading the data, I only got confused about the error.

We could have an error when not able to load the file vs wrong column names. 

I would be happy to help as well. 

Great work again.
