### ISSUE TITLE
autotrain.trainers.common:wrapper:80 - 'text'

### ISSUE THREAD

**Issue by sahithip** [huggingface/autotrain-advanced#424]
### Prerequisites

- [X] I have read the [documentation](https://hf.co/docs/autotrain).
- [X] I have checked other issues for similar problems.

### Backend

Colab

### Interface Used

CLI

### CLI Command

Tried this:
!autotrain llm --train --project-name abc --model mistralai/Mistral-7B-Instruct-v0.1  --data-path . --use-peft --quantization int4 --train-batch-size 12 --epochs 3 --lr 2e-4 --trainer sft --target_modules q_proj,v_proj --push-to-hub --repo-id abc --token abc

Also tried this:
!autotrain llm --train --project-name abc --model mistralai/Mistral-7B-Instruct-v0.1  --data-path . --use-peft --quantization int4 --train-batch-size 12 --epochs 3 --lr 2e-4 --trainer sft --target_modules q_proj,v_proj --push-to-hub --text-column text --repo-id abc --token abc

### Error Logs

/usr/local/lib/python3.10/dist-packages/trl/trainer/sft_trainer.py:247: UserWarning: You passed a tokenizer with `padding_side` not equal to `right` to the SFTTrainer. This might lead to some unexpected behaviour due to overflow issues when training a model in half-precision. You might consider adding `tokenizer.padding_side = 'right'` to your code.
  warnings.warn(
  0% 0/1194 [00:00<?, ?it/s]❌ ERROR  | 2023-12-20 22:00:35 | autotrain.trainers.common:wrapper:79 - train has failed due to an exception: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/common.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/clm/__main__.py", line 446, in train
    trainer.train()
  File "/usr/local/lib/python3.10/dist-packages/trl/trainer/sft_trainer.py", line 280, in train
    output = super().train(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 1537, in train
    return inner_training_loop(
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 1821, in _inner_training_loop
    for step, inputs in enumerate(epoch_iterator):
  File "/usr/local/lib/python3.10/dist-packages/accelerate/data_loader.py", line 639, in __iter__
    next_batch, next_batch_info = self._fetch_batches(main_iterator)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/data_loader.py", line 601, in _fetch_batches
    batches.append(next(iterator))
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 674, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 32, in fetch
    data.append(next(self.dataset_iter))
  File "/usr/local/lib/python3.10/dist-packages/trl/trainer/utils.py", line 565, in __iter__
    buffer.append(self.formatting_func(next(iterator)))
  File "/usr/local/lib/python3.10/dist-packages/trl/trainer/utils.py", line 541, in <lambda>
    self.formatting_func = lambda x: x[dataset_text_field]
KeyError: 'text'

❌ ERROR  | 2023-12-20 22:00:35 | autotrain.trainers.common:wrapper:80 - 'text'

### Additional Information

Train data: ['./train.csv']
Valid data: []
Column mapping: {'text': 'text', 'rejected_text': 'rejected', 'prompt': 'prompt'}

Saving the dataset (1/1 shards): 100% 4768/4768 [00:00<00:00, 545020.62 examples/s]
Saving the dataset (1/1 shards): 100% 4768/4768 [00:00<00:00, 481368.19 examples/s]
> INFO    Starting local training...
> INFO    ['accelerate', 'launch', '--num_machines', '1', '--num_processes', '1', '--mixed_precision', 'no', '-m', 'autotrain.trainers.clm', '--training_config', '']
The following values were not passed to `accelerate launch` and had defaults used instead:
	`--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
/usr/local/lib/python3.10/dist-packages/trl/trainer/ppo_config.py:141: UserWarning: The `optimize_cuda_cache` arguement will be deprecated soon, please use `optimize_device_cache` instead.
  warnings.warn(
🚀 INFO   | 2023-12-20 21:57:43 | __main__:process_input_data:41 - loading dataset from disk
🚀 INFO   | 2023-12-20 21:57:43 | __main__:process_input_data:82 - Train data: Dataset({
    features: ['autotrain_text'],
    num_rows: 4768
})
🚀 INFO   | 2023-12-20 21:57:43 | __main__:process_input_data:83 - Valid data: Dataset({
    features: ['autotrain_text'],
    num_rows: 4768
})

The train.csv has "text" column.

**Comment by abhishekkrthakur** [comment]
i was just looking at it. what was the issue? :)

**Comment by sahithip** [comment]
Was fixed in [423](https://github.com/huggingface/autotrain-advanced/issues/423)
