### ISSUE TITLE
[BUG]  RuntimeError during Model Training with CUDA: Device-Side Assert Triggered

### ISSUE THREAD

**Issue by cometothed4rkside** [huggingface/autotrain-advanced#426]
### Prerequisites

- [X] I have read the [documentation](https://hf.co/docs/autotrain).
- [X] I have checked other issues for similar problems.

### Backend

Local

### Interface Used

CLI

### Error Logs

🚀 INFO   | 2023-12-21 01:48:47 | __main__:train:47 - loading dataset from disk
🚀 INFO   | 2023-12-21 01:48:47 | __main__:train:58 - loading dataset from disk
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
  0%|                                                                                        | 0/51051 [00:00<?, ?it/s]C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:250: block: [0,0,0], thread: [1,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:250: block: [0,0,0], thread: [3,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:250: block: [0,0,0], thread: [4,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:250: block: [0,0,0], thread: [5,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:250: block: [0,0,0], thread: [6,0,0] Assertion `t >= 0 && t < n_classes` failed.
❌ ERROR  | 2023-12-21 01:48:49 | autotrain.trainers.common:wrapper:79 - train has failed due to an exception: Traceback (most recent call last):
  File "C:\Users\test\AppData\Local\Programs\Python\Python310\lib\site-packages\autotrain\trainers\common.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\test\AppData\Local\Programs\Python\Python310\lib\site-packages\autotrain\trainers\text_classification\__main__.py", line 169, in train
    trainer.train()
  File "C:\Users\test\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\trainer.py", line 1537, in train
    return inner_training_loop(
  File "C:\Users\test\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\trainer.py", line 1854, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "C:\Users\test\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\trainer.py", line 2737, in training_step
    self.accelerator.backward(loss)
  File "C:\Users\test\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\accelerator.py", line 1903, in backward
    self.scaler.scale(loss).backward(**kwargs)
  File "C:\Users\test\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\cuda\amp\grad_scaler.py", line 183, in scale
    self._lazy_init_scale_growth_tracker(outputs.device)
  File "C:\Users\test\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\cuda\amp\grad_scaler.py", line 161, in _lazy_init_scale_growth_tracker
    self._scale = torch.full((), self._init_scale, dtype=torch.float32, device=dev)
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

❌ ERROR  | 2023-12-21 01:48:49 | autotrain.trainers.common:wrapper:80 - CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

  0%|                                                                                        | 0/51051 [00:00<?, ?it/s]

**Comment by abhishekkrthakur** [comment]
please provide the cli command used in order for me to help you

**Comment by abhishekkrthakur** [comment]
please select proper task type. it seems like a regression task and you have selected classification. text regression is not available yet.

**Comment by abhishekkrthakur** [comment]
do you have any rating which are 1.5, 2.5, or other floats? or just 1,2,3,4,5 ?

**Comment by abhishekkrthakur** [comment]
in that case you can train using text-classification task. so, the selected task doesnt seem to be an issue. which GPU are you using? can you set "mixed-precision" to "fp16" and if that doesnt work, to "none"?
