### ISSUE TITLE
[Errno 2] No such file or directory: 'my_autotrain_llm/checkpoint-108/adapter_model.bin'

### ISSUE THREAD

**Issue by athuKawale** [huggingface/autotrain-advanced#428]
### Prerequisites

- [X] I have read the [documentation](https://hf.co/docs/autotrain).
- [X] I have checked other issues for similar problems.

### Backend

Colab

### Interface Used

CLI

### CLI Command

!autotrain llm \
--train \
--model ${MODEL_NAME} \
--project-name ${PROJECT_NAME} \
--data-path data/ \
--text-column text \
--lr ${LEARNING_RATE} \
--batch-size ${BATCH_SIZE} \
--epochs ${NUM_EPOCHS} \
--block-size ${BLOCK_SIZE} \
--warmup-ratio ${WARMUP_RATIO} \
--lora-r ${LORA_R} \
--lora-alpha ${LORA_ALPHA} \
--lora-dropout ${LORA_DROPOUT} \
--weight-decay ${WEIGHT_DECAY} \
--gradient-accumulation ${GRADIENT_ACCUMULATION} \
--quantization ${QUANTIZATION} \
--mixed-precision ${MIXED_PRECISION} \
$( [[ "$PEFT" == "True" ]] && echo "--peft" ) \
$( [[ "$PUSH_TO_HUB" == "True" ]] && echo "--push-to-hub --token ${HF_TOKEN} --repo-id ${REPO_ID}" )

### UI Screenshots & Parameters

learning_rate = 2e-4
num_epochs = 4
batch_size = 1
block_size = 1024
trainer = "sft"
warmup_ratio = 0.1
weight_decay = 0.01
gradient_accumulation = 4
mixed_precision = "fp16"
peft = True
quantization = "int4"
lora_r = 16
lora_alpha = 32
lora_dropout = 0.045

### Error Logs

```
❌ ERROR  | 2023-12-21 06:55:38 | autotrain.trainers.common:wrapper:86 - train has failed due to an exception: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/common.py", line 83, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/clm/__main__.py", line 446, in train
    trainer.train()
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 1537, in train
    return inner_training_loop(
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 1990, in _inner_training_loop
    self.control = self.callback_handler.on_train_end(args, self.state, self.control)
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer_callback.py", line 373, in on_train_end
    return self.call_event("on_train_end", args, state, control)
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer_callback.py", line 414, in call_event
    result = getattr(callback, event)(
  File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/clm/callbacks.py", line 36, in on_train_end
    adapters_weights = torch.load(best_model_path)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 986, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 435, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 416, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'my_autotrain_llm/checkpoint-108/adapter_model.bin'

❌ ERROR  | 2023-12-21 06:55:38 | autotrain.trainers.common:wrapper:87 - [Errno 2] No such file or directory: 'my_autotrain_llm/checkpoint-108/adapter_model.bin'
```

### Additional Information

I had previously executed the same code with identical parameters and setup, and it ran seamlessly. However, I am currently encountering an error.

**Comment by abhishekkrthakur** [comment]
>  I have checked other issues for similar problems.

I dont think you have: https://github.com/huggingface/autotrain-advanced/issues/427

Which version are you on?

**Comment by athuKawale** [comment]
I have just installed it with !pip install -U autotrain-advanced this command at the start of execution

**Comment by abhishekkrthakur** [comment]
its probably fetching the old version. please make sure you have the latest version using `!autotrain --version` command. it should be 0.6.71 or later.

**Comment by athuKawale** [comment]
it is working! version problem like you said, thank you!
