### ISSUE TITLE
Does autotrain work with GGUF models ?

### ISSUE THREAD

**Issue by FiveTechSoft** [huggingface/autotrain-advanced#431]
Trying to find any GGUF from HuggingFace that works with autotrain

Is there any to use ? They just show sagemaker

many thanks

**Comment by abhishekkrthakur** [comment]
No. its not possible at the moment

**Comment by venturaEffect** [comment]
And do you know how to convert the autotrain models into gguf format? I'm trying to use llama.cpp but it doesn't work.

[https://github.com/ggerganov/llama.cpp/discussions/2948](https://github.com/ggerganov/llama.cpp/discussions/2948l)

Appreciate.

**Comment by AhilanPonnusamy** [comment]
Looking for the same information. I would like to build GGUF model from autotrained model. Followed this tutorial without success https://mdeore.medium.com/transpose-huggingface-models-to-gguf-format-6071c86ad2cc any pointers on this is highly appreciated.

**Comment by abhishekkrthakur** [comment]
No you cannot use it and its not autotrain specific.

**Comment by AhilanPonnusamy** [comment]
Got it.. Thank you for the confirmation

**Comment by venturaEffect** [comment]
Is it finally a way to convert a finetune model into .gguf format. I think is pretty obvious. Appreciate.

**Comment by venturaEffect** [comment]
> Looking for the same information. I would like to build GGUF model from autotrained model. Followed this tutorial without success https://mdeore.medium.com/transpose-huggingface-models-to-gguf-format-6071c86ad2cc any pointers on this is highly appreciated.

Did you fin a way? Appreciate.

**Comment by abhishekkrthakur** [comment]
autotrain wont convert it to gguf, but you can use this tool: https://huggingface.co/spaces/ggml-org/gguf-my-repo

**Comment by venturaEffect** [comment]
Well. It is missing the config.json file @abhishekkrthakur there is a hell of a workflow to get it done. I went to the merge adapter space you have duplicated used GPU and get a connection error  but not really explaining why? And I see you have people complaining about the same from Februar and didn't get any answer.

Please, I'm spending days with this and it is clearly very confusing and full of end roads.

**Comment by abhishekkrthakur** [comment]
ive already responded you in the discussion you opened. opening multiple posts is not going to solve your issue. reading and following docs might

**Comment by venturaEffect** [comment]
> ive already responded you in the discussion you opened. opening multiple posts is not going to solve your issue. reading and following docs might

Docs are incomplete.

**Comment by abhishekkrthakur** [comment]
yes, if you expect this package to launch a spaceship, then docs are incomplete

**Comment by venturaEffect** [comment]
Ok, I see many people asking often the same questions. And yes, it isn't clear in the docs. You even have typos.
