### ISSUE TITLE
num_samples should be a positive integer value, but got num_samples=0

### ISSUE THREAD

**Issue by FiveTechSoft** [huggingface/autotrain-advanced#432]
### Prerequisites

- [X] I have read the [documentation](https://hf.co/docs/autotrain).
- [X] I have checked other issues for similar problems.

### Backend

Local

### Interface Used

CLI

### CLI Command

❌ ERROR  | 2023-12-22 08:41:18 | autotrain.trainers.common:wrapper:91 - num_samples should be a positive integer value, but got num_samples=0

### UI Screenshots & Parameters

❌ ERROR  | 2023-12-22 08:41:18 | autotrain.trainers.common:wrapper:91 - num_samples should be a positive integer value, but got num_samples=0

### Error Logs

❌ ERROR  | 2023-12-22 08:41:18 | autotrain.trainers.common:wrapper:91 - num_samples should be a positive integer value, but got num_samples=0

**Comment by FiveTechSoft** [comment]
what to do ?

**Comment by abhishekkrthakur** [comment]
>  I have checked other issues for similar problems.

No you did not 🥲

https://github.com/huggingface/autotrain-advanced/issues/397

**Comment by FiveTechSoft** [comment]
> change block_size to something like 128 or even lower

autotrainer should warn about it, just a suggestion :-)
