### ISSUE TITLE
It looks like it isn't using my data .csv file but everything seems fine

### ISSUE THREAD

**Issue by venturaEffect** [huggingface/autotrain-advanced#444]
I've opened UI locally and set I think everything fine for the finetuning:

<img width="1014" alt="autotrain1" src="https://github.com/huggingface/autotrain-advanced/assets/29057173/c5bb280e-5f55-4f64-904a-a3956c8cafd2">
<img width="400" alt="autotrain2" src="https://github.com/huggingface/autotrain-advanced/assets/29057173/90e54c16-1099-4139-9922-1e15665c4242">

But somehow it seems it doesn't take me data from the the "text" column. Am  I doing something wrong?

<img width="263" alt="autotrain3" src="https://github.com/huggingface/autotrain-advanced/assets/29057173/8092ca47-15cd-4e4c-8699-ea57ea0addb3">
<img width="437" alt="autotrain4" src="https://github.com/huggingface/autotrain-advanced/assets/29057173/c027f882-8c98-448f-b186-3774240b9e92">

Appreciate any suggestion.

**Comment by venturaEffect** [comment]
Thanks for answering.

When trying to use the finetuned model with the script you provide on the readme of the finetuned model with autotrain, when trying to run it I get an error message like it is missing the offload_dir. When adding this parameter in AutoModelForCausalLM.from_pretrained(...) I get an error too. 

Can't figure out what is wrong:

`(autotrain) zasear@zaesarius:~/autotrain$ python usage.py
tokenizer_config.json: 100%|████| 1.44k/1.44k [00:00<00:00, 15.4MB/s]
tokenizer.model: 100%|████████████| 493k/493k [00:00<00:00, 4.76MB/s]
tokenizer.json: 100%|███████████| 1.80M/1.80M [00:00<00:00, 5.93MB/s]
special_tokens_map.json: 100%|██████| 437/437 [00:00<00:00, 3.72MB/s]
adapter_config.json: 100%|██████████| 587/587 [00:00<00:00, 3.11MB/s]
Loading checkpoint shards: 100%|███████| 3/3 [00:52<00:00, 17.44s/it]
WARNING:root:Some parameters are on the meta device device because they were offloaded to the cpu.
adapter_model.safetensors: 100%|█| 27.3M/27.3M [00:00<00:00, 35.8MB/s
/home/zasear/.local/lib/python3.10/site-packages/torch/nn/modules/module.py:2025: UserWarning: for model.layers.29.self_attn.q_proj.lora_A.default.weight: copying from a non-meta parameter in the checkpoint to a meta parameter in the current model, which is a no-op. (Did you mean to pass `assign=True` to assign items in the state dictionary to their corresponding key in the module instead of copying them in place?)
  warnings.warn(f'for {key}: copying from a non-meta parameter in the checkpoint to a meta '
/home/zasear/.local/lib/python3.10/site-packages/torch/nn/modules/module.py:2025: UserWarning: for model.layers.29.self_attn.q_proj.lora_B.default.weight: copying from a non-meta parameter in the checkpoint to a meta parameter in the current model, which is a no-op. (Did you mean to pass `assign=True` to assign items in the state dictionary to their corresponding key in the module instead of copying them in place?)
  warnings.warn(f'for {key}: copying from a non-meta parameter in the checkpoint to a meta '
/home/zasear/.local/lib/python3.10/site-packages/torch/nn/modules/module.py:2025: UserWarning: for model.layers.29.self_attn.v_proj.lora_A.default.weight: copying from a non-meta parameter in the checkpoint to a meta parameter in the current model, which is a no-op. (Did you mean to pass `assign=True` to assign items in the state dictionary to their corresponding key in the module instead of copying them in place?)
  warnings.warn(f'for {key}: copying from a non-meta parameter in the checkpoint to a meta '
/home/zasear/.local/lib/python3.10/site-packages/torch/nn/modules/module.py:2025: UserWarning: for model.layers.29.self_attn.v_proj.lora_B.default.weight: copying from a non-meta parameter in the checkpoint to a meta parameter in the current model, which is a no-op. (Did you mean to pass `assign=True` to assign items in the state dictionary to their corresponding key in the module instead of copying them in place?)
  warnings.warn(f'for {key}: copying from a non-meta parameter in the checkpoint to a meta '
/home/zasear/.local/lib/python3.10/site-packages/torch/nn/modules/module.py:2025: UserWarning: for model.layers.30.self_attn.q_proj.lora_A.default.weight: copying from a non-meta parameter in the checkpoint to a meta parameter in the current model, which is a no-op. (Did you mean to pass `assign=True` to assign items in the state dictionary to their corresponding key in the module instead of copying them in place?)
  warnings.warn(f'for {key}: copying from a non-meta parameter in the checkpoint to a meta '
/home/zasear/.local/lib/python3.10/site-packages/torch/nn/modules/module.py:2025: UserWarning: for model.layers.30.self_attn.q_proj.lora_B.default.weight: copying from a non-meta parameter in the checkpoint to a meta parameter in the current model, which is a no-op. (Did you mean to pass `assign=True` to assign items in the state dictionary to their corresponding key in the module instead of copying them in place?)
  warnings.warn(f'for {key}: copying from a non-meta parameter in the checkpoint to a meta '
/home/zasear/.local/lib/python3.10/site-packages/torch/nn/modules/module.py:2025: UserWarning: for model.layers.30.self_attn.v_proj.lora_A.default.weight: copying from a non-meta parameter in the checkpoint to a meta parameter in the current model, which is a no-op. (Did you mean to pass `assign=True` to assign items in the state dictionary to their corresponding key in the module instead of copying them in place?)
  warnings.warn(f'for {key}: copying from a non-meta parameter in the checkpoint to a meta '
/home/zasear/.local/lib/python3.10/site-packages/torch/nn/modules/module.py:2025: UserWarning: for model.layers.30.self_attn.v_proj.lora_B.default.weight: copying from a non-meta parameter in the checkpoint to a meta parameter in the current model, which is a no-op. (Did you mean to pass `assign=True` to assign items in the state dictionary to their corresponding key in the module instead of copying them in place?)
  warnings.warn(f'for {key}: copying from a non-meta parameter in the checkpoint to a meta '
/home/zasear/.local/lib/python3.10/site-packages/torch/nn/modules/module.py:2025: UserWarning: for model.layers.31.self_attn.q_proj.lora_A.default.weight: copying from a non-meta parameter in the checkpoint to a meta parameter in the current model, which is a no-op. (Did you mean to pass `assign=True` to assign items in the state dictionary to their corresponding key in the module instead of copying them in place?)
  warnings.warn(f'for {key}: copying from a non-meta parameter in the checkpoint to a meta '
/home/zasear/.local/lib/python3.10/site-packages/torch/nn/modules/module.py:2025: UserWarning: for model.layers.31.self_attn.q_proj.lora_B.default.weight: copying from a non-meta parameter in the checkpoint to a meta parameter in the current model, which is a no-op. (Did you mean to pass `assign=True` to assign items in the state dictionary to their corresponding key in the module instead of copying them in place?)
  warnings.warn(f'for {key}: copying from a non-meta parameter in the checkpoint to a meta '
/home/zasear/.local/lib/python3.10/site-packages/torch/nn/modules/module.py:2025: UserWarning: for model.layers.31.self_attn.v_proj.lora_A.default.weight: copying from a non-meta parameter in the checkpoint to a meta parameter in the current model, which is a no-op. (Did you mean to pass `assign=True` to assign items in the state dictionary to their corresponding key in the module instead of copying them in place?)
  warnings.warn(f'for {key}: copying from a non-meta parameter in the checkpoint to a meta '
/home/zasear/.local/lib/python3.10/site-packages/torch/nn/modules/module.py:2025: UserWarning: for model.layers.31.self_attn.v_proj.lora_B.default.weight: copying from a non-meta parameter in the checkpoint to a meta parameter in the current model, which is a no-op. (Did you mean to pass `assign=True` to assign items in the state dictionary to their corresponding key in the module instead of copying them in place?)
  warnings.warn(f'for {key}: copying from a non-meta parameter in the checkpoint to a meta '
Traceback (most recent call last):
  File "/home/zasear/autotrain/usage.py", line 7, in <module>
    model = AutoModelForCausalLM.from_pretrained(
  File "/home/zasear/.local/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 566, in from_pretrained
    return model_class.from_pretrained(
  File "/home/zasear/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3787, in from_pretrained
    model.load_adapter(
  File "/home/zasear/.local/lib/python3.10/site-packages/transformers/integrations/peft.py", line 222, in load_adapter
    self._dispatch_accelerate_model(
  File "/home/zasear/.local/lib/python3.10/site-packages/transformers/integrations/peft.py", line 471, in _dispatch_accelerate_model
    dispatch_model(
  File "/home/zasear/.local/lib/python3.10/site-packages/accelerate/big_modeling.py", line 368, in dispatch_model
    raise ValueError(
ValueError: We need an `offload_dir` to dispatch this model according to this `device_map`, the following submodules need to be offloaded: model.layers.27, model.layers.28, model.layers.29, model.layers.30, model.layers.31, model.norm, lm_head.`

Here the code you provide with the path of the model I'm using:

`
from transformers import AutoModelForCausalLM, AutoTokenizer

model_path = "Zaesar/ai_lawyer"

tokenizer = AutoTokenizer.from_pretrained(model_path)
model = AutoModelForCausalLM.from_pretrained(
    model_path,
    device_map="auto",
    torch_dtype='auto'
).eval()

# Prompt content: "hi"
messages = [
    {"role": "user", "content": "hi"}
]

input_ids = tokenizer.apply_chat_template(conversation=messages, tokenize=True, add_generation_prompt=True, return_tensors='pt')
output_ids = model.generate(input_ids.to('cuda'))
response = tokenizer.decode(output_ids[0][input_ids.shape[1]:], skip_special_tokens=True)

# Model response: "Hello! How can I assist you today?"
print(response)
`

Can you see what is wrong?

Appreciate

**Comment by venturaEffect** [comment]
> its because you trained a peft model without `--merge-adapter` argument. the code in the model card is only for non-peft or merged models. however, you can modify the code a bit and it will work:
> 
> ```
> from transformers import AutoModelForCausalLM, AutoTokenizer
> from peft import PeftModel
> 
> model_path = "PATH_TO_THIS_REPO"
> base_model_path = "PATH_TO_BASE_MODEL"
> 
> tokenizer = AutoTokenizer.from_pretrained(model_path)
> model = AutoModelForCausalLM.from_pretrained(
>     base_model_path,
>     device_map="auto",
>     torch_dtype='auto'
> )
> 
> model.resize_token_embeddings(len(tokenizer), pad_to_multiple_of=8)
> model = PeftModel.from_pretrained(model, model_path)
> .
> .
> .
> ```

Oh, I've used the autotrain UI locally. So there isn't set the merge-adapter by default. How should I add it? I ask for use it in the future properly. 

Appreciate

**Comment by abhishekkrthakur** [comment]
you can find merge_adapter in params which is set to false by default. you can change it to true.

**Comment by venturaEffect** [comment]
Ok, followed your advice. Tried again from scratch setting `merge-adapter` to True. But now looking at the terminal, it appears new errors.

<img width="543" alt="autotrain6" src="https://github.com/huggingface/autotrain-advanced/assets/29057173/d762781f-c34c-4736-b530-fb0adf8fc278">

Any idea what is wrong?

Appreciate.

**Comment by venturaEffect** [comment]
> it seems to have run out of gpu memory. you can also merge adapter using this space after the training is over and model is pushed: https://huggingface.co/spaces/autotrain-projects/llm-merge-adapter

How is it possible? I'm using an NVIDIA 4090 batch_size is pretty low and I didn't got this issue before.

**Comment by venturaEffect** [comment]
> its because you trained a peft model without `--merge-adapter` argument. the code in the model card is only for non-peft or merged models. however, you can modify the code a bit and it will work:
> 
> ```
> from transformers import AutoModelForCausalLM, AutoTokenizer
> from peft import PeftModel
> 
> model_path = "PATH_TO_THIS_REPO"
> base_model_path = "PATH_TO_BASE_MODEL"
> 
> tokenizer = AutoTokenizer.from_pretrained(model_path)
> model = AutoModelForCausalLM.from_pretrained(
>     base_model_path,
>     device_map="auto",
>     torch_dtype='auto'
> )
> 
> model.resize_token_embeddings(len(tokenizer), pad_to_multiple_of=8)
> model = PeftModel.from_pretrained(model, model_path)
> .
> .
> .
> ```

Used the again the option setting the merge-adapter false and the updated code to run it with the base model too but got a warning and it stopped without letting me interacting with it.

<img width="460" alt="autotrain8" src="https://github.com/huggingface/autotrain-advanced/assets/29057173/b12fae0a-d9fa-4717-a4c7-9ab24b4368a8">


This is the code with the update: 

`
from transformers import AutoModelForCausalLM, AutoTokenizer

model_path = "Zaesar/ai_lawyer_2"
base_model_path = "mistralai/Mistral-7B-Instruct-v0.2"

tokenizer = AutoTokenizer.from_pretrained(model_path)
model = AutoModelForCausalLM.from_pretrained(
    base_model_path,
    device_map="auto",
    torch_dtype='auto'
).eval()

# Prompt content: "hi"
messages = [
    {"role": "user", "content": "hi"}
]

input_ids = tokenizer.apply_chat_template(conversation=messages, tokenize=True, add_generation_prompt=True, return_tensors='pt')
output_ids = model.generate(input_ids.to('cuda'))
response = tokenizer.decode(output_ids[0][input_ids.shape[1]:], skip_special_tokens=True)

# Model response: "Hello! How can I assist you today?"
print(response)
`

Any clue why it is still not working? Appreciate.

**Comment by venturaEffect** [comment]
Ok, I made it through to run the finetuned model tweaking a bit the code template you provide once it is autotrained on push to HF. But again, when asked about the data it was finetuned it doesn't have any idea about it. And I've followed the video tutorial you have made step by step and my csv file seems completely fine. I created the 'text' column with the instruction and the output in it. On the UI I selected the 'text' column and the finetuned went through. I've added the base model on the template as you have suggested. In any case it has no clue about the finetuned data. Something that I get pretty weird is this warning: 
`Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.

/home/zasear/.local/lib/python3.10/site-packages/transformers/generation/utils.py:1636: UserWarning: You are calling .generate() with the `input_ids` being on a device type different than your model's device. `input_ids` is on cpu, whereas the model is on cuda. You may experience unexpected behaviors or slower generation. Please make sure that you have put `input_ids` to the correct device by calling for example input_ids = input_ids.to('cuda') before running `.generate()`.
  warnings.warn(`

Everything else seems fine. As you have seen before it looks everything right but it looks like the autotrain didn't do the job on fine tuning.

Any suggestion? 
Appreciate.

BTW, Happy New Year.
