### ISSUE TITLE
What is the difference between autotrain and kohya_ss?

### ISSUE THREAD

**Issue by loboere** [huggingface/autotrain-advanced#448]
What is the difference between autotrain and kohya_ss?

**Comment by katywilliams1121** [comment]
autotrain is easy

Kohya is hard

There you go.... solved it

**Comment by loboere** [comment]
Don't worry, don't get angry, can you further develop the answer as to why this is so?

**Comment by katywilliams1121** [comment]
well... you get much deeper control in the kohya SS library. that in the auto you will get the basic settings you will need for training your Lora
