### ISSUE TITLE
Progress bar is finishing prematurely [BUG]

### ISSUE THREAD

**Issue by KnutJaegersberg** [huggingface/autotrain-advanced#450]
### Prerequisites

- [X] I have read the [documentation](https://hf.co/docs/autotrain).
- [X] I have checked other issues for similar problems.

### Backend

Local

### Interface Used

CLI

### CLI Command

autotrain llm --train --project_name everythingLM-20b --model /run/media/knut/HD/huggingface\ models/language\ models/LLMs/pretrained/40b/internlm-20b-llama/ --data_path . --train_batch_size 1 --num_train_epochs 5 --trainer sft --use_int4 --use_peft --merge_adapter --block_size 1000 --max-length 4096 --target_modules "q_proj,k_proj,v_proj,o_proj" --use_flash_attention

### UI Screenshots & Parameters

![image](https://github.com/huggingface/autotrain-advanced/assets/17965169/f31f8ed4-d893-485e-8f7e-a59e1e4505a5)

### Error Logs

 56%|███████████████████████████████████████▏                              | 3000/5365 [1:41:55<1:20:20,  2.04s/it]
> INFO    Finished training, saving model...

### Additional Information

I don't know how this happens, but i've had this since quite a while. the progress bar reaches 50-60 percent and then training finishes, also indicating that the epochs have roughly reached the goal. It just stores the model as it should. 
Something gotta be wrong here, either the estimate is off, or perhaps it's not using the records right. I don't think I have wrongly formated the records. But the models I get out of it are working, which is why I've ignored it and just occasionally picked double the epochs I wanted. It happens with both peft and full fine tuning.

**Comment by abhishekkrthakur** [comment]
sft with packing doesnt show actual progress. training is indeed finished. if you'd like the progress bar be fixed, please open an issue in TRL repo :)

**Comment by KnutJaegersberg** [comment]
Thanks glad it's fine!
