### ISSUE TITLE
[BUG] Bert-base Turkish Sentiment Model

### ISSUE THREAD

**Issue by cometothed4rkside** [huggingface/autotrain-advanced#453]
### Prerequisites

- [X] I have read the [documentation](https://hf.co/docs/autotrain).
- [X] I have checked other issues for similar problems.

### Backend

Local

### Interface Used

CLI

### Error Logs

Why was Bert-base Turkish Sentiment Model removed?

**Comment by abhishekkrthakur** [comment]
add environment variable: `AUTOTRAIN_CUSTOM_MODELS` with value `savasy/bert-base-turkish-sentiment-cased` and you will be able to use it.
