### ISSUE TITLE
[FEATURE REQUEST] documentation for params

### ISSUE THREAD

**Issue by mrticker** [huggingface/autotrain-advanced#459]
### Feature Request

When you run autotrain on Spaces, you get a set of params like below. Are there any other params you could set? Is there any documentation for it? I realize some of these are params for a Model and what not, but "peft" for example is not.
> {
>   "block_size": 1024,
>   "model_max_length": 2048,
>   "padding": "right",
>   "use_flash_attention_2": false,
>   "disable_gradient_checkpointing": false,
>   "logging_steps": -1,
>   "evaluation_strategy": "epoch",
>   "save_total_limit": 1,
>   "save_strategy": "epoch",
>   "auto_find_batch_size": false,
>   "mixed_precision": "fp16",
>   "lr": 0.00003,
>   "epochs": 1,
>   "batch_size": 2,
>   "warmup_ratio": 0.1,
>   "gradient_accumulation": 1,
>   "optimizer": "adamw_torch",
>   "scheduler": "linear",
>   "weight_decay": 0,
>   "max_grad_norm": 1,
>   "seed": 42,
>   "apply_chat_template": false,
>   "quantization": "int4",
>   "target_modules": "",
>   "merge_adapter": false,
>   "peft": true,
>   "lora_r": 16,
>   "lora_alpha": 32,
>   "lora_dropout": 0.05
> }
```

```

### Motivation

Bonus question: I get "Token indices sequence length is longer than the specified maximum sequence length for this model" when training. Is there a setting for the tokenizer to truncate sequences that are too long? Or maybe it does that and the message is just a warning?

**Comment by KnutJaegersberg** [comment]
What I like about autotrain-advanced is that it concentrates pretty much everything there is to know in one place, but more documentation than just browsing the explanations in the code would be nice.

**Comment by elen07zz** [comment]
i cant make this work and your video tutorial is outdated

**Comment by abhishekkrthakur** [comment]
most of the params are from transformers. is there anything specific? cli dont have an official support as of now. why are you not using the ui ?

**Comment by elen07zz** [comment]
> most of the params are from transformers. is there anything specific? cli dont have an official support as of now. why are you not using the ui ?

how can i use the ui?

**Comment by mrticker** [comment]
> most of the params are from transformers. is there anything specific? cli dont have an official support as of now. why are you not using the ui ?

For example, how do I set cache dir for the model?

`AutoTrain advanced CLI: error: unrecognized arguments: --cache-dir /cache`
