### ISSUE TITLE
[BUG]Model size is much smaller than based model

### ISSUE THREAD

**Issue by winster-bai** [huggingface/autotrain-advanced#460]
### Prerequisites

- [X] I have read the [documentation](https://hf.co/docs/autotrain).
- [X] I have checked other issues for similar problems.

### Backend

Local

### Interface Used

CLI

### Error Logs

Hello, I am a beginner in LLM. I generated the model folder locally according to the Youtube video operation, but the folder size is only about 130Mb. The base model I use is 7b llama2. Is this normal? Why is the model size reduced so much? How do I get the normal size model? I would be grateful if you could answer it for me.

**Comment by Kamleshpaul** [comment]
you got model `adapter` you can inference with that as well or you can merge that to base model 

this is not a bug 

https://github.com/huggingface/autotrain-advanced/issues/299

check this issue
