### ISSUE TITLE
KeyError: 'name' when running locally on windows

### ISSUE THREAD

**Issue by 512DuncanL** [huggingface/autotrain-advanced#461]
### Prerequisites

- [X] I have read the [documentation](https://hf.co/docs/autotrain).
- [X] I have checked other issues for similar problems.

### Backend

Local

### Interface Used

UI

### Error Logs

![Screenshot 2024-01-13 175512](https://github.com/huggingface/autotrain-advanced/assets/49137796/0ebc60f7-f514-4a7d-ab56-75ddfcccb2e4)

### Additional Information

Not sure why but im getting the error `KeyError: 'name'` when trying to run the command `autotrain app` inside conda on windows.

**Comment by abhishekkrthakur** [comment]
incorrect token? not using write token?
