### ISSUE TITLE
[BUG]AutoTrain advanced CLI: error: unrecognized arguments: --output

### ISSUE THREAD

**Issue by mastafadhil** [huggingface/autotrain-advanced#463]
### Prerequisites

- [X] I have read the [documentation](https://hf.co/docs/autotrain).
- [X] I have checked other issues for similar problems.

### Backend

Local

### Interface Used

CLI

### CLI Command

autotrain dreambooth --model "stabilityai/stable-diffusion-xl-base-1.0" --output "E:/autobooth/model" --image-path "C:/Users/imacs/Pictures/ai/New folder" --prompt "photo of fadhil" --resolution 1024 --batch-size 1 --num-steps 500 --fp16 --gradient-accumulation 4 --lr 1e-4 --project-name "fadhil"

### Error Logs

usage: autotrain <command> [<args>]
AutoTrain advanced CLI: error: unrecognized arguments: --output E:/autobooth/model

### Additional Information

I am currently using Python 3.10.6, was able to install everything. 

I am following this specific tutorial : https://www.youtube.com/watch?v=gF078Lhnr94&t=894s

and was unable to proceed using the arg "--output", is there a new way that i am not aware of to pass on the argument to output the trained model? 

if i dont use "--output" arg in the CLI command, how do i reuse or locate the trained model (where is it saved by default)? Thanks in advance.

**Comment by abhishekkrthakur** [comment]
many arguments change from time to time. you need the same version in the tutorial (not recommended) or use the modified arguments. please see colab links in readme and other issues. this has been mentioned quite a few times btw :) 
use `autotrain dreambooth --help` to get new arguments.
