### ISSUE TITLE
[FEATURE REQUEST] Local documentation?

### ISSUE THREAD

**Issue by mathiasjg** [huggingface/autotrain-advanced#464]
### Feature Request

I'd love to see some documentation for running autotrain-advanced locally. I was a bit surprised to see that there is the recommendation to run autotrain-advanced locally but then no documentation to support it. 

### Motivation

I am hoping to be able to use autotrain locally on my machine to finetune some LLM's but there is no documentation.

### Additional Context

Running apps in huggingface spaces is very unwanted and not safe, hopefully a solution comes soon, thanks!

**Comment by waghydjemy** [comment]
I am facing this issue here https://github.com/huggingface/autotrain-advanced/issues/480
