### ISSUE TITLE
[BUG] block_size gets reset to 1024 from 4096 for LLMs

### ISSUE THREAD

**Issue by mrticker** [huggingface/autotrain-advanced#467]
### Prerequisites

- [X] I have read the [documentation](https://hf.co/docs/autotrain).
- [X] I have checked other issues for similar problems.

### Backend

Other cloud providers

### Interface Used

CLI

### CLI Command

autotrain llm (...) --block-size 4096

### Error Logs

?? WARNING | 2024-01-18 21:58:29 | __main__:train:270 - The block_size passed (4096) is larger than the maximum length for the model(1024). Using block_size=1024.
?? INFO   | 2024-01-18 21:58:29 | __main__:train:277 - Using block size 1024

### Additional Information

I set block size to 4096. Autotrain resets it to 1024. 

Looks like you need to explicitly set `model_max_length` (why? this should come from the model config on HF).

Also, it's `--model_max_length` and not `--model-max-length` (underscores  instead of hyphens  like everything else).

**Comment by jackshiwl** [comment]
same here, @abhishekkrthakur  could you please check on this? seems like a major issue

**Comment by abhishekkrthakur** [comment]
if model max len is 1024, you cannot set block size > 1024. you will need to change model's max len for larger block size :) does that help?

**Comment by mrticker** [comment]
That helps immensely. However, the question is, why is _model_max_length_ set to 1024 implicitly?

The docs say:

> model_max_length (int, optional) — The maximum length (in number of tokens) for the inputs to the transformer model. When the tokenizer is loaded with from_pretrained(), this will be set to the value stored for the associated model in max_model_input_sizes (see above). If no value is provided, will default to VERY_LARGE_INTEGER (int(1e30)).

So, I would expect _model_max_length_ to be a VERY_LARGE_INTEGER integer by default, or, at the second guess, to maybe _max_position_embeddings_ set in the model's config.json. Why would I ever expect 1024???

**Comment by jackshiwl** [comment]
@abhishekkrthakur there seems to be a bug with this.

I am currently using deepseek 6.7b instruct model, which has max model length of 16384. But if I ONLY set block-size to be 16384, this will not work, and it will set block-size back to 1024. Only if I specify both block-size and model_max_length to 16384, this will work.

checking if this is normal. thanks

**Comment by abhishekkrthakur** [comment]
@jackshiwl what kind of hardware do you train block size and model max len at 16384 on?

**Comment by jackshiwl** [comment]
I have access to my institute's high performance computing, so the hardware is 4 x Nvidia V100-32GB/node (total of 9nodes). Requires massive amount of RAM, but I am still testing this out currently. 

However, regarding the issue mentioned above, it is not related to a very high value like 16384. For example, if I set only
```
--block-size 2048 \
```
it will show this: 
```
⚠️ WARNING | 2024-01-25 08:29:48 | __main__:train:270 - The block_size passed (2048) is larger than the maximum length for the model(1024). Using block_size=1024.
🚀 INFO   | 2024-01-25 08:29:48 | __main__:train:277 - Using block size 1024
```

only if I set BOTH:
```
--model_max_length 2048 \
--block-size 2048 \
```
Then it will work:
```
Loading checkpoint shards: 100% 2/2 [01:01<00:00, 30.91s/it]
🚀 INFO   | 2024-01-25 08:34:32 | __main__:train:277 - Using block size 2048
```

**Comment by abhishekkrthakur** [comment]
that seems correct. the reason we set model max len to 1024 is because not everyone has beefy machine. so if model max len is lets say 4096 and user sets block size of same length, the training will most probably fail going oom. some models also do have unrealisticly large max len (no max len at all). this also causes issues. i can set model_max_len to a default of 2048 or 4096 but going higher might cause issues for many users without a system with many gpus/ram

**Comment by jackshiwl** [comment]
understood. thanks a lot for clarifying.

**Comment by mrticker** [comment]
I think _model_max_length_ should be set to model's max length, as in the model's config.json, if it set there. If it's not set there, then the default value of 1024/2048/4096/whatever should be set.

Better yet, _model_max_length_ should be set to _block_size_ provided by the user, if any. For example, if I set _block_size_ to 4096, it should override the default _model_max_length_ of 1024.

If there is no further discussion I will close this issue.
