### ISSUE TITLE
[BUG] Where does autotrain save the trained models?

### ISSUE THREAD

**Issue by mrticker** [huggingface/autotrain-advanced#472]
### Prerequisites

- [X] I have read the [documentation](https://hf.co/docs/autotrain).
- [X] I have checked other issues for similar problems.

### Backend

Other cloud providers

### Interface Used

CLI

### Error Logs

```
INFO   | 2024-01-23 15:59:51 | __main__:train:477 - Finished training, saving model...
{'loss': 1.3648, 'learning_rate': 0.0, 'epoch': 1.0}
{'train_runtime': 29.9506, 'train_samples_per_second': 0.267, 'train_steps_per_second': 0.033, 'train_loss': 1.3648121356964111, 'epoch': 1.0}
```

### Additional Information

So I trained a LoRA adapter. I don't see it anywhere. Where does it get saved locally? Does it even get saved locally?

**Comment by abhishekkrthakur** [comment]
in the project folder

**Comment by zygmuntz** [comment]
> in the project folder

And where is the project folder?

**Comment by abhishekkrthakur** [comment]
autotrain llm --train --project PROJECT-NAME

so wherever you run this command, project folder will be created :)
