### ISSUE TITLE
[Feature Request] Add token classification task

### ISSUE THREAD

**Issue by jyotiyadav94** [huggingface/autotrain-advanced#483]
### Prerequisites

- [X] I have read the [documentation](https://hf.co/docs/autotrain).
- [X] I have checked other issues for similar problems.

### Backend

Local

### Interface Used

CLI

### UI Screenshots & Parameters

<img width="701" alt="Screenshot 2024-01-16 at 15 12 14" src="https://github.com/huggingface/autotrain-advanced/assets/72126242/cfeb3854-237e-47c2-ae85-9be5cd4d3eb2">

### Error Logs

I have recently noticed that the option for the Token Classification AutoML model is no longer available on the platform. I wanted to inquire about the status of this model and whether there are any plans to make it available again in the future.

**Comment by abhishekkrthakur** [comment]
#493

**Comment by abhishekkrthakur** [comment]
Token classification is now available: https://huggingface.co/docs/autotrain/token_classification
