### ISSUE TITLE
[BUG] Issue with setting up training on HF and Colab

### ISSUE THREAD

**Issue by vanjy-eng** [huggingface/autotrain-advanced#491]
### Prerequisites

- [X] I have read the [documentation](https://hf.co/docs/autotrain).
- [X] I have checked other issues for similar problems.

### Backend

Colab

### Interface Used

UI

### UI Screenshots & Parameters

![Screenshot 2024-02-06 at 22 15 22](https://github.com/huggingface/autotrain-advanced/assets/93622962/5f51a18e-4838-4af3-aee9-e145bf2c4960)
![Screenshot 2024-02-06 at 22 15 43](https://github.com/huggingface/autotrain-advanced/assets/93622962/e4ab45d0-6869-4426-b986-54eec7d90642)

### Error Logs

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
lida 0.0.10 requires kaleido, which is not installed.
llmx 0.0.15a0 requires cohere, which is not installed.
llmx 0.0.15a0 requires openai, which is not installed.
tensorflow-metadata 1.14.0 requires protobuf<4.21,>=3.20.3, but you have protobuf 4.23.4 which is incompatible.
tensorflow-probability 0.22.0 requires typing-extensions<4.6.0, but you have typing-extensions 4.9.0 which is incompatible.
> INFO    Authenticating user...
Traceback (most recent call last):
  File "/usr/local/bin/autotrain", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/autotrain/cli/autotrain.py", line 48, in main
    command.run()
  File "/usr/local/lib/python3.10/dist-packages/autotrain/cli/run_app.py", line 51, in run
    from autotrain.app import app
  File "/usr/local/lib/python3.10/dist-packages/autotrain/app.py", line 28, in <module>
    _, _, USERS = app_utils.user_validation()
  File "/usr/local/lib/python3.10/dist-packages/autotrain/app_utils.py", line 118, in user_validation
    user_token, valid_can_pay, who_is_training = _login_user(user_token)
  File "/usr/local/lib/python3.10/dist-packages/autotrain/app_utils.py", line 98, in _login_user
    username = user_info["name"]
KeyError: 'name'

**Comment by abhishekkrthakur** [comment]
you can ignore the pip error. it doesnt cause any issue. the second error is because you are probably trying to use a paid hardware and you dont have a payment method attached to your account. if you are not using a paid hardware, please let me know so i can investigate more.

**Comment by vanjy-eng** [comment]
Even though I am not trying to use paid hardware, I also have billing enabled and corresponding payment methods that I use for my other HF bills.

**Comment by vanjy-eng** [comment]
Ok. The token is an Organization token which HF states: _Unlike [user access tokens](https://huggingface.co/settings/tokens), an Organization API token can only be used to provide read access to repos, or for billing access to a compute resource._
Switching to user token with write.

**Comment by abhishekkrthakur** [comment]
unfortunately, org tokens dont work. however, you can select org username/account after using the user token of a user belonging to that org.

**Comment by vanjy-eng** [comment]
Works like a charm. Thanks.
