### ISSUE TITLE
Getting an error when training non sdxl base models with dreambooth

### ISSUE THREAD

**Issue by jandzouana** [huggingface/autotrain-advanced#496]
I get this error when I try to train with models that are not the base SDXL model like the SDD-1B Model. This is the error I get:
```
if "text_embeds" not in added_cond_kwargs:
TypeError: argument of type 'NoneType' is not iterable
```

I'm using google colab to run AutoTrain. Anyone know why this is happening?

**Comment by Dadpoole** [comment]
Ive had same issue. I tried some other non-SDXL 1.0, such as PONY XL, and get same error. I assume it is in the parameters, but haven't been able to figure it out.
