### ISSUE TITLE
[BUG] IsADirectoryError: [Errno 21] Is a directory: 'images/.ipynb_checkpoints'

### ISSUE THREAD

**Issue by simonushie** [huggingface/autotrain-advanced#502]
### Prerequisites

- [X] I have read the [documentation](https://hf.co/docs/autotrain).
- [X] I have checked other issues for similar problems.

### Backend

Colab

### Interface Used

UI

### Error Logs

> INFO    Namespace(version=False, revision=None, tokenizer=None, image_path='images/', class_image_path=None, prompt='photo of VM', class_prompt=None, num_class_images=100, class_labels_conditioning=None, prior_preservation=None, prior_loss_weight=1.0, resolution=1024, center_crop=None, train_text_encoder=None, sample_batch_size=4, num_steps=500, checkpointing_steps=100000, resume_from_checkpoint=None, scale_lr=None, scheduler='constant', warmup_steps=0, num_cycles=1, lr_power=1.0, dataloader_num_workers=0, use_8bit_adam=None, adam_beta1=0.9, adam_beta2=0.999, adam_weight_decay=0.01, adam_epsilon=1e-08, max_grad_norm=1.0, allow_tf32=None, prior_generation_precision=None, local_rank=-1, xformers=None, pre_compute_text_embeddings=None, tokenizer_max_length=None, text_encoder_use_attention_mask=None, rank=4, xl=None, fp16=True, bf16=None, validation_prompt=None, num_validation_images=4, validation_epochs=50, checkpoints_total_limit=None, validation_images=None, logging=None, train=None, deploy=None, inference=None, username=None, backend='local-cli', token=None, repo_id=None, push_to_hub=None, model='stabilityai/stable-diffusion-xl-base-1.0', project_name='linkedin_pfp_project', seed=42, epochs=1, gradient_accumulation=4, disable_gradient_checkpointing=None, lr=0.0001, log='none', data_path=None, train_split='train', valid_split=None, batch_size=30, func=<function run_dreambooth_command_factory at 0x79cd083fed40>)
> INFO    Running DreamBooth Training
> WARNING Parameters supplied but not used: inference, train_split, log, version, backend, data_path, valid_split, train, func, deploy
> INFO    Dataset: linkedin_pfp_project (dreambooth)

> INFO    Saving concept images
> INFO    images/IMG_20240120_175659.jpg
> INFO    Saving concept images
> INFO    images/IMG_20240120_170036.jpg
> INFO    Saving concept images
> INFO    images/IMG_20240120_180028.jpg
> INFO    Saving concept images
> INFO    images/.ipynb_checkpoints
Traceback (most recent call last):
  File "/usr/local/bin/autotrain", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/autotrain/cli/autotrain.py", line 50, in main
    command.run()
  File "/usr/local/lib/python3.10/dist-packages/autotrain/cli/run_dreambooth.py", line 400, in run
    params = dreambooth_munge_data(params, local=self.args.backend.startswith("local"))
  File "/usr/local/lib/python3.10/dist-packages/autotrain/cli/utils.py", line 318, in dreambooth_munge_data
    params.image_path = dset.prepare()
  File "/usr/local/lib/python3.10/dist-packages/autotrain/dataset.py", line 81, in prepare
    return preprocessor.prepare()
  File "/usr/local/lib/python3.10/dist-packages/autotrain/preprocessor/dreambooth.py", line 93, in prepare
    self._save_concept_images(_file)
  File "/usr/local/lib/python3.10/dist-packages/autotrain/preprocessor/dreambooth.py", line 75, in _save_concept_images
    with open(_file, "rb") as f:
IsADirectoryError: [Errno 21] Is a directory: 'images/.ipynb_checkpoints'

**Comment by simonushie** [comment]
i see a `ipynb_checkpoints.ipynb` file autogenerated in the directory that can't be deleted

**Comment by abhishekkrthakur** [comment]
you need to recreate the images/ folder. if you see closed issues, you'll find this being discussed. its not a software issue, the folder gets created by colab when you have images created immediately after creating the space. you can just right click on the folder and delete it (after making hidden files visible)

**Comment by simonushie** [comment]
> you need to recreate the images/ folder. if you see closed issues, you'll find this being discussed. its not a software issue, the folder gets created by colab when you have images created immediately after creating the space. you can just right click on the folder and delete it (after making hidden files visible)

correct, i just realized that now myself, i deleted the folder and reuploaded the images, bug went away
![image](https://github.com/huggingface/autotrain-advanced/assets/43451941/dadd214c-9f5f-4d60-8eea-1d9100c965cb)

thanks @abhishekkrthakur
