### ISSUE TITLE
[BUG] Flash attention depreciated

### ISSUE THREAD

**Issue by jackshiwl** [huggingface/autotrain-advanced#505]
### Prerequisites

- [X] I have read the [documentation](https://hf.co/docs/autotrain).
- [X] I have checked other issues for similar problems.

### Backend

Local

### Interface Used

CLI

### CLI Command

When I use flash attention via 
```
--use_flash_attention_2 \
```

It gives this warning:
```
The model was loaded with use_flash_attention_2=True, which is deprecated and may be removed in a future release. Please use `attn_implementation="flash_attention_2"` instead.
```

Any idea how to work around this? Is this a concern? Or can I still proceed normally with this? Thanks

### Error Logs

-

**Comment by abhishekkrthakur** [comment]
its just a deprecation warning. and doesnt mean it doesnt work :) it will be fixed in one of the future releases
