### ISSUE TITLE
[BUG] Unable to access training_params.json file

### ISSUE THREAD

**Issue by ahsan-masood** [huggingface/autotrain-advanced#507]
### Prerequisites

- [X] I have read the [documentation](https://hf.co/docs/autotrain).
- [X] I have checked other issues for similar problems.

### Backend

Local

### Interface Used

CLI

### CLI Command

```
autotrain dreambooth 
--project-name project01 \
--model stabilityai/sdxl-turbo \
--image-path tempf/frames/ \
--prompt "person" \
--resolution 1024 \
--batch-size 1 \
--num-steps 500 \
--fp16 \
--gradient-accumulation 4 \
--lr 1e-4 \
--xformers \
--train-text-encoder
```

### Error Logs

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\ahsan\miniconda3\Lib\site-packages\autotrain\trainers\dreambooth\__main__.py", line 338, in <module>
    training_config = json.load(open(args.training_config))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'project01training_params.json'
```

### Additional Information

With recent update autotrain is forcing to use only alphanumeric `project_name` with an exception to hyphen (-), however it is unable to access `training_params.json` file. I think it's a bug since there should be a backslash after the project_name, as the error is showing, it's missing. 

Guide me if I'm wrong and missing something.

**Comment by abhishekkrthakur** [comment]
it should be fixed now. apologies for the inconvenience.

**Comment by ahsan-masood** [comment]
> it should be fixed now. apologies for the inconvenience.

thanks for the quick fix
