### ISSUE TITLE
[BUG] Could not find a config file - will assume vocab was not modified

### ISSUE THREAD

**Issue by jackshiwl** [huggingface/autotrain-advanced#508]
### Prerequisites

- [X] I have read the [documentation](https://hf.co/docs/autotrain).
- [X] I have checked other issues for similar problems.

### Backend

Local

### Interface Used

CLI

### Error Logs
Cannot seem to find the file. On version 0.6.87

```
/app/env/lib/python3.10/site-packages/peft/utils/save_and_load.py:148: UserWarning: Could not find a config file in /scratch/users/xxx/xxx/deepseek-coder-6.7b-instruct - will assume that the vocabulary was not modified.
  warnings.warn(
```

**Comment by jackshiwl** [comment]
@abhishekkrthakur  could you kindly let me know if this warning is ok to ignore? Happening in version 0.6.87

**Comment by abhishekkrthakur** [comment]
it seems like this is a adapter only model?

**Comment by jackshiwl** [comment]
<img width="1108" alt="image" src="https://github.com/huggingface/autotrain-advanced/assets/87535974/023a3598-0195-4399-b869-c7b4f78ffa7e">

**Comment by ChunchunWang5** [comment]
i found the same bug:
UserWarning: Could not find a config file in ./cognitivecomputations/dolphin-2.1-mistral-7b - will assume that the vocabulary was not modified.
warnings.warn(

**Comment by waleyW** [comment]
> i found the same bug: UserWarning: Could not find a config file in ./cognitivecomputations/dolphin-2.1-mistral-7b - will assume that the vocabulary was not modified. warnings.warn(

Excause me, have you solved this problem?

**Comment by ChunchunWang5** [comment]
> > i found the same bug: UserWarning: Could not find a config file in ./cognitivecomputations/dolphin-2.1-mistral-7b - will assume that the vocabulary was not modified. warnings.warn(
> 
> Excause me, have you solved this problem?

No. However, I found that this bug can be ignored. I encountered this bug during the process of qlora fine-tuning, but after the training was completed, I obtained the complete fine-tuned model and evaluation results.

**Comment by abhishekkrthakur** [comment]
y'all really need to read the pinned issue.

**Comment by jackshiwl** [comment]
There is no info on this in the pinned issue? This is a totally different issue. @abhishekkrthakur

**Comment by abhishekkrthakur** [comment]
if you are using a 3rd party mistral model, its better to ask the author about the warning.

**Comment by waleyW** [comment]
> > > i found the same bug: UserWarning: Could not find a config file in ./cognitivecomputations/dolphin-2.1-mistral-7b - will assume that the vocabulary was not modified. warnings.warn(
> > 
> > 
> > Excause me, have you solved this problem?
> 
> No. However, I found that this bug can be ignored. I encountered this bug during the process of qlora fine-tuning, but after the training was completed, I obtained the complete fine-tuned model and evaluation results.

If I fine-tune the LLaMA-13B model, the warning can be ignored, and I can obtain the completely fine-tuned model. However, when I fine-tune the CodeLLaMA-34B model and after merging the weights, attempting to infer from the model results in a 'tensor mismatch' error.

**Comment by SizheWei** [comment]
> > > > i found the same bug: UserWarning: Could not find a config file in ./cognitivecomputations/dolphin-2.1-mistral-7b - will assume that the vocabulary was not modified. warnings.warn(
> > > 
> > > 
> > > Excause me, have you solved this problem?
> > 
> > 
> > No. However, I found that this bug can be ignored. I encountered this bug during the process of qlora fine-tuning, but after the training was completed, I obtained the complete fine-tuned model and evaluation results.
> 
> If I fine-tune the LLaMA-13B model, the warning can be ignored, and I can obtain the completely fine-tuned model. However, when I fine-tune the CodeLLaMA-34B model and after merging the weights, attempting to infer from the model results in a 'tensor mismatch' error.

I met the same error while I was fine-tuning LLaVA-v1.5(Vicuna-v1.5-7B + ViT-L@336px). I tried to save checkpoints each 50 steps, but I met this warning at each saving time.

**Comment by abhishekkrthakur** [comment]
llava isnt supported. missing config.json is not an issue anymore.
