### ISSUE TITLE
[BUG] Fine-tuning seems to be always stopping at 73%?

### ISSUE THREAD

**Issue by jackshiwl** [huggingface/autotrain-advanced#509]
### Prerequisites

- [X] I have read the [documentation](https://hf.co/docs/autotrain).
- [X] I have checked other issues for similar problems.

### Backend

Local

### Interface Used

CLI

### CLI Command

While fine-tuning, the model training seems to stop at 73% and proceed to merge/save model

### Error Logs

<img width="632" alt="image" src="https://github.com/huggingface/autotrain-advanced/assets/87535974/1a0b29b5-8880-4c91-97a4-45d7701eb27f">

**Comment by abhishekkrthakur** [comment]
its a TRL bug. progress bar is not representative. it will eventually be fixed after a couple more issues are fixed. training finished successfully, dont worry.

**Comment by abhishekkrthakur** [comment]
fixed in latest release

**Comment by jackshiwl** [comment]
hi, thanks for fixing. Just checking, this is fixed in 0.6.92 is it?
