### ISSUE TITLE
[BUG] ValueError - "project_name must be alphanumeric" when running through HuggingFace

### ISSUE THREAD

**Issue by thinkingkoala** [huggingface/autotrain-advanced#511]
### Prerequisites

- [X] I have read the [documentation](https://hf.co/docs/autotrain).
- [X] I have checked other issues for similar problems.

### Backend

Hugging Face Space/Endpoints

### Interface Used

UI

### UI Screenshots & Parameters

![image](https://github.com/huggingface/autotrain-advanced/assets/139218006/a178f575-c659-4000-bd86-7e3a5a520fe7)

Get this error constantly no matter how I modify the project name. Worked well the day before.
Running through UI on https://huggingface.co/spaces/multimodalart/lora-ease

### Error Logs

> INFO    {'username': '***', 'project_name': 'faceofnadia', 'data_path': '***/autotrain-faceofnadia', 'token': 'hf_**********************************', 'script_path': '23b6a7d2-1cfc-4f7b-b01f-5536e7c46c76', ...}}
> INFO    ['python', '-m', 'autotrain.trainers.generic', '--config', '/tmp/model/training_params.json']
> INFO    Started training with PID 41
> INFO    Running jobs: [41]
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:7860 (Press CTRL+C to quit)
Traceback (most recent call last):
  File "/app/env/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/app/env/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/app/src/autotrain/trainers/generic/__main__.py", line 43, in <module>
    _config = GenericParams(**_config)
  File "/app/src/autotrain/trainers/common.py", line 133, in __init__
    raise ValueError("project_name must be alphanumeric but can contain hyphens")
ValueError: project_name must be alphanumeric but can contain hyphens

**Comment by thinkingkoala** [comment]
@abhishekkrthakur I think the issue is that project_name is overwritten inside the app_utils.py:

`    if not local:
        params.project_name = "/tmp/model"`

Could you please take a look?

**Comment by abhishekkrthakur** [comment]
thats not the issue. lora ease space needs an update. im checking in with maintainers :)

**Comment by abhishekkrthakur** [comment]
yes, it was an autotrain issue. apologies. issue has now been resolved.

**Comment by jackshiwl** [comment]
hi, 0.6.94 still throws up this error.

**Comment by abhishekkrthakur** [comment]
this issue has been resolved. general users never had this problem. its only a problem with generic task.
