### ISSUE TITLE
[BUG]RuntimeError: No GPU found. A GPU is needed for quantization. 

### ISSUE THREAD

**Issue by zeeshan5k** [huggingface/autotrain-advanced#516]
### Prerequisites

- [X] I have read the [documentation](https://hf.co/docs/autotrain).
- [X] I have checked other issues for similar problems.

### Backend

Local

### Interface Used

CLI

### CLI Command

autotrain llm --train --project-name llm101 --model abhishek/llama-2-7b-hf-small-shards --data-path . --use-peft --quantization int4 --lr 2e-4 --train-batch-size 12 --epochs 3 --trainer sft

### Error Logs

INFO | 2024-02-17 14:57:25 | __main__.process_input_data:83 - Valid data: None
ERROR | 2024-02-17 14:57:26 | autotrain.trainers.common.wrapper:91 - train has failed due to an exception: Traceback (most recent call last):
File "C:\Users\zau3\AppData\Roaming\Python\Python311\site-packages\autotrain\trainers\common.py", line 88, in wrapper
    return func(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\zau3\AppData\Roaming\Python\Python311\site-packages\autotrain\trainers\clm\__main__.py", line 186, in train
    model = AutoModelForCausalLM.from_pretrained(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\zau3\AppData\Roaming\Python\Python311\site-packages\transformers\models\auto\auto_factory.py", line 566, in from_pretrained
    return model_class.from_pretrained(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\zau3\AppData\Roaming\Python\Python311\site-packages\transformers\modeling_utils.py", line 3032, in from_pretrained
    raise RuntimeError("No GPU found. A GPU is needed for quantization.")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: No GPU found. A GPU is needed for quantization.

ERROR | 2024-02-17 14:57:26 | autotrain.trainers.common.wrapper:92 - No GPU found. A GPU is needed for quantization.

### Additional Information

i am using autotrain locally without gpu with shards of 7b model

**Comment by abhishekkrthakur** [comment]
As the error states, you cannot use quantization without gpu. removing quantization arg should fix the issue

**Comment by zeeshan5k** [comment]
Thanks
