### ISSUE TITLE
[FEATURE REQUEST] Support for Qwen1.5-0.5 fine tuning

### ISSUE THREAD

**Issue by allandclive** [huggingface/autotrain-advanced#519]
### Feature Request

Add support to fine tune Qwen1.5 models.

https://huggingface.co/collections/Qwen/qwen15-65c0a2f577b1ecb76d786524

### Motivation

 Qwen has also a collection of good performing small models

**Comment by abhishekkrthakur** [comment]
do you get an error when training: https://huggingface.co/Qwen/Qwen1.5-7B-Chat ?

**Comment by allandclive** [comment]
I want to fine tune 0.5B model. I am interested in Qwen1.5 small models

**Comment by abhishekkrthakur** [comment]
are you getting an error?

**Comment by allandclive** [comment]
Under Base Model, I only see Qwen-14B

**Comment by abhishekkrthakur** [comment]
you can pass environment variable `AUTOTRAIN_CUSTOM_MODELS=Qwen/some_other_model` to use it.

**Comment by allandclive** [comment]
I was using the UI, am new to using AutoTrain. How do I set that?

**Comment by abhishekkrthakur** [comment]
click on settings on autotrain space, then new variable:
<img width="1129" alt="image" src="https://github.com/huggingface/autotrain-advanced/assets/1183441/b67665b5-4ba9-4eea-aba5-a68126163ef2">

**Comment by allandclive** [comment]
thanks. solved
