### ISSUE TITLE
[BUG] version 0.6.93 will spam: huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks... 

### ISSUE THREAD

**Issue by jackshiwl** [huggingface/autotrain-advanced#522]
### Prerequisites

- [X] I have read the [documentation](https://hf.co/docs/autotrain).
- [X] I have checked other issues for similar problems.

### Backend

Local

### Interface Used

CLI

### CLI Command

With version 0.6.93, it will spam the parallelism warning

### Error Logs

<img width="1383" alt="image" src="https://github.com/huggingface/autotrain-advanced/assets/87535974/0cac297b-1a75-4f59-aba0-189ef1d23572">

**Comment by abhishekkrthakur** [comment]
Feel free to ignore warnings if they are not causing any immediate issues.

**Comment by abhishekkrthakur** [comment]
or do as warning says ;)

`export TOKENIZERS_PARALLELISM=false`
