### ISSUE TITLE
[BUG] Using `bitsandbytes` 8-bit quantization requires Accelerate: `pip install accelerate` and the latest version of bitsandbytes

### ISSUE THREAD

**Issue by matthewfarant** [huggingface/autotrain-advanced#528]
### Prerequisites

- [X] I have read the [documentation](https://hf.co/docs/autotrain).
- [X] I have checked other issues for similar problems.

### Backend

Local

### Interface Used

UI

### Error Logs

ImportError: Using `bitsandbytes` 8-bit quantization requires Accelerate: `pip install accelerate` and the latest version of bitsandbytes: `pip install -i https://pypi.org/simple/ bitsandbytes`

❌ ERROR  | 2024-02-26 10:11:57 | autotrain.trainers.common:wrapper:92 - Using `bitsandbytes` 8-bit quantization requires Accelerate: `pip install accelerate` and the latest version of bitsandbytes: `pip install -i https://pypi.org/simple/ bitsandbytes`
🚀 INFO   | 2024-02-26 10:11:57 | autotrain.trainers.common:pause_space:49 - Pausing space...

**Comment by abhishekkrthakur** [comment]
please paste params used and model

**Comment by matthewfarant** [comment]
Hi @abhishekkrthakur , these are the details:

Task = LLM SFT
Model = mistralai/Mixtral-8x7B-Instruct-v0.1


```
{
  "block_size": 1024,
  "model_max_length": 2048,
  "padding": "right",
  "use_flash_attention_2": false,
  "disable_gradient_checkpointing": false,
  "logging_steps": -1,
  "evaluation_strategy": "epoch",
  "save_total_limit": 1,
  "save_strategy": "epoch",
  "auto_find_batch_size": false,
  "mixed_precision": "fp16",
  "lr": 0.00003,
  "epochs": 3,
  "batch_size": 2,
  "warmup_ratio": 0.1,
  "gradient_accumulation": 1,
  "optimizer": "adamw_torch",
  "scheduler": "linear",
  "weight_decay": 0,
  "max_grad_norm": 1,
  "seed": 42,
  "chat_template": "none",
  "quantization": "int4",
  "target_modules": "all-linear",
  "merge_adapter": false,
  "peft": true,
  "lora_r": 16,
  "lora_alpha": 32,
  "lora_dropout": 0.05
}
```

**Comment by abhishekkrthakur** [comment]
are you running it on windows? could you please tell me how you installed autotrain?

**Comment by matthewfarant** [comment]
I'm running it on Autotrain UI in **HuggingFace spaces** @abhishekkrthakur

**Comment by flameface** [comment]
same error, it's running on Autotrain UI, i removed `"mixed_precision": "fp16"` as the space running on CPU

**Comment by abhishekkrthakur** [comment]
you should not remove any params. if you dont want mixed precision, set it to none:

`mixed_precision: "none"`

**Comment by flameface** [comment]
![image](https://github.com/huggingface/autotrain-advanced/assets/84311327/69535db1-4d3d-499c-9258-bff83bcbee85)

Still same error

**Comment by flameface** [comment]
hello?

**Comment by abhishekkrthakur** [comment]
have you tried after that? some packages were updated this week. please factory rebuild your autotrain space before trying it.

**Comment by dragonAZH** [comment]
> have you tried after that? some packages were updated this week. please factory rebuild your autotrain space before trying it.

Still getting the error as of current.

**Comment by flameface** [comment]
![image](https://github.com/huggingface/autotrain-advanced/assets/84311327/66fca8bc-b5a4-4c90-a743-3d1512513428)

Still same.

**Comment by flameface** [comment]
I'm using google/gemma-7b, will you try it.

Training Data: (data.csv)
```
text
"human: hello \n bot: id-chat hi nice to meet you"
"human: how are you \n bot: id-chat I am fine"
"human: generate an image of a cat \n bot: id-image a cute furry cat"
```

Column mapping:-
```
{"text": "text", "target": "target"}
```

**Comment by sivakmar** [comment]
I get this same issue how to fix it?
OR  | 2024-03-04 11:17:08 | autotrain.trainers.common:wrapper:91 - train has failed due to an exception: Traceback (most recent call last):
  File "/app/env/lib/python3.10/site-packages/autotrain/trainers/common.py", line 88, in wrapper
    return func(*args, **kwargs)
  File "/app/env/lib/python3.10/site-packages/autotrain/trainers/clm/__main__.py", line 230, in train
    model = AutoModelForCausalLM.from_pretrained(
  File "/app/env/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 561, in from_pretrained
    return model_class.from_pretrained(
  File "/app/env/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3024, in from_pretrained
    hf_*********.validate_environment(
  File "/app/env/lib/python3.10/site-packages/transformers/quantizers/quantizer_bnb_4bit.py", line 62, in validate_environment
    raise ImportError(
ImportError: Using `bitsandbytes` 8-bit quantization requires Accelerate: `pip install accelerate` and the latest version of bitsandbytes: `pip install -i https://pypi.org/simple/ bitsandbytes`

❌ ERROR  | 2024-03-04 11:17:08 | autotrain.trainers.common:wrapper:92 - Using `bitsandbytes` 8-bit quantization requires Accelerate: `pip install accelerate` and the latest version of bitsandbytes: `pip install -i https://pypi.org/simple/ bitsandbytes`
🚀 INFO   | 2024-03-04 11:17:08 | autotrain.trainers.common:pause_space:49 - Pausing space...

**Comment by SyntaxPratyush** [comment]
@abhishekkrthakur I am receiving the same error when running it on google colab: 
![image](https://github.com/huggingface/autotrain-advanced/assets/157193581/b21c0412-532e-4ad1-bd59-912bb29baa41)

**Comment by SrushtiAckno** [comment]
@SyntaxPratyush Same here, @abhishekkrthakur can you please look into the same..

**Comment by lkk117766** [comment]
I also encountered the same issue

**Comment by lkk117766** [comment]
Someone says we need to downgrade transformers library to version 4.30, on order to fix this error

However, GemmerTokenizer need to upgrade transformers to version 4.38 ... !!

**Comment by abhishekkrthakur** [comment]
taking a look again.

**Comment by abhishekkrthakur** [comment]
I spun up a new autotrain space, added a10g gpu and i am able to train mistralai/Mistral-7B-v0.1 successfully. 
do you have this issue with a specific gpu or a specific model?


<img width="1039" alt="image" src="https://github.com/huggingface/autotrain-advanced/assets/1183441/947ca181-26a2-4ddf-9553-19235f237240">

**Comment by SyntaxPratyush** [comment]
@abhishekkrthakur Could you please show me a detailed tutorial on how to do it on autotrain-advanced as there are no proper explanations on how to do it, I am having specific issues on finding the proper format for train.csv & the column mapping as write know I am getting Error-500: Check Logs for more Info, and the logs are empty

**Comment by abhishekkrthakur** [comment]
@SyntaxPratyush here is a train.csv for llm task that you can try with: https://github.com/huggingface/autotrain-example-datasets/blob/main/alpaca1k.csv

**Comment by SyntaxPratyush** [comment]
@abhishekkrthakur column mapping pls

**Comment by abhishekkrthakur** [comment]
you dont need to change anything in column mapping if you use that file. also, lets not hijack this thread as its a completely different issue. you can post your queries in huggingface forums and i can help there.

**Comment by SyntaxPratyush** [comment]
ok thanks

**Comment by SyntaxPratyush** [comment]
![image](https://github.com/huggingface/autotrain-advanced/assets/157193581/27443dbf-05b8-4b9f-85a7-ff0cc3d4906f)
while running
![image](https://github.com/huggingface/autotrain-advanced/assets/157193581/65c03bcb-0414-4c45-b2ca-8f1f9a0d8840)

**Comment by abhishekkrthakur** [comment]
which gpu did you use?

**Comment by abhishekkrthakur** [comment]
you cannot use peft and quantization on cpu. please select appropriate gpu. e.g. A10g

**Comment by SyntaxPratyush** [comment]
i cant pay for it, I'm an 8th grade student doing a hackathon

**Comment by abhishekkrthakur** [comment]
im closing this issue as its deviating a lot from the title and the originally reported issue doesnt exist. the error appears because users are trying to train gpu models on a cpu machine.
