### ISSUE TITLE
[FEATURE REQUEST] classification tasks confusion matrix

### ISSUE THREAD

**Issue by flozi00** [huggingface/autotrain-advanced#534]
### Feature Request

Confusion matrix for the model cards when training classification tasks

### Motivation

Some more insights about the model performance 
Especially for ranked tasks like the DIBT project which could be converted to regression tasks too.

**Comment by flozi00** [comment]
Inspired by this article: https://lajavaness.medium.com/regression-with-text-input-using-bert-and-transformers-71c155034b13

**Comment by abhishekkrthakur** [comment]
can be done
