### ISSUE TITLE
[BUG] "GET /is_model_training HTTP/1.1" 200 OK stuck 

### ISSUE THREAD

**Issue by haskovic99** [huggingface/autotrain-advanced#546]
### Prerequisites

- [X] I have read the [documentation](https://hf.co/docs/autotrain).
- [X] I have checked other issues for similar problems.

### Backend

Colab

### Interface Used

UI

### Error Logs

 GET /is_model_training HTTP/1.1" 200 OK

### Additional Information

Stuck for hours at those messages pop up again and again. It this normal or its problem?

**Comment by abhishekkrthakur** [comment]
is_model_training will continuously check  if a model is training. its not an issue. does your training fail? do you have any other errors/issues in the logs?

**Comment by leovfxuk** [comment]
How long should this loop run for? I'm getting the same thing for hours. There's no percentage read out. Last night I had to leave it running for so long that I went to bed and came back and colab session had ended. Don't know if the loop ever finished or not.

**Comment by abhishekkrthakur** [comment]
is_model_training is polled continuously. if your model is trained, you find it on hf hub or locally. the logs/errors are also displayed in the same output where you see is_model_training

**Comment by leovfxuk** [comment]
OK Thanks. So is it the case that if I have a file: pytorch_lora_weights.safetensors then the training is finished and I can end the runtime?

**Comment by abhishekkrthakur** [comment]
yes!

**Comment by abhishekkrthakur** [comment]
does the UI say model is training?

**Comment by leovfxuk** [comment]
yes

**Comment by leovfxuk** [comment]
I should wait until this finishes?

Am i just being impatient?

**Comment by abhishekkrthakur** [comment]
<img width="611" alt="image" src="https://github.com/huggingface/autotrain-advanced/assets/1183441/8f7162ac-a7ab-4f57-b8fa-6ab0bf8cc08c">
i meant in the ui. what does it say here?

**Comment by leovfxuk** [comment]
OK. That says "no running jobs"

**Comment by abhishekkrthakur** [comment]
then its done
