### ISSUE TITLE
[BUG] AttributeError: 'Args' object has no attribute 'checkpoints_total_limit'

### ISSUE THREAD

**Issue by sbarbat** [huggingface/autotrain-advanced#549]
### Prerequisites

- [X] I have read the [documentation](https://hf.co/docs/autotrain).
- [X] I have checked other issues for similar problems.

### Backend

Colab

### Interface Used

UI

### CLI Command

Dreambooth training from the UI. Even setting up `checkpoints_total_limit` in the config doesnt fix the issue

### Error Logs

Steps: 100% 1/1 [00:04<00:00,  4.97s/it, loss=0.455, lr=0.0001]❌ ERROR  | 2024-03-11 15:47:27 | autotrain.trainers.common:wrapper:91 - train has failed due to an exception: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/common.py", line 88, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/dreambooth/__main__.py", line 186, in train
    main(_args)
  File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/dreambooth/train.py", line 907, in main
    if args.checkpoints_total_limit is not None:
AttributeError: 'Args' object has no attribute 'checkpoints_total_limit'

**Comment by abhishekkrthakur** [comment]
which model?

**Comment by shaase** [comment]
Hi, I'm also seeing this error, using `stability/stable-diffusion-xl-base-1.0`

**Comment by abhishekkrthakur** [comment]
fixed. please update to 0.7.13 or later
