### ISSUE TITLE
[BUG]{'image_encoder', 'feature_extractor'} was not found in config. Values will be initialized to default values. Dreambooth LORA

### ISSUE THREAD

**Issue by leonhart8t3** [huggingface/autotrain-advanced#557]
### Prerequisites

- [X] I have read the [documentation](https://hf.co/docs/autotrain).
- [X] I have checked other issues for similar problems.

### Backend

Local

### Interface Used

CLI

### CLI Command

Fetching 17 files: 100% 17/17 [00:03<00:00,  5.44it/s]
{'image_encoder', 'feature_extractor'} was not found in config. Values will be initialized to default values.

Loading pipeline components...:   0% 0/7 [00:00<?, ?it/s]{'attention_type', 'reverse_transformer_layers_per_block', 'dropout'} was not found in config. Values will be initialized to default values.

### Error Logs

Fetching 17 files: 100% 17/17 [00:03<00:00,  5.44it/s]
{'image_encoder', 'feature_extractor'} was not found in config. Values will be initialized to default values.

Loading pipeline components...:   0% 0/7 [00:00<?, ?it/s]{'attention_type', 'reverse_transformer_layers_per_block', 'dropout'} was not found in config. Values will be initialized to default values.

### Additional Information

Default all values except: dreambooth LORA SDXL 1.0 to complete and data

**Comment by abhishekkrthakur** [comment]
does it cause results to be bad?

**Comment by leonhart8t3** [comment]
Sorry I should have been more specific. It gets stuck there and doesn't progress for me. I have had success reverting back to version 1.7.5 & 1.7.2 installs.

**Comment by dotnetautor** [comment]
With the current version, I observed the same issue for ‘autotrain.trainers.dreambooth’ with "model":"stabilityai/stable-diffusion-xl-base-1.0". 

The weights are calculated. Subsequently, the following messages where displayed:

```
Steps: 100% 500/500 [56:02<00:00,  7.01s/it, loss=0.0476, lr=0.0003]
{'latents_std', 'latents_mean', 'force_upcast'} was not found in config. Values will be initialized to default values.
…
{'feature_extractor', 'image_encoder'} was not found in config. Values will be initialized to default values.
…
{'dropout', 'reverse_transformer_layers_per_block', 'attention_type'} was not found in config. Values will be initialized to default values.
```

The SDXL LoRA from the current version does not work at all. Reverting back to version 0.7.1 resolved the issue used with the same dataset and the same parameters. 

Please note that the messages above where not observed with version 0.7.1.

**Comment by abhishekkrthakur** [comment]
dreambooth seems to be working fine. please update to 0.7.36 or later

**Comment by dotnetautor** [comment]
I can partially confirm that. It seems that all versions work fine, but the most recent ones no longer work on computers with low RAM (<= 12GB). In contrast, version 0.7.1 continues to function on 'smaller' computers. With the current version(s), the conversion to the `pytorch_lora_weights_kohya.safetensors` file appears to be aborted due to a lack of memory, and the created file `pytorch_lora_weights.safetensors` seems not to be usable without this conversion.

**Comment by abhishekkrthakur** [comment]
ohh okay. so conversion is the only issue for low ram machines?

**Comment by dotnetautor** [comment]
From my perspective, it looks like this could it be.

**Comment by abhishekkrthakur** [comment]
you can ignore:

{'latents_std', 'latents_mean', 'force_upcast'} was not found in config. Values will be initialized to default values.
…
{'feature_extractor', 'image_encoder'} was not found in config. Values will be initialized to default values.
…
{'dropout', 'reverse_transformer_layers_per_block', 'attention_type'} was not found in config. Values will be initialized to default values.

**Comment by demtha11** [comment]
I get the same errors and my loras dont work. I tried twice and used a paid Colab account, is that considered a low vram machine?

**Comment by abhishekkrthakur** [comment]
what are same errors? i dont see any errors mentioned in this issue. what do you mean when you say lora doesnt work? how are you doing the inferencce? unfortunately, its not possible to help without any details :)

**Comment by Kolza33** [comment]
How can I reverting back to version 0.7.1 - 1.7.5 - 1.7.2 installs?

**Comment by moha23** [comment]
> you can ignore:
> 
> {'latents_std', 'latents_mean', 'force_upcast'} was not found in config. Values will be initialized to default values. … {'feature_extractor', 'image_encoder'} was not found in config. Values will be initialized to default values. … {'dropout', 'reverse_transformer_layers_per_block', 'attention_type'} was not found in config. Values will be initialized to default values.

@abhishekkrthakur Would highly appreciate some intuition on why these warnings show up?  is it because the scripts expect us to provide some weights for these modules in the config, and since we are not providing any, it loads from default settings? Can't find which part of code is raising the error.. just worried about if lora is correctly attaching to the base model at all..
