### ISSUE TITLE
getting this error while running Gui in kaggle

### ISSUE THREAD

**Issue by osangni101020** [huggingface/autotrain-advanced#560]
### Prerequisites

- [X] I have read the [documentation](https://hf.co/docs/autotrain).
- [X] I have checked other issues for similar problems.

### Backend

Other cloud providers

### Interface Used

UI

### UI Screenshots & Parameters

![Screenshot_2024-03-27-23-26-19-495_com android chrome](https://github.com/huggingface/autotrain-advanced/assets/156106886/cd0ea3cc-d263-485c-b2ff-9ac9e5845257)

### Error Logs

provided in image

**Comment by osangni101020** [comment]
![Screenshot_2024-03-27-23-26-16-678_com android chrome](https://github.com/huggingface/autotrain-advanced/assets/156106886/3c9e4199-6574-4eb9-a920-6f246b9b6765)
another screenshot i forgot to add

**Comment by abhishekkrthakur** [comment]
could you please add all the params?
