### ISSUE TITLE
[BUG] Config.json file not generated after finetuning model using Autotrain with Nvidia DGX

### ISSUE THREAD

**Issue by RishubAmpliforce** [huggingface/autotrain-advanced#571]
### Prerequisites

- [X] I have read the [documentation](https://hf.co/docs/autotrain).
- [X] I have checked other issues for similar problems.

### Backend

Hugging Face Space/Endpoints

### Interface Used

CLI

### UI Screenshots & Parameters

![image](https://github.com/huggingface/autotrain-advanced/assets/111860324/bc2508a7-ed3e-49e5-b17d-84186b0948a9)

### Error Logs

After model training I wanted to deploy the model in inference points but could'nt deploy it because config.json was missing.

**Comment by yitzshapiro** [comment]
I also have this issue

**Comment by abhishekkrthakur** [comment]
you have trained an adapter model (peft=true) which doesnt generate config.json. it doesnt matter though, the model can still be loaded with AutoModelForCausalLM or with Inference endpoints. are you getting an error?

**Comment by RishubAmpliforce** [comment]
Error Trace:
Server message:Endpoint failed to start. 203Z","level":"ERROR","fields":{"message":"Download encountered an error: \nTraceback (most recent call last):\n\n File \"/opt/conda/lib/python3.10/site-packages/text_generation_server/utils/peft.py\", line 15, in download_and_unload_peft\n model = AutoPeftModelForCausalLM.from_pretrained(\n\n File \"/opt/conda/lib/python3.10/site-packages/peft/auto.py\", line 72, in from_pretrained\n peft_config = PeftConfig.from_pretrained(pretrained_model_name_or_path, **kwargs)\n\n File \"/opt/conda/lib/python3.10/site-packages/peft/config.py\", line 151, in from_pretrained\n return cls.from_peft_type(**kwargs)\n\n File \"/opt/conda/lib/python3.10/site-packages/peft/config.py\", line 118, in from_peft_type\n return config_cls(**kwargs)\n\nTypeError: LoraConfig.__init__() got an unexpected keyword argument 'layer_replication'\n\n\nDuring handling of the above exception, another exception occurred:\n\n\nTraceback (most recent call last):\n\n File \"/opt/conda/bin/text-generation-server\", line 8, in <module>\n sys.exit(app())\n\n File \"/opt/conda/lib/python3.10/site-packages/text_generation_server/cli.py\", line 225, in download_weights\n utils.download_and_unload_peft(\n\n File \"/opt/conda/lib/python3.10/site-packages/text_generation_server/utils/peft.py\", line 23, in download_and_unload_peft\n model = AutoPeftModelForSeq2SeqLM.from_pretrained(\n\n File \"/opt/conda/lib/python3.10/site-packages/peft/auto.py\", line 72, in from_pretrained\n peft_config = PeftConfig.from_pretrained(pretrained_model_name_or_path, **kwargs)\n\n File \"/opt/conda/lib/python3.10/site-packages/peft/config.py\", line 151, in from_pretrained\n return cls.from_peft_type(**kwargs)\n\n File \"/opt/conda/lib/python3.10/site-packages/peft/config.py\", line 118, in from_peft_type\n return config_cls(**kwargs)\n\nTypeError: LoraConfig.__init__() got an unexpected keyword argument 'layer_replication'\n"},"target":"text_generation_launcher","span":{"name":"download"},"spans":[{"name":"download"}]} Error: DownloadError


I tried using inference endpoints

**Comment by abhishekkrthakur** [comment]
does it work if you dont choose tgi container?

**Comment by RishubAmpliforce** [comment]
I have'nt tried that

**Comment by RishubAmpliforce** [comment]
![image](https://github.com/huggingface/autotrain-advanced/assets/111860324/13998d4e-d53b-4c0f-b82e-e6d8b0b29df2)


I just tried this in GoogleColab

**Comment by RishubAmpliforce** [comment]
![image](https://github.com/huggingface/autotrain-advanced/assets/111860324/9eb9447f-afdf-4fff-bf7f-3e27ade2b549)


I tried downloading the model in colab

**Comment by abhishekkrthakur** [comment]
you must use latest version of transformers and peft if you want to use colab or any other machine. for inferencce endpoints im checking internally

**Comment by abhishekkrthakur** [comment]
this issue is resolved. please let me know if you are still facing problem else ill close it .

**Comment by venturaEffect** [comment]
I also don't have the config.json file after using autotrain for finetuning.

**Comment by abhishekkrthakur** [comment]
adapter models dont have config.json. please see the FAQs in docs: https://hf.co/docs/autotrain

**Comment by venturaEffect** [comment]
Well and how to solve it?? It is supposed as you said on other issues to use the merge adapter for this but it doesn't work. It gives always an error and people are complaining about that from febraur with no response.

**Comment by venturaEffect** [comment]
And this is the whole explaination and solution to the missing config.json problem?

"I am getting config.json not found error
This means you have trained an adapter model (peft=true) which doesnt generate config.json. It doesnt matter though, the model can still be loaded with AutoModelForCausalLM or with Inference endpoints. If you want to merge weights with base models, you can use autotrain tools. Please read about it in miscelleneous section."

BTW, there is no further explanation on the miscellaneous section.
