### ISSUE TITLE
[BUG] Autotrain, Dreambooth Collab fails on last step

### ISSUE THREAD

**Issue by blissiraDC** [huggingface/autotrain-advanced#575]
### Prerequisites

- [X] I have read the [documentation](https://hf.co/docs/autotrain).
- [X] I have checked other issues for similar problems.

### Backend

Colab

### Interface Used

CLI

### CLI Command

Get this error on the Collab every time when using Dreambooth

Fetching 17 files: 100% 17/17 [00:07<00:00,  2.21it/s]
{'image_encoder', 'feature_extractor'} was not found in config. Values will be initialized to default values.

### Error Logs

Fetching 17 files: 100% 17/17 [00:07<00:00,  2.21it/s]
{'image_encoder', 'feature_extractor'} was not found in config. Values will be initialized to default values.

Loading pipeline components...:   0% 0/7 [00:00<?, ?it/s]Loaded tokenizer_2 as CLIPTokenizer from `tokenizer_2` subfolder of stabilityai/stable-diffusion-xl-base-1.0.

Loading pipeline components...:  14% 1/7 [00:00<00:00,  8.51it/s]{'reverse_transformer_layers_per_block', 'attention_type', 'dropout'} was not found in config. Values will be initialized to default values.
INFO     | 2024-04-08 17:53:36 | autotrain.app_utils:get_running_jobs:24 - Running jobs: [14179]
INFO     | 2024-04-08 17:54:36 | autotrain.app_utils:get_running_jobs:24 - Running jobs: [14179]
INFO     | 2024-04-08 17:54:36 | autotrain.app_utils:get_process_status:47 - No process found with PID: 14179
INFO     | 2024-04-08 17:54:36 | autotrain.app_utils:get_running_jobs:29 - Killing PID: 14179
INFO     | 2024-04-08 17:54:36 | autotrain.app_utils:get_running_jobs:33 - Error while killing process: [Errno 3] No such process
INFO     | 2024-04-08 17:54:36 | autotrain.app_utils:get_running_jobs:34 - Process 14179 is already completed. Skipping...

**Comment by abhishekkrthakur** [comment]
i dont see any error. whats the error ?

**Comment by abhishekkrthakur** [comment]
fixed in latest version
