### ISSUE TITLE
from huggingface_hub import get_full_repo_name  # for backward compatibility

### ISSUE THREAD

**Issue by Sandeep-Narahari** [huggingface/autotrain-advanced#579]
### Prerequisites

- [X] I have read the [documentation](https://hf.co/docs/autotrain).
- [X] I have checked other issues for similar problems.

### Backend

Local

### Interface Used

CLI

### CLI Command

autotrain dreambooth --model stabilityai/stable-diffusion-xl-base-1.0  --project-name v3d --image-path images/ --prompt "photo of sks man" --resolution 1024 --batch-size 1 --num-steps 1500 --fp16 --gradient-accumulation 4 --lr 1e-4 

### UI Screenshots & Parameters

![image](https://github.com/huggingface/autotrain-advanced/assets/46187761/d79b8acf-6ce5-4351-b50c-82ffa4049a45)

### Error Logs

![image](https://github.com/huggingface/autotrain-advanced/assets/46187761/356461eb-21e5-4b09-8fc8-ad522d7dfcf8)

### Additional Information

I have installed as per the instructions as per the readme

**Comment by csabakecskemeti** [comment]
I can confirm `conda install chardet` helps. Plus don't forget to export your  HF_TOKEN
