### ISSUE TITLE
[BUG] Running this on windows? AttributeError: module 'os' has no attribute 'setsid'. Did you mean: 'getpid'? 

### ISSUE THREAD

**Issue by jazelly** [huggingface/autotrain-advanced#583]
### Prerequisites

- [X] I have read the [documentation](https://hf.co/docs/autotrain).
- [X] I have checked other issues for similar problems.

### Backend

Local

### Interface Used

CLI

### CLI Command

`autotrain app --port 8080 --host 127.0.0.1`

### Error Logs

```
File "C:\Users\31711\anaconda3\Lib\site-packages\autotrain\cli\run_app.py", line 100, in run
    preexec_fn=os.setsid,
               ^^^^^^^^^
AttributeError: module 'os' has no attribute 'setsid'. Did you mean: 'getpid'?
```

### Additional Information

`os.setsid` is only supported in UNIX system. Is there any workaround for this on Windows?

**Comment by abhishekkrthakur** [comment]
No. you can use WSL or docker image.
