### ISSUE TITLE
[BUG] pip dependency error

### ISSUE THREAD

**Issue by yangsx3** [huggingface/autotrain-advanced#585]
### Prerequisites

- [X] I have read the [documentation](https://hf.co/docs/autotrain).
- [X] I have checked other issues for similar problems.

### Backend

Colab

### Interface Used

UI

### UI Screenshots & Parameters

Use colab only

### Error Logs

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow-metadata 1.14.0 requires protobuf<4.21,>=3.20.3, but you have protobuf 4.23.4 which is incompatible.
INFO     | 2024-04-15 01:35:42 | autotrain.cli.run_app:run:86 - AutoTrain Public URL: NgrokTunnel: "https://1320-34-170-50-131.ngrok-free.app/" -> "http://localhost:7860/"
INFO     | 2024-04-15 01:35:42 | autotrain.cli.run_app:run:87 - Please wait for the app to load...
/usr/lib/python3.10/subprocess.py:1796: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = _posixsubprocess.fork_exec(
Your installed package `nvidia-ml-py` is corrupted. Skip patch functions `nvmlDeviceGet{Compute,Graphics,MPSCompute}RunningProcesses`. You may get incorrect or incomplete results. Please consider reinstall package `nvidia-ml-py` via `pip3 install --force-reinstall nvidia-ml-py nvitop`.
Your installed package `nvidia-ml-py` is corrupted. Skip patch functions `nvmlDeviceGetMemoryInfo`. You may get incorrect or incomplete results. Please consider reinstall package `nvidia-ml-py` via `pip3 install --force-reinstall nvidia-ml-py nvitop`.
INFO     | 2024-04-15 01:35:47 | autotrain.app:<module>:30 - Starting AutoTrain...

**Comment by abhishekkrthakur** [comment]
its not an error that will cause any issues and can be ignored. it has also been discussed several times in closed issues.
