### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by andreherful** [huggingface/autotrain-advanced#587]
### Prerequisites

- [X] I have read the [documentation](https://hf.co/docs/autotrain).
- [X] I have checked other issues for similar problems.

### Backend

Hugging Face Space/Endpoints

### Interface Used

UI

### UI Screenshots & Parameters

Hello, I start the autotrain over docker and autotrain, insert all information and added a dataset of huggingphase space. i'm getting each time the error below, because the files are only on json available. 

### Error Logs

FileNotFoundError: Couldn't find a dataset script at /app/cognitivecomputations/dolphin/flan1m-alpaca-uncensored.jsonl/flan1m-alpaca-uncensored.jsonl.py or any data file in the same directory.

ERROR    | 2024-04-06 09:30:03 | autotrain.trainers.common:wrapper:116 - Couldn't find a dataset script at /app/cognitivecomputations/dolphin/flan1m-alpaca-uncensored.jsonl/flan1m-alpaca-uncensored.jsonl.py or any data file in the same directory.
INFO     | 2024-04-06 09:30:03 | autotrain.trainers.common:pause_space:73 - Pausing space...

**Comment by abhishekkrthakur** [comment]
please provide screenshot of ui with all values filled

**Comment by andreherful** [comment]
sure. here it is
![Screenshot 2024-04-15 at 17 24 19](https://github.com/huggingface/autotrain-advanced/assets/97897979/a19d65d1-4f75-4809-a28f-a241de3325d9)
![Screenshot 2024-04-15 at 17 46 24](https://github.com/huggingface/autotrain-advanced/assets/97897979/3d4e1d62-4fbd-40d5-8d2e-cc12e23b751f)

**Comment by abhishekkrthakur** [comment]
hub dataset looks wrong
train split is not defined

**Comment by andreherful** [comment]
> hub dataset looks wrong train split is not defined

what should be inserted there?
i think i had it also on train split the name "flan1m-alpaca-uncensored.json" with the same error.
