### ISSUE TITLE
Autotrain google colab -- start training from check point?

### ISSUE THREAD

**Issue by krecicki** [huggingface/autotrain-advanced#597]
### Prerequisites

- [X] I have read the [documentation](https://hf.co/docs/autotrain).
- [X] I have checked other issues for similar problems.

### Backend

Colab

### Interface Used

CLI

### Error Logs

The GPU disconnected and I had to save all of the checkpoint files and training files and I want to start training again, but how do I start training from the checkpoint files?

**Comment by abhishekkrthakur** [comment]
which task?
