### ISSUE TITLE
[FEATURE REQUEST] Raise einops to 0.8.0

### ISSUE THREAD

**Issue by mhupfauer** [huggingface/autotrain-advanced#604]
### Feature Request

Raise einops dependency to version 0.8.0, if possible 

### Motivation

With the strict 0.7.0 requirement there are dependency conflicts with ~~other hf libraries~~ `flash-attn`

**Comment by abhishekkrthakur** [comment]
what does it break? :)

**Comment by mhupfauer** [comment]
Just checked it is in fact 'just' `flash-attn` which installs the latest [einops version](https://github.com/Dao-AILab/flash-attention/blob/main/setup.py#L346).
