### ISSUE TITLE
Deploy endpoint needs model access??!

### ISSUE THREAD

**Issue by javagamedev1** [huggingface/autotrain-advanced#612]
Hello!
So, Im doing everything correct.

I used llama3 as base to fine tune the model.

But when I deploy to the endpoint it gives me the error:

I need to request access to the model.
To accept the terms.

But I already did that, so my guess is that when I create the endpoint Im not autenticate with my hugging face token.
Because even if this pass, using other models, is going to have trouble when access my fine tuned model.

So the question is, what I need to do?

**Comment by abhishekkrthakur** [comment]
this is not autotrain issue. its an Endpoints issue. please email api-enterprise@huggingface.co with details.

or,

merge the model weights manually.
