### ISSUE TITLE
[BUG] Unclear use case

### ISSUE THREAD

**Issue by arthurwolf** [huggingface/autotrain-advanced#617]
### Prerequisites

- [X] I have read the [documentation](https://hf.co/docs/autotrain).
- [X] I have checked other issues for similar problems.

### Backend

Local

### Interface Used

CLI

### CLI Command

It's taken me about 5 minutes of reading first through a Reddit post, then through the Github file, then through the HF docs, to **finally** understands this doesn't **train** LLMs, but can only finetune them. Everything I had read before that suggested/implied it's capable of doing training...

Clickbait is not a good strategy for Open-Source projects.

### Error Logs

no error logs.

**Comment by abhishekkrthakur** [comment]
Omg. it is called training even if its finetuning 🤦🏽‍♂️🤦🏽‍♂️🤦🏽‍♂️
What do you want? pre-training? Are you planning to "train" an llm on single gpu?

**Comment by arthurwolf** [comment]
> Omg. it is called training even if its finetuning 🤦🏽‍♂️🤦🏽‍♂️🤦🏽‍♂️

It's not just called that, as I explained, I wanted to know if it did training or just fine-tuning, and that took quite a bit of time to figure out...

> What do you want?

Accurate, not-misleading information?

> Are you planning to "train" an llm on single gpu?

No ... ?

**Comment by abhishekkrthakur** [comment]
What did you explain? Could you provide references? 
Fine-tuning IS training. Parameter efficient fine tuning is also training. AutoTrain supports both. 
In both cases, we are "training" either full network or parts of it.
We can also freeze some layers and "train" some. 

How do you define training? Please elaborate and let us know. and we might just add it!!!!
Looking forward.

**Comment by arthurwolf** [comment]
> What did you explain? 

See original comment ?

> Could you provide references?

* https://github.com/huggingface/autotrain-advanced
* https://huggingface.co/docs/autotrain/index

> How do you define training?

https://chat.openai.com/share/a8ebdfcb-a0af-4db0-96ca-06e37ac25964

> Fine-tuning IS training. 

Fine-tuning is a step of training...

You can also do some further fine-tuning "after" training (which is also "further" training).

But fine-turing isn't training, training is a larger/more complex/more involved process than "just" fine-tuning...

And yes, fine-tuning is in a certain sense a form of training. It's just not the way I understood the information I was provided, and I really expect I won't be the only one...

Nothing I've read (until being quite a bit into the docs) explained that the training this tool can do is limited to fine-tuning, and it consistently was leaving that question ambiguous (again, I was looking for the answer to that question, and it took a long time to find the answer, which was a frustrating experience...).

**Comment by abhishekkrthakur** [comment]
this conversation isnt going anywhere. please start with reading the basics of machine learning. when you are done, im happy to discuss further. till then, closing this non-issue.
