### ISSUE TITLE
[BUG] llm-merge-adapter space bug after autotrain finetuned model

### ISSUE THREAD

**Issue by ahmed8047762** [huggingface/autotrain-advanced#622]
### Prerequisites

- [X] I have read the [documentation](https://hf.co/docs/autotrain).
- [X] I have checked other issues for similar problems.

### Backend

Hugging Face Space/Endpoints

### Interface Used

UI

### Error Logs

TypeError: LoraConfig.init() got an unexpected keyword argument 'layer_replication'

### Additional Information

I finetuned **HuggingFaceH4/zephyr-7b-beta** model on custom dataset using **autotrain** and tried to merge it with base model using duplicated space of your space but after 8/8 model's shreds were loaded, following error occured:

**TypeError: LoraConfig.init() got an unexpected keyword argument 'layer_replication'**

any idea how to resolve this issue?

**Comment by ahmed8047762** [comment]
@abhishekkrthakur requirements.txt of **llm-merge-adapter space**? Because while finetuning, I didn't separately installed any library, all the dependencies were installed through **autotrain**.

**Comment by ahmed8047762** [comment]
@abhishekkrthakur In the cli tool and space, is there a parameter to load a 4 or 8 bit quantized version of base model?

**Comment by abhishekkrthakur** [comment]
if you trained it using autotrain, it should be mergable by both the cli and the space. are you facing any issues again? requirements were updated.

**Comment by ahmed8047762** [comment]
Thanks a lot, the bug is resolved.

I was asking about parameter for loading a quantized base model for merging because that would've been very helpful in merging smaller 7b models inside colab free tier rather than buying compute for it
