### ISSUE TITLE
[BUG] OSError: [Errno 22] Invalid argument: '/proc/63/task/63/net'

### ISSUE THREAD

**Issue by ruchibahl18** [huggingface/autotrain-advanced#623]
### Prerequisites

- [X] I have read the [documentation](https://hf.co/docs/autotrain).
- [X] I have checked other issues for similar problems.

### Backend

Local

### Interface Used

CLI

### CLI Command

! autotrain spacerunner \
 --project-name custom_autotrain_spacerunner \
 --script-path / \
 --username $USER_NAME \
 --token $HF_TOKEN \
 --backend spaces-a10gl \
 --args padding=right

### Error Logs

INFO | 2024-05-04 23:47:32 | autotrain.trainers.generic.utils:create_dataset_repo:11 - Creating dataset repo...
INFO | 2024-05-04 23:47:33 | autotrain.trainers.generic.utils:create_dataset_repo:19 - Uploading dataset...
Traceback (most recent call last):
 File "/usr/local/bin/autotrain", line 8, in <module>
 sys.exit(main())
 File "/usr/local/lib/python3.10/dist-packages/autotrain/cli/autotrain.py", line 62, in main
 command.run()
 File "/usr/local/lib/python3.10/dist-packages/autotrain/cli/run_spacerunner.py", line 132, in run
 dataset_id = create_dataset_repo(
 File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/generic/utils.py", line 20, in create_dataset_repo
 api.upload_folder(
 File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 119, in _inner_fn
 return fn(*args, **kwargs)
 File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/hf_api.py", line 1230, in _inner
 return fn(self, *args, **kwargs)
 File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/hf_api.py", line 4774, in upload_folder
 add_operations = _prepare_upload_folder_additions(
 File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/hf_api.py", line 8479, in _prepare_upload_folder_additions
 for path in sorted(folder_path.glob("**/*")) # sorted to be deterministic
 File "/usr/lib/python3.10/pathlib.py", line 1034, in glob
 for p in selector.select_from(self):
 File "/usr/lib/python3.10/pathlib.py", line 493, in _select_from
 for p in successor_select(starting_point, is_dir, exists, scandir):
 File "/usr/lib/python3.10/pathlib.py", line 441, in _select_from
 entries = list(scandir_it)
OSError: [Errno 22] Invalid argument: '/proc/63/task/63/net'

### Additional Information

Also when I try this command

autotrain spacerunner \
    --project-name custom_llama_training \
    --script-path /path/to/script/py/ \
    --username abhishek \
    --token $HF_WRITE_TOKEN \
    --backend spaces-a10gl \
    --args padding=right;push_to_hub
    --env TOKENIZERS_PARALLELISM=false;TRANSFORMERS_VERBOSITY=error

I get no such option present push_to_hub

Kindly provide fix

**Comment by abhishekkrthakur** [comment]
`--script-path` should be the path to folder that has `script.py` (and other things that you want to upload)

**Comment by ruchibahl18** [comment]
@abhishekkrthakur  yes the script.py is under / folder

**Comment by abhishekkrthakur** [comment]
the command will then attempt to upload everything inside /. this is not recommended. please move the script and other files you want to upload together with script to their own individual folder and try again. 

Thank you for pointing this. ill add a note in help/docs.

**Comment by ruchibahl18** [comment]
@abhishekkrthakur Thank you for that worked after moving script under different folder.
However is spacerunner a paid module because next I get this issue 

    raise HfHubHTTPError(str(e), response=response) from e
huggingface_hub.utils._errors.HfHubHTTPError: 402 Client Error: Payment Required for url: https://huggingface.co/api/repos/create (Request ID: Root=1-66395084-7787facd15dabf7776da68f9;8d208450-39f4-4279-9710-a1e5e03f4d83)

You must add a payment method to your account to use paid hardware on Spaces. Visit your billing settings to add one: https://huggingface.co/settings/billing

**Comment by abhishekkrthakur** [comment]
yes. its a paid service when you use paid hardware: `spaces-a10gl`. you can use `spaces-cpuf` which is free.
