### ISSUE TITLE
[FEATURE REQUEST]: Supporting Audio Tasks

### ISSUE THREAD

**Issue by riteshkrjnu** [huggingface/autotrain-advanced#636]
### Feature Request

Are there any plans to include support for audio tasks such as audio classification, ASR, and TTS in AutoTrain soon? Are they excluded by design? If not, are they already being worked upon, and should we expect them to be there sometime soon?

### Motivation

Audio is the only major category of tasks/pipelines unavailable on AutoTrain. Since much of our research focuses on audio, we would like to know if it would be worthwhile to include support for such tasks. We might be able to contribute if it's not already in the pipeline.

**Comment by abhishekkrthakur** [comment]
if there is interest why not. which one is the most interesting to you?

**Comment by riteshkrjnu** [comment]
ASR, to begin with :)
