### ISSUE TITLE
[BUG] Config name is missing for Datasets with no default config

### ISSUE THREAD

**Issue by Aryan-401** [huggingface/autotrain-advanced#644]
### Prerequisites

- [X] I have read the [documentation](https://hf.co/docs/autotrain).
- [X] I have checked other issues for similar problems.

### Backend

Other cloud providers

### Interface Used

UI

### UI Screenshots & Parameters

![image](https://github.com/huggingface/autotrain-advanced/assets/58473359/50f79872-12ec-4317-97e2-155b5477de9c)

### Error Logs

ERROR    | 2024-05-16 09:52:25 | autotrain.trainers.common:wrapper:120 - train has failed due to an exception: Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/autotrain/trainers/common.py", line 117, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/autotrain/trainers/object_detection/__main__.py", line 49, in train
    train_data = load_dataset(
  File "/opt/conda/lib/python3.10/site-packages/datasets/load.py", line 2587, in load_dataset
    builder_instance = load_dataset_builder(
  File "/opt/conda/lib/python3.10/site-packages/datasets/load.py", line 2296, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
  File "/opt/conda/lib/python3.10/site-packages/datasets/builder.py", line 374, in __init__
    self.config, self.config_id = self._create_builder_config(
  File "/opt/conda/lib/python3.10/site-packages/datasets/builder.py", line 584, in _create_builder_config
    raise ValueError(
ValueError: Config name is missing.
Please pick one among the available configs: ['full', 'mini']
Example of usage:
	`load_dataset('license-plate-object-detection', 'full')`

ERROR    | 2024-05-16 09:52:25 | autotrain.trainers.common:wrapper:121 - Config name is missing.
Please pick one among the available configs: ['full', 'mini']
Example of usage:
	`load_dataset('license-plate-object-detection', 'full')`

### Additional Information

Seems like the Problem is due to Non-Default configs in the dataset I'm trying to use. Next logical question is this by design? If yes, how can I use datasets without any default to autotrain? 

Links to support Theory: 
- https://discuss.huggingface.co/t/need-help-setting-up-autotrain-locally/84225
- https://discuss.huggingface.co/t/config-default-not-found-for-dataset/49752

**Comment by abhishekkrthakur** [comment]
it was by design but ive added a workaround.
for the dataset you mention, you can use config_name:split_name as split.

for example: `full:train` in train split
and `full:test` or `full:validation` in valid split

make sure you are on version 0.7.99 or above.
