### ISSUE TITLE
[BUG] AutoTrain_LLM.ipynb quantization = none

### ISSUE THREAD

**Issue by beddows** [huggingface/autotrain-advanced#646]
### Prerequisites

- [X] I have read the [documentation](https://hf.co/docs/autotrain).
- [X] I have checked other issues for similar problems.

### Backend

Colab

### Interface Used

UI

### Error Logs

NameError                                 Traceback (most recent call last)
[<ipython-input-2-30a241eb6b88>](https://localhost:8080/#) in <cell line: 29>()
     27 mixed_precision = "fp16" # @param ["fp16", "bf16", "none"] {type:"raw"}
     28 peft = True # @param ["False", "True"] {type:"raw"}
---> 29 quantization = none # @param ["int4", "int8", "none"] {type:"raw"}
     30 lora_r = 8 #@param {type:"number"}
     31 lora_alpha = 32 #@param {type:"number"}

NameError: name 'none' is not defined

### Additional Information

For the quantization hyperparameter, choosing none in the dropdown doesn't work. Editing the code and changing to None, "none", or "None" also doesn't work. peft is set to True. [Notebook](https://colab.research.google.com/github/huggingface/autotrain-advanced/blob/main/colabs/AutoTrain_LLM.ipynb)

**Comment by kjartanm** [comment]
Yes, this is still an issue. 

The notebook is linked from Cloudflare in a tutorial for using their LoRa/finetuning setup:

https://developers.cloudflare.com/workers-ai/tutorials/fine-tune-models-with-autotrain

It seems that at one point adding quotes fixed the issue, but not any longer.

**Comment by abhishekkrthakur** [comment]
your backend provider needs to update autotrain version

**Comment by abhishekkrthakur** [comment]
okay.isee the problem now. it links to older colab. please use the new colab in the readme of this repository

**Comment by kjartanm** [comment]
The old colab is still linked from the readme (colabs section at the bottom)

**Comment by abhishekkrthakur** [comment]
fixing it today with addition of more colabs. thank you for pointing this out

**Comment by abhishekkrthakur** [comment]
this issue is now fixed.
