### ISSUE TITLE
[BUG] Distant computer (4 GPUs 10GiB of VRAM each) crashes the second i launch the finetuning using AutoTrain localy of mistral 7B 

### ISSUE THREAD

**Issue by HichamBouchtib** [huggingface/autotrain-advanced#650]
### Prerequisites

- [X] I have read the [documentation](https://hf.co/docs/autotrain).
- [X] I have checked other issues for similar problems.

### Backend

Local

### Interface Used

CLI

### CLI Command

autotrain --config config.yml

### UI Screenshots & Parameters

This is my CLI when the distant computer crashes : 
![Capture d’écran (61)](https://github.com/huggingface/autotrain-advanced/assets/123313540/ca5fb666-91d8-4ad0-9c42-608bd99623b2)
This is my Config.yml file  : 
![image](https://github.com/huggingface/autotrain-advanced/assets/123313540/9a5ee0ba-16fc-4d5b-b1df-c8fb5c2fbc6d)

### Error Logs

This is the error in BitVise when the computer crashes
![Capture d'écran 2024-05-10 100356](https://github.com/huggingface/autotrain-advanced/assets/123313540/166250ea-410b-4312-b4dd-ed99df339726)

### Additional Information

Hello Everyone, im a newbie to AutoTrain, im trying to finetune a 7B mistral param using AutoTrain localy (since i got 4 gpus with 10 GiB of Vram each) in a distant computer for which im using BitVise to connect via SSh. i was using the SFT Trainer of Huggingface and faced many issues related to CUDA memory for that reason i decided to move to Autotrain since its easier. 
N.B : I have done everything i know to optimize (LoRa, 4bit model loading, lower batch size, etc...) i also tried the DDP before (Distributed data paralel). 
I have found some memory usage estimation of fine tuning this same model in BF16 precision that says the peak of Adam is 56gb of Vram which i dont have for the moment. Do you think renting some GPUs from RunPod or Huggingface would fix the issue for me ? 
Thank you for your guidance.

**Comment by abhishekkrthakur** [comment]
are you running the `autotrain --config` command on the same computer or a remote pc?

**Comment by abhishekkrthakur** [comment]
maybe your gpus are not supported. which gpu do you have? 
can you try with quantization: null?

**Comment by hichambht32** [comment]
I will try using quantization: null soon, although I doubt it will fix the error. Based on my experience, the minimum effective level of quantization is 4-bit. Setting it to null will not quantize the model at all.

**Comment by abhishekkrthakur** [comment]
if you cant run nvidia-smi, then thats the possible cause. you will need to restart the remote machine :)

**Comment by hichambht32** [comment]
No, you didnt get it. its not about i can not run the nvidia-smi. the whole ssh conneciton is broken but once i restart it everything works just fine i can run whatever i wish (including nvidia-smi). But the problem is the second i launch the finetunine with the autotrain -- config config.yml the machine crashes

**Comment by hichambht32** [comment]
Can you tell me whether my gpus are supported ? Maybe they are insufficient right ?
