### ISSUE TITLE
Text Classification (Multi-Class) not supported anymore?

### ISSUE THREAD

**Issue by LeDuySon** [huggingface/autotrain-advanced#659]
Hi everyone, i have tried the Autotrain UI in huggingface space and i can't find how to train text classification multi-class setting? Can anyone help me with this?

**Comment by abhishekkrthakur** [comment]
there is a text classification dropdown. isnt there? 🤔

**Comment by abhishekkrthakur** [comment]
just to close. it is supported and still there.
