### ISSUE TITLE
Sort models alphabetically in the UI

### ISSUE THREAD

**Issue by scherguimirakl** [huggingface/autotrain-advanced#664]
### Feature Request

Would it be possible to sort the list of the models shown in the UI ?

### Motivation

The list of models shown in the UI is not sorted alphabetically. This makes finding the right model very difficult and one has to go through the list multiple times.

**Comment by abhishekkrthakur** [comment]
models are currently sorted by popularity. in case you cant find your favourite model in the list or have difficulties finding it, you can try: https://huggingface.co/docs/autotrain/faq#the-model-i-want-to-use-doesnt-show-up-in-the-model-selection-dropdown
