### ISSUE TITLE
404 or too many times

### ISSUE THREAD

**Issue by cexll** [huggingface/autotrain-advanced#667]
<img width="2522" alt="image" src="https://github.com/huggingface/autotrain-advanced/assets/26520956/b0f82423-d23e-4ae3-808b-efc98181087d">

Device: MacOS 14
Browser: Chrome 125.0.6422.141

**Comment by cexll** [comment]
<img width="1019" alt="image" src="https://github.com/huggingface/autotrain-advanced/assets/26520956/c7ace8aa-9de2-48d7-968c-d1af1c6c739b">

**Comment by abhishekkrthakur** [comment]
did you figure out the issue?

**Comment by cexll** [comment]
edge it work
