### ISSUE TITLE
[FEATURE REQUEST]API of pony-diffusion-v6 is no longer displayed. 

### ISSUE THREAD

**Issue by Sagamichika** [huggingface/autotrain-advanced#668]
### Feature Request

API of pony-diffusion-v6 is no longer displayed. Was it deleted?

### Motivation

I was using the pony-diffusion-v6 API model to train, but one day it disappeared from the model list. I would like this to be revived as soon as possible. I think it's probably because the model was removed from the original HuggingFace. Please let me know if there is any other way to deal with this other than asking the management to add it.

**Comment by abhishekkrthakur** [comment]
note: if model was removed from hf and you dont have it locally, you cant use it.

**Comment by Sagamichika** [comment]
thank you. I had read it beforehand. I read it and tried it, but it didn't work so I posted it.
Maybe I need to upload Pony Diffusion v-6 on hugging face with my own account?

**Comment by Sagamichika** [comment]
I am using Colab via ngrok

**Comment by abhishekkrthakur** [comment]
> note: if model was removed from hf and you dont have it locally, you cant use it.

you can upload the same files in your account and use it instead

**Comment by Sagamichika** [comment]
Huggingface doesn't seem to have a pony diffusion v6 model currently available. No matter which option you choose, an error will occur. Looks like we'll just have to wait for it to be added. thank you.

**Comment by abhishekkrthakur** [comment]
if a model is not available, it cannot be used. you can upload the model as private to your own username and then use it.
