### ISSUE TITLE
AutoTrain says "This space has been paused by owner" when I am not doing it.

### ISSUE THREAD

**Issue by ArtinMFar1** [huggingface/autotrain-advanced#670]
Hello, I keep trying to train a model using AutoTrain with my own training data and it keeps doing what the title says

Model: https://huggingface.co/meta-llama/Meta-Llama-3-8B
Dataset: 
[coolbot dataset 2.csv](https://github.com/user-attachments/files/15738216/coolbot.dataset.2.csv)

**Comment by abhishekkrthakur** [comment]
space pauses itself to save you money on failure or success. even after its paused, you can click on logs to see what happened. you can find the trained models in your huggingface account if the training finished.

**Comment by Parkourer10** [comment]
same dude i got the same issue

**Comment by ChaithanyaVamshi** [comment]
Is the issue resolved? space is pausing automatically when the training starts

**Comment by Parkourer10** [comment]
the issue is still the same

**Comment by abhishekkrthakur** [comment]
is anyone reading this: https://github.com/huggingface/autotrain-advanced/issues/670#issuecomment-2154614314 ? :)

**Comment by vincentclaes** [comment]
Make sure to select the tab "container" to see the issue

![Screenshot 2024-08-31 at 14 10 48](https://github.com/user-attachments/assets/62fe0500-edf9-4f7c-baa6-160275eed729)

**Comment by lucasmouraweb** [comment]
I resolved, you need request the model access before use in autotrain
![image](https://github.com/user-attachments/assets/c9c9e178-1a9f-403c-a301-d3577c1ce4ad)

**Comment by BERRAMOU2017** [comment]
@lucasmouraweb 
how did you request access to the model please ?
