### ISSUE TITLE
can i use this on a orange pi 5? or cpu only?

### ISSUE THREAD

**Issue by develperbayman** [huggingface/autotrain-advanced#671]
### Feature Request

i know its not a power house but if i wanted to train small models? i cannot get the npu to work that would be cool and it uses a mali610 gpu

### Motivation

coolness if it worked im creating/want to ...small llms for specific task

### Additional Context

not much im poor and have old hardware and a opi5

**Comment by abhishekkrthakur** [comment]
it works fine on cpu
