### ISSUE TITLE
[BUG] KeyError: 'chat_template'

### ISSUE THREAD

**Issue by yitzshapiro** [huggingface/autotrain-advanced#682]
### Prerequisites

- [X] I have read the [documentation](https://hf.co/docs/autotrain).
- [X] I have checked other issues for similar problems.

### Backend

Colab

### Interface Used

UI

### UI Screenshots & Parameters

<img width="814" alt="image" src="https://github.com/huggingface/autotrain-advanced/assets/145394865/29dc57c4-3937-41e4-a53c-aed3d023522e">

{
    "block_size": 1024,
    "model_max_length": 2048,
    "padding": "right",
    "use_flash_attention_2": false,
    "disable_gradient_checkpointing": false,
    "logging_steps": -1,
    "evaluation_strategy": "epoch",
    "save_total_limit": 1,
    "auto_find_batch_size": false,
    "mixed_precision": "fp16",
    "lr": 3e-05,
    "epochs": 3,
    "batch_size": 2,
    "warmup_ratio": 0.1,
    "gradient_accumulation": 4,
    "optimizer": "adamw_torch",
    "scheduler": "linear",
    "weight_decay": 0.0,
    "max_grad_norm": 1.0,
    "seed": 42,
    "chat_template": "none",
    "quantization": "int4",
    "target_modules": "all-linear",
    "merge_adapter": false,
    "peft": true,
    "lora_r": 16,
    "lora_alpha": 32,
    "lora_dropout": 0.05,
    "unsloth": false,
    "push_to_hub": true
}

### Error Logs

INFO     | 2024-06-13 20:31:54 | autotrain.cli.autotrain:main:56 - Using AutoTrain configuration: config.yml
INFO     | 2024-06-13 20:31:54 | autotrain.parser:__post_init__:124 - Running task: lm_training
INFO     | 2024-06-13 20:31:54 | autotrain.parser:__post_init__:125 - Using backend: local
Traceback (most recent call last):
File "/usr/local/bin/autotrain", line 8, in <module>
sys.exit(main())
File "/usr/local/lib/python3.10/dist-packages/autotrain/cli/autotrain.py", line 57, in main
cp = AutoTrainConfigParser(args.config)
File "<string>", line 4, in __init__
File "/usr/local/lib/python3.10/dist-packages/autotrain/parser.py", line 127, in __post_init__
self.parsed_config = self._parse_config()
File "/usr/local/lib/python3.10/dist-packages/autotrain/parser.py", line 142, in _parse_config
params["chat_template"] = self.config["data"]["chat_template"]
KeyError: 'chat_template'
An error occurred while starting training!
Error: Training failed with exit code: 1

### Additional Information

Tried using all the different chat_templates, and still am getting the same error above

**Comment by abhishekkrthakur** [comment]
you should have a config.yml generated, could you share it please?

**Comment by yitzshapiro** [comment]
This is what's generated:

backend: local
base_model: microsoft/Phi-3-mini-128k-instruct
data:
  column_mapping:
    text: text
  path: data/formatted_train.csv
  train_split: train
  valid_split: null
hub:
  push_to_hub: true
  token: ${{HF_TOKEN}}
  username: ${{HF_USERNAME}}
log: tensorboard
params:
  batch_size: 2
  block_size: 1024
  chat_template: none
  epochs: 3
  gradient_accumulation: 4
  lr: 3.0e-05
  mixed_precision: fp16
  model_max_length: 2048
  optimizer: adamw_torch
  peft: true
  scheduler: linear
  target_modules: all-linear
  unsloth: false
project_name: Slottify-Phi-3-mini-128k-instruct
task: llm

**Comment by arthurgcarvalho** [comment]
Same here

backend: local
base_model: openai-community/gpt2
data:
  column_mapping:
    text: text
  path: data/train.csv
  train_split: train.csv
  valid_split: null
hub:
  push_to_hub: true
  token: ${{HF_TOKEN}}
  username: ${{HF_USERNAME}}
log: tensorboard
params:
  batch_size: 2
  block_size: 1024
  chat_template: none
  epochs: 3
  gradient_accumulation: 4
  lr: 3.0e-05
  mixed_precision: fp16
  model_max_length: 2048
  optimizer: adamw_torch
  peft: true
  scheduler: linear
  target_modules: all-linear
  unsloth: false
project_name: autotrain-f954p-3o4yn
task: llm

**Comment by abhishekkrthakur** [comment]
this issue is now resolved in latest release. please let me know if you are still facing problems.
version 0.7.122+

**Comment by arthurgcarvalho** [comment]
Thank you for your help/ I am still facing the problem. Some relevant info:

Results of **pip show autotrain-advanced**
Name: autotrain-advanced
Version: 0.7.123
Summary: 
Home-page: https://github.com/huggingface/autotrain-advanced
Author: HuggingFace Inc.
Author-email: [autotrain@huggingface.co](mailto:autotrain@huggingface.co)
License: Apache 2.0
Location: /usr/local/lib/python3.10/dist-packages
Requires: accelerate, albumentations, authlib, bitsandbytes, codecarbon, cryptography, datasets, diffusers, einops, evaluate, fastapi, hf-transfer, httpx, huggingface-hub, invisible-watermark, ipadic, itsdangerous, jiwer, joblib, loguru, nltk, nvitop, optuna, packaging, pandas, peft, Pillow, protobuf, py7zr, pycocotools, pydantic, pyngrok, python-multipart, pyyaml, requests, rouge-score, sacremoses, scikit-learn, sentence-transformers, sentencepiece, seqeval, tensorboard, tiktoken, timm, torchmetrics, tqdm, transformers, trl, uvicorn, werkzeug, xgboost
Required-by:


**config.yml**
backend: local
base_model: google/gemma-2b
data:
  column_mapping:
    text: text
  path: data/train.csv
  train_split: train
  valid_split: null
hub:
  push_to_hub: true
  token: ${{HF_TOKEN}}
  username: ${{HF_USERNAME}}
log: tensorboard
params:
  batch_size: 2
  block_size: 1024
  epochs: 3
  gradient_accumulation: 4
  lr: 3.0e-05
  mixed_precision: fp16
  model_max_length: 2048
  optimizer: adamw_torch
  peft: true
  scheduler: linear
  target_modules: all-linear
  unsloth: false
project_name: autotrain-jo5a6-odfwk
task: llm

**Comment by abhishekkrthakur** [comment]
@arthurgcarvalho the fix was for colab ui. are you using the colab ui? or launching training using autotrain --config command?

**Comment by arthurgcarvalho** [comment]
Yep, I am using Colab UI by running the following commands (from the template at https://github.com/huggingface/autotrain-advanced?tab=readme-ov-file):

!pip install -U autotrain-advanced > install_logs.txt 2>&1
from IPython.display import display
from autotrain.app.colab import colab_app
elements = colab_app()
display(elements)

**Comment by arthurgcarvalho** [comment]
In case it helps:

![image](https://github.com/huggingface/autotrain-advanced/assets/39745844/039ca554-5f25-4ebc-8e8d-2e7a4a476f91)

**Comment by abhishekkrthakur** [comment]
apologies. i overlooked. issue is resolved in latest version now.

**Comment by yitzshapiro** [comment]
THANK YOU!
