### ISSUE TITLE
Where is the fine-tuned model output?

### ISSUE THREAD

**Issue by RonPisaturo** [huggingface/autotrain-advanced#684]
I’m new to using AutoTrain on Hugging Face and I encountered an issue during my first attempt at fine-tuning a model. I have a free account, because I want to see whether I can get something to work before I start paying for training. Here’s a summary of what I did and the problem I’m facing:
Training Configuration:
I trained using Mistral-7B-Instruct-v0.2 and also openai-community/gpt2.
Dataset: I uploaded a tiny JSONL file (24 records) with a single “text” field for training.
Training Parameters: I set the training to run for one epoch.
Training Process:
The training ran for a couple of seconds.
I received a message that the space was paused, which I assumed meant the training had completed.
Issue:
After the training supposedly completed, I can’t find any output files or trained models.
I checked all available tabs and sections in the AutoTrain interface but didn’t see anything labeled “Models,” “Artifacts,” “Results,” or similar.
I reviewed the logs but didn’t find any clear indications of where the output is stored.
I checked my Hugging Face profile under the “Models” heading, but it says “None yet.”
Questions:
Where should I look in the AutoTrain interface to find the trained model and output files?
Are there any additional steps I need to take to ensure the trained model is saved and accessible?
With a free account, I don’t have any GPUs assigned. But is that a problem with only 24 short training samples and one epoch?
Any guidance or tips would be greatly appreciated!

**Comment by abhishekkrthakur** [comment]
paused space can also mean that the training failed. 
if training finished, you will find the model files in your hf namespace. if it failed, you can check logs of space to know why.

**Comment by RonPisaturo** [comment]
It seems the logs go away when the space pauses. 
Is it possible that the problem is that I don't have persistent storage with my free account?

**Comment by abhishekkrthakur** [comment]
no. logs do remain when space pauses if you didnt restart. could you share space link and i can check internally?

**Comment by RonPisaturo** [comment]
Thank you very much.
https://huggingface.co/spaces/RonPisaturo/autotrain-advanced

**Comment by abhishekkrthakur** [comment]
thanks. i was able to identify the issue and fix it. it should work as expected now. please note: you seem to be using cpu for a large model, it might not alwways work. please factory rebuild your autotrain space and make sure you are on version: 0.7.129+

**Comment by RonPisaturo** [comment]
Thank you so much!  was able to fine-tune a small Microsoft model and gpt2 using T4 small. Now I will try to fine-tune Mistral-7B-Instruct-v0.3 using T4 medium.
Thank you again!
