### ISSUE TITLE
Bug or Download Manipulation of Model

### ISSUE THREAD

**Issue by Necentt** [huggingface/autotrain-advanced#689]
As the author of the model, I am concerned about the unusual download activity observed. The download count is very high, the download graph is erratic, and most importantly, there are many downloads but no corresponding likes or discussions in the community.

https://huggingface.co/Necent/distilbert-base-uncased-detected-jailbreak

**Comment by abhishekkrthakur** [comment]
if you dont want the model to be downloaded, you can make it "private". 
Also, this doesnt seem like an issue related to AutoTrain. Please email: website@huggingface.co if you have concerns.
