### ISSUE TITLE
[FEATURE REQUEST] Allow us to save our models locally

### ISSUE THREAD

**Issue by BovineOverlord** [huggingface/autotrain-advanced#701]
### Feature Request

Right now we're forced to save our models onto HF. I want to be 100% local. Please let us save models locally.

### Motivation

Open-source should always strive to be 100% local. As it currently is, autotrain is dependent on HF to operate.

**Comment by abhishekkrthakur** [comment]
No one is forcing you to do anything. :D

You can just use "autotrain config" command to train and set push_to_hub to false.

**Comment by BovineOverlord** [comment]
Ah I was not aware of that. Where is the default location of the config.yaml anyways? I'm unable to find it.

**Comment by BovineOverlord** [comment]
This is what I get when running that command-
C:\Users\Bob>autotrain config
usage: autotrain <command> [<args>]
AutoTrain advanced CLI: error: argument {app,llm,setup,dreambooth,api,text-classification,image-classification,tabular,spacerunner,seq2seq,token-classification,tools,text-regression,object-detection,sentence-transformers,image-regression}: invalid choice: 'config' (choose from 'app', 'llm', 'setup', 'dreambooth', 'api', 'text-classification', 'image-classification', 'tabular', 'spacerunner', 'seq2seq', 'token-classification', 'tools', 'text-regression', 'object-detection', 'sentence-transformers', 'image-regression')

**Comment by BovineOverlord** [comment]
That command does not work, as I do not know what the path to config is. It's why I asked for the default location; I'm unable to find it.

**Comment by abhishekkrthakur** [comment]
you are probably using a **very very old** version of autotrain. please update to the latest pypi release: https://pypi.org/project/autotrain-advanced/

**Comment by BovineOverlord** [comment]
I again ran the pip install autotune-advanced command and it says everything is already installed; I am using the current version.

**Comment by abhishekkrthakur** [comment]
what is the version? what does `autotrain --version` command say?

**Comment by BovineOverlord** [comment]
0.8.3.
C:\Users\Bob\Desktop>autotrain --version
0.8.3

I'm thinking the conf is not being generated? I can create one manually if you direct me to the correct directory.

**Comment by abhishekkrthakur** [comment]
I just tried it and seems to be working fine.

```

❯ autotrain --help
usage: autotrain <command> [<args>]

positional arguments:
  {app,llm,setup,dreambooth,api,text-classification,image-classification,tabular,spacerunner,seq2seq,token-classification,tools,text-regression,object-detection,sentence-transformers,image-regression}
                        commands
    tools               Run AutoTrain tools

options:
  -h, --help            show this help message and exit
  --version, -v         Display AutoTrain version
  --config CONFIG       Optional configuration file

For more information about a command, run: `autotrain <command> --help`
```

as you can see `--config` exists.

You need to create a config.yml, for example: my_config.yml and then use the command `autotrain --config my_config.yml` . The model will be stored in the project-name specified in the config, like here: https://github.com/huggingface/autotrain-advanced/blob/main/configs/llm_finetuning/gpt2_sft.yml#L3.

**Comment by BovineOverlord** [comment]
I'm not saying the --config command does not exist- it does. I mean the file itself.

Even after creating it and placing in what I believe is the main directory (C:\Program Files\Python310\Lib\site-packages\autotrain), this is what I get when running "autotrain --config my_config.yml"-
FileNotFoundError: [Errno 2] No such file or directory: 'my_config.yml'

**Comment by abhishekkrthakur** [comment]
for the command you provided, your config yaml should be in the same directory as where you are running the autotrain command. it just seems like you are providing wrong path to the command.

**Comment by BovineOverlord** [comment]
I cd to the directory;
C:\Program Files\Python310\Lib\site-packages\autotrain>autotrain --config my_config.yml
INFO     | 2024-07-15 15:35:04 | autotrain.cli.autotrain:main:58 - Using AutoTrain configuration: my_config.yml
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python310\Scripts\autotrain.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Program Files\Python310\lib\site-packages\autotrain\cli\autotrain.py", line 59, in main
    cp = AutoTrainConfigParser(args.config)
  File "<string>", line 4, in __init__
  File "C:\Program Files\Python310\lib\site-packages\autotrain\parser.py", line 123, in __post_init__
    task = self.config.get("task")
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by abhishekkrthakur** [comment]
please see the example configs here: https://github.com/huggingface/autotrain-advanced/tree/main/configs
