### ISSUE TITLE
maybe problem with token

### ISSUE THREAD

**Issue by Aluminary** [huggingface/autotrain-advanced#702]
I have never used hugging face but I have found a token it looks like on google I will be pasting the link and if you don't trust me then put it through something. also please make a report problem button somewhere instead of out sourcing to git or don't i don't even know how you guys work. here it is https://huggingface.co/HuggingFaceH4/starchat-beta/commit/4d8424c69643590f193cc97dc7eebff66500ebc6.diff?file=tokenizer.json i hope i didn't waste your time if i did i am sorry.

**Comment by abhishekkrthakur** [comment]
im not sure if i fully understand your concern. could you please make sure its related to autotrain and elaborate? if your issue is related to website or something else, you can post here: https://discuss.huggingface.co/
