### ISSUE TITLE
[FEATURE REQUEST] Add support for multi label text classification.

### ISSUE THREAD

**Issue by Susmigo** [huggingface/autotrain-advanced#703]
### Feature Request

Hi There,

I have gone through the documention https://huggingface.co/docs/autotrain/text_classification. I could not find anything about multi label text classification. Please provide support on this.

Thanks :)

### Motivation

Multi Label classification

**Comment by Susmigo** [comment]
@abhishekkrthakur, Could you please provide any suggestions on this?

Thanks : )

**Comment by josephrocca** [comment]
@abhishekkrthakur This would be useful for me too. Any chance this feature request could be re-opened? My use case is classifying a paragraph of text with several tags.

**Comment by paneru-rajan** [comment]
I spend quite some time and realized it does not support multi label text classification. My usecase is exactly same as @josephrocca .
