### ISSUE TITLE
Concerning sequence to sequence task using autotrain 

### ISSUE THREAD

**Issue by qipotianMFXT** [huggingface/autotrain-advanced#711]
### Feature Request

"Hello, does `autotrain --config <path_to_config_file>` currently support sequence-to-sequence tasks?"

### Motivation

autotrain --config <path_to_config_file>  supports sequence-to-sequence tasks

**Comment by tombenj** [comment]
seq2seq simply doesn't work with autotrain. all params are hard coded and.

**Comment by abhishekkrthakur** [comment]
would you mind elaborating? it should not be the case. if it is, ill fix it asap.
