### ISSUE TITLE
[FEATURE REQUEST] Documentation for VLM data

### ISSUE THREAD

**Issue by zoeleu** [huggingface/autotrain-advanced#716]
### Feature Request

Information about how to train VLMs just like is available for the other types of models.

### Motivation

Wanting to know what to upload

**Comment by zoeleu** [comment]
Still an issue.

**Comment by abhishekkrthakur** [comment]
walkthroughs in the docs doesnt work?

**Comment by zoeleu** [comment]
Sorry, I am not finding info on this. Is it here? https://huggingface.co/docs/autotrain/index

**Comment by abhishekkrthakur** [comment]
yes. second point

![image](https://github.com/user-attachments/assets/ca146170-1ffd-4d60-ad2d-553e1cd1154e)

**Comment by zoeleu** [comment]
Yes, that works. I still think VLM data should be added here:
![image](https://github.com/user-attachments/assets/2189fee0-f93d-4fa1-a4ff-4db9ba543f59)

**Comment by abhishekkrthakur** [comment]
surely, we are improving vlm at the moment. more updates will follow after we add support for more vlms :)
