### ISSUE TITLE
Args' object has no attribute 'prior_loss_weight - [BUG]

### ISSUE THREAD

**Issue by m-nameer** [huggingface/autotrain-advanced#724]
### Prerequisites

- [X] I have read the [documentation](https://hf.co/docs/autotrain).
- [X] I have checked other issues for similar problems.

### Backend

Local

### Interface Used

CLI

### Error Logs

ERROR    | 2024-08-08 09:15:21 | autotrain.trainers.common:wrapper:120 - train has failed due to an exception: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/common.py", line 117, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/dreambooth/__main__.py", line 185, in train
    main(_args)
  File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/dreambooth/train.py", line 876, in main
    loss = loss + args.prior_loss_weight * prior_loss
AttributeError: 'Args' object has no attribute 'prior_loss_weight'

ERROR    | 2024-08-08 09:15:21 | autotrain.trainers.common:wrapper:121 - 'Args' object has no attribute 'prior_loss_weight'
Steps:   0% 0/500 [00:00<?, ?it/s]
INFO     | 2024-08-08 09:15:24 | autotrain.cli.run_dreambooth:run:393 - Job ID: 8705

**Comment by abhishekkrthakur** [comment]
please make sure you have the correct version of everything (including diffusers) from https://github.com/huggingface/autotrain-advanced/blob/main/requirements.txt
