### ISSUE TITLE
Billing

### ISSUE THREAD

**Issue by Robert-Nemec** [huggingface/autotrain-advanced#725]
Hello guys,

This appears to be a technical error. Can you please give me the specific detailed AI video creation history and explain? i have had 1 short 8 second and 1 14 second video created and it didn't take long in each case, of course i pay the fees for that. but at the beginning the https://huggingface. co/spaces/fudan-generative-ai/hallo generator hung up several times, it turned a "work in progress" wheel but it hung up several times in a row and didn't finish, so I canceled it after 20 minutes each time and reloaded the page without getting any results and without any indication that something was going on in the background. for these technical problems and the seemingly unfathomable time on the invoice of 1349 minutes, I would like to be reimbursed and will not pay. as mentioned, can you give me a list of the 2 successful videos and how long they took and then correct the invoice? thank you. 

Yours sincerely Tilbury 

Anfang der weitergeleiteten Nachricht:

Von: huggingface <[website_at_huggingface_co_tnjs47cbnzxg2a_f9tz8784@icloud.com](mailto:website_at_huggingface_co_tnjs47cbnzxg2a_f9tz8784@icloud.com)>
Betreff: [Hugging Face] Service termination notice
Datum: 7. August 2024 um 08:02:18 MESZ
An: Hide My Email <[tilbury.plaid_0z@icloud.com](mailto:tilbury.plaid_0z@icloud.com)>
Antwort an: [website_at_huggingface_co_tnjs47cbnzxg2a_f9tz8784@icloud.com](mailto:website_at_huggingface_co_tnjs47cbnzxg2a_f9tz8784@icloud.com)

Hello plain,

Your [invoice for period 2024-07-01 - 2024-07-31](https://huggingface.co/settings/billing/invoice/in_1PjwGFHOZE5QsVPNDJqbz1jq), due August 7th, 2024, remains unpaid.

Consequently, your access to all Hugging Face paid services will be terminated immediately.

To resume service, please proceed to the payment of all due amounts. If needed, you can update your payment method by clicking [here](https://huggingface.co/settings/billing/payment).

The Hugging Face team

Hugging Face: The AI community building the future.

**Comment by abhishekkrthakur** [comment]
please email billing@huggingface.co for billing issues.
