### ISSUE TITLE
[BUG]"GET /ui/ HTTP/1.1" 401 Unauthorized

### ISSUE THREAD

**Issue by zhouyiqing0304** [huggingface/autotrain-advanced#726]
### Prerequisites

- [X] I have read the [documentation](https://hf.co/docs/autotrain).
- [X] I have checked other issues for similar problems.

### Backend

Local

### Interface Used

UI

### CLI Command

run 
    autotrain app --port 8080 --host 127.0.0.1
then open http://127.0.0.1:8080/ui/ in my browser

### Error Logs

![image](https://github.com/user-attachments/assets/f016d9e7-95bc-4bbe-ab9a-d68d2b48efec)

**Comment by zhouyiqing0304** [comment]
@abhishekkrthakur 
run on local
{
    "detail": "Invalid or expired token"
}

**Comment by abhishekkrthakur** [comment]
Are you exporting HF_TOKEN env var?

**Comment by zhouyiqing0304** [comment]
?

**Comment by zhouyiqing0304** [comment]
> 您是否正在导出 HF_TOKEN 环境 var？
how to use HF_TOKEN

**Comment by zhouyiqing0304** [comment]
using windows
@abhishekkrthakur

**Comment by zhouyiqing0304** [comment]
![image](https://github.com/user-attachments/assets/46a5ec69-f56f-4fd4-8b09-07210cfb6269)

**Comment by nekohacker591** [comment]
how to solve HF_TOKEN?

**Comment by kstyagi23** [comment]
@nekohacker591 for Linux / Mac you can simply do:
`export HF_TOKEN=your_huggingface_access_token`

For windows (Powershell): `cmd HF_TOKEN=access_token`
(cmd): `$env:HF_TOKEN = "access_token"`


Make sure your access token has write permissions.

**Comment by miningnome** [comment]
For CMD in Windows:

set HF_USERNAME=<your_hugging_face_username>
set HF_TOKEN=<your_hugging_face_write_token>
