### ISSUE TITLE
Zero gpu driver issue

### ISSUE THREAD

**Issue by ashlksandeepa** [huggingface/autotrain-advanced#727]
I am keep getting runtime error when starting my space. This was working fine before but since two weeks non of my spaces are working. It keep saying “RuntimeError: CUDA has been initialized before importing the `spaces` package”
Can you please help me to fix this
![IMG_9377](https://github.com/user-attachments/assets/4f8c2464-ce21-4b7b-b9c9-82ecdc7f3c99)

**Comment by abhishekkrthakur** [comment]
it doesnt seem like autotrain issue
