### ISSUE TITLE
[BUG] lora files inert / don't work with fooocus, only kohya version do but they are limited

### ISSUE THREAD

**Issue by YuPete** [huggingface/autotrain-advanced#730]
### Prerequisites

- [X] I have read the [documentation](https://hf.co/docs/autotrain).
- [X] I have checked other issues for similar problems.

### Backend

Colab

### Interface Used

CLI

### UI Screenshots & Parameters

![Screenshot 2024-08-14 at 11 19 10 PM](https://github.com/user-attachments/assets/b024eb64-1d2e-41f4-ab67-3b6570542862)

### Error Logs

Only the kohya versions work as when I select the normal safetensor file, my face does not appear in the resulting image even with the same prompt. I am running sdxl on fooocus on colab and while the default kohya version is ok, I’d like to increase the steps and get a better model. However, it seems like anything past 500 steps only produces the normal .safetensor model and the kohya model does not accompany it. Any way to enable kohya for more steps

**Comment by abhishekkrthakur** [comment]
> However, it seems like anything past 500 steps only produces the normal .safetensor model and the kohya model does not accompany it

do you have any error logs?


Also, if it doesnt generate kohya, you can do so after the training finishes using `autotrain tools convert_to_kohya` command:

```
❯ autotrain tools convert_to_kohya --help
usage: autotrain <command> [<args>] tools convert_to_kohya [-h] [--input-path INPUT_PATH] [--output-path OUTPUT_PATH]

options:
  -h, --help            show this help message and exit
  --input-path INPUT_PATH
                        Input path
  --output-path OUTPUT_PATH
                        Output path
```

**Comment by YuPete** [comment]
Hi abhishek, 

I didn't record any of the error log but your fix has worked! Thank you so much for responding, you are a life saver!

Peter
