### ISSUE TITLE
[BUG] Flux Dev training against license.

### ISSUE THREAD

**Issue by yumlevi** [huggingface/autotrain-advanced#745]
### Prerequisites

- [X] I have read the [documentation](https://hf.co/docs/autotrain).
- [X] I have checked other issues for similar problems.

### Backend

Hugging Face Space/Endpoints

### Interface Used

CLI

### Error Logs

https://huggingface.co/spaces/autotrain-projects/train-flux-lora-ease

You can't offer training when money exchanges hands.

**Comment by abhishekkrthakur** [comment]
ill be closing this issue as its being discussed internally :)
