### ISSUE TITLE
[BUG] I am using 2 nodes of 4 GPUs each, (total 8GPUs), but num_machines is always set to 1.

### ISSUE THREAD

**Issue by jackswl** [huggingface/autotrain-advanced#748]
### Prerequisites

- [X] I have read the [documentation](https://hf.co/docs/autotrain).
- [X] I have checked other issues for similar problems.

### Backend

Local

### Interface Used

CLI

### CLI Command

```
autotrain --config /home/xxx
```

### Error Logs

I am trying to execute with 2 nodes of 4 GPUs each, via 
```
#PBS -l select=2:ncpus=128:ngpus=4:mem=880GB
```
However, the accelerate launch is always showing num_machines=1 when executing the CLI command:
```
autotrain --config /home/xxx
```

@abhishekkrthakur any idea on how to work on this? Am I right to say that autotrain does not support multi-nodes? How to work around this?
Thanks!

**Comment by abhishekkrthakur** [comment]
autotrain doesnt support multi-node, yet.

**Comment by jackswl** [comment]
thanks for the reply. 

BTW, do you happen to have a rough timeline of when autotrain will allow multi-node usage? 
just asking so I can know roughly when to get back to this topic when multi-node is out! 
thanks a lot.
