### ISSUE TITLE
Can AutoTrain be used on CPU alone?

### ISSUE THREAD

**Issue by apple-1** [huggingface/autotrain-advanced#754]
I tried to run autotrain without a gpu and got this error:

RuntimeError: No GPU found. A GPU is needed for quantization.

Can I turn quantization off and use it only on CPU for smaller training tasks?

**Comment by abhishekkrthakur** [comment]
yes. turn quantization and othet related stuff which need gpu and you can use it on cpu

**Comment by apple-1** [comment]
Okay, thanks!

One more thing - Where can I specify a different directory (other than
Anaconda cache on C), where the model can be downloaded? I don't have much
space on C drive.

**Comment by abhishekkrthakur** [comment]
https://stackoverflow.com/questions/63312859/how-to-change-huggingface-transformers-default-cache-directory
