### ISSUE TITLE
[BUG] Valid split autoset to None for LLM training

### ISSUE THREAD

**Issue by rhingo** [huggingface/autotrain-advanced#758]
### Prerequisites

- [X] I have read the [documentation](https://hf.co/docs/autotrain).
- [X] I have checked other issues for similar problems.

### Backend

Local

### Interface Used

CLI

### CLI Command

```autotrain --config <path_to_config.yml>```

### Error Logs

Not necessarily an error, but I noticed that for the LLM training task, in the `llm_munge_data` function in `autotrain.cli.utils.py` the `params.valid_split` by default is set to None. This overrides any user specified validation split in the yaml config file. For the other "munge_data" functions it looks like the default for `params.valid_split = "validation"`. Can this please be fixed to allow the user to specify a validation split?

**Comment by abhishekkrthakur** [comment]
this has been discussed several times :) opening duplicate issues isnt going to solve it faster
