### ISSUE TITLE
401 unauthorized 

### ISSUE THREAD

**Issue by Esmail-ibraheem** [huggingface/autotrain-advanced#763]
### Prerequisites

- [X] I have read the [documentation](https://hf.co/docs/autotrain).
- [X] I have checked other issues for similar problems.

### Backend

Local

### Interface Used

UI

### CLI Command

app --port 8081 --host 0.0.0.0

### UI Screenshots & Parameters

  warnings.warn(msg, RuntimeWarning)
INFO     | 2024-09-14 09:36:40 | autotrain.app.ui_routes:<module>:32 - Starting AutoTrain...
INFO     | 2024-09-14 09:36:53 | autotrain.app.ui_routes:<module>:294 - AutoTrain started successfully
INFO     | 2024-09-14 09:36:53 | autotrain.app.app:<module>:13 - Starting AutoTrain...
INFO     | 2024-09-14 09:36:53 | autotrain.app.app:<module>:23 - AutoTrain version: 0.8.9
INFO     | 2024-09-14 09:36:53 | autotrain.app.app:<module>:24 - AutoTrain started successfully
INFO:     Started server process [36640]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://192.168.20.172:8081 (Press CTRL+C to quit)
INFO:     192.168.20.172:65436 - "GET / HTTP/1.1" 307 Temporary Redirect
INFO:     192.168.20.172:65436 - "GET /ui/ HTTP/1.1" 401 Unauthorized

### Error Logs

  warnings.warn(msg, RuntimeWarning)
INFO     | 2024-09-14 09:36:40 | autotrain.app.ui_routes:<module>:32 - Starting AutoTrain...
INFO     | 2024-09-14 09:36:53 | autotrain.app.ui_routes:<module>:294 - AutoTrain started successfully
INFO     | 2024-09-14 09:36:53 | autotrain.app.app:<module>:13 - Starting AutoTrain...
INFO     | 2024-09-14 09:36:53 | autotrain.app.app:<module>:23 - AutoTrain version: 0.8.9
INFO     | 2024-09-14 09:36:53 | autotrain.app.app:<module>:24 - AutoTrain started successfully
INFO:     Started server process [36640]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://192.168.20.172:8081 (Press CTRL+C to quit)
INFO:     192.168.20.172:65436 - "GET / HTTP/1.1" 307 Temporary Redirect
INFO:     192.168.20.172:65436 - "GET /ui/ HTTP/1.1" 401 Unauthorized

**Comment by abhishekkrthakur** [comment]
you need to export your HF_TOKEN : https://huggingface.co/docs/autotrain/quickstart#running-autotrain-user-interface-ui

**Comment by Esmail-ibraheem** [comment]
ok but i want use autotrain in different port not 8080 i want it for example in 8081
