### ISSUE TITLE
Constatnly getting error 404. And the docs are far from being useful.

### ISSUE THREAD

**Issue by venturaEffect** [huggingface/autotrain-advanced#768]
I'm trying everything. This is already, I don't know how many times I tried autotrain. From the very first time it was released til now. So many errors. Unbelievable.

Now, trying it again. Created a space, created a script.py with my custom model, a config.yaml (btw, the documentation is very poor and the example doesn't show much plus the link it sends to get more info is just a generic github repo not providing info for the configuration. Are you serious?)

Also to get information for setting the column mapping is very basic and if needed to set it as chat template it tells look at LLM Parameters Section. I've searched everywhere and there is no place where it talks for the chat template settings when it is a conversation. Is this really democratising ML as Hugging Face says? Really? Or is it just to burn GPUs and ask for expert support?

After changing the GPU tried on my local machine. As always awq is a pain in the ass for Windows users. So went back to the Space and changed the GPU to T4. Put the JSON Dataset on HuggingFace tried link it, making it public, tried from local files, changed the JSON to be just "text" format on the JSON holding question-response as it is a chat format and well, maybe it is wrong but there is no explanation and the links provided aren't any good resource. Come on!

When always clicking on Start Training I get: Error: 400

Please check the logs for more information.

So I go to logs: And there is just: 

INFO     | 2024-09-19 03:51:59 | autotrain.app.ui_routes:handle_form:500 - hardware: local-ui
INFO:     10.16.18.75:51854 - "POST /ui/create_project HTTP/1.1" 400 Bad Request

Is it really ok to just get this info to know what is wrong? Look at the logs. Well even looking there is no info enough to understand what is the issue.

I'm really surprised of how it is possible to make it work. No, for real, this is not democratizing and it is far well explained to not have to ask for support. Maybe there is something pretty basic but there is no way to find what is wrong.

Would appreciate any support as I've tried autotrain MANY times.

**Comment by GunaAlexander** [comment]
me too

**Comment by abhishekkrthakur** [comment]
could you try deleting your cache and try again? could you try using chrome instead?

**Comment by abhishekkrthakur** [comment]
if everything fails, you can always follow the instructions for alternative way to use AutoTrain Space which is written in the login screen:

<img width="585" alt="image" src="https://github.com/user-attachments/assets/ba900270-50d1-4a30-9e25-0562a1e3a03f">
