### ISSUE TITLE
[BUG] Can't Push LLM Model to Hub

### ISSUE THREAD

**Issue by allandclive** [huggingface/autotrain-advanced#769]
### Prerequisites

- [X] I have read the [documentation](https://hf.co/docs/autotrain).
- [X] I have checked other issues for similar problems.

### Backend

Colab

### Interface Used

UI

### UI Screenshots & Parameters

![brave_screenshot_colab research google com (12)](https://github.com/user-attachments/assets/77f1fe8e-6e03-48c1-bbcb-290b52c7eb60)

### Error Logs

`Training is starting... Please wait!
INFO     | 2024-09-19 08:24:08 | autotrain.cli.autotrain:main:60 - Using AutoTrain configuration: config.yml
INFO     | 2024-09-19 08:24:08 | autotrain.parser:__post_init__:148 - Running task: lm_training
INFO     | 2024-09-19 08:24:08 | autotrain.parser:__post_init__:149 - Using backend: local
WARNING  | 2024-09-19 08:24:08 | autotrain.trainers.common:__init__:180 - Parameters supplied but not used: input, instruction, output
INFO     | 2024-09-19 08:24:08 | autotrain.parser:run:212 - {'model': 'Qwen/Qwen2.5-0.5B-Instruct', 'project_name': 'autotrain-97886-5s45p', 'data_path': 'saillab/alpaca_luganda_taco', 'train_split': 'train', 'valid_split': None, 'add_eos_token': True, 'block_size': 1024, 'model_max_length': 2048, 'padding': 'right', 'trainer': 'default', 'use_flash_attention_2': False, 'log': 'tensorboard', 'disable_gradient_checkpointing': False, 'logging_steps': -1, 'eval_strategy': 'epoch', 'save_total_limit': 1, 'auto_find_batch_size': False, 'mixed_precision': 'fp16', 'lr': 3e-05, 'epochs': 3, 'batch_size': 2, 'warmup_ratio': 0.1, 'gradient_accumulation': 4, 'optimizer': 'adamw_torch', 'scheduler': 'linear', 'weight_decay': 0.0, 'max_grad_norm': 1.0, 'seed': 42, 'chat_template': None, 'quantization': 'int4', 'target_modules': 'all-linear', 'merge_adapter': False, 'peft': True, 'lora_r': 16, 'lora_alpha': 32, 'lora_dropout': 0.05, 'model_ref': None, 'dpo_beta': 0.1, 'max_prompt_length': 128, 'max_completion_length': None, 'prompt_text_column': None, 'text_column': 'text', 'rejected_text_column': None, 'push_to_hub': True, 'username': None, 'token': None, 'unsloth': False}
INFO     | 2024-09-19 08:24:08 | autotrain.backends.local:create:8 - Starting local training...
INFO     | 2024-09-19 08:24:08 | autotrain.commands:launch_command:489 - ['accelerate', 'launch', '--num_machines', '1', '--num_processes', '1', '--mixed_precision', 'fp16', '-m', 'autotrain.trainers.clm', '--training_config', 'autotrain-97886-5s45p/training_params.json']
INFO     | 2024-09-19 08:24:08 | autotrain.commands:launch_command:490 - {'model': 'Qwen/Qwen2.5-0.5B-Instruct', 'project_name': 'autotrain-97886-5s45p', 'data_path': 'saillab/alpaca_luganda_taco', 'train_split': 'train', 'valid_split': None, 'add_eos_token': True, 'block_size': 1024, 'model_max_length': 2048, 'padding': 'right', 'trainer': 'default', 'use_flash_attention_2': False, 'log': 'tensorboard', 'disable_gradient_checkpointing': False, 'logging_steps': -1, 'eval_strategy': 'epoch', 'save_total_limit': 1, 'auto_find_batch_size': False, 'mixed_precision': 'fp16', 'lr': 3e-05, 'epochs': 3, 'batch_size': 2, 'warmup_ratio': 0.1, 'gradient_accumulation': 4, 'optimizer': 'adamw_torch', 'scheduler': 'linear', 'weight_decay': 0.0, 'max_grad_norm': 1.0, 'seed': 42, 'chat_template': None, 'quantization': 'int4', 'target_modules': 'all-linear', 'merge_adapter': False, 'peft': True, 'lora_r': 16, 'lora_alpha': 32, 'lora_dropout': 0.05, 'model_ref': None, 'dpo_beta': 0.1, 'max_prompt_length': 128, 'max_completion_length': None, 'prompt_text_column': None, 'text_column': 'text', 'rejected_text_column': None, 'push_to_hub': True, 'username': None, 'token': None, 'unsloth': False}
The following values were not passed to `accelerate launch` and had defaults used instead:
`--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
INFO     | 2024-09-19 08:24:20 | autotrain.trainers.clm.train_clm_default:train:26 - Starting default/generic CLM training...

Downloading readme:   0%|          | 0.00/542 [00:00<?, ?B/s]
Downloading readme: 100%|██████████| 542/542 [00:00<00:00, 2.14MB/s]

Downloading data:   0%|          | 0.00/91.6M [00:00<?, ?B/s]
Downloading data:  11%|█▏        | 10.5M/91.6M [00:00<00:03, 25.4MB/s]
Downloading data:  46%|████▌     | 41.9M/91.6M [00:00<00:00, 92.6MB/s]
Downloading data:  80%|████████  | 73.4M/91.6M [00:00<00:00, 145MB/s]
Downloading data: 100%|██████████| 91.6M/91.6M [00:00<00:00, 126MB/s]

Downloading data:   0%|          | 0.00/22.6M [00:00<?, ?B/s]
Downloading data:  46%|████▋     | 10.5M/22.6M [00:00<00:00, 27.7MB/s]
Downloading data: 100%|██████████| 22.6M/22.6M [00:00<00:00, 49.7MB/s]

Generating train split:   0%|          | 0/49601 [00:00<?, ? examples/s]
Generating train split:  10%|█         | 5000/49601 [00:00<00:01, 43799.89 examples/s]
Generating train split:  24%|██▍       | 12000/49601 [00:00<00:00, 54561.97 examples/s]
Generating train split:  38%|███▊      | 19000/49601 [00:00<00:00, 58766.73 examples/s]
Generating train split:  52%|█████▏    | 26000/49601 [00:00<00:00, 58497.63 examples/s]
Generating train split:  65%|██████▍   | 32000/49601 [00:00<00:00, 56329.54 examples/s]
Generating train split:  79%|███████▊  | 39000/49601 [00:00<00:00, 56915.91 examples/s]
Generating train split:  95%|█████████▍| 47000/49601 [00:00<00:00, 58023.71 examples/s]
Generating train split: 100%|██████████| 49601/49601 [00:00<00:00, 56634.02 examples/s]

Generating test split:   0%|          | 0/12401 [00:00<?, ? examples/s]
Generating test split:  56%|█████▋    | 7000/12401 [00:00<00:00, 62401.97 examples/s]
Generating test split: 100%|██████████| 12401/12401 [00:00<00:00, 61162.21 examples/s]
INFO     | 2024-09-19 08:24:29 | autotrain.trainers.clm.utils:process_input_data:398 - Train data: Dataset({
features: ['instruction', 'input', 'output', 'id', 'text'],
num_rows: 49601
})
INFO     | 2024-09-19 08:24:29 | autotrain.trainers.clm.utils:process_input_data:399 - Valid data: None
INFO     | 2024-09-19 08:24:36 | autotrain.trainers.clm.utils:configure_logging_steps:471 - configuring logging steps
INFO     | 2024-09-19 08:24:36 | autotrain.trainers.clm.utils:configure_logging_steps:484 - Logging steps: 25
INFO     | 2024-09-19 08:24:36 | autotrain.trainers.clm.utils:configure_training_args:489 - configuring training args
INFO     | 2024-09-19 08:24:36 | autotrain.trainers.clm.utils:configure_block_size:552 - Using block size 1024
INFO     | 2024-09-19 08:24:37 | autotrain.trainers.clm.utils:get_model:587 - Can use unsloth: False
WARNING  | 2024-09-19 08:24:37 | autotrain.trainers.clm.utils:get_model:629 - Unsloth not available, continuing without it...
INFO     | 2024-09-19 08:24:37 | autotrain.trainers.clm.utils:get_model:631 - loading model config...
INFO     | 2024-09-19 08:24:37 | autotrain.trainers.clm.utils:get_model:639 - loading model...
`low_cpu_mem_usage` was None, now set to True since model is quantized.
INFO     | 2024-09-19 08:24:47 | autotrain.trainers.clm.utils:get_model:670 - model dtype: torch.float16
INFO     | 2024-09-19 08:24:47 | autotrain.trainers.clm.utils:get_model:677 - preparing peft model...

Running tokenizer on train dataset:   0%|          | 0/49601 [00:00<?, ? examples/s]
Running tokenizer on train dataset:   2%|▏         | 1000/49601 [00:01<01:11, 678.47 examples/s]
Running tokenizer on train dataset:   4%|▍         | 2000/49601 [00:02<01:10, 674.32 examples/s]Token indices sequence length is longer than the specified maximum sequence length for this model (2066 > 2048). Running this sequence through the model will result in indexing errors

Running tokenizer on train dataset:   6%|▌         | 3000/49601 [00:04<01:08, 679.98 examples/s]
Running tokenizer on train dataset:   8%|▊         | 4000/49601 [00:05<01:08, 670.47 examples/s]
Running tokenizer on train dataset:  10%|█         | 5000/49601 [00:07<01:06, 671.21 examples/s]
Running tokenizer on train dataset:  12%|█▏        | 6000/49601 [00:08<01:04, 675.32 examples/s]
Running tokenizer on train dataset:  14%|█▍        | 7000/49601 [00:11<01:14, 571.86 examples/s]
Running tokenizer on train dataset:  16%|█▌        | 8000/49601 [00:13<01:20, 519.66 examples/s]
Running tokenizer on train dataset:  18%|█▊        | 9000/49601 [00:14<01:12, 562.22 examples/s]
Running tokenizer on train dataset:  20%|██        | 10000/49601 [00:16<01:06, 596.60 examples/s]
Running tokenizer on train dataset:  22%|██▏       | 11000/49601 [00:17<01:01, 627.57 examples/s]
Running tokenizer on train dataset:  24%|██▍       | 12000/49601 [00:19<00:58, 638.66 examples/s]
Running tokenizer on train dataset:  26%|██▌       | 13000/49601 [00:20<00:56, 652.08 examples/s]
Running tokenizer on train dataset:  28%|██▊       | 14000/49601 [00:22<00:54, 656.88 examples/s]
Running tokenizer on train dataset:  30%|███       | 15000/49601 [00:24<00:55, 622.44 examples/s]
Running tokenizer on train dataset:  32%|███▏      | 16000/49601 [00:26<01:02, 535.97 examples/s]
Running tokenizer on train dataset:  34%|███▍      | 17000/49601 [00:29<01:08, 476.05 examples/s]
Running tokenizer on train dataset:  36%|███▋      | 18000/49601 [00:31<01:09, 453.88 examples/s]
Running tokenizer on train dataset:  38%|███▊      | 19000/49601 [00:33<01:01, 501.60 examples/s]
Running tokenizer on train dataset:  40%|████      | 20000/49601 [00:34<00:54, 545.19 examples/s]
Running tokenizer on train dataset:  42%|████▏     | 21000/49601 [00:36<00:49, 578.46 examples/s]
Running tokenizer on train dataset:  44%|████▍     | 22000/49601 [00:37<00:45, 610.63 examples/s]
Running tokenizer on train dataset:  46%|████▋     | 23000/49601 [00:39<00:46, 566.40 examples/s]
Running tokenizer on train dataset:  48%|████▊     | 24000/49601 [00:42<00:50, 506.92 examples/s]
Running tokenizer on train dataset:  50%|█████     | 25000/49601 [00:43<00:46, 530.80 examples/s]
Running tokenizer on train dataset:  52%|█████▏    | 26000/49601 [00:45<00:41, 570.34 examples/s]
Running tokenizer on train dataset:  54%|█████▍    | 27000/49601 [00:46<00:37, 606.31 examples/s]
Running tokenizer on train dataset:  56%|█████▋    | 28000/49601 [00:47<00:34, 630.86 examples/s]
Running tokenizer on train dataset:  58%|█████▊    | 29000/49601 [00:49<00:31, 646.08 examples/s]
Running tokenizer on train dataset:  60%|██████    | 30000/49601 [00:50<00:29, 660.68 examples/s]
Running tokenizer on train dataset:  62%|██████▏   | 31000/49601 [00:52<00:27, 666.02 examples/s]
Running tokenizer on train dataset:  65%|██████▍   | 32000/49601 [00:54<00:31, 562.84 examples/s]
Running tokenizer on train dataset:  67%|██████▋   | 33000/49601 [00:56<00:31, 531.83 examples/s]
Running tokenizer on train dataset:  69%|██████▊   | 34000/49601 [00:58<00:27, 576.40 examples/s]
Running tokenizer on train dataset:  71%|███████   | 35000/49601 [00:59<00:24, 605.95 examples/s]
Running tokenizer on train dataset:  73%|███████▎  | 36000/49601 [01:01<00:21, 628.18 examples/s]
Running tokenizer on train dataset:  75%|███████▍  | 37000/49601 [01:02<00:19, 639.65 examples/s]
Running tokenizer on train dataset:  77%|███████▋  | 38000/49601 [01:04<00:17, 652.50 examples/s]
Running tokenizer on train dataset:  79%|███████▊  | 39000/49601 [01:05<00:16, 656.04 examples/s]
Running tokenizer on train dataset:  81%|████████  | 40000/49601 [01:07<00:15, 619.35 examples/s]
Running tokenizer on train dataset:  83%|████████▎ | 41000/49601 [01:09<00:15, 539.41 examples/s]
Running tokenizer on train dataset:  85%|████████▍ | 42000/49601 [01:11<00:13, 551.74 examples/s]
Running tokenizer on train dataset:  87%|████████▋ | 43000/49601 [01:13<00:11, 585.59 examples/s]
Running tokenizer on train dataset:  89%|████████▊ | 44000/49601 [01:14<00:09, 607.44 examples/s]
Running tokenizer on train dataset:  91%|█████████ | 45000/49601 [01:16<00:07, 628.74 examples/s]
Running tokenizer on train dataset:  93%|█████████▎| 46000/49601 [01:17<00:05, 627.98 examples/s]
Running tokenizer on train dataset:  95%|█████████▍| 47000/49601 [01:19<00:03, 652.85 examples/s]
Running tokenizer on train dataset:  97%|█████████▋| 48000/49601 [01:20<00:02, 665.27 examples/s]
Running tokenizer on train dataset:  99%|█████████▉| 49000/49601 [01:22<00:01, 555.87 examples/s]
Running tokenizer on train dataset: 100%|██████████| 49601/49601 [01:24<00:00, 515.23 examples/s]
Running tokenizer on train dataset: 100%|██████████| 49601/49601 [01:24<00:00, 587.26 examples/s]
/usr/local/lib/python3.10/dist-packages/multiprocess/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
self.pid = os.fork()

Grouping texts in chunks of 1024 (num_proc=4):   0%|          | 0/49601 [00:00<?, ? examples/s]
Grouping texts in chunks of 1024 (num_proc=4):   2%|▏         | 1000/49601 [00:03<02:38, 307.36 examples/s]
Grouping texts in chunks of 1024 (num_proc=4):   4%|▍         | 2000/49601 [00:04<01:28, 535.62 examples/s]
Grouping texts in chunks of 1024 (num_proc=4):   6%|▌         | 3000/49601 [00:05<01:06, 700.60 examples/s]
Grouping texts in chunks of 1024 (num_proc=4):   8%|▊         | 4000/49601 [00:05<00:50, 898.33 examples/s]
Grouping texts in chunks of 1024 (num_proc=4):  10%|█         | 5000/49601 [00:05<00:36, 1218.72 examples/s]
Grouping texts in chunks of 1024 (num_proc=4):  12%|█▏        | 6000/49601 [00:06<00:37, 1171.51 examples/s]
Grouping texts in chunks of 1024 (num_proc=4):  14%|█▍        | 7000/49601 [00:07<00:37, 1129.76 examples/s]
Grouping texts in chunks of 1024 (num_proc=4):  16%|█▌        | 8000/49601 [00:08<00:34, 1208.21 examples/s]
Grouping texts in chunks of 1024 (num_proc=4):  20%|██        | 10000/49601 [00:09<00:28, 1410.06 examples/s]
Grouping texts in chunks of 1024 (num_proc=4):  22%|██▏       | 11000/49601 [00:11<00:33, 1142.05 examples/s]
Grouping texts in chunks of 1024 (num_proc=4):  24%|██▍       | 12000/49601 [00:12<00:34, 1096.27 examples/s]
Grouping texts in chunks of 1024 (num_proc=4):  26%|██▌       | 13000/49601 [00:12<00:27, 1335.73 examples/s]
Grouping texts in chunks of 1024 (num_proc=4):  28%|██▊       | 14000/49601 [00:14<00:35, 1009.40 examples/s]
Grouping texts in chunks of 1024 (num_proc=4):  30%|███       | 15000/49601 [00:16<00:44, 770.60 examples/s]
Grouping texts in chunks of 1024 (num_proc=4):  32%|███▏      | 16000/49601 [00:17<00:43, 778.61 examples/s]
Grouping texts in chunks of 1024 (num_proc=4):  34%|███▍      | 17000/49601 [00:17<00:32, 1017.95 examples/s]
Grouping texts in chunks of 1024 (num_proc=4):  36%|███▋      | 18000/49601 [00:18<00:32, 965.36 examples/s]
Grouping texts in chunks of 1024 (num_proc=4):  38%|███▊      | 19000/49601 [00:19<00:32, 942.34 examples/s]
Grouping texts in chunks of 1024 (num_proc=4):  40%|████      | 20000/49601 [00:20<00:29, 1002.28 examples/s]
Grouping texts in chunks of 1024 (num_proc=4):  42%|████▏     | 21000/49601 [00:20<00:21, 1350.86 examples/s]
Grouping texts in chunks of 1024 (num_proc=4):  44%|████▍     | 22000/49601 [00:21<00:17, 1539.08 examples/s]
Grouping texts in chunks of 1024 (num_proc=4):  46%|████▋     | 23000/49601 [00:22<00:22, 1202.49 examples/s]
Grouping texts in chunks of 1024 (num_proc=4):  48%|████▊     | 24000/49601 [00:23<00:22, 1143.92 examples/s]
Grouping texts in chunks of 1024 (num_proc=4):  50%|█████     | 25000/49601 [00:23<00:16, 1462.46 examples/s]
Grouping texts in chunks of 1024 (num_proc=4):  52%|█████▏    | 26000/49601 [00:24<00:15, 1547.19 examples/s]
Grouping texts in chunks of 1024 (num_proc=4):  54%|█████▍    | 27000/49601 [00:25<00:17, 1326.29 examples/s]
Grouping texts in chunks of 1024 (num_proc=4):  56%|█████▋    | 28000/49601 [00:26<00:17, 1210.96 examples/s]
Grouping texts in chunks of 1024 (num_proc=4):  58%|█████▊    | 29000/49601 [00:26<00:14, 1394.93 examples/s]
Grouping texts in chunks of 1024 (num_proc=4):  60%|██████    | 30000/49601 [00:26<00:11, 1779.98 examples/s]
Grouping texts in chunks of 1024 (num_proc=4):  62%|██████▏   | 31000/49601 [00:28<00:13, 1354.60 examples/s]
Grouping texts in chunks of 1024 (num_proc=4):  65%|██████▍   | 32000/49601 [00:29<00:15, 1116.71 examples/s]
Grouping texts in chunks of 1024 (num_proc=4):  67%|██████▋   | 33000/49601 [00:30<00:14, 1159.54 examples/s]
Grouping texts in chunks of 1024 (num_proc=4):  69%|██████▊   | 34000/49601 [00:30<00:12, 1281.42 examples/s]
Grouping texts in chunks of 1024 (num_proc=4):  71%|███████   | 35000/49601 [00:32<00:15, 942.24 examples/s]
Grouping texts in chunks of 1024 (num_proc=4):  73%|███████▎  | 36000/49601 [00:34<00:17, 775.98 examples/s]
Grouping texts in chunks of 1024 (num_proc=4):  75%|███████▍  | 37000/49601 [00:35<00:14, 841.53 examples/s]
Grouping texts in chunks of 1024 (num_proc=4):  77%|███████▋  | 38000/49601 [00:36<00:12, 924.74 examples/s]
Grouping texts in chunks of 1024 (num_proc=4):  79%|███████▊  | 39000/49601 [00:37<00:13, 784.74 examples/s]
Grouping texts in chunks of 1024 (num_proc=4):  81%|████████  | 40000/49601 [00:39<00:14, 649.23 examples/s]
Grouping texts in chunks of 1024 (num_proc=4):  85%|████████▍ | 42000/49601 [00:40<00:07, 1057.07 examples/s]
Grouping texts in chunks of 1024 (num_proc=4):  87%|████████▋ | 43000/49601 [00:41<00:05, 1110.89 examples/s]
Grouping texts in chunks of 1024 (num_proc=4):  89%|████████▊ | 44000/49601 [00:42<00:05, 1041.72 examples/s]
Grouping texts in chunks of 1024 (num_proc=4):  91%|█████████ | 45000/49601 [00:42<00:03, 1202.49 examples/s]
Grouping texts in chunks of 1024 (num_proc=4):  93%|█████████▎| 46000/49601 [00:43<00:02, 1312.87 examples/s]
Grouping texts in chunks of 1024 (num_proc=4):  94%|█████████▎| 46401/49601 [00:43<00:02, 1399.39 examples/s]
Grouping texts in chunks of 1024 (num_proc=4):  96%|█████████▌| 47401/49601 [00:43<00:01, 1785.51 examples/s]
Grouping texts in chunks of 1024 (num_proc=4):  96%|█████████▋| 47801/49601 [00:44<00:01, 1305.52 examples/s]
Grouping texts in chunks of 1024 (num_proc=4):  97%|█████████▋| 48201/49601 [00:45<00:01, 1145.95 examples/s]
Grouping texts in chunks of 1024 (num_proc=4):  99%|█████████▉| 49201/49601 [00:45<00:00, 1182.31 examples/s]
Grouping texts in chunks of 1024 (num_proc=4): 100%|██████████| 49601/49601 [00:48<00:00, 484.62 examples/s]
Grouping texts in chunks of 1024 (num_proc=4): 100%|██████████| 49601/49601 [00:52<00:00, 938.25 examples/s]
INFO     | 2024-09-19 08:27:06 | autotrain.trainers.clm.train_clm_default:train:87 - creating trainer
ERROR    | 2024-09-19 08:27:06 | autotrain.trainers.common:wrapper:120 - train has failed due to an exception: Traceback (most recent call last):
File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_errors.py", line 304, in hf_raise_for_status
response.raise_for_status()
File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 1021, in raise_for_status
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://huggingface.co/api/repos/create

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/common.py", line 117, in wrapper
return func(*args, **kwargs)
File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/clm/__main__.py", line 23, in train
train_default(config)
File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/clm/train_clm_default.py", line 88, in train
callbacks = utils.get_callbacks(config)
File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/clm/utils.py", line 558, in get_callbacks
callbacks = [UploadLogs(config=config), LossLoggingCallback(), TrainStartCallback()]
File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/common.py", line 192, in __init__
self.api.create_repo(
File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
return fn(*args, **kwargs)
File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/hf_api.py", line 3256, in create_repo
hf_raise_for_status(r)
File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_errors.py", line 367, in hf_raise_for_status
raise HfHubHTTPError(message, response=response) from e
huggingface_hub.utils._errors.HfHubHTTPError:  (Request ID: Root=1-66ebe05a-40b4fae6096332c669829e2c;e21feeee-8f21-4912-93e8-677ca12f8b28)

403 Forbidden: You don't have the rights to create a model under the namespace "None".
Cannot access content at: https://huggingface.co/api/repos/create.
If you are trying to create or update content,make sure you have a token with the `write` role.

ERROR    | 2024-09-19 08:27:06 | autotrain.trainers.common:wrapper:121 -  (Request ID: Root=1-66ebe05a-40b4fae6096332c669829e2c;e21feeee-8f21-4912-93e8-677ca12f8b28)

403 Forbidden: You don't have the rights to create a model under the namespace "None".
Cannot access content at: https://huggingface.co/api/repos/create.
If you are trying to create or update content,make sure you have a token with the `write` role.
INFO     | 2024-09-19 08:27:10 | autotrain.parser:run:217 - Job ID: 1411
Training completed successfully!`

### Additional Information

the Token key is "write",

**Comment by abhishekkrthakur** [comment]
could you please confirm if you wrote the username before clicking on "start training" button?

**Comment by allandclive** [comment]
> could you please confirm if you wrote the username before clicking on "start training" button?

I did, i checked my account and copy pasted it, still no Push to Hub.

**Comment by elgraniti** [comment]
I had the same issue before, you just need to pass your username and token as an ENV variable not directly in the yml file.

Like this:

# Load Miniconda module 
module load miniconda

# Activate the environment
source activate autotrain

# Run the job that opens a webpage
export HF_USERNAME=CR7
export HF_TOKEN=hf_CristianoisbetterthanMessicr7

autotrain --config CR7_140CLtrain.yml

hub:
  username: ${HF_USERNAME}
  token: ${HF_TOKEN}

Hope this will help.

**Comment by Drwaish** [comment]
I export the token and username but still facing issue on Colab. Can you share the pic ?

**Comment by abhishekkrthakur** [comment]
this seems fine. closing
