### ISSUE TITLE
[BUG] Running sentence-transformers:triplet task with local data will fail with exception: KeyError: 'target'

### ISSUE THREAD

**Issue by S1yuan** [huggingface/autotrain-advanced#770]
### Prerequisites

- [X] I have read the [documentation](https://hf.co/docs/autotrain).
- [X] I have checked other issues for similar problems.

### Backend

Local

### Interface Used

CLI

### CLI Command

autotrain --config train.yml

### Error Logs

![err](https://github.com/user-attachments/assets/c9cdcf05-e3c6-46c5-83a6-b8c5b850c0b0)

### Additional Information

the default value of target_column is set at autotrain/trainers/sent_transformers/params.py as follow:
![image](https://github.com/user-attachments/assets/8edb75a0-e4e0-4217-8aa2-673901446320)
but triplet task do not need a target_column, so train datas have no target_column in schema.

In this case, SentenceTransformersPreprocessor.prepare_columns will raise a KeyError exception because target_column have a default value 'target'.

![image](https://github.com/user-attachments/assets/9de71490-374f-4433-9c53-9640c9cbc0c2)

To fix this bug, set the default value of target_column to None. 

btw. the default value of sentence3_column has same bug.

**Comment by S1yuan** [comment]
and here are my train configs:

task: sentence-transformers:triplet
base_model: /mnt/bn/query-rewrite/autotrain/Alibaba-NLP/gte-large-en-v1.5
project_name: gte-large-en-v1-5-st-triplet-local-dataset
log: tensorboard
backend: local

data:
  path: /mnt/bn/query-rewrite/autotrain/data/datas # this must be the path to the directory containing the train and valid files
  train_split: train # this is the name of the train file (csv or jsonl)
  valid_split: test # this is the name of the valid file (csv or jsonl), optional
  column_mapping:
    sentence1_column: anchor
    sentence2_column: positive
    sentence3_column: negative

params:
  max_seq_length: 8192
  epochs: 1
  batch_size: 8
  lr: 2e-5
  optimizer: adamw_torch
  scheduler: linear
  gradient_accumulation: 1
  mixed_precision: fp16

**Comment by abhishekkrthakur** [comment]
okay. i was able to reproduce the error.
a quick fix would be to add `target_column: null` in column mappings. that way you should be able to train the model.
in the meantime, im taking a look at how to fix this issue properly.

**Comment by abhishekkrthakur** [comment]
also fixed in version 0.8.20 and above.
thank you for reporting this issue :)

**Comment by abhishekkrthakur** [comment]
closing as fixed
