### ISSUE TITLE
Lm Studio cannot access HF

### ISSUE THREAD

**Issue by FBTCAD** [huggingface/autotrain-advanced#783]
working on Windows when trying to fetch a model on HF from LM Studio, the network connection fails. 
It works fine with jan ai. 
Yesterday LM Studio connection to HF was working. 
Thanks
Francis

**Comment by abhishekkrthakur** [comment]
seems like an LM Studio issue? 
This repository is only auto AutoTrain :)

**Comment by FBTCAD** [comment]
Maybe, but LM Studio runs locally on PC so I was thinking HF network
rejects LM Studio attempt to connect ?

**Comment by abhishekkrthakur** [comment]
in that case, please email website@huggingface.co :)
