### ISSUE TITLE
Tokenizer error

### ISSUE THREAD

**Issue by Percy-J** [huggingface/autotrain-advanced#798]
Hi HuggingFace and mates

I fine tune Extractive Question Answer on AutoTrain online, I uploaded dataset proper and did the column mapping correctly, keep getting this issues:

"ValueError: Asking to pad but the tokenizer does not have a padding token. Please select a token to use as `pad_token` `(tokenizer.pad_token = tokenizer.eos_token e.g.)` or add a new pad token via `tokenizer.add_special_tokens({'pad_token': '[PAD]'})`.

Thanks for helps!!!

**Comment by abhishekkrthakur** [comment]
which model is it?

**Comment by Percy-J** [comment]
> which model is it?

meta-llama/Llama-3.2-3B-Instruct

**Comment by abhishekkrthakur** [comment]
why do you want to use an llm model for extractive question answering task? seems like an overkill.
