### ISSUE TITLE
[BUG] Cannot train Dreambooth with sdxl

### ISSUE THREAD

**Issue by cindyloo** [huggingface/autotrain-advanced#804]
### Prerequisites

- [X] I have read the [documentation](https://hf.co/docs/autotrain).
- [X] I have checked other issues for similar problems.

### Backend

Colab

### Interface Used

CLI

### UI Screenshots & Parameters

!autotrain dreambooth \
--model ${MODEL_NAME} \
--project-name ${PROJECT_NAME} \
--image-path /content/gdrive/MyDrive/AI/autotrain/images/ \
--prompt "${PROMPT}" \
--resolution ${RESOLUTION} \
--batch-size ${BATCH_SIZE} \
--num-steps ${NUM_STEPS} \
--gradient-accumulation ${GRADIENT_ACCUMULATION} \
--lr ${LEARNING_RATE} \
--mixed-precision ${MIXED_PRECISION} \
--username ${HF_USERNAME} \
$( [[ "$USE_XFORMERS" == "True" ]] && echo "--xformers" ) \
$( [[ "$TRAIN_TEXT_ENCODER" == "True" ]] && echo "--train-text-encoder" ) \
$( [[ "$USE_8BIT_ADAM" == "True" ]] && echo "--use-8bit-adam" ) \
$( [[ "$DISABLE_GRADIENT_CHECKPOINTING" == "True" ]] && echo "--disable_gradient-checkpointing" ) \
$( [[ "$PUSH_TO_HUB" == "True" ]] && echo "--push-to-hub --token ${HF_TOKEN}" )

### Error Logs

NFO     | 2024-11-12 18:41:44 | autotrain.preprocessor.dreambooth:_save_concept_images:87 - Saving concept images
INFO     | 2024-11-12 18:41:44 | autotrain.preprocessor.dreambooth:_save_concept_images:88 - /content/gdrive/MyDrive/AI/autotrain/images/nestpas.jpg
INFO     | 2024-11-12 18:41:44 | autotrain.preprocessor.dreambooth:_save_concept_images:87 - Saving concept images
INFO     | 2024-11-12 18:41:44 | autotrain.preprocessor.dreambooth:_save_concept_images:88 - /content/gdrive/MyDrive/AI/autotrain/images/sabine_two_feet_flip.jpg
INFO     | 2024-11-12 18:41:44 | autotrain.preprocessor.dreambooth:_save_concept_images:87 - Saving concept images
I

INFO     | 2024-11-12 18:41:44 | autotrain.backends.local:create:20 - Starting local training...
INFO     | 2024-11-12 18:41:44 | autotrain.commands:launch_command:523 - ['python', '-m', 'autotrain.trainers.dreambooth', '--training_config', 'db-sbne/training_params.json']
INFO     | 2024-11-12 18:41:44 | autotrain.commands:launch_command:524 - {'model': 'stabilityai/stable-diffusion-2-1', 'vae_model': None, 'revision': None, 'tokenizer': None, 'image_path': 'db-sbne/autotrain-data', 'class_image_path': None, 'prompt': 'a sbne chicken', 'class_prompt': None, 'num_class_images': 100, 'class_labels_conditioning': None, 'prior_preservation': False, 'prior_loss_weight': 1.0, 'project_name': 'db-sbne', 'seed': 42, 'resolution': 1024, 'center_crop': False, 'train_text_encoder': False, 'batch_size': 1, 'sample_batch_size': 4, 'epochs': 1, 'num_steps': 500, 'checkpointing_steps': 100000, 'resume_from_checkpoint': None, 'gradient_accumulation': 4, 'disable_gradient_checkpointing': False, 'lr': 0.0001, 'scale_lr': False, 'scheduler': 'constant', 'warmup_steps': 0, 'num_cycles': 1, 'lr_power': 1.0, 'dataloader_num_workers': 0, 'use_8bit_adam': False, 'adam_beta1': 0.9, 'adam_beta2': 0.999, 'adam_weight_decay': 0.01, 'adam_epsilon': 1e-08, 'max_grad_norm': 1.0, 'allow_tf32': False, 'prior_generation_precision': None, 'local_rank': -1, 'xformers': False, 'pre_compute_text_embeddings': False, 'tokenizer_max_length': None, 'text_encoder_use_attention_mask': False, 'rank': 4, 'xl': False, 'mixed_precision': 'fp16', 'token': None, 'push_to_hub': False, 'username': 'cindyloo337', 'validation_prompt': None, 'num_validation_images': 4, 'validation_epochs': 50, 'checkpoints_total_limit': None, 'validation_images': None, 'logging': False}
Returning existing local_dir `db-sbne` as remote repo cannot be accessed in `snapshot_download` (404 Client Error. (Request ID: Root=1-6733a16c-20b926282da64b5a53cc8450;a241750b-e782-46b2-b73b-064f46ecf236)

Repository Not Found for url: https://huggingface.co/api/datasets/db-sbne/autotrain-data/revision/main.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.).
You are using a model of type clip_text_model to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py:1142: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
{'thresholding', 'clip_sample_range', 'dynamic_thresholding_ratio', 'sample_max_value', 'rescale_betas_zero_snr', 'variance_type', 'timestep_spacing'} was not found in config. Values will be initialized to default values.
{'latents_std', 'scaling_factor', 'latents_mean', 'force_upcast'} was not found in config. Values will be initialized to default values.
{'resnet_skip_time_act', 'class_embeddings_concat', 'attention_type', 'time_embedding_dim', 'transformer_layers_per_block', 'conv_out_kernel', 'timestep_post_act', 'dropout', 'conv_in_kernel', 'mid_block_type', 'addition_embed_type', 'time_embedding_type', 'encoder_hid_dim', 'resnet_out_scale_factor', 'mid_block_only_cross_attention', 'projection_class_embeddings_input_dim', 'cross_attention_norm', 'num_attention_heads', 'encoder_hid_dim_type', 'reverse_transformer_layers_per_block', 'time_cond_proj_dim', 'resnet_time_scale_shift', 'addition_time_embed_dim', 'addition_embed_type_num_heads', 'time_embedding_act_fn', 'class_embed_type'} was not found in config. Values will be initialized to default values.
ERROR    | 2024-11-12 18:42:23 | autotrain.trainers.common:wrapper:215 - train has failed due to an exception: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/common.py", line 212, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/dreambooth/__main__.py", line 185, in train
    main(_args)
  File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/dreambooth/train.py", line 684, in main
    train_dataset = DreamBoothDataset(
  File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/dreambooth/train.py", line 170, in __init__
    raise ValueError("Instance images root doesn't exists.")
ValueError: Instance images root doesn't exists.

ERROR    | 2024-11-12 18:42:23 | autotrain.trainers.common:wrapper:216 - Instance images root doesn't exists.
INFO     | 2024-11-12 18:42:25 | autotrain.cli.run_dreambooth:run:392 - Job ID: 45466

### Additional Information

I have tried multiple ways to address the ValueError: Instance images root doesn't exists. I looked inside `train.py` and `train_xl.py` and I don't see how else to specify the image directory for that module as it is properly accessing the concept images

what is the difference and why is it trying to access 
`Repository Not Found for url: https://huggingface.co/api/datasets/db-sbne/autotrain-data/revision/main.` ?

my HF_TOKEN is a write token with the proper var name, so there shouldn't be an issue writing anythign to my HF account..

please advise, thank you

**Comment by Redbeard-himalaya** [comment]
This issue seems caused by the behaviour change of func "huggingface_hub.snapshot_download", which doesn't raise exception anymore when it fails to access remote repo, it return local_dir instead. See below log:
Returning existing local_dir db-sbne as remote repo cannot be accessed in snapshot_download (404 Client Error. (Request ID: Root=1-6733a16c-20b926282da64b5a53cc8450;a241750b-e782-46b2-b73b-064f46ecf236)

This changed behaviour leads 'config.image_path = os.path.join(config.project_name, "concept1")', which omits the folder "autotrain-data" in the path and cause instance_data_root not existing.

My temp workaround works on colab:
sed -i -e 's/^\(\s*\)config\.image_path = os\.path\.join(config\.project_name, "concept1")/\1config\.image_path = os\.path\.join(config\.project_name if config\.token else config\.image_path, "concept1")/' /usr/local/lib/python3.10/dist-packages/autotrain/trainers/dreambooth/__main__.py

**Comment by sumitjhaonline** [comment]
INFO     | 2024-11-16 17:06:44 | autotrain.cli.run_dreambooth:run:388 - Running DreamBooth Training
WARNING  | 2024-11-16 17:06:44 | autotrain.trainers.common:__init__:286 - Parameters supplied but not used: config, train, data_path, version, func, valid_split, deploy, train_split, inference, log, backend
INFO     | 2024-11-16 17:06:44 | autotrain.preprocessor.dreambooth:_save_concept_images:87 - Saving concept images
INFO     | 2024-11-16 17:06:44 | autotrain.preprocessor.dreambooth:_save_concept_images:88 - images/cropped-IMG_4464.png
INFO     | 2024-11-16 17:06:44 | autotrain.preprocessor.dreambooth:_save_concept_images:87 - Saving concept images
INFO     | 2024-11-16 17:06:44 | autotrain.preprocessor.dreambooth:_save_concept_images:88 - images/cropped-IMG_3583.png
INFO     | 2024-11-16 17:06:44 | autotrain.preprocessor.dreambooth:_save_concept_images:87 - Saving concept images
INFO     | 2024-11-16 17:06:44 | autotrain.preprocessor.dreambooth:_save_concept_images:88 - images/cropped-IMG_7141.png
INFO     | 2024-11-16 17:06:44 | autotrain.preprocessor.dreambooth:_save_concept_images:87 - Saving concept images
INFO     | 2024-11-16 17:06:44 | autotrain.preprocessor.dreambooth:_save_concept_images:88 - images/cropped-IMG_7147.png
INFO     | 2024-11-16 17:06:44 | autotrain.preprocessor.dreambooth:_save_concept_images:87 - Saving concept images
INFO     | 2024-11-16 17:06:44 | autotrain.preprocessor.dreambooth:_save_concept_images:88 - images/cropped-IMG_3598.png
INFO     | 2024-11-16 17:06:44 | autotrain.preprocessor.dreambooth:_save_concept_images:87 - Saving concept images
INFO     | 2024-11-16 17:06:44 | autotrain.preprocessor.dreambooth:_save_concept_images:88 - images/cropped-IMG_7544 2.png
INFO     | 2024-11-16 17:06:44 | autotrain.preprocessor.dreambooth:_save_concept_images:87 - Saving concept images
INFO     | 2024-11-16 17:06:44 | autotrain.preprocessor.dreambooth:_save_concept_images:88 - images/cropped-IMG_3634.png
INFO     | 2024-11-16 17:06:44 | autotrain.preprocessor.dreambooth:_save_concept_images:87 - Saving concept images
INFO     | 2024-11-16 17:06:44 | autotrain.preprocessor.dreambooth:_save_concept_images:88 - images/cropped-IMG_5027.png
INFO     | 2024-11-16 17:06:44 | autotrain.preprocessor.dreambooth:_save_concept_images:87 - Saving concept images
INFO     | 2024-11-16 17:06:44 | autotrain.preprocessor.dreambooth:_save_concept_images:88 - images/.ipynb_checkpoints
Traceback (most recent call last):
  File "/usr/local/bin/autotrain", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/autotrain/cli/autotrain.py", line 70, in main
    command.run()
  File "/usr/local/lib/python3.10/dist-packages/autotrain/cli/run_dreambooth.py", line 391, in run
    job_id = project.create()
  File "/usr/local/lib/python3.10/dist-packages/autotrain/project.py", line 567, in create
    self.params = self._process_params_data()
  File "/usr/local/lib/python3.10/dist-packages/autotrain/project.py", line 539, in _process_params_data
    return dreambooth_munge_data(self.params, self.local)
  File "/usr/local/lib/python3.10/dist-packages/autotrain/project.py", line 304, in dreambooth_munge_data
    params.image_path = dset.prepare()
  File "/usr/local/lib/python3.10/dist-packages/autotrain/dataset.py", line 124, in prepare
    return preprocessor.prepare()
  File "/usr/local/lib/python3.10/dist-packages/autotrain/preprocessor/dreambooth.py", line 118, in prepare
    self._save_concept_images(_file)
  File "/usr/local/lib/python3.10/dist-packages/autotrain/preprocessor/dreambooth.py", line 100, in _save_concept_images
    with open(_file, "rb") as f:
IsADirectoryError: [Errno 21] Is a directory: 'images/.ipynb_checkpoints'



**RESOLVE THIS ISSUE**

**Comment by abhishekkrthakur** [comment]
discussed many times

READ OTHER ISSUES!

**Comment by abhishekkrthakur** [comment]
autotrain doesnt support dreambooth anymore. to train loras please use: https://huggingface.co/spaces/autotrain-projects/train-flux-lora-ease
