### ISSUE TITLE
[BUG] the newer version does not work

### ISSUE THREAD

**Issue by unbreakablepunjab** [huggingface/autotrain-advanced#807]
### Prerequisites

- [X] I have read the [documentation](https://hf.co/docs/autotrain).
- [X] I have checked other issues for similar problems.

### Backend

Local

### Interface Used

CLI

### Error Logs

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
cudf-cu12 24.10.1 requires pandas<2.2.3dev0,>=2.0, but you have pandas 2.2.3 which is incompatible.
gcsfs 2024.10.0 requires fsspec==2024.10.0, but you have fsspec 2024.9.0 which is incompatible.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 2.2.3 which is incompatible.
tensorflow 2.17.1 requires tensorboard<2.18,>=2.17, but you have tensorboard 2.16.2 which is incompatible.
Successfully installed Mako-1.3.6 PyWavelets-1.7.0 albucore-0.0.20 albumentations-1.4.21 alembic-1.14.0 authlib-1.3.2 autotrain-advanced-0.8.31 bitsandbytes-0.44.1 brotli-1.1.0 colorlog-6.9.0 datasets-3.1.0 diffusers-0.27.2 dill-0.3.8 evaluate-0.4.3 fastapi-0.115.4 fsspec-2024.9.0 hf-transfer-0.1.8 inflate64-1.0.0 invisible-watermark-0.2.0 ipadic-1.0.0 jiwer-3.0.5 lightning-utilities-0.11.8 loguru-0.7.2 multiprocess-0.70.16 multivolumefile-0.2.3 nvidia-ml-py-12.535.161 nvitop-1.3.2 optuna-4.0.0 packaging-24.1 pandas-2.2.3 py7zr-0.22.0 pybcj-1.0.2 pycryptodomex-3.21.0 pyngrok-7.2.1 pyppmd-1.1.0 python-multipart-0.0.17 pyzstd-0.16.2 rapidfuzz-3.10.1 rouge-score-0.1.2 sacremoses-0.1.1 seqeval-1.2.2 simsimd-6.0.5 starlette-0.41.2 tensorboard-2.16.2 texttable-1.7.0 tiktoken-0.6.0 torchmetrics-1.5.1 tqdm-4.67.0 trl-0.12.0 uvicorn-0.32.0 werkzeug-3.1.2 xxhash-3.5.0

**Comment by abhishekkrthakur** [comment]
doesnt look like an error but more like a warning. are you unable to train models?

**Comment by unbreakablepunjab** [comment]
yes

**Comment by unbreakablepunjab** [comment]
> [abhishekkrthakur](/abhishekkrthakur)
i get Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/autotrain/trainers/dreambooth/__main__.py", line 5, in <module>
    from diffusers.utils import convert_all_state_dict_to_peft, convert_state_dict_to_kohya
  File "/usr/local/lib/python3.10/dist-packages/diffusers/__init__.py", line 5, in <module>
    from .utils import (
  File "/usr/local/lib/python3.10/dist-packages/diffusers/utils/__init__.py", line 38, in <module>
    from .dynamic_modules_utils import get_class_from_dynamic_module
  File "/usr/local/lib/python3.10/dist-packages/diffusers/utils/dynamic_modules_utils.py", line 28, in <module>
    from huggingface_hub import cached_download, hf_hub_download, model_info
ImportError: cannot import name 'cached_download' from 'huggingface_hub' (/usr/local/lib/python3.10/dist-packages/huggingface_hub/__init__.py)

**Comment by abhishekkrthakur** [comment]
autotrain doesnt support dreambooth anymore. to train loras please use: https://huggingface.co/spaces/autotrain-projects/train-flux-lora-ease
