### ISSUE TITLE
I need refund

### ISSUE THREAD

**Issue by anseltrust** [huggingface/autotrain-advanced#817]
I completely misunderstand the pro version, I need a refund please, I can send my invoice

**Comment by abhishekkrthakur** [comment]
for billing issues, please email billing [at] huggingface.co

**Comment by anseltrust** [comment]
What is the email address I can't find it anywhere in the website

**Comment by abhishekkrthakur** [comment]
i just wrote it above.

**Comment by anseltrust** [comment]
Sorry but I can't see

huggingface.co is this the mail account??

**Comment by abhishekkrthakur** [comment]
billing [at] huggingface.co
