### ISSUE TITLE
Unable to create zerospace even I purchased huggingface pro account

### ISSUE THREAD

**Issue by inapp-admin** [huggingface/autotrain-advanced#824]
Hi team,

I am writing this behalf of my organization. Yesterday, we purchased hugging face pro account for our organization. But, today when a member in my organization tried to create zero space with owner: organization, it is asking to purchase enterprise. What could be the reason.

**Comment by abhishekkrthakur** [comment]
this github repo is only for autotrain issues. please contact hugging face support :)
